### ISSUE TITLE
how does the StyleAlign Integrated feature works?[Feature Request]: 

### ISSUE THREAD

**Issue by geowjm** [lllyasviel/stable-diffusion-webui-forge#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

i searched everywhere and cant seem to find how to implement it 

### Proposed workflow

...

**Comment by jepjoo** [comment]
One way is to use with **Dynamic Prompts extension**.

- Batch size: 2
- Prompt something like this: {pizza|watermelon} on a kitchen table by window, summer at noon, photograph, 1980's
- Enable Style aligned
- Dynamic Prompts settings:
![Screenshot 2024-02-07 at 23-24-53 Stable Diffusion](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/48107422/1c4129af-b506-4322-bf93-0ebc809de19b)

Result:
![xdx](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/48107422/a3d1d445-1799-481a-bbdb-ff738c24bd6b)

Can use batch size 3+ too, just prompts {1|2|3} then.

IMPORTANT NOTE: Currently I'm seeing good results only with SDXL Turbo models. Results with regular SDXL models seem bugged (they work fine in normal A1111). SD 1.5 I have not tested.

**Comment by lllyasviel** [comment]
i revised and they should work better now

**Comment by geowjm** [comment]
> One way is to use with **Dynamic Prompts extension**.
> 
> * Batch size: 2
> * Prompt something like this: {pizza|watermelon} on a kitchen table by window, summer at noon, photograph, 1980's
> * Enable Style aligned
> * Dynamic Prompts settings:
>   ![Screenshot 2024-02-07 at 23-24-53 Stable Diffusion](https://private-user-images.githubusercontent.com/48107422/303143313-1c4129af-b506-4322-bf93-0ebc809de19b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNjk5ODQsIm5iZiI6MTcwNzM2OTY4NCwicGF0aCI6Ii80ODEwNzQyMi8zMDMxNDMzMTMtMWM0MTI5YWYtYjUwNi00MzIyLWJmOTMtMGViYzgwOWRlMTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDA1MjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ODVmOTM3NGE4MjNkNjMxNDkwZTMzMTIxMGRjZDkyZTJjNzgyNjc1MTlkMDI1MDI2MzkwZGJiMzE3N2E3YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DtdKk8u3Xri-iGAdAQkXskR1DBENMnU7h5XOE2PqJSk)
> 
> Result: ![xdx](https://private-user-images.githubusercontent.com/48107422/303145131-a3d1d445-1799-481a-bbdb-ff738c24bd6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNjk5ODQsIm5iZiI6MTcwNzM2OTY4NCwicGF0aCI6Ii80ODEwNzQyMi8zMDMxNDUxMzEtYTNkMWQ0NDUtMTc5OS00ODFhLWJiZGItZmY3MzhjMjRiZDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDA1MjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZjkzZDIyM2M1NTM0NDY3ODAxNmNkZDk0MjM1MmNhYTdmM2JmY2M2NGQ3YjVkNGNiM2I5YjFhMTViZjRmNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ThLRwdTyci2a_cdec84_CNszwKqMKW0UbGL9ZCJSQQ0)
> 
> Can use batch size 3+ too, just prompts {1|2|3} then.
> 
> IMPORTANT NOTE: Currently I'm seeing good results only with SDXL Turbo models. Results with regular SDXL models seem bugged (they work fine in normal A1111). SD 1.5 I have not tested.

thank you!, i will try it  the results look amazing!

**Comment by jepjoo** [comment]
> i revised and they should work better now

Updated and works on regular SDXL models as well as PlaygroundV2 now. Thanks!
