### ISSUE TITLE
custom models/controlnet/etc. folders

### ISSUE THREAD

**Issue by xenosolarresearch** [lllyasviel/stable-diffusion-webui-forge#1009]
I'm guessing this is a stupid question and I'm missing something obvious, but I can't figure out how to configure custom folders for checkpoints, etc. In previous Forge release there was a "config.json" in the "webui" folder but can't find an equivalent here...

**Comment by technixp** [comment]
you need to create a symlink.
example: `mklink /d <stable-drive-and-webui>\models\Stable-diffusion\e-drive-models e:\models`
use CMD with admin priv.

ref: https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/5053

**Comment by MartinHammarstedt** [comment]
You can also specify custom folders by adding command line arguments to the `COMMANDLINE_ARGS` variable in `webui-user.bat`.

|            |                                         |
| ---------- | --------------------------------------- |
| --data-dir | base path where all user data is stored |
| --models-dir | base path where models are stored; overrides --data-dir |
| --ckpt-dir | Path to directory with stable diffusion checkpoints |
| --vae-dir | Path to directory with VAE files |
| --gfpgan-dir | GFPGAN directory |
| --embeddings-dir | embeddings directory for textual inversion (default: embeddings) |
| --textual-inversion-templates-dir | directory with textual inversion templates |
| --hypernetwork-dir | hypernetwork directory |
| --localizations-dir | localizations directory |

For example:
```bat
set COMMANDLINE_ARGS=--models-dir C:/my/path/stable-diffusion-webui/models --embeddings-dir C:/my/path/stable-diffusion-webui/embeddings
```

**Comment by xenosolarresearch** [comment]
Thank you! That's perfect

**Comment by xenosolarresearch** [comment]
Thank you! That's perfect,
