### ISSUE TITLE
no run FLUX model, AttributeError: 'NoneType' object has no attribute 'unet_key_prefix' 

### ISSUE THREAD

**Issue by EguHoPor** [lllyasviel/stable-diffusion-webui-forge#1010]
Hi all, maybe I'm doing something wrong, but my FLUX.dev model doesn't work on forge, even without changing values in the interface and just setting the model - I get an error.
AttributeError: 'NoneType' object has no attribute 'unet_key_prefix' 

My configuration:

CPU: e5-2667v4
GPU: nVidia RTX 3090
RAM: 32Gb

Traceback:
Loading Model: {'checkpoint_info': {'filename': 'C:\\sdforge\\webui\\models\\Stable-diffusion\\flux_dev.safetensors', 'hash': 'b04b3ba1'}, 'vae_filename': None, 'unet_storage_dtype': None}
Traceback (most recent call last):
  File "C:\sdforge\webui\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "C:\sdforge\webui\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\sdforge\webui\modules\txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "C:\sdforge\webui\modules\processing.py", line 785, in process_images
    p.sd_model, just_reloaded = forge_model_reload()
  File "C:\sdforge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\sdforge\webui\modules\sd_models.py", line 512, in forge_model_reload
    sd_model = forge_loader(state_dict, sd_vae=state_dict_vae)
  File "C:\sdforge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\sdforge\webui\backend\loader.py", line 175, in forge_loader
    state_dicts, estimated_config = split_state_dict(sd, sd_vae=sd_vae)
  File "C:\sdforge\webui\backend\loader.py", line 147, in split_state_dict
    guess = huggingface_guess.guess(sd)
  File "C:\sdforge\webui\repositories\huggingface_guess\huggingface_guess\__init__.py", line 7, in guess
    result.unet_key_prefix = [unet_key_prefix]
AttributeError: 'NoneType' object has no attribute 'unet_key_prefix'
'NoneType' object has no attribute 'unet_key_prefix'
*** Error completing request
*** Arguments: ('task(hoca9dy8a37uyx9)', <gradio.route_utils.Request object at 0x000001BF7CB1A050>, '', '', [], 1, 1, 1, 3.5, 1152, 896, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', None, 0, 20, 'Euler', 'Simple', False, '', 0.8, -1, False, -1, 0, 0, 0, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 3, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', '', 0, '', '', 0, '', '', True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "C:\sdforge\webui\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

---

**Comment by Panchovix** [comment]
I think flux at fp16 is not supported at the moment, when I try to load it I get the same error.

**Comment by jokero3answer** [comment]
![image](https://github.com/user-attachments/assets/c71eec7b-f756-4dec-a66e-8355e7fc2527)
Same here.

**Comment by Kimthanh27** [comment]
same here.

**Comment by nguyenvnhat24** [comment]
Me too

**Comment by vixenius** [comment]
try adding         set COMMANDLINE_ARGS= --disable-xformers        to webui-user.bat, that fixed it for me

**Comment by jokero3answer** [comment]
It does work, but with a serious drop in speed.
@vixenius

**Comment by protector131090** [comment]
same error

**Comment by EguHoPor** [comment]
> try adding set COMMANDLINE_ARGS= --disable-xformers to webui-user.bat, that fixed it for me

Unfortunately it doesn't help

**Comment by EguHoPor** [comment]
Anyway, I managed to get it to run, you have to select as UI - all to do it

Then set as VAE - ae.safetensors
https://huggingface.co/black-forest-labs/FLUX.1-dev/resolve/main/ae.safetensors?download=true

Works adequately with Euler and Simple
In other cases the result is unsuccessful
(Although in ComfyUI it worked with UniPC, which is strange).

**Comment by vegito5ama** [comment]
If (like me) anyone found it ambiguous to follow EguHoPor's solution, refer to the screenshot - 

![image](https://github.com/user-attachments/assets/27c08612-7f93-47e2-b0aa-51ede75b2217)

**Comment by DKPC69** [comment]
I Think i found the problem most of yous are having run update.bat then download ae.safetensors, clip_l.safetensors put those in your vae folder then download t5xxl_fp16.safetensors and put in your text encoder folder, make sure you have all three selected in your vae/text encoder in your ui - This all worked for me generating fine now
