### ISSUE TITLE
Why the VAE support removal? making the WebUI useless.

### ISSUE THREAD

**Issue by Reaper1121** [lllyasviel/stable-diffusion-webui-forge#1013]
Why was the VAE support removed completely and can it be brought back? at least for **SD 1.5** and **SDXL**.

I am a power user and heavily relied on being able to choose different **VAE's**, without this functionality my life is ruined and I refuse to use **ComfyUI**. Please consider bringing it back, it means the world to me.

**Comment by TroubleDarkness** [comment]
Hi. 

If you're talking about the latest Forge WebUI release, you still can choose any VAE you want. You just need to switch UI preset to "SD" or "All" in the upper left corner of WebUI.

![image](https://github.com/user-attachments/assets/d94a1fa3-f8a3-4d79-8f27-96351e5d40a2)

I don't think you need to do anything else.
