### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Set-PP** [lllyasviel/stable-diffusion-webui-forge#1015]
when I try to make image using [flux1-dev-bnb-nf4.safetensors](https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/blob/main/flux1-dev-bnb-nf4.safetensors)    It show TypeError: 'NoneType' object is not iterable . 

I am using webui webui_forge_cu124_torch24  
core i 9  32 GB RAM with Rtx3070ti graphic.  

![Screenshot 2024-08-12 133924](https://github.com/user-attachments/assets/ed1ebf79-56a5-4ff3-b2e8-1c5438457c3a)

**Comment by protector131090** [comment]
same here

**Comment by tritant** [comment]
> when I try to make image using [flux1-dev-bnb-nf4.safetensors](https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/blob/main/flux1-dev-bnb-nf4.safetensors) It show TypeError: 'NoneType' object is not iterable .
> 
> I am using webui webui_forge_cu124_torch24 core i 9 32 GB RAM with Rtx3070ti graphic.
> 
> ![Screenshot 2024-08-12 133924](https://private-user-images.githubusercontent.com/178140300/356960501-ed1ebf79-56a5-4ff3-b2e8-1c5438457c3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDg5MTUsIm5iZiI6MTcyMzQ0ODYxNSwicGF0aCI6Ii8xNzgxNDAzMDAvMzU2OTYwNTAxLWVkMWViZjc5LTU2YTUtNGZmMy1iMmU4LTFjNTQzODQ1N2MzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwNzQzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjM1ZjdjZTEzNGMwZmQxOTRlNmExZjBhOTNkMTFmODI5NWMxMTc5YmVhN2Q5MTc4MzkyYzdhODFiYmExN2EyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xt0Gt5oFgExlGb1Oc8O2ct9FTe_0jApBzcgx_N1hdwg)

Probably because you are using xformer, try removing it

**Comment by therootx** [comment]
> > when I try to make image using [flux1-dev-bnb-nf4.safetensors](https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/blob/main/flux1-dev-bnb-nf4.safetensors) It show TypeError: 'NoneType' object is not iterable .
> > I am using webui webui_forge_cu124_torch24 core i 9 32 GB RAM with Rtx3070ti graphic.
> > ![Screenshot 2024-08-12 133924](https://private-user-images.githubusercontent.com/178140300/356960501-ed1ebf79-56a5-4ff3-b2e8-1c5438457c3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDg5MTUsIm5iZiI6MTcyMzQ0ODYxNSwicGF0aCI6Ii8xNzgxNDAzMDAvMzU2OTYwNTAxLWVkMWViZjc5LTU2YTUtNGZmMy1iMmU4LTFjNTQzODQ1N2MzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwNzQzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjM1ZjdjZTEzNGMwZmQxOTRlNmExZjBhOTNkMTFmODI5NWMxMTc5YmVhN2Q5MTc4MzkyYzdhODFiYmExN2EyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xt0Gt5oFgExlGb1Oc8O2ct9FTe_0jApBzcgx_N1hdwg)
> 
> Probably because you are using xformer, try removing it

I also have same issue, I was running with xformers but removing it not solve the problem. Still same error.

**Comment by Lenanetka** [comment]
Macbook Air M1 with 16 GB RAM. Auto1111 web_UI  is working for me.
I run forge web ui with "./webui.sh" command, web ui is opened but generation always failed with the same error. I'm too noob to understand if I did something wrong.
Here what I have with all default settings and with just 1 word in promt.
![Screenshot_2024_08_12_10_09_29](https://github.com/user-attachments/assets/95f0c255-d70c-4fc4-8409-1ec05f93036d)
![Screenshot_2024_08_12_10_13_01](https://github.com/user-attachments/assets/1e9822b4-1ff5-4dad-baaf-eec76f758539)
Last login: Mon Aug 12 10:02:14 on ttys015
user@MacBook-Air stable-diffusion-webui-forge % ./webui.sh

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.
################################################################

################################################################
Running on user user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.14 (main, Mar 19 2024, 21:46:16) [Clang 15.0.0 (clang-1500.3.9.4)]
Version: f2.0.1v1.10.1-previous-247-g9f6d263c3
Commit hash: 9f6d263c3f3e07f2e7874263d36b528b887b3b26
Installing requirements
Legacy Preprocessor init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.
Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
Total VRAM 16384 MB, total RAM 16384 MB
pytorch version: 2.3.1
Set vram state to: SHARED
Device: mps
VAE dtype preferences: [torch.float32] -> torch.float32
CUDA Using Stream: False
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Using sub quadratic optimization for cross attention
Using split attention for VAE
ControlNet preprocessor location: /Volumes/AlphaBoss/stable-diffusion-webui-forge/models/ControlNetPreprocessor
2024-08-12 10:08:42,459 - ControlNet - INFO - ControlNet UI callback registered.
Model selected: {'checkpoint_info': {'filename': '/Volumes/AlphaBoss/stable-diffusion-webui-forge/models/Stable-diffusion/flux1-dev-bnb-nf4.safetensors', 'hash': '0184473b'}, 'vae_filename': None, 'unet_storage_dtype': None}
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 10.6s (prepare environment: 2.3s, launcher: 1.9s, import torch: 2.0s, initialize shared: 0.2s, other imports: 1.1s, load scripts: 0.9s, create ui: 1.1s, gradio launch: 0.9s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
Loading Model: {'checkpoint_info': {'filename': '/Volumes/AlphaBoss/stable-diffusion-webui-forge/models/Stable-diffusion/flux1-dev-bnb-nf4.safetensors', 'hash': '0184473b'}, 'vae_filename': None, 'unet_storage_dtype': None}
StateDict Keys: {'transformer': 2350, 'vae': 244, 'text_encoder': 198, 'text_encoder_2': 220, 'ignore': 0}
Using Detected T5 Data Type: torch.float8_e4m3fn
Using Detected UNet Type: nf4
Using pre-quant state dict!
Working with z of shape (1, 16, 32, 32) = 16384 dimensions.
K-Model Created: {'storage_dtype': 'nf4', 'computation_dtype': torch.bfloat16}
Model loaded in 10.4s (unload existing model: 0.2s, load state dict: 0.2s, forge model load: 10.0s).
Skipping unconditional conditioning when CFG = 1. Negative Prompts are ignored.
To load target model ModuleDict
Begin to load 1 model
Moving model(s) has taken 0.01 seconds
Distilled CFG Scale: 3.5
To load target model KModel
Begin to load 1 model
Moving model(s) has taken 52.71 seconds
  0%|                                                    | 0/20 [00:00<?, ?it/s]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
  0%|                                                    | 0/20 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/modules_forge/main_thread.py", line 37, in loop
    task.work()
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/modules_forge/main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/modules/txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/modules/processing.py", line 799, in process_images
    res = process_images_inner(p)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/modules/processing.py", line 942, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/modules/processing.py", line 1313, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 234, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/modules/sd_samplers_common.py", line 272, in launch_sampling
    return func()
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 234, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/k_diffusion/sampling.py", line 128, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/modules/sd_samplers_cfg_denoiser.py", line 186, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/backend/sampling/sampling_function.py", line 339, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/backend/sampling/sampling_function.py", line 284, in sampling_function_inner
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/backend/sampling/sampling_function.py", line 254, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/backend/modules/k_model.py", line 43, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/backend/nn/flux.py", line 393, in forward
    out = self.inner_forward(img, img_ids, context, txt_ids, timestep, y, guidance)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/backend/nn/flux.py", line 350, in inner_forward
    img = self.img_in(img)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/backend/operations.py", line 112, in forward
    return torch.nn.functional.linear(x, self.weight, self.bias)
RuntimeError: linear(): input and weight.T shapes cannot be multiplied (4032x64 and 1x98304)
linear(): input and weight.T shapes cannot be multiplied (4032x64 and 1x98304)
*** Error completing request
*** Arguments: ('task(x6jm8v1z5unhnre)', <gradio.route_utils.Request object at 0x1738328f0>, 'mouse', '', [], 1, 1, 1, 3.5, 1152, 896, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', None, 0, 20, 'Euler', 'Simple', False, -1, False, -1, 0, 0, 0, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 3, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', '', 0, '', '', 0, '', '', True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "/Volumes/AlphaBoss/stable-diffusion-webui-forge/modules/call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

**Comment by HelloWarcraft** [comment]
I solved the problem by the steps below:
step1: change torch

> according to Readme
> 
>  Some other CUDA/Torch Versions:
> 
> [Forge with CUDA 12.1 + Pytorch 2.3.1](https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch231.7z) <- Recommended
> 
> [Forge with CUDA 12.4 + Pytorch 2.4](https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu124_torch24.7z) <- Fastest, but MSVC may be broken, xformers may not work
> 
> [Forge with CUDA 12.1 + Pytorch 2.1](https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch21.7z) <- the previously used old environments

```shell
pip install torch==2.3.1+cu121 torchvision==0.18.1+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
```
step2: uninstall xformers
```shell
pip uninstall xformers
```
step3: launch webUI
```shell
cd ./stable-diffusion-webui-forge
python launch.py
```
---
if you dont want to uninstall xformers, you should do two steps:
```shell
pip install torch==2.3.1+cu121 torchvision==0.18.1+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
cd ./stable-diffusion-webui-forge
python launch.py --disable-xformers
```

If you are a windows user, you can edit `run.bat, update.bat or environment.bat` in text editor

**Comment by jokero3answer** [comment]
Doesn't --disable-xformers cause a serious drop in raw speed?
@HelloWarcraft

**Comment by HelloWarcraft** [comment]
> Doesn't --disable-xformers cause a serious drop in raw speed? @HelloWarcraft
`Xformers` really does well in  accelating the process of image generation, but it will cause error here. That is to say, you can not generate image successfully when using xformers now.
Hope that the author could solve the problem

**Comment by therootx** [comment]
I just changed the model I've used and updated Torch 2.3.1+cu118 to 2.3.1+cu121 but didn't disable xformers and it worked.

**Comment by HelloWarcraft** [comment]
> I just changed the model I've used and updated Torch 2.3.1+cu118 to 2.3.1+cu121 but didn't disable xformers and it worked.
Cheers!
Do you installed xformers in you environment?
I tried `python launch.py --xformers` with `torch==2.3.1+cu121` just now, and got an error of `NoneTypeError`. So I think changing the toch from `cu124` to `cu121` and removing or disabling xformers are both important.

**Comment by therootx** [comment]
> > I just changed the model I've used and updated Torch 2.3.1+cu118 to 2.3.1+cu121 but didn't disable xformers and it worked.
> 
> Nice Have you installed xformers in you environment? I tried `python launch.py --xformers` with `torch==2.3.1+cu121` just now, and got an error of `NoneTypeError`. So I thought changing the toch from `cu124` to `cu121` and removing or disabling xformers might be both important.

No I didn't add the --xformers into environment but I didn't uninstall it either. Torch and I think correct model usage is important. My fp8 model was incorrect.
![image](https://github.com/user-attachments/assets/94fb4233-ddb9-4bd8-a731-0596ccdbb19e)
I had 11gb one and changed it to 17gb one.

**Comment by jokero3answer** [comment]
![image](https://github.com/user-attachments/assets/ff02ffb0-913a-48cc-a06a-6947c6b4b6e4)
The other three work except for xformers, but they run super slow!

**Comment by jokero3answer** [comment]
![image](https://github.com/user-attachments/assets/48c86b28-e019-4813-a7c6-06a48360dc44)

**Comment by HelloWarcraft** [comment]
> No I didn't add the --xformers into environment but I didn't uninstall it either. Torch and I think correct model usage is important. My fp8 model was incorrect. ![image](https://private-user-images.githubusercontent.com/32716475/356989990-94fb4233-ddb9-4bd8-a731-0596ccdbb19e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTM5OTksIm5iZiI6MTcyMzQ1MzY5OSwicGF0aCI6Ii8zMjcxNjQ3NS8zNTY5ODk5OTAtOTRmYjQyMzMtZGRiOS00YmQ4LWE3MzEtMDU5NmNjZGJiMTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA5MDgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNGY3MjMyNTRhM2U4MzE1Y2M4NjhkZDNmYjI1N2M4YzRmMjllNDljMzYyYzU5OWM4MDJlYTIxZWUwNzQwMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X596v3WSLup_5410U3X_-dUEfN2uUQ-nlbr2A6E7qR4) I had 11gb one and changed it to 17gb one.

That's fine since it works.😄 We can wait for Zhang lvmin to optimize the Forge2.0

**Comment by HelloWarcraft** [comment]
> ![image](https://private-user-images.githubusercontent.com/130854108/356991851-48c86b28-e019-4813-a7c6-06a48360dc44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTQzNDcsIm5iZiI6MTcyMzQ1NDA0NywicGF0aCI6Ii8xMzA4NTQxMDgvMzU2OTkxODUxLTQ4Yzg2YjI4LWUwMTktNDgxMy1hN2M2LTA2YTQ4MzYwZGM0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwOTE0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmIxZDJlZDhkNGIxOTE4NjE3ZWRhMmExODYyMjg0ODZjMjYzYjcyNWM5NDRlYWU0OGVlYjNkODJkMzBiZWRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.REzYk95b2Qt8j2JBT8ZHY6TgmCWRMTJbQ0tzdtHfXRI)


> If your device supports CUDA newer than 11.7 then you can use NF4. (Most RTX 3XXX/4XXX GPUs supports this.) Congratulations. Enjoy the speed. In this case, you only need to download the flux1-dev-bnb-nf4.safetensors.
> 
> **If your device is GPU with GTX 10XX/20XX then your device may not support NF4, please download the flux1-dev-fp8.safetensors.**
> 
> info from https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/981

**Comment by Set-PP** [comment]
Solved the problem, I tried deleting [flux1-dev-bnb-nf4.safetensors](https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/blob/main/flux1-dev-bnb-nf4.safetensors)  and download again.  and I reduce GPU Weight (MB) to 6000MB . Now It run smoothly. 
![Uploading Screenshot 2024-08-12 165419.png…]()

**Comment by xam0482** [comment]
我不确认 在更新了那个 python 扩展以后  可以正常了
diffusers-0.29.2 的可能较大


![屏幕截图 2024-08-12 200418](https://github.com/user-attachments/assets/fdda63b5-bc7d-4fd1-a8ba-2b9ba7258bb4)

**Comment by xam0482** [comment]
bnb nf版本模型需要安装依赖 bitsandbytes>=0.43.3

**Comment by mhioi** [comment]
> I solved the problem by the steps below: step1: change torch
> 
> > according to Readme
> > Some other CUDA/Torch Versions:
> > [Forge with CUDA 12.1 + Pytorch 2.3.1](https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch231.7z) <- Recommended
> > [Forge with CUDA 12.4 + Pytorch 2.4](https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu124_torch24.7z) <- Fastest, but MSVC may be broken, xformers may not work
> > [Forge with CUDA 12.1 + Pytorch 2.1](https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch21.7z) <- the previously used old environments
> 
> ```shell
> pip install torch==2.3.1+cu121 torchvision==0.18.1+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
> ```
> 
> step2: uninstall xformers
> 
> ```shell
> pip uninstall xformers
> ```
> 
> step3: launch webUI
> 
> ```shell
> cd ./stable-diffusion-webui-forge
> python launch.py
> ```
> 
> if you dont want to uninstall xformers, you should do two steps:
> 
> ```shell
> pip install torch==2.3.1+cu121 torchvision==0.18.1+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
> cd ./stable-diffusion-webui-forge
> python launch.py --disable-xformers
> ```
> 
> If you are a windows user, you can edit `run.bat, update.bat or environment.bat` in text editor to change the torch version.
> 
> the command also works: `pip install torch==2.4.0+cu121 torchvision==0.19.0+cu121 --extra-index-url https://download.pytorch.org/whl/cu121`

worked for me! thanks!

**Comment by DKPC69** [comment]
I Think i found the problem most of yous are having run update.bat then download ae.safetensors, clip_l.safetensors put those in your vae folder then download t5xxl_fp16.safetensors and put in your text encoder folder, make sure you have all three selected in your vae/text encoder in your ui - This all worked for me generating fine now
