### ISSUE TITLE
'--ckpt-dir' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by rktvr** [lllyasviel/stable-diffusion-webui-forge#1017]
as the title says.

can't use --ckpt-dir anymore in webui-user.bat

**Comment by Priestru** [comment]
set COMMANDLINE_ARGS=--ckpt-dir "C:\ComfyUI_windows_portable\ComfyUI\models\checkpoints"

works for me

**Comment by rktvr** [comment]
> set COMMANDLINE_ARGS=--ckpt-dir "C:\ComfyUI_windows_portable\ComfyUI\models\checkpoints"
> 
> works for me

thank you, that works. not sure why using the format in the webui-user.bat was breaking it.
