### ISSUE TITLE
Hires fix: show hires checkpoint and sampler selection   (requires Reload UI) cannot be applied 

### ISSUE THREAD

**Issue by LKas112** [lllyasviel/stable-diffusion-webui-forge#1018]
even the box is ticked separate checkpoint cannot be chosen for hires fix

**Comment by zethfoxster** [comment]
on this same issue train, can we have the old behavior where it would unload the previous model and load the new one also work with flux.
I was successfully able to start an image in any model pipeline and change it to sd15 on hires previously. it would be awesome if when hires checkpoints was reenabled that we get that ability back as well. thank you!

**Comment by andy8992** [comment]
;_; damn you flux...
