### ISSUE TITLE
Missing VAE Selection in XL UI

### ISSUE THREAD

**Issue by void95** [lllyasviel/stable-diffusion-webui-forge#1022]
Hello, i was wondering why the VAE Selection is missing in the XL Section. I got some SDXL Vaes and cant select them in the XL UI. 

Is there a way to Add the VAE Support back?

**Comment by vihangasa14** [comment]
Try all button , it worked well there

**Comment by MartinHammarstedt** [comment]
If you're not afraid to mess around in the code, you can change the `False` to `True` in these two lines, to make the VAE selector visible also in the SDXL preset:

https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/f6ef105cb333692d8695ebe14c8409f98675e2f4/modules_forge/main_entry.py#L233-L234

**Comment by void95** [comment]
Thank u so much for ur advice ! :)
