### ISSUE TITLE
Bug: Flux Distilled CFG Scale sticks after first generation regardless of subsequent changes

### ISSUE THREAD

**Issue by aoleg** [lllyasviel/stable-diffusion-webui-forge#1025]
When using the flux1-dev-bnb-nf4.safetensors model, the Distilled CFG Scale can only be set once. If I generate an image with a certain Distilled CFG Scale, changing that value and generating the same image (same seed and parameters) again results in identical image.

This is not a gradio issue. "Distilled CFG Scale: 1.2" and "Distilled CFG Scale: 0.8" appear in the resulting PNG file metadata, yet the two images are identical otherwise. Notably, I can change the "CFG" value, and that change is applied properly.

UPD: might still be a gradio issue. Flipping the UI switch from "flux" to "all" and back, then filling in resolution, CFG and Distilled CFG Scale again properly changes the "Distilled CFG Scale" value - yet again, after the first generation that chosen value sticks.

UPD2: flipping the UI switch does not work. Could've been a single random occasion.

Restarting Forge (and thus reloading the checkpoint) allows to set a different Distilled CFG Scale, yet that also only works once.

In the log below, the "Distilled CFG Scale: 0.8" appears twice, but only during the first generation. No such text in subsequent generations.

**Comment by xilog080** [comment]
I am experiencing a very similar but slightly worse version of this.

In my case, flipping from Flux to All and back again makes no difference.  Distilled CFG will be unchanged despite changing the slider
Flipping back to All, reloading UI and then flipping back to Flux again makes no difference.  Distilled CFG will be unchanged despite changing the slider
The only way for me to change the Distilled CFG Scale is to completely exit Forge and restart from scratch.  Then I can use a different Distilled CFG.  But just as the OP states, it is now stuck there and will not change again until a full reload, despite what the slider says in the UI.

**Comment by aoleg** [comment]
Flipping the UI no longer fixes this for me either, so it might've been a random occasion. Distilled CFG Scale is currently stuck until full restart of the Forge.

**Comment by tritant** [comment]
Same here

**Comment by xilog080** [comment]
Just to add a bit more info, switching to a different flux checkpoint corrects the issue without reloading Forge:

1. generate an image using flux1-dev-bnb-nf4.safetensors and distilled CFG=1 (image A)
2. change distilled CFG=3.5 and regenerate (image B)
3. same image (A=B) but should be different
4. change checkpoint to flux1-dev-fp8.safetensors and generate image 
5. image is clearly using correct distilled CFG, completely different in character (image C)
6. change checkpoint back to flux1-dev-bnb-nf4.safetensors
7. image is similar to image C and nothing like image B, as should have been the case in step 3.

Obviously changing checkpoint and generating an image is slower than restarting Forge, this is just to add(hopefully useful) info.

**Comment by Degio64** [comment]
To speed up things, while waiting for the bug to be fixed: after generating the first image, change Distilled CFG and select any different checkpoint (even an old SDXL) and regenerate. As soon as the checkpoint is loaded and the image starts being built, press Skip and go back to flux1-dev-bnb-nf4.safetensors and generate.
The new image will use the new Distilled CFG.

**Comment by ptits** [comment]
The same here, updated 10 min ago

**Comment by Metal079** [comment]
Yep still happens

**Comment by tritant** [comment]
No fix for that? it's really very restrictive.

**Comment by Degio64** [comment]
Apparently also changing Swap Method (from Queue to Asynch or viceversa) works.
When you change Distilled CFG, if you want to see a different result, just remember to change also Swap Method.
Again... just a faster method while waiting for a bux fix.

**Comment by Degio64** [comment]
Today, with the latest update, it seems fixed

**Comment by kerizane** [comment]
Recently fixed, please test and close.

**Comment by aoleg** [comment]
Tested and fixed.

**Comment by xilog080** [comment]
Thanks for fixing.

**Comment by ptits** [comment]
Works perfect now

**Comment by stripealipe** [comment]
Hmmm... this still seems to persist for me. No change between generated image when changing values. Using Flux FP8 safetensors with FP8 relevant clips and VAE etc. Any thoughts? Thanks.

**Comment by xilog080** [comment]
Are you fully up to date?  It's respecting changes to Distilled CFG for me, using FP8 Flux, FP8 T5xxl, clip_l and default Flux VAE.
