### ISSUE TITLE
Is there any possibility to put the old API for Forge? 

### ISSUE THREAD

**Issue by EguHoPor** [lllyasviel/stable-diffusion-webui-forge#1028]
This may sound silly, but I'm using Stable Diffusion plugin for photoshop, unfortunately it's not updated since 2023, is there any way to enable the old API or is it better to look for alternative ways to interact?
![image](https://github.com/user-attachments/assets/bd87e3ef-7dea-44b1-9849-63e5dff7f787)

**Comment by altoiddealer** [comment]
I think this is a dupe Issue - see here

https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/993


The API was stripped out while the backend changes were being made - it's only a matter of time before Illyasviel restores these endpoints.

**Comment by EguHoPor** [comment]
E boiz, thanks fix this)))
@lllyasviel
