### ISSUE TITLE
Sampling method LCM don't work

### ISSUE THREAD

**Issue by kutchek** [lllyasviel/stable-diffusion-webui-forge#1042]
Traceback (most recent call last):
  File "D:\programs\webui_forge\webui\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "D:\programs\webui_forge\webui\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\programs\webui_forge\webui\modules\txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "D:\programs\webui_forge\webui\modules\processing.py", line 799, in process_images
    res = process_images_inner(p)
  File "D:\programs\webui_forge\webui\modules\processing.py", line 942, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\programs\webui_forge\webui\modules\processing.py", line 1313, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\programs\webui_forge\webui\modules\sd_samplers_kdiffusion.py", line 203, in sample
    x = self.model_wrap.predictor.noise_scaling(sigmas[0], x, torch.zeros_like(x), max_denoise=opts.sgm_noise_multiplier)
  File "D:\programs\webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'LCMCompVisDenoiser' object has no attribute 'predictor'
'LCMCompVisDenoiser' object has no attribute 'predictor'
*** Error completing request
*** Arguments: ('task(5ux4rx0bi0544tj)', <gradio.route_utils.Request object at 0x0000015B8FCF0FD0>, 'detailed, wallpaper, abstract, background, digital illustration, art, gentle gradients, <lora:LCM_LoRA_Weights_SD15:1>, ', '(worst quality, low quality, normal quality, watemark:1.3)', [], 1, 1, 2, 3.5, 512, 768, False, 0.4, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', [], 0, 20, 'LCM', 'Automatic', False, -1, False, -1, 0, 0, 0, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='tile_colorfix', model='control_v11f1e_sd15_tile [a371b31b]', weight=1.2, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=0.5, threshold_a=8, threshold_b=0.5, guidance_start=0.0, guidance_end=1.0, pixel_perfect=True, control_mode='ControlNet is more important', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 3, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\programs\webui_forge\webui\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

---

**Comment by gjlll4137** [comment]
Same here

**Comment by l0stl0rd** [comment]
same here on MacOs

**Comment by gfcprogramer** [comment]
Same here on windows 10

**Comment by andy8992** [comment]
same ;_;

**Comment by kerizane** [comment]
Looks like this was fixed: https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/22a19943d240dbecc35cc869c37ba300ad7f6c4b

Please test and close.

**Comment by kutchek** [comment]
It worked
