### ISSUE TITLE
Model Not Recognized / 'Nonetype' Object

### ISSUE THREAD

**Issue by chuckstarza** [lllyasviel/stable-diffusion-webui-forge#1045]
I have installed the web ui and can run 1.5 and xl models fine. 
If I try to run flux1-schnell-fp8 or flux_schell I get this error string:

venv "C:\Users\Alex Admin\Downloads\webui_forge_cu121_torch231\webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-248-gf6ef105c
Commit hash: f6ef105cb333692d8695ebe14c8409f98675e2f4
Installing requirements
Launching Web UI with arguments:
Total VRAM 12287 MB, total RAM 32698 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: C:\Users\Alex Admin\Downloads\webui_forge_cu121_torch231\webui\models\ControlNetPreprocessor
2024-08-13 09:47:08,345 - ControlNet - INFO - ControlNet UI callback registered.
Model selected: {'checkpoint_info': {'filename': 'C:\\Users\\Alex Admin\\Downloads\\webui_forge_cu121_torch231\\webui\\models\\Stable-diffusion\\flux_schnell.safetensors', 'hash': '875161af'}, 'vae_filename': None, 'unet_storage_dtype': None}
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 19.3s (prepare environment: 5.6s, launcher: 2.5s, import torch: 4.2s, initialize shared: 0.3s, other imports: 1.2s, load scripts: 1.9s, create ui: 2.1s, gradio launch: 1.4s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
Loading Model: {'checkpoint_info': {'filename': 'C:\\Users\\Alex Admin\\Downloads\\webui_forge_cu121_torch231\\webui\\models\\Stable-diffusion\\flux_schnell.safetensors', 'hash': '875161af'}, 'vae_filename': None, 'unet_storage_dtype': None}
Traceback (most recent call last):
  File "C:\Users\Alex Admin\Downloads\webui_forge_cu121_torch231\webui\backend\loader.py", line 181, in forge_loader
    state_dicts, estimated_config = split_state_dict(sd, sd_vae=sd_vae)
  File "C:\Users\Alex Admin\Downloads\webui_forge_cu121_torch231\webui\backend\loader.py", line 152, in split_state_dict    guess = huggingface_guess.guess(sd)
  File "C:\Users\Alex Admin\Downloads\webui_forge_cu121_torch231\webui\repositories\huggingface_guess\huggingface_guess\__init__.py", line 7, in guess
    result.unet_key_prefix = [unet_key_prefix]
AttributeError: 'NoneType' object has no attribute 'unet_key_prefix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex Admin\Downloads\webui_forge_cu121_torch231\webui\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "C:\Users\Alex Admin\Downloads\webui_forge_cu121_torch231\webui\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\Users\Alex Admin\Downloads\webui_forge_cu121_torch231\webui\modules\txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "C:\Users\Alex Admin\Downloads\webui_forge_cu121_torch231\webui\modules\processing.py", line 785, in process_images
    p.sd_model, just_reloaded = forge_model_reload()
  File "C:\Users\Alex Admin\Downloads\webui_forge_cu121_torch231\webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Alex Admin\Downloads\webui_forge_cu121_torch231\webui\modules\sd_models.py", line 512, in forge_model_reload
    sd_model = forge_loader(state_dict, sd_vae=state_dict_vae)
  File "C:\Users\Alex Admin\Downloads\webui_forge_cu121_torch231\webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Alex Admin\Downloads\webui_forge_cu121_torch231\webui\backend\loader.py", line 183, in forge_loader
    raise ValueError('Failed to recognize model type!')
ValueError: Failed to recognize model type!
Failed to recognize model type!
*** Error completing request
*** Arguments: ('task(mwa4kgo7sbk7zo7)', <gradio.route_utils.Request object at 0x000002237C2B2260>, 'lady', '', [], 1, 1, 1, 3.5, 1152, 896, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', None, 0, 20, 'Euler', 'Simple', False, -1, False, -1, 0, 0, 0, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 3, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', '', 0, '', '', 0, '', '', True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "C:\Users\Alex Admin\Downloads\webui_forge_cu121_torch231\webui\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

---

Any ideas?

**Comment by DivinesImmortus** [comment]
Try those just scroll a bit down

https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/981

**Comment by chuckstarza** [comment]
> Try those just scroll a bit down
> 
> #981

Sorted - had wrong model - duh!
Thanks
