### ISSUE TITLE
Reactor Face Model Dropdown Selection not show

### ISSUE THREAD

**Issue by asilvamaia** [lllyasviel/stable-diffusion-webui-forge#1057]
After install Reactor, when click in facemodel, the dropdown menu to select the models is not show. In the terminal, show this error:
AttributeError: type object 'Column' has no attribute 'update'

**Comment by DenOfEquity** [comment]
previously discussed, fix here: https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/889#issuecomment-2257289510
