### ISSUE TITLE
Please, can we fix it?? It's annoying, every time I need to work with LoRA is a pain.

### ISSUE THREAD

**Issue by ExperienceRO** [lllyasviel/stable-diffusion-webui-forge#1064]
Hello...
It's been very annoying.
Every time I load a LoRA it jumps from 20 secs gen to 20 minutes gen. I need to reload the console, to make it work normally again.

Some info that may be usefull:
`• version: [f2.0.1v1.10.1-previous-252-g00f1cd36b]`
`•  python: 3.10.11`
`•  torch: 2.1.2+cu121`
`•  xformers: N/A`
`•  gradio: 4.40.0`

This is the console without LoRA:
![image](https://github.com/user-attachments/assets/fde6b4b0-620b-43d0-8415-f6308cf01e61)

And then, it is with LoRA
![image](https://github.com/user-attachments/assets/e39070f2-f480-4c35-a0e4-557edb08f633)

Why it happens??
I have no clue..
Maybe my machine is too weak??
![image](https://github.com/user-attachments/assets/36bc2c2a-d9fa-4dec-9fef-d2982a766bd1)

I don't think it is, since I can run ComfyUI with Flux without problems, or even Cyberpunk 2077 with 50+ mods..
Also this problem doesn't seems to happens with A1111, that's why I believe it's a problem with some optimization in Forge.

Thank You in Advanced.

**Comment by Synergyart** [comment]
One potential issue is that you're using Python 3.10.11, while Forge requires 3.10.6.

Additionally, your Forge version is [f2.0.1v1.10.1-previous-252-g00f1cd36b], whereas mine is f2.0.1v1.10.1-previous-252-g00f1cd36—I'm not sure where the "b" at the end comes from.

Also, for PyTorch, I have version 2.3.1+cu121/2.4.0+cu124 and you have 2.1.2+cu121.

I ran both the recommended version and CUDA 12.4 of Forge with no problems. I suggest you re-download the "recommended" zip file, update Forge with the Update.bat, and check again. It seems like there might be an issue with your Forge setup.

![Captura de pantalla 2024-08-13 180618](https://github.com/user-attachments/assets/e1dfe420-904b-4905-829f-1d23e8dd5f7d)
![Captura de pantalla 2024-08-13 180544](https://github.com/user-attachments/assets/e1f2ac5b-8d0f-46b6-98bd-d1fcd0d40079)

**Comment by ExperienceRO** [comment]
Problem is, it is not a new issue:
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/782#issuecomment-2254226275

Two weeks ago, I've related it, in that time it was another version..
Anyway, I'll remake it once again... Who knows??

Thank you.

**Comment by alebeard** [comment]
You just hit the nail on the head right there , " Two weeks ago, I've
related it, in that time it was another version.."
Right now this is being rebuilt pretty much daily so if it's not working
for you you need to wait a little while and check to see if an update is
patching it, I suspect it will let us all know when it is a solid working
mode until then there is an option to download the last full working model
before he started the rebuild.

**Comment by ExperienceRO** [comment]
Yeah, but no.
If the problem was there two weeks ago and TODAY it remains, so, it means THIS problem wasn't checked yet.
Som yeah..
I'll keep remind about it. If you don't work with the ones who are making it, and you don't have a solution, please, abstain from this kind of answer you provided. It don't solve nothing, and worse, it make the community look a shit.
Thank you.

**Comment by ExperienceRO** [comment]
Thank you for the fix!

![image](https://github.com/user-attachments/assets/d3865cc5-3e53-4ffa-8920-a41f6826ae44)
