### ISSUE TITLE
"ROCK AND ROLL” breaks generation.

### ISSUE THREAD

**Issue by random-667** [lllyasviel/stable-diffusion-webui-forge#1073]
Using the recommended flux model and the phrase "ROCK AND ROLL" in quotes and all caps causes the image generation to slow down and the resulting image is fried.
I've had no other issues with flux and forge.
Also, the issue isn't there in comfyui with the original flux-dev model.
Seems like "AND" is causing the issue.

**Comment by rabidcopy** [comment]
The reason for this is the `AND` syntax. When `AND` is in the prompt, it treats it as two prompts being combined. Try placing a `\` before the `A` in `AND`. https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#composable-diffusion

**Comment by kerizane** [comment]
Please close this issue.
