### ISSUE TITLE
Recent "NoneType" fix only caused another issue...

### ISSUE THREAD

**Issue by pflky** [lllyasviel/stable-diffusion-webui-forge#1074]
---
RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same
Input type (struct c10::Half) and bias type (float) should be the same
---

Errors out when trying to use controlnet models. This happens when trying to run the bdsqlsz controlnet models, and other models as well. So far the only model I haven't had issue with is Union. 

Running regular SDXL settings and VAE, tried even custom VAE's, all return the same issue. Tried "precision half" flag and others, still the same issue. Config settings for things like VAE precision also have no effect. I don't think it's a VAE issue. It's how the controlnet models themselves are being handled. Running no launch flags on webui-user.bat.

This issue existed previously, but the error it returned before was the "Nonetype" error, and above is the new error. Up to date on everything: 

version: f2.0.1v1.10.1-previous-258-gc73dd119 •  python: 3.10.6  •  torch: 2.3.1+cu121  •  xformers: N/A  •  gradio: 4.40.

These models work fine on main branch of A1111 with controlnet extension, but not with Forge's built-in controlnet.

**Comment by a3nima** [comment]
Got the same error wirth controlnet. Any hint on what could be the reason or just wait till controlnet is overhauled?

**Comment by pflky** [comment]
> Got the same error wirth controlnet. Any hint on what could be the reason or just wait till controlnet is overhauled?

Based on the error, it's clear there's some issue with how precision is being handled, and it's certainly not a UI setting issue. I figured out that using "--all-in-fp32" does allow them to work, but obviously this isn't desirable. And there's no trigger I can see for making only controlnet models process in FP32.

**Comment by kou201** [comment]
Same problem here.

**Comment by uboua3000** [comment]
same!
