### ISSUE TITLE
AssertionError: You do not have CLIP state dict!

### ISSUE THREAD

**Issue by CyDefUnicorn** [lllyasviel/stable-diffusion-webui-forge#1075]
This is with a freshly downloaded and installed version of forge

When running any model, images generate with no problem. When using the Flux NF4 model, images still also generate no with no issues. However when using the original Dev model, Schnell, or models from Kijai regarding Flux that's NOT NF4, I get the following error:

Traceback (most recent call last):
  File "C:\Users\Sam\Documents\AI-Programs\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\Users\Sam\Documents\AI-Programs\stable-diffusion-webui-forge\modules\txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "C:\Users\Sam\Documents\AI-Programs\stable-diffusion-webui-forge\modules\processing.py", line 789, in process_images
    p.sd_model, just_reloaded = forge_model_reload()
  File "C:\Users\Sam\Documents\AI-Programs\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Sam\Documents\AI-Programs\stable-diffusion-webui-forge\modules\sd_models.py", line 501, in forge_model_reload
    sd_model = forge_loader(state_dict, additional_state_dicts=additional_state_dicts)
  File "C:\Users\Sam\Documents\AI-Programs\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Sam\Documents\AI-Programs\stable-diffusion-webui-forge\backend\loader.py", line 245, in forge_loader
    component = load_huggingface_component(estimated_config, component_name, lib_name, cls_name, local_path, component_sd)
  File "C:\Users\Sam\Documents\AI-Programs\stable-diffusion-webui-forge\backend\loader.py", line 59, in load_huggingface_component
    assert isinstance(state_dict, dict) and len(state_dict) > 16, 'You do not have CLIP state dict!'
AssertionError: You do not have CLIP state dict!
You do not have CLIP state dict!

**Comment by pp517462915** [comment]
I have a same error:(

**Comment by ovchvi** [comment]
same, ive just installed torch21, cuz 231 and 24 getting me to the typeerror "'NoneType' object is not iterable" then i trying to use flux or sdxl, only sd1 worked fine, now i cannot even launch

**Comment by xabila** [comment]
Same here, but it' s ok with flux1-dev-bnb-nf4.safetensors . Unfortunately LORA are not working with NF4 tensors yet...

**Comment by LordBanter** [comment]
Same here 1060 3GB VRAM. Latest Forge UI (version: f2.0.1v1.10.1-previous-260-gaadc0f04, python: 3.10.6, torch: 2.3.1+cu121, xformers: N/A, gradio: 4.40.0).

Surprisingly both flux1-dev-bnb-nf4, flux1-dev-bnb-nf4-v2 and flux1-schnell-bnb-nf4 models work no problem.

The rest of Flux models is either 'AssertionError: You do not have CLIP state dict!' or blue screen and PC resets.

**Comment by CyDefUnicorn** [comment]
Yeah seems anything outside the Flux NF4 varients will not work. My assumption is there is no UI option (at least for me) in forge to select the CLIP files for Flux

**Comment by Sheriff1980** [comment]
I moved my clip_l.safetensors, and t5xxl_fp16.safetensors to the VAE folder, then selected the three optionsin the VAE/Text Encoder box and got it running. It is sloooooow though. right now it is taking about 3-5 minutes from the time I click Generate to the time it finishes. I will probably play around with the settings and see if I can get it to speed up a little. 
![Screenshot 2024-08-14 105325](https://github.com/user-attachments/assets/0c24060d-25d7-4ef2-9685-53dcc5a14372)

**Comment by mx109** [comment]
I had the same problem with flux.1 model download from Stability Matrix's Model Browser. But I found another version of the flux.1 dev which works for me. That version is linked to this threat:
https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/981
I've just downloaded the flux1-dev-bnb-nf4-v2.safetensors file and placed in StabilityMatrix\Data\Models\StableDiffusion and run with Stable Diffusion WebUI Forge

**Comment by CyDefUnicorn** [comment]
Awesome! Will try that out and see how it goes. Thanks for the link

**Comment by caoddgao** [comment]
I got the same issue when I was using SD3 model in Forge, the other models are all fine including Flux NF4. 
Loading Model: {'checkpoint_info': {'filename': 'C:\\stable-diffusion\\A1111UI\\models\\Stable-diffusion\\SD3 Base\\sd3_medium.safetensors', 'hash': '9b88d133'}, 'additional_modules': [], 'unet_storage_dtype': None}
StateDict Keys: {'unet': 491, 'vae': 244, 'ignore': 0}
Traceback (most recent call last):
  File "C:\stable-diffusion\webui_forge\webui\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\stable-diffusion\webui_forge\webui\modules\txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "C:\stable-diffusion\webui_forge\webui\modules\processing.py", line 789, in process_images
    p.sd_model, just_reloaded = forge_model_reload()
  File "C:\stable-diffusion\webui_forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\stable-diffusion\webui_forge\webui\modules\sd_models.py", line 501, in forge_model_reload
    sd_model = forge_loader(state_dict, additional_state_dicts=additional_state_dicts)
  File "C:\stable-diffusion\webui_forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\stable-diffusion\webui_forge\webui\backend\loader.py", line 245, in forge_loader
    component = load_huggingface_component(estimated_config, component_name, lib_name, cls_name, local_path, component_sd)
  File "C:\stable-diffusion\webui_forge\webui\backend\loader.py", line 59, in load_huggingface_component
    assert isinstance(state_dict, dict) and len(state_dict) > 16, 'You do not have CLIP state dict!'
AssertionError: You do not have CLIP state dict!
You do not have CLIP state dict!

**Comment by kenny00968** [comment]
解决了吗？我也遇到同样的问题

**Comment by vsakovskaya** [comment]
> > 是的，只需使用以下模型之一：
> > 
> > * [flux1-dev-bnb-nf4-v2.safetensors](https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/blob/main/flux1-dev-bnb-nf4-v2.safetensors) 在 NF4 中具有主模型的完整 flux-dev 检查点。<- 推荐
> > * [flux1-dev-fp8.safetensors](https://huggingface.co/lllyasviel/flux1_dev/blob/main/flux1-dev-fp8.safetensors) FP8 中带有主模型的完整 flux-dev 检查点。
> 
> 有模型，但运行SD3模型或者flux模型就会出现AssertionError: You do not have CLIP state dict! You do not have CLIP state dict!错误，没有图片显示就提示这个错误

I was having this issue today. It turns out you can't use the "official" flux model from their huggingface page. You should use one of the mentioned models from lllyasviel's huggingface page

**Comment by kenny00968** [comment]
> > > 是的，只需使用以下模型之一：
> > > 
> > > * [flux1-dev-bnb-nf4-v2.safetensors](https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/blob/main/flux1-dev-bnb-nf4-v2.safetensors) 在 NF4 中具有主模型的完整 flux-dev 检查点。<- 推荐
> > > * [flux1-dev-fp8.safetensors](https://huggingface.co/lllyasviel/flux1_dev/blob/main/flux1-dev-fp8.safetensors) FP8 中带有主模型的完整 flux-dev 检查点。
> > 
> > 
> > 有模型，但运行SD3模型或者flux模型就会出现AssertionError： You do not have CLIP state dict！You do not have CLIP state dict！错误，没有图片显示就提示这个错误
> 
> 我今天遇到了这个问题。事实证明，您不能使用他们 huggingface 页面上的“官方”通量模型。您应该使用 lllyasviel 的 huggingface 页面中提到的模型之一

SD3模型也用不了，你的可以用吗？我把SD3模型的CLIP文件放在Forge版的models也用不了，也是提示同样的错误，其他的模型却可以正常使用

**Comment by yamfun** [comment]
if you use the nf4v2, you don't have to do anything.

if you use the others like the q4_0, in the VAE/Text Encoder, you fill in stuff like  clip_l.safetensors ae.safetensors 
 t5xxl_fp8_e4m3fn.safetensors  (ae, clip_l and any t5 I guess).

if that dropdown have no such option, you download them and put it in the clip and vae folders first

**Comment by CyDefUnicorn** [comment]
> if you use the nf4v2, you don't have to do anything.
> 
> if you use the others like the q4_0, in the VAE/Text Encoder, you fill in stuff like  clip_l.safetensors ae.safetensors 
>  t5xxl_fp8_e4m3fn.safetensors  (ae, clip_l and any t5 I guess).
> 
> if that dropdown have no such option, you download them and put it in the clip and vae folders first
> 

I'm assuming v2 has all those already baked in then

**Comment by kenny00968** [comment]
我找到答案了，是因为“官方”的FLUX模型和webui forge版作者的FLUX模型不一样（也有可能不支持“官方”的模型，我试过把SD3模型和所需文件放进去也会这样报错）,所以，当你使用“官方”版的FLUX模型就会报错，才会提示“AssertionError: You do not have CLIP state dict!
You do not have CLIP state dict!”这样的错误，希望能帮到你~

**Comment by bbecausereasonss** [comment]
Wait so, you can only use an NF4 model but you can't use Lora with it?

**Comment by madrooky** [comment]
> Same here 1060 3GB VRAM. 
> ... or blue screen and PC resets.

Even the fp8 variants use way more memory. Got 32gb ram and 12gb vram and both is maxed out and i am not sure how much data is shifted to ssd page file. No surprise you PC gives up trying to load these.

**Comment by Nabby109** [comment]
I got that error until I figured out how to add all the extra files. If you're using the official models, you also need to have their vae called ae.safetensors in your models/vae folder, and their text encoders clip_l.safetensors, t5xxl_fp8_e4m3fn.safetensors, and t5xxl_fp16.safetensors in your models/text_encoders folder. Then you select all of them in the vae/text encoder drop down in forge. I've used both the official fp8 and fp32 on my 4090 with great results. The fp8 version is really no slower than SDXL, but the fp32 version runs out of gpu memory and does a little song and dance with it that takes a couple minutes - but on the plus side it still finishes.

![Screenshot 2024-08-27 115646](https://github.com/user-attachments/assets/f48179ca-d397-48cf-9a8d-8c218f388773)

**Comment by ewebgh33** [comment]
Came here from a google search with same issues
Thanks @Nabby109 for this explanation
I don't know why the Blackforest HF page doesn't tell anyone this!!

**Comment by djsolidsnake86** [comment]
> @kenny00968 yes, just use one of these models:
> 
>     * [flux1-dev-bnb-nf4-v2.safetensors](https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/blob/main/flux1-dev-bnb-nf4-v2.safetensors) Full flux-dev checkpoint with main model in NF4. <- Recommended
> 
>     * [flux1-dev-fp8.safetensors](https://huggingface.co/lllyasviel/flux1_dev/blob/main/flux1-dev-fp8.safetensors) Full flux-dev checkpoint with main model in FP8.

hello why you recommend the nf4?
also which other plugins and loras you suggest to use with the nf4 version? thanks

**Comment by Nabby109** [comment]
> > @kenny00968 yes, just use one of these models:
> > ```
> > * [flux1-dev-bnb-nf4-v2.safetensors](https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/blob/main/flux1-dev-bnb-nf4-v2.safetensors) Full flux-dev checkpoint with main model in NF4. <- Recommended
> > 
> > * [flux1-dev-fp8.safetensors](https://huggingface.co/lllyasviel/flux1_dev/blob/main/flux1-dev-fp8.safetensors) Full flux-dev checkpoint with main model in FP8.
> > ```
> 
> hello why you recommend the nf4? also which other plugins and loras you suggest to use with the nf4 version? thanks

NF4 is the next generation of the Flux model. It is engineered to be faster and more accurate than the initial version.

**Comment by adnanbaqi** [comment]
All you need to know, files to download and path to save to is here https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1050

**Comment by ivans80** [comment]
> I moved my clip_l.safetensors, and t5xxl_fp16.safetensors to the VAE folder, then selected the three optionsin the VAE/Text Encoder box and got it running. It is sloooooow though. right now it is taking about 3-5 minutes from the time I click Generate to the time it finishes. I will probably play around with the settings and see if I can get it to speed up a little. ![Screenshot 2024-08-14 105325](https://private-user-images.githubusercontent.com/93754847/357918849-0c24060d-25d7-4ef2-9685-53dcc5a14372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4ODcwMTgsIm5iZiI6MTcyOTg4NjcxOCwicGF0aCI6Ii85Mzc1NDg0Ny8zNTc5MTg4NDktMGMyNDA2MGQtMjVkNy00ZWYyLTk2ODUtNTNkY2M1YTE0MzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDIwMDUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MjUxYTgxODJiMmUyYzYxNGM1NjlhYTZlOTMyN2Y2ZTRkMTQ0MDhhMDdkMTczOTE0MDc2YTAzMDg2OTI4ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qYpQu5_cQ9FZzVFC6O0C9dsLhkXabB7zdZVGm79IiAM)

You can install xformers if you don't and as I read, some users reported faster rendering if you set Swap method to Async and Swap Location to shared. But when I tried it, I got pc crash

**Comment by ivans80** [comment]
> Wait so, you can only use an NF4 model but you can't use Lora with it?

You can use Lora

> I moved my clip_l.safetensors, and t5xxl_fp16.safetensors to the VAE folder, then selected the three optionsin the VAE/Text Encoder box and got it running. It is sloooooow though. right now it is taking about 3-5 minutes from the time I click Generate to the time it finishes. I will probably play around with the settings and see if I can get it to speed up a little. ![Screenshot 2024-08-14 105325](https://private-user-images.githubusercontent.com/93754847/357918849-0c24060d-25d7-4ef2-9685-53dcc5a14372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4ODcwMTgsIm5iZiI6MTcyOTg4NjcxOCwicGF0aCI6Ii85Mzc1NDg0Ny8zNTc5MTg4NDktMGMyNDA2MGQtMjVkNy00ZWYyLTk2ODUtNTNkY2M1YTE0MzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDIwMDUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MjUxYTgxODJiMmUyYzYxNGM1NjlhYTZlOTMyN2Y2ZTRkMTQ0MDhhMDdkMTczOTE0MDc2YTAzMDg2OTI4ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qYpQu5_cQ9FZzVFC6O0C9dsLhkXabB7zdZVGm79IiAM)

clip_l and t5 go to models/text_encoder, not in models/VAE

**Comment by Nabby109** [comment]
> > @kenny00968yes, just use one of these models:
> > ```
> > * [flux1-dev-bnb-nf4-v2.safetensors](https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/blob/main/flux1-dev-bnb-nf4-v2.safetensors) Full flux-dev checkpoint with main model in NF4. <- Recommended
> > 
> > * [flux1-dev-fp8.safetensors](https://huggingface.co/lllyasviel/flux1_dev/blob/main/flux1-dev-fp8.safetensors) Full flux-dev checkpoint with main model in FP8.
> > ```
> 
> hello why you recommend the nf4? also which other plugins and loras you suggest to use with the nf4 version? thanks

I am now personally using and recommending the Q8 GGUF version as well as the experimental Quantized version of the T5 encoder. From what I have seen it performs better than the NF4.

**Comment by djsolidsnake86** [comment]
> > > @kenny00968yes, just use one of these models:
> > > ```
> > > * [flux1-dev-bnb-nf4-v2.safetensors](https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/blob/main/flux1-dev-bnb-nf4-v2.safetensors) Full flux-dev checkpoint with main model in NF4. <- Recommended
> > > 
> > > * [flux1-dev-fp8.safetensors](https://huggingface.co/lllyasviel/flux1_dev/blob/main/flux1-dev-fp8.safetensors) Full flux-dev checkpoint with main model in FP8.
> > > ```
> > 
> > 
> > hello why you recommend the nf4? also which other plugins and loras you suggest to use with the nf4 version? thanks
> 
> I am now personally using and recommending the Q8 GGUF version as well as the experimental Quantized version of the T5 encoder. From what I have seen it performs better than the NF4.

someone can confirm this?

**Comment by ivans80** [comment]
> > > > @kenny00968yes, just use one of these models:
> > > > ```
> > > > * [flux1-dev-bnb-nf4-v2.safetensors](https://huggingface.co/lllyasviel/flux1-dev-bnb-nf4/blob/main/flux1-dev-bnb-nf4-v2.safetensors) Full flux-dev checkpoint with main model in NF4. <- Recommended
> > > > 
> > > > * [flux1-dev-fp8.safetensors](https://huggingface.co/lllyasviel/flux1_dev/blob/main/flux1-dev-fp8.safetensors) Full flux-dev checkpoint with main model in FP8.
> > > > ```
> > > 
> > > 
> > > hello why you recommend the nf4? also which other plugins and loras you suggest to use with the nf4 version? thanks
> > 
> > 
> > I am now personally using and recommending the Q8 GGUF version as well as the experimental Quantized version of the T5 encoder. From what I have seen it performs better than the NF4.
> 
> someone can confirm this?

I can confirm that is not true, in my opinion. I don't see any difference in model load and render speed. And they are just slightly different in results, for mem sometimes q8 have better details, sometimes nf4. on picture bellow you can see those differences in some examples.

![Untitled-1](https://github.com/user-attachments/assets/a44239af-f117-490f-b709-49eda66e57e6)

**Comment by Nabby109** [comment]
> I can confirm that is not true, in my opinion. I don't see any difference in model load and render speed. And they are just slightly different in results, for mem sometimes q8 have better details, sometimes nf4. on picture bellow you can see those differences in some examples.

Actually most people I've previously discussed this with - the ones who convinced me to make the switch - have said the Q8 performs slightly slower than the NF4 but the Q8 gets enough of an advantage to prompt adherence and text handling to be worth that trade off. But it seems quite a lot of people are running these same comparisons and I think it's going to be hotly debated for some time. The differences are definitely minor and probably reveal themselves differently to users of various hardware - differences will be more pronounced on a 3090 ti than a 4090 for instance because of the 4090's higher memory clocks and Cuda cores. 

It doesn't feel terribly different from those of us who have been arguing that we prefer the sound of vinyl records over MP3's. There's definitely something there, but it's not something everyone is going to notice and it's not going to live up to the expectations of anyone whose primary priority is raw speed.

**Comment by ivans80** [comment]
> > I can confirm that is not true, in my opinion. I don't see any difference in model load and render speed. And they are just slightly different in results, for mem sometimes q8 have better details, sometimes nf4. on picture bellow you can see those differences in some examples.
> 
> Actually most people I've previously discussed this with - the ones who convinced me to make the switch - have said the Q8 performs slightly slower than the NF4 but the Q8 gets enough of an advantage to prompt adherence and text handling to be worth that trade off. But it seems quite a lot of people are running these same comparisons and I think it's going to be hotly debated for some time. The differences are definitely minor and probably reveal themselves differently to users of various hardware - differences will be more pronounced on a 3090 ti than a 4090 for instance because of the 4090's higher memory clocks and Cuda cores.
> 
> It doesn't feel terribly different from those of us who have been arguing that we prefer the sound of vinyl records over MP3's. There's definitely something there, but it's not something everyone is going to notice and it's not going to live up to the expectations of anyone whose primary priority is raw speed.

Honestly I downloaded Q8 after you said that give better results. So I wanted to see difference. I am hobbyst and don't need to make thousands of images, so personally I don't care about speed if something is slower, but better. Honestly I don't see any difference between these two checkpoints. To be honest I made 1 picture 896x1152 px. If we increase batch size or resolution, maybe in that case there will be difference in render speed.

About details...if I understand you good, you said that will be more differnce on lower VRAM? Well I have RTX 4060Ti with 16GB VRAM, maybe peoples with 3xxx series and 8Gb for example will really meet more differences, but I read on your post that you have 4090 and you are the one who said that Q8 performing better, so I made this comparison. Anyway, even with slight of difference, I am kind of person who will say: why not keep both checkpoints if I can?

**Comment by Nabby109** [comment]
What I meant was if there's a speed difference it's going to be more noticeable on a card with lower clocks and cores. If we say the speed difference between the two is 10% just to pull a number out of the air, 10% difference on a card that takes 10 seconds average to generate an image is going to be practically indistinguishable from just the standard variance from one generation to another. Whereas if it normally takes you a full minute to generate an image, that 10% is going to be more noticeable.
Barring that, Q8 vs NF4 is probably going to come down to personal preference. The real fun then is if you don't see a big difference between the 12gb Q8 or NF4 and the full 24gb dev fp16, maybe bump it down to the Q4 and see how you feel about the quality. There's a whole range Quantized model sizes to experiment with.
And the different sizes become a lot more useful for those of us who Lora train. If I train on the 6gb model I can fit a larger batch size, keep my latent stored in VRAM, etc. And then turn around and generate with the Lora on a Q8 with the only difference between the two models being the amount of quantization. (Though for the moment I'm training almost entirely on dev2pro)

**Comment by ivans80** [comment]
> What I meant was if there's a speed difference it's going to be more noticeable on a card with lower clocks and cores. If we say the speed difference between the two is 10% just to pull a number out of the air, 10% difference on a card that takes 10 seconds average to generate an image is going to be practically indistinguishable from just the standard variance from one generation to another. Whereas if it normally takes you a full minute to generate an image, that 10% is going to be more noticeable. Barring that, Q8 vs NF4 is probably going to come down to personal preference. The real fun then is if you don't see a big difference between the 12gb Q8 or NF4 and the full 24gb dev fp16, maybe bump it down to the Q4 and see how you feel about the quality. There's a whole range Quantized model sizes to experiment with. And the different sizes become a lot more useful for those of us who Lora train. If I train on the 6gb model I can fit a larger batch size, keep my latent stored in VRAM, etc. And then turn around and generate with the Lora on a Q8 with the only difference between the two models being the amount of quantization. (Though for the moment I'm training almost entirely on dev2pro)

Q4_1 (batch of 4)
![q4a](https://github.com/user-attachments/assets/649fe274-dcf2-4b68-a70f-f061f8b73f35)

NF4 (batch of 4)
![nf4a](https://github.com/user-attachments/assets/8a73bbf6-b441-495f-bf75-6c9f3ccaae82)

Q8_0 (batch of 4)
![q8a](https://github.com/user-attachments/assets/1af97930-626d-4d04-b530-3376d756f218)

Q8_0 (batch of 1)
![q8b](https://github.com/user-attachments/assets/dbb55c9a-9e50-4feb-9d94-2d66fcbfb33c)

I don't understand why I have weird speed with Q8 and batch of 4, especially because you said there is slight difference in speed between Q8 and Nf4. When I use Q8 and 1 image in batch, speed is ok and similar with other checkpoints.

Also Im tried Q4_1 and Q2_K and there are big difference between them and Q8. Also there are solid difference between Q4 and Q2. I tried to make wedding card, with frame made of roses, text with names, and wedding elements surround text. Q2 don't put any element in image, except wedding rings which render is very bad. Also, there are lot of noise around the roses frame. Q8 render image 10x better with same prompt

**Comment by hosseinrashidi75** [comment]
Download the ae.safetensors file and place it in the webui_forge\webui\models\VAE folder. Next, download the following two files:
t5xxl_fp8_e4m3fn_scaled.safetensors
clip_l.safetensors
and place them in the \webui_forge\webui\models\text_encoder folder
When using Flux in the Forge UI, in the VAE / Text Encoder drop-down tab,
select all three items and then click the Generate button.

Download links t5xxl_fp8_e4m3fn_scaled.safetensors ,clip_l.safetensors:

https://huggingface.co/comfyanonymous/flux_text_encoders/tree/main

Download link ae.safetensors:

https://huggingface.co/black-forest-labs/FLUX.1-schnell/tree/main

Download VAE for SDXL:

https://huggingface.co/stabilityai/sdxl-vae/tree/main
Location: webui_forge\webui\models\VAE

**Comment by pmcxgz** [comment]
> I got that error until I figured out how to add all the extra files. If you're using the official models, you also need to have their vae called ae.safetensors in your models/vae folder, and their text encoders clip_l.safetensors, t5xxl_fp8_e4m3fn.safetensors, and t5xxl_fp16.safetensors in your models/text_encoders folder. Then you select all of them in the vae/text encoder drop down in forge. I've used both the official fp8 and fp32 on my 4090 with great results. The fp8 version is really no slower than SDXL, but the fp32 version runs out of gpu memory and does a little song and dance with it that takes a couple minutes - but on the plus side it still finishes.
> 
> ![Screenshot 2024-08-27 115646](https://github.com/user-attachments/assets/f48179ca-d397-48cf-9a8d-8c218f388773)

Nicely worked!

**Comment by pythonwood** [comment]
solved.

same problem when testing sd3.5 (medium/large/turbo) in git branch 【sd35】
with: 
1 VAE/text_encode=clip_l + txx5 
2 (Sampler)   Sampling method=Euler 
3 Schedule type=Automatic

after I download clip_g and  use it and change automatic to SGM Uniform then error just go !



as  https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/2183 show

![Image](https://github.com/user-attachments/assets/ddfe4884-589d-428f-8da7-3b52490b703c)


what  i confuse is that why clip_g is necessory when clip_l is present?
