### ISSUE TITLE
Distilled CFG is not counted in Scripts: X/Y/Z Plot

### ISSUE THREAD

**Issue by ptits** [lllyasviel/stable-diffusion-webui-forge#1102]
Not possible to select Distilled CFG for making grids

**Comment by Degio64** [comment]
+1

**Comment by acezard** [comment]
Would be great to have that. It's a really powerful parameter from what I can see

**Comment by davidastgtciv** [comment]
Adding in a line for the option worked for me.

--- a/scripts/xyz_grid.py
+++ b/scripts/xyz_grid.py
@@ -243,6 +243,7 @@ axis_options = [
     AxisOption("Steps", int, apply_field("steps")),
     AxisOptionTxt2Img("Hires steps", int, apply_field("hr_second_pass_steps")),
     AxisOption("CFG Scale", float, apply_field("cfg_scale")),
+    AxisOption("Distilled CFG Scale", float, apply_field("distilled_cfg_scale")),^M
     AxisOptionImg2Img("Image CFG Scale", float, apply_field("image_cfg_scale")),
     AxisOption("Prompt S/R", str, apply_prompt, format_value=format_value),
     AxisOption("Prompt order", str_permutations, apply_order, format_value=format_value_join_list),
