### ISSUE TITLE
using UniPC with Flux gives no Results (Noise Images)

### ISSUE THREAD

**Issue by void95** [lllyasviel/stable-diffusion-webui-forge#1108]
When Using UniPC with Flux i always get Images of Noise / no Results

**Comment by DenOfEquity** [comment]
Not all samplers are compatible with all models.

**Comment by gpl666** [comment]
> When Using UniPC with Flux i always get Images of Noise / no Results

Same problem here: in ComfyUI everything works with any sampler using the standard KSampler node, i can't understand why in Forge this doesn't happen, i can only use the "[Forge] Flux realistic" samplers, UniPC is my favorite sampler so this is really sad...
