### ISSUE TITLE
No Negative Prompt for SDXL with CFG1 

### ISSUE THREAD

**Issue by void95** [lllyasviel/stable-diffusion-webui-forge#1115]
Is it normal that there is no neg. Prompt for SDXL with CFG 1 , im using a hyper/turbo model and it uses CFG1 but i cant set a neg. prompt.

**Comment by michP247** [comment]
1802850

**Comment by rabidcopy** [comment]
Generally negative prompts are ineffective on Hyper/Turbo/Lightning models with the exception of the CFG-preserved Hyper-SD loras which are meant to be used with non-1 CFG. At 1 CFG negative prompts essentially have no effect. Thus at 1 CFG it is better to not process the negative prompt at all as it just slows down inference to no benefit.
