### ISSUE TITLE
[Bug]: IP adapters won't work

### ISSUE THREAD

**Issue by aolko** [lllyasviel/stable-diffusion-webui-forge#112]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Getting
```
ValueError: Query/Key/Value should either all have the same dtype, or (in the quantized case) Key/Value should have dtype torch.int32
      query.dtype: torch.float16
      key.dtype  : torch.float32
      value.dtype: torch.float32
```
on generation with 2 controlnets with `ip-adapter`.

### Steps to reproduce the problem

1. Set the controlnet as follows and upload non-square image
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/581458/b1b502b8-f54f-4149-9e54-bbcecc1f6c51)
2. Press `Generate`

### What should have happened?

Normal image generation

### What browsers do you use to access the UI ?

Google Chrome, Other

### Sysinfo

[sysinfo-2024-02-07-19-14.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14200517/sysinfo-2024-02-07-19-14.json)

### Console logs

```Shell
pinokio cuts logs, sorry
https://paste.ee/p/3sUzP
```

**Comment by lllyasviel** [comment]
update and try again?

**Comment by aolko** [comment]
> update and try again?

Now they work. How well do ip-adapters and references work with "Batch upload"?
