### ISSUE TITLE
ReActor extension no longer working after update

### ISSUE THREAD

**Issue by EuroCluddy** [lllyasviel/stable-diffusion-webui-forge#1135]
After the most recent Forge update, it still shows it's installed in the extensions list, but it seems to be hidden in the main ui list
<img width="1116" alt="Screenshot 2024-08-15 at 09 41 00" src="https://github.com/user-attachments/assets/d7646586-6e4b-4a5a-85c1-d78145172736">
<img width="1159" alt="Screenshot 2024-08-15 at 09 41 37" src="https://github.com/user-attachments/assets/32799561-26aa-43c5-8b75-8d103d4a103b">

**Comment by maciekmasiul** [comment]
I also have a problem with Reactor. It generally works but there is a problem with the user interface. For example, I cannot use the face model.
![Przechwytywanie](https://github.com/user-attachments/assets/86dd4611-73b6-46d4-b153-c8bb6b58b2bf)
![cmd](https://github.com/user-attachments/assets/e2ec8ea4-e4f8-4c05-a89e-a41384a1ac8c)

**Comment by EuroCluddy** [comment]
Snap. I forgot about that. Pre-vanishing from my UI completely, I also had this problem

**Comment by DenOfEquity** [comment]
Three installs seems excessive? About two too many.
There have been lots of updates in last few minutes/hours - possible something temporarily broke.
ReActor is displaying and working for me, fully updated. Run **update.bat** in forge directory. If that doesn't help, check console for errors.

Some other common ReActor problems have been already been discussed and solved:
selecting face models: https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/889#issuecomment-2257289510
onnxruntime error: https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/906#issuecomment-2264387863

**Comment by maciekmasiul** [comment]
Thank you [DenOfEquity](https://github.com/DenOfEquity)
The solution you linked worked.

**Comment by EuroCluddy** [comment]
> "Three installs seems excessive? About two too many" to change multiple faces at once, it's extremely handy. Not a triple install, just a duplication of the original folder gives you three available reactor slots. 

Many thanks for the great feedback  👍
