### ISSUE TITLE
A1111 Extension "OneButtonPrompt" doesn't work

### ISSUE THREAD

**Issue by pyros-sd-models** [lllyasviel/stable-diffusion-webui-forge#1138]
How to reproduce:

Install Forge
Install OneButtonPrompt

Choose OneButtonPrompt under Scripts

Choose OneButtonPrompt Preset

It results in this:

![Screenshot 2024-08-12 115722](https://github.com/user-attachments/assets/1109d159-8342-40d0-a7a8-f319bbfaeb19)

The extension still works, just the UI won't display the presets, which make them hard to edit.
No issues with A1111.

I love this extension. Hopefully something can be done about it! Ty!

**Comment by DenOfEquity** [comment]
Errors because the extension is written for Gradio3, but new Forge uses Gradio4. Extension needs update, author has it on their todo list.
https://github.com/AIrjen/OneButtonPrompt/issues/214

**Comment by pyros-sd-models** [comment]
Well then I'm closing this issue! Thanks for pointing it out! I'm stupid that I didn't think of it myself, even tho I just recently did a gradio 3 to 4 upgrade myself, haha
