### ISSUE TITLE
sd-civitai-browser-plus, model info not loading, missing icons, 

### ISSUE THREAD

**Issue by angomania** [lllyasviel/stable-diffusion-webui-forge#1143]
Extension CivitAi Browser +
- Model info not loading
- missing Icons in CivitAi Browser tab
- also other functions on the ui are not working. For example: mouse click to enlarge the rendered picture

I´ve installed only this plugin. Everything else is default installation.
![1111](https://github.com/user-attachments/assets/d257f763-d6cc-4c6e-80d6-52032cf6e63f)
![11112](https://github.com/user-attachments/assets/93f719c0-3bb0-4806-9739-2c3273b68418)

**Comment by Synergyart** [comment]
Same here! Also `sd-webui-tagcomplete` stops working when Civitai Browser is on and the settins tab gets screw too.

I get this error on the console.
```
E:\FORGE CUDA 12.4\webui\extensions\sd-civitai-browser-plus\scripts\civitai_gui.py:204: GradioDeprecationWarning: unexpected argument for Button: label
  refresh = gr.Button(label="", value="", elem_id=refreshbtn, icon="placeholder")
```

![Captura de pantalla 2024-08-17 155621](https://github.com/user-attachments/assets/3134de1c-544b-45bf-9523-4c7103ee3ba3)
![Captura de pantalla 2024-08-17 155528](https://github.com/user-attachments/assets/bbdf3839-bd3b-4b05-83c0-4d75c9d89c83)

**Comment by angomania** [comment]
...yes, I noticed that too.

**Comment by ewirtz65** [comment]
Same issue,  never returns info, just sits on loading forever

**Comment by Psokratease** [comment]
Same... I hope this issue gets some attention.

**Comment by angomania** [comment]
> Same... I hope this issue gets some attention.

The tool is great for plugins info

**Comment by DenOfEquity** [comment]
Fixed by extension update.
