### ISSUE TITLE
AssertionError: You do not have VAE state dict! You do not have VAE state dict! when using GGUF?

### ISSUE THREAD

**Issue by Telllinex** [lllyasviel/stable-diffusion-webui-forge#1150]
Maybe i am blind but how to fix this?

**Comment by Akis-M** [comment]
You need to select clip_l and t5xxl_fp16 or fp8 in the text encoder section

**Comment by Telllinex** [comment]
> You need to select clip_l and t5xxl_fp16 or fp8 in the text encoder section to work with any flux dev variant model (which the GGUF quants are)

I did select clip-l and fp8 t5xxl and still this error showed up

**Comment by Telllinex** [comment]
> It should look like this: ![image](https://private-user-images.githubusercontent.com/131813549/358275215-e1e23a28-8bc6-4def-aa7e-3375e539ad97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MzYwMTUsIm5iZiI6MTcyMzczNTcxNSwicGF0aCI6Ii8xMzE4MTM1NDkvMzU4Mjc1MjE1LWUxZTIzYTI4LThiYzYtNGRlZi1hYTdlLTMzNzVlNTM5YWQ5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxNTI4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDFmYTcwNDEzMWYyMjlmMTc2NzMyNDc4ZTlkMjU2YjU5NzNhZWQxYjU3YWE1YmVhNDViODA3M2QyMGE0YTNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rk-twSAkpB70n3EZIY6tw2YcYE3k-RIRTlAu9KbWyXw)

Thanks, it worked after adding ae.st

**Comment by ZeroCool22** [comment]
> It should look like this: ![image](https://private-user-images.githubusercontent.com/131813549/358275215-e1e23a28-8bc6-4def-aa7e-3375e539ad97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3Mzk1NzQsIm5iZiI6MTcyMzczOTI3NCwicGF0aCI6Ii8xMzE4MTM1NDkvMzU4Mjc1MjE1LWUxZTIzYTI4LThiYzYtNGRlZi1hYTdlLTMzNzVlNTM5YWQ5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxNjI3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWE4Y2MxNTU3MmZiMDMzNGJlM2U0NzExMzI0MzViMjVkOGE3MGM1Y2UyZmE5YWU5ZDUyNTlhMDVjMGVjYTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XgnAeSfKXMeuRWMxbxcZ7ED-GS2zmbUVu1dRA2Py8t8)

From where i get **ae.safetensor**?

**Comment by parthwagh9999** [comment]
> > It should look like this: ![image](https://private-user-images.githubusercontent.com/131813549/358275215-e1e23a28-8bc6-4def-aa7e-3375e539ad97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3Mzk1NzQsIm5iZiI6MTcyMzczOTI3NCwicGF0aCI6Ii8xMzE4MTM1NDkvMzU4Mjc1MjE1LWUxZTIzYTI4LThiYzYtNGRlZi1hYTdlLTMzNzVlNTM5YWQ5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxNjI3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWE4Y2MxNTU3MmZiMDMzNGJlM2U0NzExMzI0MzViMjVkOGE3MGM1Y2UyZmE5YWU5ZDUyNTlhMDVjMGVjYTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XgnAeSfKXMeuRWMxbxcZ7ED-GS2zmbUVu1dRA2Py8t8)
> 
> From where i get **ae.safetensor**?

use huggingface or comfyui guide on flux
