### ISSUE TITLE
Unexpected error: Processing could not begin

### ISSUE THREAD

**Issue by nailz420** [lllyasviel/stable-diffusion-webui-forge#1170]
Using Flux, multiple different models. Started happening after successfully generating 1 batch, Restarting webui doesn't resolve the issue. The expectation is that at least the error should be a lot more informative.

2024-08-15 22:33:35 INFO [modules.shared_state] Starting job task(va04fsvmzmy9jfi)
X/Y/Z plot will create 0 images on 1 0x1 grid; 2 images per cell. (Total steps to process: 0)
Unexpected error: Processing could not begin, you may need to refresh the tab or restart the service. 0it [00:00, ?it/s]
Total progress: 0it [00:00, ?it/s]
2024-08-15 22:33:35 INFO [modules.shared_state] Ending job task(va04fsvmzmy9jfi) (0.03 seconds)

version: [f2.0.1v1.10.1-previous-298-g243952f3](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/243952f3642162b27ab2f2561048020eb162a5d8)  •  python: 3.10.6  •  torch: 2.3.1+cu121  •  xformers: N/A  •  gradio: 4.40.0  •  checkpoint: [a8038adff1](https://google.com/search?q=a8038adff1ec920863d4a27b06b1fb2f0c92fa50cd7cc5029b6848df8aca69fa)

**Comment by DenOfEquity** [comment]
The console reports this message if `X/Y/Z plot` script is enabled without any settings being entered.
