### ISSUE TITLE
Flux over API?

### ISSUE THREAD

**Issue by bkev** [lllyasviel/stable-diffusion-webui-forge#1176]
Sorry if I've got this completely wrong but I've been able to connect Forge to Openweb-ui via the Openweb-ui settings via the Forge API. This works, connects and loads models. 
If I select a non-flux model, I am able to generate images in Openweb-ui.

If I select a Flux model (a restart of Forge is needed as changing the model in Openweb-ui doesn't seem to take effect unless Forge is restarted) and try to generate an image it is just a black square. I can see an error of "\ForgeUI\webui\modules\processing.py:1003: RuntimeWarning: invalid value encountered in cast
  x_sample = x_sample.astype(np.uint8)"

Does Openweb-ui need to support a particular API for the Flux model to work?

**Comment by redfoo22** [comment]
Been getting black square for 2 days now via api. Curl doesn't work either. Anybody????

**Comment by adnanbaqi** [comment]
A sample code would be helpful i am trying to generate images but they all are blurry

**Comment by andrew-j-m** [comment]
Here's some code...

```
import requests
import io
import base64
from PIL import Image

url = "http://127.0.0.1:7860"
requests.get(url=f"{url}/sdapi/v1/sd-models")
option_payload = {
    "sd_model_checkpoint": "Flux1-Dev BNB NF4 v2.safetensors",
    "CLIP_stop_at_last_layers": 2
}
requests.post(url=f"{url}/sdapi/v1/options", json=option_payload)
payload = {
    "prompt": "a wizard casting a spell",
    "batch_size": 1,
    "steps": 20,
    "seed": -1,
    "distilled_cfg_scale": 3.5,
    "cfg_scale": 1,
    "width": 1024,
    "height": 1024,
    "sampler_name": "Euler",
    "scheduler": "Simple"
}
response = requests.post(url=f"{url}/sdapi/v1/txt2img", json=payload)
r = response.json()
x = 1
i = r['images'][0]
image = Image.open(io.BytesIO(base64.b64decode(i.split(",",1)[0])))
image.save("image.jpg")
```
![image](https://github.com/user-attachments/assets/48abbc38-1294-449a-90a9-d1b638d5ea17)
