### ISSUE TITLE
The image quality generated by flux nf4 v2 is very bad

### ISSUE THREAD

**Issue by martjay** [lllyasviel/stable-diffusion-webui-forge#1199]
I'm not very good at using this model, but the images generated by Forge are really bad and unacceptable. I see that the images you generate are very clear. Why? Who can tell me how to do?

![00001-3790620460](https://github.com/user-attachments/assets/f8b4a399-eabf-4b26-abb3-d94ab600a134)

![00001-3790620461](https://github.com/user-attachments/assets/c1a201e7-dcf0-44e6-9863-56b91b89147a)

**Comment by martjay** [comment]
Yesterday, I used Forge to generate some high-definition images, but I also found an issue where the images always force background blurring. How should I adjust the degree of blurring or turn off the blurring effect?

![00019-3565085270](https://github.com/user-attachments/assets/32e47a27-3515-47dd-ba7f-6e78adafb494)
![00020-3464440842](https://github.com/user-attachments/assets/655420dd-f2d0-4ebd-be3c-0a6bc252e6e7)
![00022-1335292795](https://github.com/user-attachments/assets/2174d423-8a44-4912-8b36-cb5ce8093d9e)
![00023-969753322](https://github.com/user-attachments/assets/fbaaa5ac-bdb5-4400-b301-568917f2af3e)
![00024-4159000574](https://github.com/user-attachments/assets/ad46536e-8d32-4d63-af5f-9203d117887a)

**Comment by martjay** [comment]
You should be able to see the noise in the picture, right? How should I remove noise? Before generation rather than post-processing.

**Comment by DenkingOfficial** [comment]
First of all that's prompting issue, "night landscape" is not enough detailed prompt to make high quality image
For example:

Prompt: night landscape

![image](https://github.com/user-attachments/assets/07c96ab6-228f-4903-be43-be80962b2211)

Prompt: A serene nightscape photograph featuring a stunning full moon dominating the sky, surrounded by a tapestry of twinkling stars. The moon casts a brilliant blue glow on the landscape below, illuminating a tranquil body of water that mirrors the lunar beauty. In the foreground, a gentle grassy hill is nestled between trees, adding depth and texture to the scene. The silhouettes of distant mountains stand tall against the night sky, creating a sense of grandeur and wonder, while the horizon line offers a subtle separation between earth and sky. The image exudes an atmosphere of peaceful tranquility and awe-inspiring beauty.

![image](https://github.com/user-attachments/assets/f8f7aaef-43bb-46f5-a4cb-a86e91080f66)

Blur on images is how model was trained, try to experiment with your prompt

Also, you're using a model, which is 4x smaller than original weights, so there're drawbacks such as image quality degradation

I suggest you to use more complex prompts and maybe move from nf4 to GGUF model

**Comment by DenkingOfficial** [comment]
@TimmekHW show the settings you use

**Comment by TimmekHW** [comment]
> @TimmekHW show the settings you use

draw me a muscular girl dressed in a gorgeous dress, let the background be a post-apocalyptic world with bomb explosions, do it in the form of a poster in ultra high image quality
Steps: 20, Sampler: Euler, Schedule type: Beta, CFG scale: 1.0, Distilled CFG Scale: 3.5, Seed: 1975254845, Size: 896x1152, Model hash: d453394a25, Model: fluxRealisticV1_v10NF4FullModel, Beta schedule alpha: 0.6, Beta schedule beta: 0.6, Version: f2.0.1v1.10.1-previous-459-gd3396001
![image](https://github.com/user-attachments/assets/7875c63c-684d-4f31-8a81-80c25874c219)

**Comment by HMRMike** [comment]
> > @TimmekHW show the settings you use
> 
> draw me a muscular girl dressed in a gorgeous dress, let the background be a post-apocalyptic world with bomb explosions, do it in the form of a poster in ultra high image quality Steps: 20, Sampler: Euler, Schedule type: Beta, CFG scale: 1.0, Distilled CFG Scale: 3.5, Seed: 1975254845, Size: 896x1152, Model hash: d453394a25, Model: fluxRealisticV1_v10NF4FullModel, Beta schedule alpha: 0.6, Beta schedule beta: 0.6, Version: f2.0.1v1.10.1-previous-459-gd3396001 

Maybe that's just how that fluxRealisticV1 checkpoint behaves. The demo images on civitai also exhibit such noise, even the fp16 version is showing that. Well, it's described as a test with minimal training after all.
https://civitai.com/images/24777724

With the same settings flux1-dev-bnb-nf4-v2 gives a much cleaner result.  
![00000-2404500107](https://github.com/user-attachments/assets/8d0ad2c9-e3f7-4d9c-a8a6-b24ad46581d7)

The Beta scheduler really likes more steps though.
![00001-2404500107](https://github.com/user-attachments/assets/023bff10-bd7a-49f6-919b-b459831e7847)
