### ISSUE TITLE
[Bug]: Dynamic Thresholding (CFG Scale Fix) not work

### ISSUE THREAD

**Issue by yamasoo** [lllyasviel/stable-diffusion-webui-forge#122]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Dynamic Thresholding (CFG Scale Fix) not work

### Steps to reproduce the problem

1. cfg=20
2. Dynamic Thresholding Mimic CFG Scale =7,
3. not work as fig
4
![2024-02-08 08 31 19](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/73381291/e075c974-1809-4ce0-858a-9b616ce983ff)
![2024-02-08 08 31 42](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/73381291/9b0d9d85-2344-48a5-84cb-d6fbd5fb72ac)

### What should have happened?

shuld be work

### What browsers do you use to access the UI ?

Google Chrome, Microsoft Edge

### Sysinfo

[sysinfo-2024-02-08-06-19.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14205003/sysinfo-2024-02-08-06-19.json)

### Console logs

```Shell
cant see anything wrong


                                                                                                                       To load target model BaseModel                                                                   | 0/12 [00:00<?, ?it/s]
Begin to load 1 model
unload clone 2
Moving model(s) has taken 0.57 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.45it/s]
Upscale script freed memory successfully.█████████████████████▎                        | 20/32 [00:04<00:01,  7.16it/s]
tiled upscale: 100%|███████████████████████████████████████████████████████████████████| 12/12 [00:01<00:00,  7.73it/s]
To load target model BaseModel
Begin to load 1 model
unload clone 1
Moving model(s) has taken 0.51 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:04<00:00,  2.80it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 32/32 [00:12<00:00,  2.53it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 32/32 [00:12<00:00,  2.66it/s]To load target model BaseModel                                                                   | 0/12 [00:00<?, ?it/s]
Begin to load 1 model
unload clone 2
Moving model(s) has taken 0.54 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.17it/s]
Upscale script freed memory successfully.█████████████████████▎                        | 20/32 [00:04<00:01,  7.02it/s]
tiled upscale: 100%|███████████████████████████████████████████████████████████████████| 12/12 [00:01<00:00,  7.57it/s]
```

**Comment by lllyasviel** [comment]
Dynamic Thresholding is integrated now

**Comment by Neytiri7** [comment]
It will be reproduced the same in the latest version.
The integrated DT does not work, nor does the other DTs you have installed.

I checked and set it to work,
It's not working.

![A20240213_012539_445085-side](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/139053327/c256007a-80ff-4b37-9e36-e329ccd1bdf7)
