### ISSUE TITLE
Can the flux model be called through the API?

### ISSUE THREAD

**Issue by 128580359** [lllyasviel/stable-diffusion-webui-forge#1221]
Hello, I'm sorry to bother you. When I try to use the API to call flux's text2img and inpaint, I can't generate pictures normally (the image is completely black), but everything is normal when using the SDXL model. So I suspect that it is because of the unique structure of the flux model that the original API cannot work well. Can you fix the API so that the flux model can also call the API normally? Thank you very much for your work!

**Comment by vatsal2473** [comment]
i am facing the same issue, were you able to resolve it ?

**Comment by vatsal2473** [comment]
If you are using flux model then you need to pass scheduler as "Simple" in the api payload -

```
{
    "batch_size": 1,
    "cfg_scale": 1,
    "distilled_cfg_scale": 3.5,
    "height": 1152,
    "prompt": "a boy running",
    "sampler_name": "Euler",
    "scheduler": "Simple",
    "seed": -1,
    "steps": 20,
    "width": 896
}
```

**Comment by ositoMalvado** [comment]
Is there a Extension to never get OOM ? I’m trying call API but get memory error . When generating trough UI there is not problem

**Comment by ositoMalvado** [comment]
> Is there a Extension to never get OOM ? I’m trying call API but get memory error . When generating trough UI there is not problem

NVM, you can use
```Python
"Never OOM Integrated": {
    args: [
        {
            unet_enabled: true,
            vae_enabled: true,
        }
    ]
}
```

**Comment by ositoMalvado** [comment]
@lllyasviel any way to set GPU vram limit like as the WEB UI? but with API
