### ISSUE TITLE
[Bug]: v-pred checkpoint seems unable to be loaded correctly

### ISSUE THREAD

**Issue by whitesky1226** [lllyasviel/stable-diffusion-webui-forge#123]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

The checkpoint trained by **v-pred** method seems unable to be loaded correctly. In the original A1111 webui, the ckpt model can be loaded correctly and generates images normally by placing a yaml configuration file with the same name as the ckpt in the ckpt folder. However, this does not seem to work in the current Forge version. After switching to the **vpred** checkpoint, it only generates noise.

### Steps to reproduce the problem

1. Switching to a vpred checkpoint model.
2. Txt2img as normal.
3. A picture full of noise is generated.

### What should have happened?

The yaml file of the ckpt model is not loaded.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

none

### Console logs

```Shell
the original A1111 webui 1.7.0:

Loading model yiffymix_v41.safetensors [b8b4c24fb6] (2 out of 2)
Loading weights [b8b4c24fb6] from F:\AI-painting\AUTOMATIC1111-sd-webui\models\Stable-diffusion\yiffymix_v41.safetensors
Creating model from config: F:\AI-painting\AUTOMATIC1111-sd-webui\models\Stable-diffusion\yiffymix_v41.yaml
Loading VAE weights specified in settings: F:\AI-painting\AUTOMATIC1111-sd-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: sdp... done.
Model loaded in 4.1s (load weights from disk: 1.5s, create model: 0.3s, apply weights to model: 0.7s, load VAE: 0.3s, load textual inversion embeddings: 1.1s).

***************************************************************
the Forge version:

Loading weights [b8b4c24fb6] from F:\AI-painting\stable-diffusion-webui-forge\models\Stable-diffusion\yiffymix_v41.safetensors
model_type EPS
UNet ADM Dimension 0
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
Loading VAE weights specified in settings: F:\AI-painting\stable-diffusion-webui-forge\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
To load target model SD1ClipModel
Begin to load 1 model
Model loaded in 4.9s (unload existing model: 1.0s, load weights from disk: 1.3s, forge load real models: 1.3s, load VAE: 0.3s, load textual inversion embeddings: 0.9s).
```

**Comment by V1Htor** [comment]
Same issue. Vpred models produce white images.

**Comment by lllyasviel** [comment]
give me an example model that i can test

**Comment by V1Htor** [comment]
> give me an example model that i can test

I use model + yaml + lyco from here https://rentry.org/5exa3

**Comment by lllyasviel** [comment]
update and try again

**Comment by whitesky1226** [comment]
Fixed. 谢谢😊

**Comment by V1Htor** [comment]
> update and try again

amazing speed!

**Comment by geriberton** [comment]
This issue seems to have resurfaced in the latest version of Forge.
