### ISSUE TITLE
Hires fix GUI section not obeying settings

### ISSUE THREAD

**Issue by Weatherby43** [lllyasviel/stable-diffusion-webui-forge#1247]
### Discussed in https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1154

<div type='discussions-op-text'>

<sup>Originally posted by **Weatherby43** August 15, 2024</sup>
I've noticed that if I go into the settings, and change the hires fix section to not show the prompts, but to show sampler scheduler and checkpoint drop downs, the UI doesn't obey. Even after restarting forge all together, it doesn't change anything. I still get the default setup under hires fix...  Can anyone point me in the direction of what I may be doing wrong, or if this is a gui bug? (I suspect it is not, because I recall original Forge and A1111 having this behavior too, but I can't remember how I fixed it, and I don't want to copy my config files over to the new version for fear of hosing something that's changed under the hood)</div>

The reproduction of this is quite simple: change the settings to show hires fix model and sampler and scheduler, uncheck show pos and neg prompt for hires. 

It doesn't change anything.

**Comment by unexpectedly** [comment]
As far as I can tell this fix does not address the checkpoint drop down? Something I very much miss.
