### ISSUE TITLE
Can't change clip skip value ?

### ISSUE THREAD

**Issue by ALBIHANY** [lllyasviel/stable-diffusion-webui-forge#1250]
Hi can somebody please help me find where can i change clip skip value on forge i normally add it through user interface on Automatic 1111 , but on forge it doesn't show up for some reason?

![image](https://github.com/user-attachments/assets/7a94b48c-ebb0-4792-bc3d-b77c64e46115)

![image](https://github.com/user-attachments/assets/aef97f40-1ed8-40b6-be24-198fc836d6f9)

**Comment by moudahaddad14** [comment]
me too, it didn't appear on top after applying it!

**Comment by ALBIHANY** [comment]
Unfortunately this is preventing me from using pony xl and some other models because they only work at clip skip 2 and there is no way to adjust that values with this issue !!!

**Comment by fraterinchristo** [comment]
sdxl_clip_l_skip in the quick settings

**Comment by fraterinchristo** [comment]
sdxl_clip_l_skip in the quick settings and you also need to change the UI to "sd" or "all"

**Comment by ALBIHANY** [comment]
> sdxl_clip_l_skip in the quick settings and you also need to change the UI to "sd" or "all"

Oh thank you so much, now i see it, you just made my day

**Comment by VictorHendricus** [comment]
> sdxl_clip_l_skip in the quick settings and you also need to change the UI to "sd" or "all"

hey, how do you change UI to sd? I cant find it. Thanks

**Comment by ALBIHANY** [comment]
> > sdxl_clip_l_skip in the quick settings and you also need to change the UI to "sd" or "all"
> 
> hey, how do you change UI to sd? I cant find it. Thanks

the check options before the checkpoint loader
