### ISSUE TITLE
It's too time-consuming to reload flux model every time generate an image

### ISSUE THREAD

**Issue by xldistance** [lllyasviel/stable-diffusion-webui-forge#1251]
![QQ截图20240818090949](https://github.com/user-attachments/assets/fb81d0d1-7d0b-4b6a-ae56-9e3d221bc499)

**Comment by pflky** [comment]
It's just swapping it from VRAM to SYSRAM, which is negligible in speed difference, while integral to keeping from having bugs and also for general memory management to keep garbage from collecting.

**Comment by andy8992** [comment]
> It's just swapping it from VRAM to SYSRAM, which is negligible in speed difference, while integral to keeping from having bugs and also for general memory management to keep garbage from collecting. Pretty much any system memory should be able to swap that in under a second.

yet it's saying, 5 to 6 seconds yea?

**Comment by Dampfinchen** [comment]
It takes much longer if you're just on the edge of using all your system ram. For me it adds almost 1 minute.

**Comment by andy8992** [comment]
> It takes much longer if you're just on the edge of using all your system ram. For me it adds almost 1 minute. If parts of the model were to be kept in VRAM, that would be a huge relief for my DRAM.

I had found a few optimization settings I didn't know about before, and if I use the taesd vae the model stays in memory most times and reloads a 10th of the time it seems. Quality takes a bit of a hit though but fiddling with parameters help mitigate that.

Still doesn't seem like this should be happening though.

**Comment by xldistance** [comment]
I set it to Swap Method:Async,Swap Location:Shared,now I don't have to reload the model every time!

**Comment by andy8992** [comment]
> I set it to Swap Method:Async,Swap Location:Shared,now I don't have to reload the model every time!

nice, i have to blindly tweak a lot of things to reduce this, I'm no expert in this field so its hard to know what to tweak on my specific system

my latest issue has been with the kmodel loading and unloading, something I changed helped this a lot but i can't even recall what it was i tried so many things
