### ISSUE TITLE
VAE -- You do not have VAE state dict!

### ISSUE THREAD

**Issue by Sup-Shero** [lllyasviel/stable-diffusion-webui-forge#1254]
I can't find VAE to load i tried to add it in commend as

--vae-dir "J:\Forge\stable-diffusion-webui-forge\models\VAE"

but there is no VEA to select

Edit: I only use forge for flux so there are no other vae in the folder I added some vea for XL and now I see them on the app

so the problem now is it can't recognize Flux VAE as .sft

**Comment by Tom-Neverwinter** [comment]
I think flux is picky on the vae it uses. the main one being ae.safetensors

**Comment by ali0une** [comment]
@Sup-Shero did you carefully read this https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1050 ?

**Comment by Sup-Shero** [comment]
I did just really stupid to think of it and really noob too

I just rename the file and it sees it now and works too 😂
