### ISSUE TITLE
Patching LoRAs for KModel:  99%|████████████████████████████████████████████████████▎| 300/304 [01:40<00:01,  2.36it/s]

### ISSUE THREAD

**Issue by Kr01iKs** [lllyasviel/stable-diffusion-webui-forge#1256]
And crashes.

**Comment by moudahaddad14** [comment]
**same but for me it crashes at 240/304**

**Comment by moudahaddad14** [comment]
@FLUX - NF4 uses a lot of RAM and VRAM when a LORA is being used. #1218

**Comment by moudahaddad14** [comment]
[https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1218](url)

**Comment by lllyasviel** [comment]
update and try again

**Comment by killerciao** [comment]
update and gives this error while using flux1-dev-bnb-nf4-v2.safetensors:
Patching LoRAs for KModel:  59%|█████▉    | 179/304 [00:02<00:02, 48.13it/s] ERROR lora diffusion_model.double_blocks.17.txt_mlp.2.weight CUDA out of memory. Tried to allocate 144.00 MiB. GPU 
Patching LoRA weights failed. Retrying by offload models.
Patching LoRAs for KModel: 100%|██████████| 304/304 [00:05<00:00, 51.52it/s]
if instead i use flux1-dev-fp8.safetensors, the lora load fine

**Comment by lllyasviel** [comment]
@killerciao does this give you image eventually? if it gives then i will just use this method

**Comment by killerciao** [comment]
> @killerciao does this give you image eventually? if it gives then i will just use this method

yes with flux1-dev-bnb-nf4-v2.safetensors after the errors,the image is generated,however without the effects of the lora

**Comment by Dampfinchen** [comment]
Is there a reason why this process is done at each generation? One time would be okay, but it does it each time after I click generate, making Loras pretty unusable for me.

**Comment by iqddd** [comment]
Still crashes.
```
Patching LoRAs for KModel:  44%|███████████████████████▎                             | 134/304 [00:03<00:03, 44.72it/s] ERROR lora diffusion_model.double_blocks.13.txt_mod.lin.weight Allocation on device
Patching LoRA weights failed. Retrying by offloading models.
Press any Key to Continue . . .
```
When this happens, other applications may crash or glitch.
If 'Enabled for UNet (always maximize offload)' is checked, OOM occurs with RAM instead of VRAM. (I have 32 GB of RAM)

**Comment by evelryu** [comment]
I have been using Forge to generate Flux (NF4 version) images, but when I use LoRAs in the prompt my computer freezes. This is the error:

Patching LoRAs for KModel: 52% 918 Patching LoRA weights failed. Retrying by offloading models.
Patching LoRAs for KModel: 92% | 280/304 [00:23408:02, 9.31it/s] ERROR Lora diffusion_model.single_blocks. weight Allocation on device
Patching LoRA weights failed. Retrying by offloading models.

The computer freezes after these lines. I can’t even take a screenshot, here's a photo: https://imgur.com/a/A10HvRt

The Lora is around 160mb

I have a 3060 12gb and 32gb ram.

**Comment by Vinfamy-New** [comment]
Same issue for me, can't use any Loras where it counts up to 304 (those that only count up to 76 work great though, fast patching too). Best I could get to was 270/304, then it stops counting, "Connection timeout" popup on the browser, then Press any key to continue ...

**Comment by AcademiaSD** [comment]
Same issue for me,

**Comment by YNWALALALA** [comment]
I also can't use those lora which count to 304(flux1-dev-bnb-nf4-v2)

**Comment by michael-shur** [comment]
same here... 
- image generated. but lora patching crashes at 298 of 304. 
- RTX3060 12GB VRAM, Win10 32GB RAM. 
- 5 different loras from 145MB to 700MB
- Flux Q4 Dev_0 .GGUF

venv "D:\models\venv_torch_2.3.2_cu_121.flux\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-351-g2f1d0475
Commit hash: 2f1d04759f36122cbb3553f0f0758755790624c7
Launching Web UI with arguments: --pin-shared-memory --cuda-malloc --cuda-stream --disable-xformers --ckpt-dir 'D:\models\Stable-diffusion' --lora-dir 'D:\models\Lora' --vae-dir 'D:\models\VAE' --embeddings-dir 'D:\models\embeddings' --controlnet-dir 'D:\models\controlnet' --esrgan-models-path 'D:\models\ESRGAN' --clip-models-path 'D:\models\clip' --device-id=0 --skip-load-model-at-start --autolaunch
Using cudaMallocAsync backend.
Total VRAM 12287 MB, total RAM 32719 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: True
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: D:\forge.flux\models\ControlNetPreprocessor
[-] ADetailer initialized. version: 24.8.0, num models: 10
2024-08-19 13:06:22,859 - ControlNet - INFO - ControlNet UI callback registered.
Model selected: {'checkpoint_info': {'filename': 'D:\\models\\Stable-diffusion\\FLUX_Q4_DEV_0.gguf', 'hash': '3f6d9145'}, 'additional_modules': ['D:\\forge.flux\\models\\text_encoder\\clip_l.safetensors', 'D:\\forge.flux\\models\\text_encoder\\t5xxl_fp8_e4m3fn.safetensors', 'D:\\models\\VAE\\FLUX_vae.safetensors'], 'unet_storage_dtype': None}
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 35.6s (prepare environment: 5.8s, import torch: 14.5s, initialize shared: 1.1s, other imports: 3.4s, list SD models: 0.6s, load scripts: 4.2s, create ui: 3.9s, gradio launch: 2.4s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
Loading Model: {'checkpoint_info': {'filename': 'D:\\models\\Stable-diffusion\\FLUX_Q4_DEV_0.gguf', 'hash': '3f6d9145'}, 'additional_modules': ['D:\\forge.flux\\models\\text_encoder\\clip_l.safetensors', 'D:\\forge.flux\\models\\text_encoder\\t5xxl_fp8_e4m3fn.safetensors', 'D:\\models\\VAE\\FLUX_vae.safetensors'], 'unet_storage_dtype': None}
[Unload] Trying to free 953674316406250018963456.00 MB for cuda:0 with 0 models keep loaded ...
StateDict Keys: {'transformer': 780, 'vae': 244, 'text_encoder': 196, 'text_encoder_2': 220, 'ignore': 0}
Using Detected T5 Data Type: torch.float8_e4m3fn
Using Detected UNet Type: gguf
Using pre-quant state dict!
Using GGUF state dict: {'F16': 476, 'Q4_0': 304}
Working with z of shape (1, 16, 32, 32) = 16384 dimensions.
K-Model Created: {'storage_dtype': 'gguf', 'computation_dtype': torch.bfloat16}
Model loaded in 127.3s (unload existing model: 0.3s, forge model load: 127.0s).
[LORA] Loaded D:\models\Lora\FLUX_fluxtastic_V2.safetensors for KModel-UNet with 494 keys at weight 1.0 (skipped 0 keys)
Skipping unconditional conditioning when CFG = 1. Negative Prompts are ignored.
To load target model JointTextEncoder
Begin to load 1 model
[Unload] Trying to free 7723.54 MB for cuda:0 with 0 models keep loaded ...
[Memory Management] Current Free GPU Memory: 11232.66 MB
[Memory Management] Required Model Memory: 5153.49 MB
[Memory Management] Required Inference Memory: 1024.00 MB
[Memory Management] Estimated Remaining GPU Memory: 5055.16 MB
Moving model(s) has taken 9.05 seconds
Distilled CFG Scale: 3.5
To load target model KModel
Begin to load 1 model
[Unload] Trying to free 9717.43 MB for cuda:0 with 0 models keep loaded ...
[Unload] Current free memory is 5963.33 MB ...
[Unload] Unload model JointTextEncoder
[Memory Management] Current Free GPU Memory: 11189.31 MB
[Memory Management] Required Model Memory: 6476.55 MB
[Memory Management] Required Inference Memory: 1024.00 MB
[Memory Management] Estimated Remaining GPU Memory: 3688.76 MB
Patching LoRAs for KModel:  98%|███████████████████████████████████████████████████▊ | 297/304 [00:16<00:00, 15.56it/s]ERROR lora diffusion_model.single_blocks.36.linear1.weight Allocation on device
Patching LoRA weights failed. Retrying by offloading models.
Patching LoRAs for KModel: 100%|█████████████████████████████████████████████████████| 304/304 [00:28<00:00, 10.82it/s]
LoRA patching has taken 28.10 seconds

**Comment by JuiceWill** [comment]
+1 on this issue - crashes Remote Desktop session, and freezes the PC for me too. 

Running on a 4090 with 24gb vram

**Comment by michael-shur** [comment]
I found on civitai small, 18MB Flux lora. If I start with that lora first, patching fails at around step 278-288 out of 304 (same as always no matter wghat size of the lora ). But image being generated and lora actually works - I use face lora that base checkpoint doesn't know. THEN I can generate 2nd image even with large, 800MB lora. Suddenly even lora patching works fine all the way down to last step 304. and everything works as it should. So it's not completely dead :)

**Comment by Samael-1976** [comment]
> I found on civitai small, 18 MB Flux lora. If I start with that lora first, patching fails at around step 278-288 out of 304 (same as always no matter what size of that lora ). But image being generated and lora actually works - I use face lora that base checkpoint doesn't know so I can be sure it worked. THEN I can generate 2nd image with other, large, even 800 MB lora. Suddenly even lora patching works fine all the way down to last step 304. and everything works as it should. So it's not completely dead :)

I've try your method, but with my 2060 and 12GB of vram, the patching arrive at 250 of 304, and after it crash

**Comment by iqddd** [comment]
The latest updates still don't fix the process. On Windows 11, 32 RAM and 16 VRAM it crashes due to OOM about midway through the process.
Is there any way to reduce memory and video memory consumption? Or maybe there is a way to pre-convert LORA to the desired format on a more memory-capable system?

**Comment by YNWALALALA** [comment]
18MB Lora is basically to count to 304.
I can now use Loras which is 36530kb, 47489kb, 51142kb.
These loras can be counted normally.（Because they are only about 100 counts）
The larger Lora also has problems with not being able to count to 304.

**Comment by markdee3** [comment]
304 steps is where i get the issues, regardless of mb size, even on 18mb

**Comment by Vinfamy-New** [comment]
I found the solution: under "Diffusion in Low Bits" (center-top of your screen), change it to "Automatic (fp16 LoRA)". Patching Loras will get to 304/304 (100%) instantly! And yes, the lora's will then work, even with flux1-dev-bnb-nf4-v2. How is that not the default setting!?

**Comment by Gravityhorse** [comment]
> I found the solution: under "Diffusion in Low Bits" (center-top of your screen), change it to "Automatic (fp16 LoRA)". Patching Loras will get to 304/304 (100%) instantly! And yes, the lora's will then work, even with flux1-dev-bnb-nf4-v2 and flux1-schnell-bnb-nf4.
> 
> How is that not the default setting!?

THIS IS THE SOLUTION
