### ISSUE TITLE
controlnet的功能比 Mikubill/sd-webui-controlnet 差远了

### ISSUE THREAD

**Issue by wodsoe** [lllyasviel/stable-diffusion-webui-forge#1271]
controlnet的功能比 Mikubill/sd-webui-controlnet 差远了，很多东西都没有，ipa那些样式啥都没

**Comment by kerizane** [comment]
Translated:

The function of controlnet is far worse than Mikubill/sd-webui-controlnet. It doesn’t have many things, and the styles of ipa don’t have anything.

**Comment by michael-shur** [comment]
important comment. so know we know that we have here one guy who knows how to use google translate and another still learning... anything else?

**Comment by kerizane** [comment]
Some changes are coming soon: https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/932
