### ISSUE TITLE
When I use flux1-dev-fp8, the resulting image is black

### ISSUE THREAD

**Issue by qw381523977** [lllyasviel/stable-diffusion-webui-forge#1291]
![微信截图_20240819211013](https://github.com/user-attachments/assets/8c65df5e-1567-450b-a31f-6b0cdf1eed28)
![微信截图_20240819210606](https://github.com/user-attachments/assets/341c02b4-7c5b-415a-b6e6-c78de5b37530)

**Comment by sunnyyangyangyang** [comment]
same issue with q4 model

**Comment by qw381523977** [comment]
> use the flux UI preset and make sure you use the right sampler (euler) and steps (dev 20 steps, schnell 4 steps) ![image](https://private-user-images.githubusercontent.com/11164997/359229024-4ac5991a-ac07-4ad3-bb8d-3ec6a76c839a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMDk1NjUsIm5iZiI6MTcyNDEwOTI2NSwicGF0aCI6Ii8xMTE2NDk5Ny8zNTkyMjkwMjQtNGFjNTk5MWEtYWMwNy00YWQzLWJiOGQtM2VjNmE3NmM4MzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDIzMTQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MjMwZDJiNWI0MmQzZjNjNDEyMDE3NzkwYjM3NGU5MzBlY2U4MDhiODc2YmI2NDdlZDc2MzhlZjQ1M2QzMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oL9aYA0gIwgx1-UlvizwLFO20qi8_yYylx5DxlQNZg4)

Yes, I'm sure I used the correct ui and sampling steps.

**Comment by sunnyyangyangyang** [comment]
> > use the flux UI preset and make sure you use the right sampler (euler) and steps (dev 20 steps, schnell 4 steps) ![image](https://private-user-images.githubusercontent.com/11164997/359229024-4ac5991a-ac07-4ad3-bb8d-3ec6a76c839a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMDk1NjUsIm5iZiI6MTcyNDEwOTI2NSwicGF0aCI6Ii8xMTE2NDk5Ny8zNTkyMjkwMjQtNGFjNTk5MWEtYWMwNy00YWQzLWJiOGQtM2VjNmE3NmM4MzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDIzMTQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MjMwZDJiNWI0MmQzZjNjNDEyMDE3NzkwYjM3NGU5MzBlY2U4MDhiODc2YmI2NDdlZDc2MzhlZjQ1M2QzMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oL9aYA0gIwgx1-UlvizwLFO20qi8_yYylx5DxlQNZg4)
> 
> Yes, I'm sure I used the correct ui and sampling steps.

it seems that this is due to webui\modules\process.py
try to open this file in a python ide such as vscode and webui is able to generate image with poor quality

**Comment by AllFatherAI** [comment]
Hey @qw381523977 how did you fixed that ?

**Comment by MysticDaedra** [comment]
Having the same issue, using a GGUF checkpoint, all my settings look identical to others with whom it is working. I see this was marked as completed... but I don't see a fix or a solution posted?

**Comment by qw381523977** [comment]
> 嘿，你是怎么解决这个问题的？

![微信截图_20240821144555](https://github.com/user-attachments/assets/f8ed15dd-809b-4c0d-a85c-6f4e505fd0b3)
 Use this package of VAE

**Comment by qw381523977** [comment]
> 遇到同样的问题，使用 GGUF 检查点，我的所有设置看起来都与它正在与之合作的其他人相同。我看到这被标记为已完成......但我没有看到发布的修复程序或解决方案？



> 遇到同样的问题，使用 GGUF 检查点，我的所有设置看起来都与它正在与之合作的其他人相同。我看到这被标记为已完成......但我没有看到发布的修复程序或解决方案？

Sorry, I haven't used the GGUF model, but you can try using the matching VAE and see if it solves your problem

**Comment by sunnyyangyangyang** [comment]
I reinstall windows so now I am able to generate images with latest version
