### ISSUE TITLE
Where can I download these models?

### ISSUE THREAD

**Issue by xxwx1574711709** [lllyasviel/stable-diffusion-webui-forge#1301]
![Uploading 微信截图_20240820011251.png…]()

**Comment by xxwx1574711709** [comment]
line 59, in load_huggingface_component
    assert isinstance(state_dict, dict) and len(state_dict) > 16, 'You do not have CLIP state dict!'
AssertionError: You do not have CLIP state dict!
You do not have CLIP state dict!

**Comment by Fretag** [comment]
I've seen that error today when trying to use some of the versions SDXL.
