### ISSUE TITLE
Where can I download these models?

### ISSUE THREAD

**Issue by xxwx1574711709** [lllyasviel/stable-diffusion-webui-forge#1302]
![微信截图_20240820011251](https://github.com/user-attachments/assets/55f75e70-2e22-47cf-bcab-b84a361e9ca5)

**Comment by xxwx1574711709** [comment]
Where can I download these models?

**Comment by navin-hariharan** [comment]
These are lora's

**Comment by DenOfEquity** [comment]
They are neither models nor loras. That's an option for inference, there's nothing to download.
