### ISSUE TITLE
birefnet downloads original image

### ISSUE THREAD

**Issue by gma-toronto** [lllyasviel/stable-diffusion-webui-forge#1311]
Birefnet processes just fine but when clicking the download arrow on the second box it download the origal image instead of the processed one.  
![Screenshot 2024-08-19 171529](https://github.com/user-attachments/assets/92d4111c-cef2-424b-b3f0-e4bd021d3e1b)

**Comment by danilomaiaweb** [comment]
same here

**Comment by kievhsiao** [comment]
same, but right-clicking and selecting "Save Image As." are ok.

**Comment by gma-toronto** [comment]
> same, but right-clicking and selecting "Save Image As." are ok.

I'm aware of that but I guess I made a mistake by assuming that it will give me an alpha Chanel.

**Comment by DenOfEquity** [comment]
explanation of what's happening here: https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1364
Right-click > Save does give an image with an alpha channel.
