### ISSUE TITLE
Hires fix: show hires checkpoint and sampler selection. Is not showing checkpoint option.

### ISSUE THREAD

**Issue by andy8992** [lllyasviel/stable-diffusion-webui-forge#1317]
How do I change models during highresfix step? Is this possible? Any other method available?

**Comment by justcoding88** [comment]
hires checkpoint is missing even if "Hires fix: show hires checkpoint and sampler selection" is ticked in settings & UI is re-started.

**Comment by Mirabilis1729** [comment]
Posted about this a few days back

https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1110

It would be nice if it got addressed however I expect FLUX has all the attention presently.

**Comment by DenOfEquity** [comment]
At the moment, this option is very thoroughly disabled - hidden, set to uninteractive, empty models list. 
A possible workaround is to generate without hires, change checkpoint, use the quick button to upscale using hires fix settings. Not ideal, admittedly.

**Comment by Cornmeister** [comment]
any updates on this issue ?

**Comment by Mirabilis1729** [comment]
> any updates on this issue ?

> This issue still persists. Please bring back functionality for this, it was a great feature.

Glad I'm not alone in this. I think because it wasn't on by default in A1111 a lot of people weren't even aware of it, or understood it but it was a fantastic way of generating unique outputs and its absence from Forge is rather lamentable.

**Comment by Langstonius** [comment]
this was literally the reason i used forge..

**Comment by Miniclash** [comment]
Same here, I switched to forge (and moved all my folders) before realizing this. Now I need to migrate back again...
