### ISSUE TITLE
[FLux.1 DEv] LoRA is Not Working After Latest Updates

### ISSUE THREAD

**Issue by Iory1998** [lllyasviel/stable-diffusion-webui-forge#1319]
2 days ago, I generated some images using the X-Labs' default flux_realism_lora.safetensors. I used it with the fp16 Flux, the GGUF-Q8 and the flux1-dev-bnb-nf4-v2.safetensors. It worked like a charm and the it enhances the quality of the images greatly. 
Today, I tried to regenerate the same images and lo and behold the images are so much different. I regenerate the images with and without the LoRA and I get the same image, which means that the LoRA is not working.

In console, I can clearly see that the LoRA is patching. The number of patches perhaps increased?
![image](https://github.com/user-attachments/assets/412e3cb9-548b-485a-a9c2-4011ae1d537b)

**Comment by Vagrin** [comment]
I'm having the same issue since updating except only in t2i. In i2i the lora I created on CivitAI works. Just a heads up in case there's an easy fix.

**Comment by Holyniwa** [comment]
I too have observed this, updated to latest commit: 5ecc525.
It will do all the necessary patching, but the output does not reflect any lora influence.

**Comment by lllyasviel** [comment]
LoRA works without problems. 

Give full console log and before/after images if it really has problems.

**Comment by Akis-M** [comment]
Noticed the same. Some LORAs work. Some don't.

**Comment by lllyasviel** [comment]
link to loras that do not work and give evidence (image with/without lora) that they are not working here: https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1038

and note that in 99% cases those are random user mistakes

**Comment by Holyniwa** [comment]
Well that's unfortunate. Sadly, I cant post any evidence of it, as forge will eat up all 32 gigs of ram of memory and if i so much as do anything, it could crash my PC. I can say it was working fine the day before, and i even used previously successful prompts before taking the time to post it here, but ya know, user errors. :\ Anyhow, I'm on a 3060 ti with 32gb of Ram. Using civit Loras and/or the realism_lora_FluxNF4 alone still didn't seem to activate the lora despite taking the time to patch. So, hope the extra info helps.
