### ISSUE TITLE
[Feature Request]: Enable CQ tests

### ISSUE THREAD

**Issue by huchenlei** [lllyasviel/stable-diffusion-webui-forge#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Enable CQ tests on repo. Only repo owner can perform this setup.

### Proposed workflow

https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

**Comment by lllyasviel** [comment]
but when i enable it i will immediately get lots of error spams in my account
but ok let me do it

**Comment by huchenlei** [comment]
You can delete the test config file from `.github` folder. I will do some local testsing and redo that config

**Comment by lllyasviel** [comment]
i think it is enabled let me know what other button i need to press
