### ISSUE TITLE
Dataset Tag Editor Extension missing

### ISSUE THREAD

**Issue by Maelstrom8** [lllyasviel/stable-diffusion-webui-forge#1320]
I used to have [Dataset Tag Editor](https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor) working with Forge, and somewhere along the path when I updated, it simply won't show up anymore in the UI. It was neat, better than Tagger. 

I do not know if it simply does not work anymore or if I messed up somewhere. I get [this](https://i.imgur.com/VAUiTYH.png) when running the bat file, which mentions errors relating the extension's config.py, dte_instance.py and main.py.

I don't normally report issues, and this isn't really a major issue, perhaps not even related to Forge, but is there maybe anything I can do or try?

**Comment by kievhsiao** [comment]
Same issue. It seems that after upgrading Gradio 4, some extensions are no longer supported. For now, I use both the 0.17 version for extensions and the new version of Forge.

**Comment by Maelstrom8** [comment]
> Same issue. It seems that after upgrading Gradio 4, some extensions are no longer supported. For now, I use both the 0.17 version for extensions and the new version of Forge.

This took a bit for me to understand, I was like "there is no 0.17 version of the Dataset Tag Editor". Anyway, yeah I'm doing this.. two installations of Forge (latest and Forge F0.0.17). One for generation, one for Dataset Tag Editing.

Either way, to be honest.. I just wanted a second opinion. This isn't really an issue with Forge, it's entirely a matter of "the author of an extension that doesn't work could probably update their extension". I'll close this.
