### ISSUE TITLE
lora not work on nf4?

### ISSUE THREAD

**Issue by WingeD123** [lllyasviel/stable-diffusion-webui-forge#1325]
loras (maybe some) make no different on images with nf4v2 ckpt.
I use Forge of 8-19 with commit 96f264e,
loras are: https://civitai.com/models/180891/flat-color-anime?modelVersionId=738709
https://civitai.com/models/633553?modelVersionId=708301
I did put trigger words in prompt, in console log shows "Patching LoRAs for KModel: 100%", but the images generated are same with/without lora.
I also tried gguf and fp8 unet, these loras work fine.

**Comment by WingeD123** [comment]
automatic (fp16 lora) selected during generation

**Comment by lllyasviel** [comment]
update and try again

**Comment by WingeD123** [comment]
> update and try again

lora works and generation is fast, thanks very much
