### ISSUE TITLE
Worse Flux performance on gtx 1060 6gb after updating.

### ISSUE THREAD

**Issue by CommanderGemini** [lllyasviel/stable-diffusion-webui-forge#1338]
Decided to update forge today to get bug fixes for some of the things that got broken with the flux update. And generation speeds dropped drastically on gtx 1060, changing torch version had no effect on generation speed.

For the time being i will just revert and stick to the commit : 9f6d263c3f3e07f2e7874263d36b528b887b3b26

On which 20 steps image using Flux1 Dev NF4 v2  checkpoint at 896x1152 takes about 8min30sec.

After updating, the generation speeds changed closer to 12-14 min per image at 896x1152 resolution. While 512x768 images went from 3min to around 4-4,5min.

**Comment by vixenius** [comment]
On 1080Ti as well

**Comment by ALBIHANY** [comment]
Yeap something happen to the performance after the last update

**Comment by nullesel** [comment]
Try setting the "GPU Weights (MB)" to something like 4096. This increased the generation speed on my 3070 Ti.

**Comment by punkerbeto** [comment]
The problem originated in commit b09c24e when Illyasviel introduced the fp16_fix.
You can fix the fix by editing the latest commit (31bed67 as of 8/21/24):

backend/nn/flux.py remove:
from backend.utils import fp16_fix
txt = fp16_fix(txt)
x = fp16_fix(x)

backend/utils.py remove:
def fp16_fix(x):
    # An interesting trick to avoid fp16 overflow
    # Source: https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1114
    # Related: https://github.com/comfyanonymous/ComfyUI/blob/f1d6cef71c70719cc3ed45a2455a4e5ac910cd5e/comfy/ldm/flux/layers.py#L180

    if x.dtype == torch.float16:
        return x.clip(-16384.0, 16384.0)
    return x

That's it! I went from 36s/it @ 1024x768 to 13s/it with nf4, 14s/it with Q4 gguf, and 14s/it with Q8. 

Hopefully this will get removed or fixed in future releases to save us GPU poor folk.

**Comment by CommanderGemini** [comment]
It seems to be fixed as of 852e88564c871ef640c12ac053e52234958653d8. Generation speeds are back to the old values.

**Comment by StanislawKarnacky** [comment]
@CommanderGemini my time not even close to that. 17-20 s/it with 512x768 :(
What is your settings? Could you share, please?

**Comment by tomudo** [comment]
> CommanderGemini
What kind of settings do you use to achieve "20 steps image using Flux1 Dev NF4 v2 checkpoint at 896x1152 takes about 8min30sec" ?

I test https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/9f6d263c3f3e07f2e7874263d36b528b887b3b26 as you mention on my GTX1060 but it is around 16 min.
