### ISSUE TITLE
XYZ Plot - Checkpoint Name gets ignored

### ISSUE THREAD

**Issue by RedDeltas** [lllyasviel/stable-diffusion-webui-forge#1343]
I've found that since updating my Forge that the Checkpoint Name gets ignored in XYZ plots. The plot still renders the Checkpoint Name but it's clearly not loading / changing the checkpoint.

Version Info:
```
Python 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
Version: f2.0.1v1.10.1-previous-363-g14ac95f9
Commit hash: 14ac95f9089a25171b30f3906f68613afa7abbfe
```
![Screenshot 2024-08-20 at 15 53 03](https://github.com/user-attachments/assets/8aadd337-606e-4a95-88ba-b416bd6f4947)
![Screenshot 2024-08-20 at 15 53 38](https://github.com/user-attachments/assets/48f744fb-c76a-4aba-a756-fe136601d0d6)

**Comment by hopperelec** [comment]
Having the same issue here
