### ISSUE TITLE
Add support for T5 gguf

### ISSUE THREAD

**Issue by ReyJ94** [lllyasviel/stable-diffusion-webui-forge#1349]
Hello i tried using flux with gguf T5 q5 k m. It was way faster than t5 fp8. Forge does not recognize gguf files when found in the text encoder folder. Could you please add support for it ?  I hope it would be easy since you already support gguf files.

**Comment by morganavr** [comment]
Would GGUF support for T5 reduce VRAM usage? If positive, then whole Flux could be fit into 8-10gb vram GPUs increasing generation speed.

**Comment by ReyJ94** [comment]
It does reduce Vram yes, but also the speed on which it takes into account the new text as you change prompts. In comfyui the difference it's night and day. I'm thinking in forge the speed would be quasi instant comparing to before (the time it takes to take a new prompt into account).

**Comment by morganavr** [comment]
Does Comfy already support GGUF T5? Maybe you could point to an appropriate commit to increase source code integration into Flux?

**Comment by aoleg** [comment]
> Does Comfy already support GGUF T5? Maybe you could point to an appropriate commit to increase source code integration into Flux?

SwarmUI also: https://github.com/mcmonkeyprojects/SwarmUI/issues/191

**Comment by lllyasviel** [comment]
Moved to https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1050#gguft5

Feel free to discuss in that thread if you find gguf t5 can have some advantages

**Comment by ReyJ94** [comment]
The advantage is that it is way faster.
