### ISSUE TITLE
Deforum extension is not showing up on Tab extensions

### ISSUE THREAD

**Issue by jd-paucar** [lllyasviel/stable-diffusion-webui-forge#1352]
As the title mentions the deforum extension is not showing up on tab extensions, anyone know how to solve it or with the same issue?

![image](https://github.com/user-attachments/assets/4a0ea7fb-4b1b-48b1-8a4b-5406e2844e39)
![image](https://github.com/user-attachments/assets/531b7044-33ac-4326-b0ec-e90f2d7bda20)

**Comment by optisynapsis** [comment]
I'm working on this, and have managed to get the Extension to show up as a tab in the UI at least.

It's more of a deforum for forge issue, but I'll update with progress.

**Comment by niknah** [comment]
Maybe the same problem as https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/919
The original deforum hasn't been updated for a while.

This one works ok for me...
https://github.com/Tok/sd-forge-deforum
