### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not str

### ISSUE THREAD

**Issue by Melyyn** [lllyasviel/stable-diffusion-webui-forge#1357]
I keep getting this error message `TypeError: tuple indices must be integers or slices, not str`. I updated Forge yesterday after a month, & now im starting to see this error a lot. Happens with all upscalers i used, though im not sure what triggers it. 

```
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [01:12<00:00,  3.61s/it]
Traceback (most recent call last):█████████████████████████████████████████████████████| 20/20 [01:12<00:00,  2.66s/it]
  File "D:\AI\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\AI\stable-diffusion-webui-forge\modules\txt2img.py", line 95, in txt2img_upscale_function
    fake_image.already_saved_as = image["name"].rsplit('?', 1)[0]
TypeError: tuple indices must be integers or slices, not str
tuple indices must be integers or slices, not str
```

**Comment by DenOfEquity** [comment]
hires fix, specifically from the quick button under the output image gallery?

**Comment by Melyyn** [comment]
> hires fix, specifically from the quick button under the output image gallery?

Yes. I'm guessing images get saved with identical names & cause conflict? so far i added [datetime]-[seed] as a file name pattern to reduce chances of identical names, & i haven't seen the issue reoccur but maybe time will tell

**Comment by DenOfEquity** [comment]
If it's like the issue I've been seeing, it should work with single image OK, but fail with batch. Batch hits a different path in the code.

**Comment by Melyyn** [comment]
> If it's like the issue I've been seeing, it should work with single image OK, but fail with batch. Batch hits a different path in the code.

You're correct. This issue only occured while i was upscaling images from batch generations. I just got the error again so i'm sure it's not a file name issue. I got the error just now after i tried to upscale an image from a batch, so i tried to upscale just that image with same setting/seed without batch & it worked without error.

**Comment by Melyyn** [comment]
Fixed, thank you @DenOfEquity https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/1360

**Comment by rankinstudio** [comment]
Still getting this issue. Latest release.
