### ISSUE TITLE
Prompt Generator Issue - Old Issue not solved yet

### ISSUE THREAD

**Issue by danilomaiaweb** [lllyasviel/stable-diffusion-webui-forge#1358]
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-373-gebe59a95
Commit hash: ebe59a95075411824836b698b6e57bae94acd566
CUDA 12.1
Launching Web UI with arguments: --precision full --opt-split-attention --always-batch-cond-uncond --no-half --skip-torch-cuda-test --pin-shared-memory --cuda-malloc --cuda-stream --ckpt-dir 'F:\ModelsForge\Checkpoints' --lora-dir 'F:\ModelsForge\Loras'
Using cudaMallocAsync backend.
Total VRAM 8191 MB, total RAM 32705 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 3050 : cudaMallocAsync
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: True
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: F:\ForgeFlux\webui\models\ControlNetPreprocessor
[-] ADetailer initialized. version: 24.8.0, num models: 10
sd-webui-prompt-all-in-one background API service started successfully.
21:32:12 - ReActor - STATUS - Running v0.7.1-a1 on Device: CUDA
2024-08-20 21:32:14,634 - ControlNet - INFO - ControlNet UI callback registered.
*** Error executing callback ui_tabs_callback for F:\ForgeFlux\webui\extensions\stable-diffusion-webui-Prompt_Generator\scripts\prompt_generator.py
    Traceback (most recent call last):
      File "F:\ForgeFlux\webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "F:\ForgeFlux\webui\extensions\stable-diffusion-webui-Prompt_Generator\scripts\prompt_generator.py", line 229, in on_ui_tabs
        row.style(equal_height=True)
    AttributeError: 'Row' object has no attribute 'style'

---
Model selected: {'checkpoint_info': {'filename': 'F:\\ModelsForge\\Checkpoints\\fluxFusionDSNF4GGUFQ4Q5Q8Fp8Fp16_v0BnbNf4AIO.safetensors', 'hash': '35aa31f8'}, 'additional_modules': ['F:\\ForgeFlux\\webui\\models\\VAE\\ae.safetensors'], 'unet_storage_dtype': 'nf4'}
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860

**Comment by DenOfEquity** [comment]
This is an issue with the extension, which hasn't been updated in over a year.
It's easy to fix:
1. open `F:\ForgeFlux\webui\extensions\stable-diffusion-webui-Prompt_Generator\scripts\prompt_generator.py` in a text editor (path copied from your error message)
2. go to line `229` - it's the line `row.style(equal_height=True)` that directly follows the line `# Doesn't seem to do anything`
3. comment out by inserting `#` at the start of the line
4. optional: extend the comment on line 228 with sarcasm.
5. save

**Comment by danilomaiaweb** [comment]
> Este é um problema com a extensão, que não é atualizada há mais de um ano. É fácil de corrigir:
> 
> 1. abrir em um editor de texto (caminho copiado da mensagem de erro)`F:\ForgeFlux\webui\extensions\stable-diffusion-webui-Prompt_Generator\scripts\prompt_generator.py`
> 2. ir para a linha - é a linha que segue diretamente a linha `229``row.style(equal_height=True)``# Doesn't seem to do anything`
> 3. comente inserindo no início da linha`#`
> 4. Opcional: Estenda o comentário na linha 228 com sarcasmo.
> 5. salvar

Wow man, it worked perfectly. Thank you so much!
