### ISSUE TITLE
unable to display GGUF model

### ISSUE THREAD

**Issue by ddysDDYS** [lllyasviel/stable-diffusion-webui-forge#1368]
![I)X Q%G` O@_E`$BTVUTKJE](https://github.com/user-attachments/assets/19193e46-e0e5-4526-b3dd-481ab0fa810d)
![WZ(Z68(JS%$DE80EBTI307Y](https://github.com/user-attachments/assets/af88b45c-d20b-4f91-830f-41b680fde3aa)

**Comment by NoMansPC** [comment]
Same. There are supposed to be different fields for the VAE and the text encoder, but they don't show up for me.
