### ISSUE TITLE
solution to RuntimeWarning: invalid value encountered in cast x_sample = x_sample.astype(np.uint8)

### ISSUE THREAD

**Issue by sunnyyangyangyang** [lllyasviel/stable-diffusion-webui-forge#1379]
use webui version before commit "[speed up a bit](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/d03fc5c2b1e1b8fb74469f14828b86a24b5e72b6)". For example, use version [Implement some rethinking about LoRA system](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/d38e560e42b20f1f34b985187adbd1cde58bb15a) , hash:d38e560e42b20f1f34b985187adbd1cde58bb15a

**Comment by lllyasviel** [comment]
make sure that your vae is "ae.safetensors" if that does not work then delete `config.json` and `ui-config.json` and try again

**Comment by sunnyyangyangyang** [comment]
problem still exists
\webui_forge_cu124_torch24\webui\modules\sd_samplers_common.py:75: RuntimeWarning: invalid value encountered in cast
  x_sample = x_sample.astype(np.uint8)

**Comment by ostap667inbox** [comment]
I can also add that this problem appears on the first generation, most often if LoRA is connected and it was patching before generation. This error appears in the console, but generation continues and a completely black image is created. If you immediately repeat the generation with the same parameters the problem does not appear.

**Comment by sunnyyangyangyang** [comment]
That bug disappear in the latest update
