### ISSUE TITLE
Question about Clip Skip

### ISSUE THREAD

**Issue by Fretag** [lllyasviel/stable-diffusion-webui-forge#1393]
Did it move or do I need to look harder?

**Comment by lllyasviel** [comment]
For sd1.5, Clip Skip is always right to VAE dropdown

You can have Clip Skip for sdxl when you click "All" on left-top

People need to note that in the original Automatic1111 webui, the Clip Skip for SDXL is a fake Slider. No matter what value you set, it does not change anything. In forge, screen space for that toolbar is very valuable, so we need to hide some fake Slider.

**Comment by Fretag** [comment]
Thank you! I always wondered why the slider didn't work for A1111/SDXL.
