### ISSUE TITLE
Hi-Res Fix reports using Distilled CFG Scale: 3.5 regardless of actual setting

### ISSUE THREAD

**Issue by aoleg** [lllyasviel/stable-diffusion-webui-forge#1400]
I am trying to generate watercolor pictures. For these, Distilled CFG values of about 0.8 (with main CFG=2 in my case) produce the most convincing result. Currently, WebUI Forge reports using a Distilled CFG of 3.5 for Hi-Res Fix, while using the correct selected value for the first pass. I am not sure whether or not Hi-Res Fix is actually using a different value, but this is what the generation log suggests.

In the log below, please observe how the value changes:

**Distilled CFG Scale: 0.8**
[Unload] Trying to free 1024.00 MB for cuda:0 with 1 models keep loaded ...
[Unload] Current free memory is 9661.34 MB ...
**Distilled CFG Scale: 0.8**
[Unload] Trying to free 1024.00 MB for cuda:0 with 1 models keep loaded ...
[Unload] Current free memory is 9661.34 MB ...
**Distilled CFG Scale: 3.5**
[Unload] Trying to free 1024.00 MB for cuda:0 with 1 models keep loaded ...
[Unload] Current free memory is 9657.34 MB ...
**Distilled CFG Scale: 3.5**

I am on commit 852e88564c871ef640c12ac053e52234958653d8.

```
Begin to load 1 model
[Unload] Trying to free 7817.77 MB for cuda:0 with 0 models keep loaded ...
[Unload] Current free memory is 3156.47 MB ...
[Unload] Unload model KModel
[Memory Management] Current Free GPU Memory: 14891.33 MB
[Memory Management] Required Model Memory: 5225.98 MB
[Memory Management] Required Inference Memory: 1024.00 MB
[Memory Management] Estimated Remaining GPU Memory: 8641.35 MB
Moving model(s) has taken 3.29 seconds
Distilled CFG Scale: 0.8
[Unload] Trying to free 1024.00 MB for cuda:0 with 1 models keep loaded ...
[Unload] Current free memory is 9661.34 MB ...
Distilled CFG Scale: 0.8
[Unload] Trying to free 1024.00 MB for cuda:0 with 1 models keep loaded ...
[Unload] Current free memory is 9661.34 MB ...
Distilled CFG Scale: 3.5
[Unload] Trying to free 1024.00 MB for cuda:0 with 1 models keep loaded ...
[Unload] Current free memory is 9657.34 MB ...
Distilled CFG Scale: 3.5
To load target model KModel
Begin to load 1 model
[Unload] Trying to free 16065.81 MB for cuda:0 with 0 models keep loaded ...
[Unload] Current free memory is 9652.34 MB ...
[Unload] Unload model JointTextEncoder
[Memory Management] Current Free GPU Memory: 14878.32 MB
[Memory Management] Required Model Memory: 11350.07 MB
[Memory Management] Required Inference Memory: 1024.00 MB
[Memory Management] Estimated Remaining GPU Memory: 2504.25 MB
Moving model(s) has taken 2.15 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:42<00:00,  2.15s/it]
To load target model IntegratedAutoencoderKL                                          | 20/120 [00:48<03:41,  2.21s/it]
```

**Comment by DenOfEquity** [comment]
You should find this be fixed now.

**Comment by rrroddri** [comment]
Is there a chance to allow the user to set the value of the CFG of Hires fix.? You just changed the whole workflow of the repo because of one user subjective experience
