### ISSUE TITLE
Changing the location of transformers-cache?

### ISSUE THREAD

**Issue by Melyyn** [lllyasviel/stable-diffusion-webui-forge#1401]
Is it possible to change the location of transformers-cache? i'm using clip interrogator extension by pharmapsychotic, i had downloaded the blip models already. forge wants to put them in `\stable-diffusion-webui-forge\system\transformers-cache`, instead, i want the blip model to be read from `\stable-diffusion-webui-forge\webui\models\diffusers`

**Comment by DenOfEquity** [comment]
Look in `{forge directory}\environment.bat`, there should be a line `set TRANSFORMERS_CACHE=%DIR%\transformers-cache`.
You can change to `set TRANSFORMERS_CACHE=models\diffusers`, or use full path.

(In the future it should be `HF_HOME` instead.)

**Comment by lllyasviel** [comment]
Forge already put all transformers or diffusers or hugging face automatic downloads in `models\diffusers` by taking care of those sys vars.
If it goes else where, then it is external extension's codes that overwrite Forge behavior

**Comment by Melyyn** [comment]
> Forge already put all transformers or diffusers or hugging face automatic downloads in `models\diffusers` by taking care of those sys vars. If it goes else where, then it is external extension's codes that overwrite Forge behavior

Thank you that's good to know

**Comment by Melyyn** [comment]
> Look in `{forge directory}\environment.bat`, there should be a line `set TRANSFORMERS_CACHE=%DIR%\transformers-cache`. You can change to `set TRANSFORMERS_CACHE=models\diffusers`, or use full path. _edit:_ use full path, works with Spaces too.
> 
> (In the future it should be `HF_HOME` instead.)

Thank you, changing to full path fixed the issue
`set TRANSFORMERS_CACHE=D:\AI\Forge\webui\models\diffusers`
