### ISSUE TITLE
img2img sensitivity to denoising broken for FLUX?

### ISSUE THREAD

**Issue by TheManBe** [lllyasviel/stable-diffusion-webui-forge#1402]
Yesterday everything was fine. I updated today, and suddenly img2img no longer behaves as expected for me with FLUX. 

Using flux1-dev-fp8-FORGE.safetensors, with the FLUX UI, ANY denoising below 0.95 or so in img2img, behaves like it is set below 0.50. That is: it is almost impossible to force some variation, and ABOVE those ridiculous values, you end up with extremely soft-blurred images.

The phenomenon doesn't seem to affect SDXL models that I tested.

**Comment by TheManBe** [comment]
OK... not sure what happened, but it has solved itself. Probably something restarted/reset.

False alarm!

**Comment by andy8992** [comment]
This issue is constant for me. Any idea what fixed it?
