### ISSUE TITLE
"Generate forever/Cancel generate forever" doesn't work properly after updating Forge

### ISSUE THREAD

**Issue by cokimax2** [lllyasviel/stable-diffusion-webui-forge#1411]
After update 0d8eb4c5..08f74875 on 08/22/2024, "Generate forever/Cancel generate forever" doesn't work properly.

Symptom

1. During "Generate forever" on going, changing prompt or parameters is not updated to generating. Forge keeps going with the initial prompt and parameters that it starts with.
2. Even though clicking on "Cancel generate forever", Forge won't stop generating. Only way to stop generating is just "Reload UI".

**Comment by TheManBe** [comment]
The "Cancel generate forever" seems to be broken since a longer while already. At least a couple of weeks in my experience.

**Comment by lllyasviel** [comment]
Users report that it works if you just use it in normal way (same as my tests last time) https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1292

but if you use complicated operations to pressure test it, like switching lots of tabs, etc, it will be broken

**Comment by TheManBe** [comment]
yes, that has been my experiences, too... It's not possible to STOP the continuous generating, and even when you force-restart flux, it seems to keep going after it's restarted  So I haven't been using the feature the last couple of days.

**Comment by cokimax2** [comment]
> Users report that it works if you just use it in normal way (same as my tests last time) #1292
> 
> but if you use complicated operations to pressure test it, like switching lots of tabs, etc, it will be broken

I found the occasion exactly when it happens.

During "Generate forever" when "Interrupt" is pressed  once, then "Cancel generate forever" doesn't work. Forge keeps generating on background. This happens in very simple operation like "a dog running" in prompt with default parameters on everything when Forge starts.

a dog running
Steps: 20, Sampler: Euler a, Schedule type: Automatic, CFG scale: 7, Seed: 46361282, Size: 512x640, Model hash: dd59ab565e, Model: realisticVisionV60B1_v60B1VAE, Version: f2.0.1v1.10.1-previous-401-g08f74875, Module 1: vae-ft-mse-840000-ema-pruned

**Comment by matt-c1** [comment]
I posted steps to reproduce here, it's very simple to break:
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1292#issuecomment-2299240282
Another user proposed a partial solution, but not as a pull request because it's not a full fix:
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1292#issuecomment-2304870336
