### ISSUE TITLE
ControlNet via API issues (unit.image)

### ISSUE THREAD

**Issue by ratzycon** [lllyasviel/stable-diffusion-webui-forge#1414]
### Discussed in https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1380

<div type='discussions-op-text'>

<sup>Originally posted by **ratzycon** August 21, 2024</sup>
Hi 👋😄

Trying to get controlnet from API to work with Forge.

no matter what i try from the API i get the same error and the controlnet image fails to apply, while it works inside the forge editor ui
the same script outputs correctly if run against regular webui

errors are thrown in the console when running it via api (KeyError: 0)

What am I doing wrong? :S or is there a bug?

this is the test script i'm using:

```python
import io
import cv2
import base64
import requests
import json
from PIL import Image, PngImagePlugin

def test(test_image):

    url = "http://localhost:7860" # change to your SD url

    img = cv2.imread(test_image)
    retval, bytes = cv2.imencode('.png', img)
    encoded_image = base64.b64encode(bytes).decode('utf-8')

    # Note: You can no longer pass file path in payload as in sd-webui-controlnet.

    payload = {
        "prompt":"2girls, reading, book, elf, simple white background, white dress, hatsune miku",
        "negative_prompt": "",
        "sampler_name": "Euler a",
        "batch_size": 1,
        "steps": 20,
        "cfg_scale": 6,
        "width": 1024,
        "height": 1024,

        # txt2img should not need any init images except for the controlnet image
        #"init_images": [test_image],
        #"init_images": [encoded_image],
        
        "alwayson_scripts": {
            "controlnet": {
                "args": [
                    {
                        "enabled": True,

                        "image": encoded_image,
                        #"mask_image": encoded_image,

                        "control_mode": "Balanced", 
                        "guidance_end": 1,
                        "guidance_start": 0,
                        "pixel_perfect": True,
                        "processor_res": 512,
                        "resize_mode": "Resize and Fill",  # "Just Resize", "Crop and Resize", "Resize and Fill"
                        "threshold_a": 0.5,
                        "threshold_b": 0.5,
                        "weight": 1,
                        "save_detected_map": True,
                        "hr_option": "Both",

                        #"module": "canny",
                        "module": "lineart_anime",
                        
                        "model": "t2i-adapter_diffusers_xl_canny [6b0c1490]",
                        #"model": "control_v11p_sd15_canny [d14c016b]",
                        #"model": "control_v11p_sd15s2_lineart_anime [3825e83e]",
                    }
                ]
            }
        }
    }

    response = requests.post(url=f'{url}/sdapi/v1/txt2img', json=payload)

    r = response.json()
    result = r['images'][0]
    image = Image.open(io.BytesIO(base64.b64decode(result.split(",", 1)[0])))

    pnginfo = PngImagePlugin.PngInfo()
    if 'parameters' in image.info and image.info['parameters'] is not None:
        pnginfo.add_text("parameters", image.info.get('parameters'))
        print("\nParameters:\n" + json.dumps(image.info, indent=4))

    image.save('test_output.png', pnginfo=pnginfo)

    print("image saved to test_output.png")

test("test.png")
```
controlnet test image:
![test](https://github.com/user-attachments/assets/30aaa50f-f0d2-4a13-a852-abb46ee24a2b)

controlnet console error:
![error](https://github.com/user-attachments/assets/1ecf6c60-895b-47f8-a26d-7adc6c06b354)

controlnet webui in editor output with same settings (no console errors):
![in editor](https://github.com/user-attachments/assets/360478cf-a3ea-4bc2-af88-2cd5648af0b1)

test output using API using Forge:
![test_output_forge](https://github.com/user-attachments/assets/d7bcdba3-0c54-4110-9a4e-cd2826d97c06)

test output if run with API against regular webui:
![test_output_webui](https://github.com/user-attachments/assets/e384ecd1-5a5f-4957-a47d-10eb1dfa5534)

[controlnet_test.zip](https://github.com/user-attachments/files/16695765/controlnet_test.zip)
</div>

**Comment by IgorAherne** [comment]
Fixed it in this pull request https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/1425#issue-2481961732

**Comment by IgorAherne** [comment]
#1425

**Comment by ratzycon** [comment]
awesome, it works now, cheers!
closing the issue

**Comment by alebeard** [comment]
Can anyone post links to working control net models that should be used
with flux?
And on a related question has anyone found control in that models that work
with pony?

**Comment by ratzycon** [comment]
https://huggingface.co/lllyasviel/sd_control_collection/tree/main

i use the sdxl ones, pony is sdxl based
they don't always work well depending on what model you use, 
I had better results with sd1.5 with anime
don't know if there are CN models for flux yet
