### ISSUE TITLE
Connection Errored Out when using FLUX

### ISSUE THREAD

**Issue by CherryIcee** [lllyasviel/stable-diffusion-webui-forge#1419]
Specs are: 
Windows 11
Intel i7-9700F 
16GB RAM
Nvidia RTX 2060 Super 8GB VRAM

Downloaded and updated **webui_forge_cu121_torch231** and I can run SD no problem. But if I switch to FLUX:
![Screenshot 2024-08-22 142304](https://github.com/user-attachments/assets/935ab2a3-c8f3-4b97-bdd8-7ddb43cbf251)

I get this:
![Screenshot 2024-08-22 142325](https://github.com/user-attachments/assets/bbf90c78-c83d-4b7d-b4d4-945160fa0eb4)

![Screenshot 2024-08-22 142405](https://github.com/user-attachments/assets/f559458d-4238-47b2-9535-ae222cbf1255)

I press the Enter key and some text flashes quickly at the bottom before I can read it and closes. 

Please let me know if you need additional info. Thanks!

**Comment by lllyasviel** [comment]
![image](https://github.com/user-attachments/assets/0197f837-b9b5-487c-a346-a793a58504a2)
make sure that each hard drive has at least 40GB free space

**Comment by CherryIcee** [comment]
I have 724GB free out  of 1.81TB

**Comment by Melyyn** [comment]
Make sure you close as many programs and browser tabs as possible, since you're vram limited you want as much free system ram as possible. I also get this error in both comfy & forge, i have rtx 4070 super 12gb vram & 32gb system ram.

**Comment by Melyyn** [comment]
Make sure you close as many programs and browser tabs as possible, since you're vram limited you want as much free system ram as possible. I also get this error in both comfy & forge, i have rtx 4070 super 12gb vram & 32gb system ram. Flux needs lot of vram.
