### ISSUE TITLE
can't change models via api

### ISSUE THREAD

**Issue by dermesut** [lllyasviel/stable-diffusion-webui-forge#1421]
although the payload is being written and sent to the options-route, nothing happens.

two lines added to the api.py seem to change that for me:

add 1:
`from modules_forge import main_entry`

add 2:

```
    def set_config(self, req: dict[str, Any]):
        checkpoint_name = req.get("sd_model_checkpoint", None)
        if checkpoint_name is not None and checkpoint_name not in sd_models.checkpoint_aliases:
            raise RuntimeError(f"model {checkpoint_name!r} not found")

        for k, v in req.items():
            shared.opts.set(k, v, is_api=True)

        # this line is to be added:
        main_entry.checkpoint_change(checkpoint_name)

        shared.opts.save(shared.config_filename)
        return
```

i don't know how to do this pull request-thingy, since i have never done that.
so maybe someone could do that, while i try to learn how to use github.

**Comment by altoiddealer** [comment]
I'll push a PR for this.

I tested and can confirm this works

**Comment by altoiddealer** [comment]
This should be closed now
