### ISSUE TITLE
Seeds not working.

### ISSUE THREAD

**Issue by user1x1user** [lllyasviel/stable-diffusion-webui-forge#1422]
All my seeds are coming out as 1 or 3. Using models STOIQONewrealityFLUXSD_F1DPreAlpha and fluxunchainedArtfulNSFW_fuT516xfp8E4m3fnV11

Worked fine on Aug 20 version

**Comment by barepixels** [comment]
I was inpainting with random seed.  The random/batch stop working.  Restarting Forge and random/batch working again

**Comment by user1x1user** [comment]
Restart didn't help me for two days but can confirm working again as of today. Many Thx
