### ISSUE TITLE
What is the benefit of Lowering GPU Weights ? 

### ISSUE THREAD

**Issue by aggregate15** [lllyasviel/stable-diffusion-webui-forge#1428]
I don't get the point of the GPU Weight Settings and why Forge starts throwing warnings if its set to Max limit ? 

On my 8GB VRAM when I set GPU Weights to their Maximum limit of 8187 MB - I get generation time of about 40 Seconds. When I set it to Default Flux Setting of 7163 MB, it tells me that enough space is reserved for calculations (and stops giving me low VRAM warnings) --- but my Generation time shoots up to 58 Secs. 

Can someone clarify what the benefit of setting up free space for calculations is ? For me it gives demonstrably worse generation times for the same settings/quality. Why should I keep spare VRAM for 'Calculations' if its not benefiting me in any way?

**Comment by andy8992** [comment]
I don't get it either, i have seen it said to lower it and get faster performance but that seems counter intuitive.

**Comment by altoiddealer** [comment]
If you scroll down a bit in this Discussion, it is explained.

https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/981

**Comment by aggregate15** [comment]
> If you scroll down a bit in this Discussion, it is explained.
> 
> #981

Yes I have read that, form what I understand:  

1. **If extra space is reserved, it can be used for larger resolutions** ----But why should I keep getting GPU degradation warnings and told to keep 12.5% spare space when I'm using normal resolutions ? I do not see that 12.5% being used anywhere for any speedups. It just reduces available VRAM for and slows down generation at regular resolutions.

2. **With full utilization there is a risk of 10X slowdown** ---- I have not experienced a single case after hundreds of generations where full utilization suddenly gives me 10X worse performance, in fact the lower weights just heat up the GPU more as it takes around 20% longer for the same result. 

I guess a one time tip/recommendation might be fine but so many warnings at **every single inference step** about GPU Degradation, etc seems a bit too much. Its basically just recommending people to generate at lower performance repeatedly when it is not such a drastic issue.

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1354

**Comment by aggregate15** [comment]
> #1354

Okay **lllyasviel**, first of all,  thanks for your hard work  and thank you very much  l that gives a lot more clarity on what is going on on some cases. Just that it almost panicked me seeing the warnings at every step, But your response pretty much clarifies that people asked for reminders on this.
