### ISSUE TITLE
The inference speed totally dropped after using the latest commit

### ISSUE THREAD

**Issue by sangoi-exe** [lllyasviel/stable-diffusion-webui-forge#1432]
I did a git pull today to update the branch, got the `f7ab23b1` commit, and to my surprise, the speed dropped from 1.5 it/s to 2 s/it on SDXL. I had to roll back to commit 74aacc5d.

Did any default setting value change that could have caused this? I'm using a 12GB 3060.

**Comment by lllyasviel** [comment]
paste full log from beginning

**Comment by sangoi-exe** [comment]
I tried to reproduce the issue but couldn't. 🥲

I did git checkout on the commit that apparently had the problem, but when I generated an image, the speed was back to normal. 😅

The only thing I remember being different now is that I think I didn’t reload the UI after doing the git pull when I encountered the problem, using the browser tab that was loaded when I was on the older commit. 😳
