### ISSUE TITLE
Lora quality degradation with the latest commit

### ISSUE THREAD

**Issue by lolxdmainkaisemaanlu** [lllyasviel/stable-diffusion-webui-forge#1441]
So I'm trying to reproduce the output of this lora. (https://civitai.com/models/652699?modelVersionId=756149) 

I've been communicating with the author and he is on an older version of Forge and is able to get MUCH more realistic skin texture with the exact same settings but I am not able to! 

Author's output: 
![image](https://github.com/user-attachments/assets/0b32a426-c237-49d9-b367-2c067f6c9818)
Author's prompt: 
Amateur photography of three women sitting closely together on a sunny day. The woman on the left is White, with a plus-size build, light skin, long straight brown hair, and wearing a black tank top and large dark sunglasses, smiling confidently at the camera. The woman in the middle is Black, with a slim build, dark skin, long braided hair, and wearing a yellow floral dress with a flower crown, smiling brightly. The woman on the right is Asian with a slim build, light skin, shoulder-length wavy dark brown hair, wearing a turquoise tank top and sunglasses, smiling warmly. The scene is an outdoor gathering, possibly a festival or picnic, with people seated on lawn chairs and blankets on the grass. The background features trees, a parked car, and other attendees dressed in casual summer attire, with some wearing leis, suggesting a relaxed, festive atmosphere. Image quality tags: bright natural light, slight motion blur in the background, vivid colors, casual setting, cluttered background. on flickr in 2007, 2005 blog, 2007 blog <lora:amateurphotov2-000049:0.6>
Steps: 20, Sampler: Heun, Schedule type: Beta, CFG scale: 1, Distilled CFG Scale: 4, Seed: 573886816, Size: 1024x1024, Model hash: 52cfce60d7, Model: flux1-dev-Q8_0, Lora hashes: "amateurphotov2-000049: 771781fd6719", Beta schedule alpha: 0.6, Beta schedule beta: 0.6, Version: f2.0.1v1.10.1-previous-401-g08f74875, Module 1: ae, Module 2: clip_l, Module 3: t5xxl_fp8_e4m3fn

My output: 
![image](https://github.com/user-attachments/assets/4ea34f25-16d7-4987-801f-d5e3137e7203)
My prompt:
Amateur photography of three women sitting closely together on a sunny day. The woman on the left is White, with a plus-size build, light skin, long straight brown hair, and wearing a black tank top and large dark sunglasses, smiling confidently at the camera. The woman in the middle is Black, with a slim build, dark skin, long braided hair, and wearing a yellow floral dress with a flower crown, smiling brightly. The woman on the right is Asian with a slim build, light skin, shoulder-length wavy dark brown hair, wearing a turquoise tank top and sunglasses, smiling warmly. The scene is an outdoor gathering, possibly a festival or picnic, with people seated on lawn chairs and blankets on the grass. The background features trees, a parked car, and other attendees dressed in casual summer attire, with some wearing leis, suggesting a relaxed, festive atmosphere. Image quality tags: bright natural light, slight motion blur in the background, vivid colors, casual setting, cluttered background. on flickr in 2007, 2005 blog, 2007 blog <lora:amateurphotov2:0.6>
Steps: 20, Sampler: Heun, Schedule type: Beta, CFG scale: 1, Distilled CFG Scale: 4, Seed: 573886816, Size: 1024x1024, Model hash: 52cfce60d7, Model: flux1-dev-Q8_0, Lora hashes: "amateurphotov2: 771781fd6719", Beta schedule alpha: 0.6, Beta schedule beta: 0.6, Version: f2.0.1v1.10.1-previous-414-gdf598c4d, Module 1: ae, Module 2: clip_l, Module 3: t5xxl_fp8_e4m3fn

As you can see, I have matched each and every setting meticulously by contacting the author and asking him for the prompt, but there is still a vast difference in outputs and the only difference is that the author is on an older commit! 

I would really appreciate if this is addressed, thanks in advance.

**Comment by lllyasviel** [comment]
you can `git checkout 08f74875` to use **"f2.0.1v1.10.1-previous-401-g08f74875"**

However, as I just tested, it gives exactly same results to the latest version.

You can test if you will have different results by `git checkout 08f74875`. However, it is likely that you also get exactly same image as you have now. If not, report here.

I somehow remember that "Heun" sampler has some deterministic issues and may have different results on different GPU architecture.  It is likely that your mentioned "Author" is on a different GPU architecture and that may be the reason. By the way, I cannot get same result to either of you, which may also because of this
