### ISSUE TITLE
[Feature Request] HiDiffusion: Unlocking Higher-Resolution Creativity and Efficiency in Pretrained Diffusion Models

### ISSUE THREAD

**Issue by Bercraft** [lllyasviel/stable-diffusion-webui-forge#1445]
[https://github.com/megvii-research/HiDiffusion](url)
Its a great upscaler, sdnext has it integrated.
Thank you.

**Comment by MisterChief95** [comment]
I know @Panchovix implemented it in reForge then spun it off into its own extension. Would be cool to see it here too. Only thing is that it relies on the ldm_patched module, which Forge is missing, so it will take some reworking to become functional, unless lllyasviel is cool with it being added.

**Comment by MisterChief95** [comment]
Ended taking this upon myself in the end. Here's a port of JankHidiffusion for reForge to lllyasviel's Forge:
https://github.com/MisterChief95/sd-forge-hidiffusion

I cleaned up the UI and switched from depending on the `ldm_patched` modules to Forge's native backend. I don't know much about the diffusion process but if there are any issues, please report them and I'll do my best to resolve them.

**Comment by Bercraft** [comment]
Thank you, its working.
