### ISSUE TITLE
[Bug] Forge API break request session if generation take more then 60 sec

### ISSUE THREAD

**Issue by generatornaya** [lllyasviel/stable-diffusion-webui-forge#1448]
Hello! I launched the Flux model via the API, and ran into a problem that forge breaks the connection after 60 seconds, and because of this the queue breaks, and the model, as you know, takes a long time to generate images. How can you raise an API session that will last longer than the standard 60 seconds? --timeout-keep-alive not helping

**Comment by wizz13150** [comment]
Hey, 

any code or logs ? Forge doesn't break the connection after 60 sec
