### ISSUE TITLE
Flux models in text_encoder folder that is put in custom shared folder path is not loaded

### ISSUE THREAD

**Issue by Digiearts** [lllyasviel/stable-diffusion-webui-forge#1456]
I put my text_encoder Flux models along with other models in custom path (shared folder). I launch forge with this additional argument in webui-user.bat set COMMANDLINE_ARGS=--forge-ref-a1111-home "[path to my stable-diffusion-webui floder]" . Other models including VAE models can be loaded properly, but my text_encoder models are not loaded.
Is there anyone know how to fix this? Do we need to add extra line of argument?

**Comment by DenOfEquity** [comment]
There is a new command line argument `--text-encoder-dir`.

**Comment by Digiearts** [comment]
How do you add this argument? it doesn't work for me. got this error message '--text-encoder-dir' is not recognized as an internal or external command,

**Comment by MemoryFreezer** [comment]
> How do you add this argument? it doesn't work for me. got this error message '--text-encoder-dir' is not recognized as an internal or external command,

I have the same issue when adding it to the webui-user.bat command line args
