### ISSUE TITLE
FLUX : Text encoder GGUF support ?

### ISSUE THREAD

**Issue by tomakorea** [lllyasviel/stable-diffusion-webui-forge#1458]
Hi, I have an RTX 3090 and I'm using Flux1-Dev with :
ae.safetensors
clip_l.safetensors
t5xxl_fp8_e4m3fn.safetensors

theses 3 files are in "text_encoder" subfolder and everything works well.

However, It seems like using t5-v1_1-xxl-encoder-Q8_0.gguf instead of t5xxl_fp8_e4m3fn.safetensors may bring the most of Flux with my setup because the precision is better with Q8 than FP8.

However, even though the GGUF text encoder file is in the folder, it's not possible to load it in SD Forge.

Would it be possible to make it work ?

Thank you !

**Comment by lllyasviel** [comment]
duplicated

https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1050#gguft5
