### ISSUE TITLE
Patching LoRAs for KModel thats Over 10mins

### ISSUE THREAD

**Issue by vehanlankaja** [lllyasviel/stable-diffusion-webui-forge#1459]
each time i load a lora or change lora weight it takes over 10 mins to patch, this is not a problem is comfyUI so i am assuming its an issue with the application or my settings, but i checked all the setting and seems to be all good.

**Comment by lllyasviel** [comment]
![image](https://github.com/user-attachments/assets/5b7015ee-f1ba-4505-a8de-869fa3322f68)
