### ISSUE TITLE
how to fix this error ?

### ISSUE THREAD

**Issue by SOLOMARS1** [lllyasviel/stable-diffusion-webui-forge#1469]
when i try to run the "flux1-dev-bnb-nf4.safetensors" it gets to this part in the command window :
[Unload] Unload model JointTextEncoder
and i get this error :
error Connection errored out

**Comment by Melyyn** [comment]
How much vram & system ram do you have?

**Comment by Melyyn** [comment]
That should be enough to run that model. i recommend increasing swap file & restarting your pc. https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1474
![image](https://github.com/user-attachments/assets/8491f713-2121-4929-a2e6-b5adc98f6fcc)

**Comment by Melyyn** [comment]
That should be enough to run that model. i recommend increasing swap file & restarting your pc. check out this post: https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1474
![image](https://github.com/user-attachments/assets/8491f713-2121-4929-a2e6-b5adc98f6fcc)

**Comment by SOLOMARS1** [comment]
> That should be enough to run that model. i recommend increasing swap file & restarting your pc. check out this post: #1474 ![image](https://private-user-images.githubusercontent.com/60199831/361153303-8491f713-2121-4929-a2e6-b5adc98f6fcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MjE4NjksIm5iZiI6MTcyNDUyMTU2OSwicGF0aCI6Ii82MDE5OTgzMS8zNjExNTMzMDMtODQ5MWY3MTMtMjEyMS00OTI5LWEyZTYtYjVhZGM5OGY2ZmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDE3NDYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYThjODhmYzQ3MzcwZjRhOWRkMDhkNjY4NzQ1OTBmODQ2NWU0MDFkYzhiYWVlOTI0MjY2MDc3MzVlYTFhMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hH6QyzWdIYlI7VvLHz7MAVK1otidC-tggGzEktkaSe0)

thx a lot i will try this

**Comment by CherryIcee** [comment]
My flux worked before Forge got updated also. Getting the same error.

**Comment by zeozeozeo** [comment]
getting a similar error with SDXL, the final generation doesn't show up in the webui (however the generation progress before it is shown), but the image does show up in outputs/txt2img-images

**Comment by Melyns** [comment]
> getting a similar error with SDXL, the final generation doesn't show up in the webui (however the generation progress before it is shown), but the image does show up in outputs/txt2img-images

i think this error is due to webui bug. happens if you get connection errored out, restart flux, & keep working on the same window. to solve that, whenever you start flux use a new webui window in your browser.
