### ISSUE TITLE
[Bug]: Updating WebUI can sometimes reset your COMMANDLINE_ARGS

### ISSUE THREAD

**Issue by RandoMandoTheFirst** [lllyasviel/stable-diffusion-webui-forge#147]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I recently updated WebUI Forge and it redownloaded webui-user.bat and undid all of my COMMANDLINE_ARGS

### Steps to reproduce the problem

1. Download WebUI forge and add some COMMANDLINE_ARGS
2. Update it after a major update
3. Open Webui-user.bat and check COMMANDLINE_ARGS

### What should have happened?

the Webui-user.bat should stay the same as it was before

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2024-02-09-07-12.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14218332/sysinfo-2024-02-09-07-12.json)

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.10-latest-86-ged60a998
Commit hash: ed60a9982690f85b6e14e3f891ae481a045b94d0
Launching Web UI with arguments:
Total VRAM 8192 MB, total RAM 32717 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2070 SUPER : native
VAE dtype: torch.float32
Using pytorch cross attention
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/realisticVisionV51_v51VAE.safetensors" to G:\Stable-Diffusion-Forge\webui\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors

100%|█████████████████████████████████████████████████████████████████████████████| 1.99G/1.99G [04:36<00:00, 7.71MB/s]
ControlNet preprocessor location: G:\Stable-Diffusion-Forge\webui\models\ControlNetPreprocessor
Checkpoint ponyDiffusionV6XL.safetensors [67ab2fd8ec] not found; loading fallback realisticVisionV51_v51VAE.safetensors
Calculating sha256 for G:\Stable-Diffusion-Forge\webui\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors: 2024-02-08 23:06:51,257 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 298.1s (prepare environment: 5.8s, import torch: 5.8s, import gradio: 2.2s, setup paths: 2.4s, initialize shared: 0.1s, other imports: 1.7s, list SD models: 277.3s, load scripts: 2.2s, create ui: 0.7s, gradio launch: 0.2s).
15012c538f503ce2ebfc2c8547b268c75ccdaff7a281db55399940ff1d70e21d
Loading weights [15012c538f] from G:\Stable-Diffusion-Forge\webui\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors
model_type EPS
UNet ADM Dimension 0
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
Loading VAE weights specified in settings: G:\Stable-Diffusion-Forge\webui\models\VAE\sdxl_vae.safetensors
To load target model SD1ClipModel
Begin to load 1 model
Moving model(s) has taken 0.23 seconds
Model loaded in 5.2s (calculate hash: 2.4s, forge load real models: 1.2s, load VAE: 1.0s, calculate empty prompt: 0.6s).
```

**Comment by strawberrymelonpanda** [comment]
Probably because of PR #135.  There was a bad path in the .bat.  Often in repos these kinds of files are webui-user.sample.bat or something, so that the end user's version is kept out of version control.  But then that would rely on users to update their files.  With as many users as the WebUI has, simplicity is probably the top concern.

Probably unlikely to see many future changes.

**Comment by huchenlei** [comment]
Let me file another issue to track this. We should probably have a more robust way to reference an existing A1111 checkout.
