### ISSUE TITLE
AssertionError: You do not have CLIP state dict! Time taken: 0.4 sec.

### ISSUE THREAD

**Issue by wujun200999** [lllyasviel/stable-diffusion-webui-forge#1471]
AssertionError: You do not have CLIP state dict!
Time taken: 0.4 sec.

**Comment by zimNMM** [comment]
![image](https://github.com/user-attachments/assets/d60b3f81-cff1-42ba-8230-a2fbe9c4cb6d)
If you are using GGUF you have to include the text encoders clip/t5 and the vae

**Comment by tazztone** [comment]
read this https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1050

**Comment by LesmaGamer** [comment]
Os modelos da CIVITAI resolveram esse erro, para mim, 
Civitai models resolve this issue for me: Forge Stable Diffusion.
