### ISSUE TITLE
[Feature Request]: Save text information about generation

### ISSUE THREAD

**Issue by ermellinka** [lllyasviel/stable-diffusion-webui-forge#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Please add in the the settings the stroke "Save text information about generation parameters as chunks to png files"
like it is in automatic1111

### Proposed workflow

Please add in the the settings the stroke "Save text information about generation parameters as chunks to png files"
like it is in automatic1111.

**Comment by ArnorWing** [comment]
There is these 2 settings in INFOTEXT and 1 option in DYNAMICPROMPTS settings
Write infotext to metadata of the generated image
Create a text file with infotext next to every generated image

**Comment by lllyasviel** [comment]
"Save text information about generation parameters as chunks to png files" is edited by automatic1111, not by Forge.
It seems that automatic1111 dev btanch changed it
