### ISSUE TITLE
What does this mean? "You do not have CLIP state dict!"

### ISSUE THREAD

**Issue by LIQUIDMIND111** [lllyasviel/stable-diffusion-webui-forge#1487]
Im trying to use the FLUX DEV regular model, NOT FP8, and i get this message: "You do not have CLIP state dict!" 

So you can only use the FLUX DEV fp8 with forge?

**Comment by tazztone** [comment]
read this https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1050

**Comment by LIQUIDMIND111** [comment]
thanks
