### ISSUE TITLE
Blurred image

### ISSUE THREAD

**Issue by sskit** [lllyasviel/stable-diffusion-webui-forge#1490]
Image Quality has gotten worse since the last update. Blurred, fuzzy images

![00008-4055724213](https://github.com/user-attachments/assets/13a92a2d-62ed-47e8-95c9-eb9156cb5c4c)

![Снимок экрана 2024-08-25 135238](https://github.com/user-attachments/assets/cc8c7cf6-be74-4ec0-a3bb-e827a9ae431a)

**Comment by sskit** [comment]
Thank you! It really is as you said. It's all about the white background. I find it strange...

**Comment by 4lt3r3go** [comment]
so whats the trick here? avoid the "background" word ?

**Comment by Mark999a** [comment]
> so whats the trick here? avoid the "background" word ?

i think combo of "white" and "background"... if you use for example "turqoise background" all is should be good

**Comment by DenOfEquity** [comment]
Thanks Mark999a for the knowledge.
