### ISSUE TITLE
The memory usage keeps increasing and does not get released.

### ISSUE THREAD

**Issue by s4130** [lllyasviel/stable-diffusion-webui-forge#1495]
英语不好,所以用中文了
每次生成图片都会增加虚拟内存但不会释放,一直吃c盘的空间,最终还会导致电脑蓝屏重启
![image](https://github.com/user-attachments/assets/5f0caf7f-ed2a-42d8-a7df-778c2b849a43)
这是正常的吗,我该怎么解决?除了重新启动

**Comment by l0stl0rd** [comment]
having similar issues and it is slowing down the machine to a crawl.

**Comment by moudahaddad14** [comment]
yup it's a bug if i'm not wrong and still needs to be fixed :/

**Comment by BaseMe2** [comment]
Lora used will also not properly be released. I've noticed this by using different prompts and wanting to delete a lora I've used prior, windows blocked it as "in usage"

**Comment by s4130** [comment]
造成我这个的原因应该是 #1598
