### ISSUE TITLE
xformers N/A

### ISSUE THREAD

**Issue by EtienneDosSantos** [lllyasviel/stable-diffusion-webui-forge#150]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

> We highly encourage Forge users to remove all cmd flags and let Forge to decide how to load models. (README.md)

Encouraging the removal of all cmd flags suggests that xformers (or a similar performance optimization) is built into Forge. Yet, the bottom bar of the webui says 'xformers: N/A', and xformers isn't an option in the settings. This seems contradictory.

Is there a better alternative to 'xformers' for optimizing cross-attention, or is 'xformers' still the best option? If 'xformers' remains the preferred choice, is the `--xformers` flag required for its operation?

![GitHub_ImagePost-v09 02 2024](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/130935112/c2bde388-3271-4f2c-a372-a884957ec988)

### Steps to reproduce the problem

-

### What should have happened?

-

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2024-02-09-12-56.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14221914/sysinfo-2024-02-09-12-56.json)

### Console logs

```Shell
venv "E:\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: f0.0.10-latest-86-ged60a998
Commit hash: ed60a9982690f85b6e14e3f891ae481a045b94d0
Launching Web UI with arguments:
Total VRAM 16380 MB, total RAM 65417 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
ControlNet preprocessor location: E:\stable-diffusion-webui-forge\models\ControlNetPreprocessor
Loading weights [4726d3bab1] from E:\stable-diffusion-webui-forge\models\Stable-diffusion\dreamshaperXL_v2TurboDpmppSDE.safetensors
2024-02-09 12:45:13,758 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
model_type EPS
UNet ADM Dimension 2816
Startup time: 34.4s (prepare environment: 11.1s, import torch: 9.0s, import gradio: 3.2s, setup paths: 3.1s, initialize shared: 0.3s, other imports: 2.2s, setup gfpgan: 0.1s, load scripts: 3.6s, create ui: 0.7s, gradio launch: 0.8s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
left over keys: dict_keys(['conditioner.embedders.0.logit_scale', 'conditioner.embedders.0.text_projection'])
Loading VAE weights specified in settings: E:\stable-diffusion-webui-forge\models\VAE\sdxl_vae.safetensors
To load target model SDXLClipModel
Begin to load 1 model
Moving model(s) has taken 0.27 seconds
Model loaded in 9.4s (load weights from disk: 1.0s, forge load real models: 6.8s, load VAE: 0.9s, calculate empty prompt: 0.6s).
```

**Comment by litvagen** [comment]
you need to install xformers-0.0.23.post1 version for resolve this problem

**Comment by EtienneDosSantos** [comment]
> you need to install xformers-0.0.23.post1 version for resolve this problem

@litvagen `pip install xformers-0.0.23.post1` didn't work,

![xformers-0 0 23 post1_not_working](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/130935112/81e7d557-025c-425e-b3aa-e314179571c7)

but `pip install xformers==0.0.23.post1` successfully installed it.

![xformers-0 0 23 post1_installed](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/130935112/40d67ef0-7336-47e9-98aa-5c67f74f83e4)

However, this broke webui-forge 😅

```Shell
venv "E:\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: f0.0.10-latest-86-ged60a998
Commit hash: ed60a9982690f85b6e14e3f891ae481a045b94d0
Launching Web UI with arguments:
Total VRAM 16380 MB, total RAM 65417 MB
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : native
VAE dtype: torch.bfloat16
Traceback (most recent call last):
  File "E:\stable-diffusion-webui-forge\launch.py", line 48, in <module>
    main()
  File "E:\stable-diffusion-webui-forge\launch.py", line 44, in main
    start()
  File "E:\stable-diffusion-webui-forge\modules\launch_utils.py", line 508, in start
    import webui
  File "E:\stable-diffusion-webui-forge\webui.py", line 19, in <module>
    initialize.imports()
  File "E:\stable-diffusion-webui-forge\modules\initialize.py", line 53, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "E:\stable-diffusion-webui-forge\modules\processing.py", line 18, in <module>
    import modules.sd_hijack
  File "E:\stable-diffusion-webui-forge\modules\sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "E:\stable-diffusion-webui-forge\modules\sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "E:\stable-diffusion-webui-forge\modules\hypernetworks\hypernetwork.py", line 13, in <module>
    from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
  File "E:\stable-diffusion-webui-forge\modules\sd_models.py", line 20, in <module>
    from modules_forge import forge_loader
  File "E:\stable-diffusion-webui-forge\modules_forge\forge_loader.py", line 5, in <module>
    from ldm_patched.modules import model_detection
  File "E:\stable-diffusion-webui-forge\ldm_patched\modules\model_detection.py", line 1, in <module>
    import ldm_patched.modules.supported_models
  File "E:\stable-diffusion-webui-forge\ldm_patched\modules\supported_models.py", line 2, in <module>
    from . import model_base
  File "E:\stable-diffusion-webui-forge\ldm_patched\modules\model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "E:\stable-diffusion-webui-forge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "E:\stable-diffusion-webui-forge\ldm_patched\ldm\modules\attention.py", line 14, in <module>
    import xformers
ModuleNotFoundError: import of xformers halted; None in sys.modules

**Comment by lllyasviel** [comment]
Forge do not need xformers to speed up it - native one is equaly fast and mem efficient

and after recent pytorch release the native one will be slightly faster than xformers so it is less necessary in the future

**Comment by Vynsyc** [comment]
> Forge do not need xformers to speed up it - native one is equaly fast and mem efficient


While i don't doubt it, I'm also still experiencing a slower generation time than I was with xformers when using the normal webui, i have to say

**Comment by lllyasviel** [comment]
then users may want to downgrade pytorch but matching them would require much efforts

if someone successfully gets peformance improvement by playing with these versions, please let us know what is the best match now on your device and we will put in in readme and let more people know

**Comment by EtienneDosSantos** [comment]
> Forge do not need xformers to speed up it - native one is equaly fast and mem efficient
> 
> and after recent pytorch release the native one will be slightly faster than xformers so it is less necessary in the future

Ok, thx for letting us know! 👌

**Comment by pas-de-2** [comment]
> While i don't doubt it, I'm also still experiencing a slower generation time than I was with xformers when using the normal webui, i have to say

Fwiw, I was experiencing this too, and it was because my a1111 venv was still on pytorch 1.12.1. `pip uninstall torch` and letting webui pull torch 2.1.2 fixed it. Identical SDXL gens went from (12s w/o xformers, 10s w/ xformers) to 7s w/o xformers.

**Comment by langorebk** [comment]
It generate much slower after I run update.bat (1.48 it/s before update and 1.20 s/it after update on same sdxl model). I've delete original aut1111, and install this one clearly

**Comment by sugatasanshiro** [comment]
mobile RTX 2080 super 8GB VRAM, Laptop
![BF3rk4p2Ut](https://github.com/user-attachments/assets/f278baa6-25b1-4691-8b69-b0fd8db25fd1)
![brave_08vhb8RlWT](https://github.com/user-attachments/assets/4444ecdf-6d12-4dd2-9d99-5e71e487062f)
![00000-3517382471](https://github.com/user-attachments/assets/0f55ac5d-6fa0-4e49-ad39-8f59d820cd68)
