### ISSUE TITLE
26-08-2024 pull broke loras?

### ISSUE THREAD

**Issue by peppepascale** [lllyasviel/stable-diffusion-webui-forge#1515]
can't add any flux loras anymore, results looks super grainy/blurry/wasted.
without loras everything works fine.

![image](https://github.com/user-attachments/assets/280742f3-d5c3-4e0d-b787-8991d718c96d)

using flux dev q8
same problem with full dev or other fluxs

**Comment by lllyasviel** [comment]
I just tested and it give same result to previous versions.
It is an old problem that some LoRA cannot be baked into Q models and must use 
![image](https://github.com/user-attachments/assets/db7bd099-a7a5-4687-af81-79cfaa4b0b9b)
to patch them in a much slower way

**Comment by peppepascale** [comment]
thanks for quick answer. 

everything was working fine till today
havent touched anything: 
![image](https://github.com/user-attachments/assets/8e440bd9-bdf4-4f67-a59b-81aa900b6b84)

now switched to that automatic (fp16) you suggested, 
result is like no lora are applyed at all.
can't figure whats the problem

**Comment by lllyasviel** [comment]
if you can provide evidence of before-after comparison of different commits I will take a look

**Comment by peppepascale** [comment]
I'm sorry, All these thousand experiments have turned me into a dumb clueless amoeba, 
I didn't realize I took img2img folder instead of txt2img. 
**everything is working fine!**
Sorry for wasting your time and good luck with your work! 
You're amazing. Thanks again.

**Comment by LeDXIII** [comment]
> if you can provide evidence of before-after comparison of different commits I will take a look

The Lora's really broke this morning - FLUX takes a huge amount of resources with them. 
I have a file from 08/21 (Not sure about the relevance of the commit, Version: f2.0.1v1.10.1-previous-373-g7d9f1350),  where Lora work good. Uploading it via png-info I get the following result: at step 3 it have to black screen on preview. 
![00004-1710600289](https://github.com/user-attachments/assets/fcc1b033-c796-4487-b841-867f772d888a)

![lora](https://github.com/user-attachments/assets/55865ee8-3fa4-4588-9c07-44d4d7b9ec22)

This error occurs with any checkpoint+Lora options. nf4, gguf_4\5, with "automatic" mode enabled or manual selection.
