### ISSUE TITLE
[Feature Request] Make Generate button position sticky

### ISSUE THREAD

**Issue by Melyns** [lllyasviel/stable-diffusion-webui-forge#1522]
When you are in the txt2img window for example, & you scroll down, the Generate button will eventually gets scrolled past, but the `txt2img_results_panel` (i believe its called) will stick, my suggestion is to make the Generate button across all modes (txt2img, img2img...) have the same behavior as `txt2img_results_panel` so no matter how down you scroll, the generate button will always remain visible on the user screen. 

This gets frustrating when you have many accordion dropdowns expanded. I believe this feature would be nice quality of life feature because you wouldn't need to scroll up again to click generate. 

Here's a youtube video i found that explain & showcases what i'm talking about (timestamped) https://youtube.com/watch?v=NzjU1GmKosQ&t=152s

**Comment by DenOfEquity** [comment]
I use compact prompt which does this. Settings -> UI alternatives -> Compact prompt layout

**Comment by Melyns** [comment]
And i'm out here trying to figure out CSS code... thank you this worked the way i wanted it
