### ISSUE TITLE
API /sdapi/v1/txt2img

### ISSUE THREAD

**Issue by sinuso** [lllyasviel/stable-diffusion-webui-forge#1539]
Hello
First of all congratulations for the work!

At the bottom of the page in [API](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API) leads to an obsolete document?
It mentions "/sdapi/v1/txt2img" but I can't find it anywhere.

**Comment by TimmekHW** [comment]
Добавь --api --listen
