### ISSUE TITLE
Juypter notebook killed

### ISSUE THREAD

**Issue by Vendetta-S** [lllyasviel/stable-diffusion-webui-forge#1560]
when I was trying to test the Q8 gguf model of flux.1 dev, for some reason it always kills the instance no matter what I do

[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ...
StateDict Keys: {'transformer': 780, 'vae': 244, 'text_encoder': 196, 'text_encoder_2': 220, 'ignore': 0}
Using Default T5 Data Type: torch.float16
Using Detected UNet Type: gguf
Using pre-quant state dict!
GGUF state dict: {'F16': 476, 'Q8_0': 304}
Killed

Please help, is this model too much or am I missing something?

**Comment by lllyasviel** [comment]
you need to figure out linux equivalence to https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1474 which is win solution

**Comment by Vendetta-S** [comment]
Ah thanks, just noticed that my notebook didn't really had any more storage
