### ISSUE TITLE
[Feature Request]: better support for dynamic thresholding?

### ISSUE THREAD

**Issue by Vynsyc** [lllyasviel/stable-diffusion-webui-forge#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

At the moment, using dynthresh in sd forge results in images gaining really fried colors, which is what usually happens if you turn the cfg scale up past 12 and higher:

![Screenshot 2024-02-09 162745](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/159470459/6c9ab299-5558-4393-8eb3-7308f6089175)
![Screenshot 2024-02-09 163108](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/159470459/d708c702-cb25-494f-85f0-ac55af52668e)
![tmp0stpyuik](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/159470459/6a41112e-f6d2-4a95-ab51-431f46c0ccc5)

Dynthresh is supposed to fix that, but so far the webui acts like it isn't even on. 

- I do not have any other extension on.
- The color issues occur no matter what sampler is being used.
- Nothing in the prompt areas seem to be the issue.
- I'm reusing settings that worked before to no avail:
![Screenshot 2024-02-09 162803](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/159470459/f84e30e0-d4a4-49c5-88b9-84a987545f51)
![Screenshot 2024-02-09 163200](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/159470459/c384e824-e45e-4783-ba7f-378a1f2eee44)
- If the issue is merely something in settings, I am unsure what I must change to fix that.

I can only really conclude that SD forge isn't optimized to use that extension or something.

### Proposed workflow

1. Go to webui
2. Activate Dynamic Thresholding
3. Turn CFG scale way up
4. Tweak DynThresh settings to for a suitable output
5. Begin genning and webui should output images without deep fried colors and contrast.

**Comment by lllyasviel** [comment]
Dynamic Thresholding is now integrated, please update and uninstall incompatible one

**Comment by Vynsyc** [comment]
Noted.
Thank you for your time and effort!
