### ISSUE TITLE
advice: enhance the access address -Currently Running: http://localhost:8889/

### ISSUE THREAD

**Issue by hanetyb** [lllyasviel/stable-diffusion-webui-forge#1577]
could you pls use real ip address instead of default localhost or give modification permission to user for change?

its not convenient to access the link when i use other PC to access the forge host. 

![image](https://github.com/user-attachments/assets/e5d9dff3-74d1-4636-ba64-6d487bd105fc)

**Comment by mkgiga** [comment]
what do you mean by real ip address?

**Comment by sinuso** [comment]
Edit the webui-user.bat file and in `set COMMANDLINE_ARGS=` add this `--server-name 192.168.111.139`

`set COMMANDLINE_ARGS=--server-name 192.168.111.139`

I use 192.168.1.20 and it works perfectly.

![image](https://github.com/user-attachments/assets/85c66da5-bc64-42ac-b9bc-1bb6b69711dc)
