### ISSUE TITLE
FLUX LORAS are blurry 

### ISSUE THREAD

**Issue by wesux** [lllyasviel/stable-diffusion-webui-forge#1587]
Every picture I create without Lora is prefectly crisp using models: NF4, FP8, FP16, Q8, and DEV

As soon as I add a LORA they all become blurry and artifacted.

**Comment by ZeroCool22** [comment]
> Every picture I create without Lora is prefectly crisp using models: NF4, FP8, FP16, Q8, and DEV
> 
> As soon as I add a LORA they all become blurry and artifacted.

What LORA for ex.?

**Comment by Vagrin** [comment]
I had the same problem. Someone said to set "Diffusion In Low Bits" to "Automatic (fp16 LoRA)" at the top. I did that and all of my LoRAs and downloaded ones have worked ever since. Good luck!

**Comment by tomsin9** [comment]
same here after update, there is no problem for using one lora, it only became blurry when i used more than one loras.
