### ISSUE TITLE
[Feature Request]: To have MultiDiffusion Integrated with upscale model selection.

### ISSUE THREAD

**Issue by Vigilence** [lllyasviel/stable-diffusion-webui-forge#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Big thanks for having tile diffusion integrated into forge, along with vae tiling!  I noticed that the it no longer allows us to use an upscaler and we can't select the upscale size. 

If the upscale model selection and scale by functions could be added that would be super! Or at least the upscale model selection, with the upscale size being done in the "resize by" section.

I currently don't know of a way to use an upscaler with the integrated MultiDiffusion extension and this would make it easier for us to use it.

![Screenshot 2024-02-09 225207](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/22781570/7ed1a2cb-c91b-4c9a-ac69-0dbcc9d4ca71)
![Screenshot 2024-02-09 225157](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/22781570/c754f6c6-fe22-4f55-8e6b-2b6feed048af)

### Proposed workflow

1. Go to MultiDiffusion Integrated 
2. Press enable
3. Change settings
4. Select Upscale Model
5. Change "Scale Size" amount
6. Add warning in cmd window that "Reize By" should match scale amount
7. Profit

Or
1. Go to MultiDiffusion Integrated 
2. Press enable
3. Change settings
4. Select Upscale Model
5. Change "Resize By" amount to the desired size you want to upscale by
6. Profit

**Comment by lllyasviel** [comment]
the upscale in tiled diffusion has long been one of the most confusing part and I never know in what order it is working.

that upscale option makes resolution computation into a mess and no one ever know how `tile size`, `a1111 i2i upscale-to factor`, `i2i image resolution`, `i2i crop-and-resie resolution`, the` tiled diffusion extension's scale facter`, and `extension upscaler factor`, and `extension upscale number in model name like 4x vs 2x`, are actually computed and it is purely impossible to predict them from a user perspective

Extras can do everything and we recommend users to just send to extras to get an optimal SR and send back, and in that way you can even pick the best upscaler in a much better way

We finally have a nice and simple tiled diffusion and please do not repeat some previou mistakes

**Comment by Vigilence** [comment]
Ok thank your reply!

So you recommend two methods,  to use ultimate sd upscale which will use tiled vae automatically, or send our image to extras and resize, then head back to img2img to add details using control net?

**Comment by lllyasviel** [comment]
use it in any way it can be used

**Comment by Gothmoth88** [comment]
what about the noise inversion part.. do i miss something? i don´t see it.

**Comment by Vigilence** [comment]
Only tiled vae and a stripped tiled diffusion were added.  Might have better luck asking original author to finish the port.

**Comment by wangwenqiao666** [comment]
it's no use, you can't turn it off

**Comment by aimarxjg** [comment]
> 以任何可以使用的方式使用它

敏神好，打扰了，现在有1个反推收费Magnific AI 放大的方法，需要用到Tiled Diffusion里面单独选择放大器选项，但是MultiDiffusion没有这个功能，希望能添加上去，谢谢了
https://twitter.com/philz1337x/status/1768679154726359128?s=20
（这方法比最近的几种高配显存的方法模型都要好，并且只需要8G显存）
