### ISSUE TITLE
New behavior for hiresbutton is great. Though I think the caption is off

### ISSUE THREAD

**Issue by andy8992** [lllyasviel/stable-diffusion-webui-forge#1592]
I think it's one level behind.

So if your image was 10x10 and you upscaled by 2 the caption would say 10x10 still. It would say, 10x10 and "original size" 10x10. 

But if you open the image you'll find it DID increase in size. 

Press the button again and it will now say 20x20 but the actual image will be 40x40. 

Hopefully that makes sense. Feature works but the caption is one iteration behind I believe.

**Comment by DenOfEquity** [comment]
That part works the same as the original highres fix - there's caption entries for 'Size' and 'Hires upscale'. Changing it would break repeatability (via loading the infotext) and backwards compatibility. That's inevitable over >=2 iterations anyway, hence adding 'Original Size' as some extra information.
