### ISSUE TITLE
[Feature Request]: Add Fooocus inpaint to Forge

### ISSUE THREAD

**Issue by trihardseven** [lllyasviel/stable-diffusion-webui-forge#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I have tried Fooocus before and one of the things I really liked was the inpainting. @lllyasviel, since you own both repos, would you consider bringing some of its features to Forge as an integrated extension in the future? 

Thank you for all the things you've given to the stable diffusion community by the way. I think Forge is easily the best UI right now.

### Proposed workflow

1. Go to img2img tab 
2. Press Fooocus Inpaint Integrated box
3. ...

### Additional information

A dev made a node/extension of it in comfy: https://github.com/Acly/comfyui-inpaint-nodes

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/fb2e2716683453e8b0ba775f7596d8c9b080177d

**Comment by umiyuki** [comment]
I am grateful to be able to use the Fooocus inpainting model in Forge.
BTW, I used the following input image and mask image to inpaint in Forge, though,↓
<img src="https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/6958622/b165a286-55cf-4839-af33-9f3fff2f0efd" width="40%">
<img src="https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/6958622/7f12f432-c019-4d69-8588-bc308f650cb5" width="40%">

This is the image that is generated. The inpainted part is almost the same as the original image.↓
<img src="https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/6958622/5c05b0b8-dd42-4980-a8e8-96dd8b3b5e6f" width="40%">

If I do the same thing with Fooocus, it will inpaint completely new content as shown in the image below.↓
<img src="https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/6958622/751c3bd7-e4bf-4309-b035-e23828afb101" width="40%">

Is there any way to make Forge work the same way as Fooocus?

**Comment by giricahunik** [comment]
Hello! just start trying forge and can't found the fooocus inpainting option. anyone know how to enable the option?
