### ISSUE TITLE
Latest main - doesn't attempt to download realisticVisionV51_v51VAE.safetensors

### ISSUE THREAD

**Issue by IgorAherne** [lllyasviel/stable-diffusion-webui-forge#1603]
https://github.com/lllyasviel/stable-diffusion-webui-forge#installing-forge
From `Installing Forge` section, use one-click installation `Forge with CUDA 12.1 + Pytorch 2.3.1`

`run.bat`

...The requirements are installed and the neural net is downloaded fine.

But if you were to do:
`update.bat`
`run.bat`

...Then the neural net doesn't get downloaded and the message is displayed: `You do not have a model!`

attaching a log.txt 
[log.txt](https://github.com/user-attachments/files/16816660/log.txt)

**Comment by IgorAherne** [comment]
Here is the callstack for the first case, which works fine:
![image](https://github.com/user-attachments/assets/5b616526-891c-4d04-8448-bda7f64e1b10)

**Comment by raz0rf0x** [comment]
[Recently removed](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/15f41b2e5e81f86ef4e32f0abaabc83320d73bc9)

**Comment by IgorAherne** [comment]
> [Recently removed](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/15f41b2e5e81f86ef4e32f0abaabc83320d73bc9)

Hm, looks like this is intended? But wouldn't we want to download a default neural network initially?

**Comment by raz0rf0x** [comment]
I'm sure plenty of people have their own preferred models making it an unnecessary download during initial setup. 

The original issue was that the model yet to be loaded during startup, and if there was no model it would error out. Now that models aren't loaded until generation it is no longer required. 

One less multi gigabyte download I'm not going to use is a positive in my book.
