### ISSUE TITLE
txt2img i can't use override_settings via API

### ISSUE THREAD

**Issue by Vugas** [lllyasviel/stable-diffusion-webui-forge#1610]
I'm trying to pass values like sd_vae and sd_model_checkpoint as an example, but it's not changing anything. It might be broken.
I'm using the latest commit.

**Comment by altoiddealer** [comment]
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1532

**Comment by Mr-Normal** [comment]
> #1532

Sorry, but I don’t understand why you sent a link to this post, the topic mentioned (non-working api) is not discussed there.
I think the answer is there https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/1465#issuecomment-2307909355
It just doesn't work and it probably won't for months.

**Comment by altoiddealer** [comment]
Specifically, the section in that issue regarding **override_settings**

**Comment by Vugas** [comment]
so sad, ehh. . .

**Comment by Mr-Normal** [comment]
> so sad, ehh. . .

I now working with api on ComfyUI, it can help you with youre problem.

**Comment by Sourdface** [comment]
Getting the same problem. I thought this issues stemmed from Automatic1111 but theirs is working as expected; this issue seems specific to Forge.

**Comment by superdotaplaya** [comment]
wonder if thats causing my issue where I just get "{'detail': 'Not Found'} " from my api calls, it worked a few weeks ago, then recently i fired it back up after updating and the api calls from my discord bot no llonger work on forge...
