### ISSUE TITLE
Is there any way to go back to older version of Forge?

### ISSUE THREAD

**Issue by DigiClau** [lllyasviel/stable-diffusion-webui-forge#1620]
The latest update version of Forge has some issues with extensions that I used to use without any problems with previous version of Forge.  Is there any way I can go back the older version after the latest update?  The version before Flux is enabled?

**Comment by derfasthirnlosenick** [comment]
git checkout 249446c
Or whatever commit you want to jump to

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/stable-diffusion-webui-forge?tab=readme-ov-file#previous-versions

**Comment by DigiClau** [comment]
> https://github.com/lllyasviel/stable-diffusion-webui-forge?tab=readme-ov-file#previous-versions

Thank you, I will check the section.
