### ISSUE TITLE
All Flux Q models are very slow on my 3060 12 GB - FP8 is working

### ISSUE THREAD

**Issue by carlmoss22** [lllyasviel/stable-diffusion-webui-forge#1622]
![ss1](https://github.com/user-attachments/assets/c4de860a-b28f-4493-8a1c-b82a94a56089)
even q5_0 and q5_k_s are unusable about 160it/s
but ppl are using this models. so what is wrong on my settings?

hope somebody can give me some hints whre to look.

thx in advance!

**Comment by lllyasviel** [comment]
update to latest and paste full console logs

**Comment by carlmoss22** [comment]
thank you for your answer!
that's crazy. i tried it min. 20 times over the last 10 days to make q models working. every time it was very slow. 

now i tried it again for your logs, updated forge, loaded q5_0 model  very slow again about 240it/s canceled it, loaded q8_0 model and suddenly it works with 5it/s

now it's working as it should! i tried it with q8,q5 and q6_k.

Thank you for your work!

**Comment by carlmoss22** [comment]
thank you for your answer!
that's crazy. i tried it min. 20 times over the last 10 days to make q models working. every time it was very slow.

now i tried it again for your logs, updated forge, loaded q5_0 model very slow again about 240it/s canceled it, loaded q8_0 model and suddenly it works with 5it/s

now it's working as it should! i tried it with q8,q5 and q6_k.

Thank you for your work!
