### ISSUE TITLE
3x Controlnet not working using Batch images

### ISSUE THREAD

**Issue by Trikos** [lllyasviel/stable-diffusion-webui-forge#1625]
Hi, Im using the forge to create img2vid to create animations because ti is super fast instead of using a1111.
The steps I take are:
img2img - Batch tab, select my path, enable all 3 controller and select Batch tab using the same path as before. In my folder there are 5 different images, when I start generating it only takes the first image and iterate 5 times on that ignoring all the others.
What can I do to fix it?
Im using Euler a, 20 step, 512x910, CFG 3, denoising 1, clipskip 2, ckpt aniverse 1.5
Controlnet: pixel perfect, control net is more important.

Some commands to enable when I start the webui maybe? Or some settings?

Thank you, amazing job

**Comment by westNeighbor** [comment]
The controlnet `batch` never works since I first started to use Forge a year ago. I mostly want it on the `txt2img`.

**Comment by DenOfEquity** [comment]
Trikos, I might be misunderstanding your process, but it seems you are setting batch within img2img and then in controlnet as well? The img2img batch will send the images to all the controlnets as needed. No need to set up the batch within controlnet too. Doing it this way is working for me.

westNeighbor, for batching within controlnet you have to set *Batch size* to match the number of images sent to controlnet via **Batch Folder** tab. *Batch count* doesn't work for this. And **Batch Upload** tab in controlnet seems to be broken at the moment.

**Comment by westNeighbor** [comment]
It looks my bad. It does work by set `Batch size`. The logic is different with A111 which is set by `Batch count`.

**Comment by westNeighbor** [comment]
@DenOfEquity  Is there a way to fix the seed number for all batch controlnet images? Currently it will increase the seed by 1 whether I fix the seed or not?

**Comment by westNeighbor** [comment]
> Trikos, I might be misunderstanding your process, but it seems you are setting batch within img2img and then in controlnet as well? The img2img batch will send the images to all the controlnets as needed. No need to set up the batch within controlnet too. Doing it this way is working for me.
> 
> westNeighbor, for batching within controlnet you have to set _Batch size_ to match the number of images sent to controlnet via **Batch Folder** tab. _Batch count_ doesn't work for this. And **Batch Upload** tab in controlnet seems to be broken at the moment.

It accumulates all the batch controlnet images into the vram, so at most ~30 batch images for a 16GB video card. So if you have 150 batch images, it takes more than 5 hours for my 4080 card. For this scenario, I think the official A1111 way is the way to go.

**Comment by DenOfEquity** [comment]
I don't know any way to fix the seed for this. There is a setting that is named like it should control it (controlnet_increment_seed_during_batch), but it's not referenced anywhere in the code. And looking at old Forge, not used there either.

**Comment by westNeighbor** [comment]
> I don't know any way to fix the seed for this. There is a setting that is named like it should control it (controlnet_increment_seed_during_batch), but it's not referenced anywhere in the code. And looking at old Forge, not used there either.

![Screenshot 2024-08-28 130031](https://github.com/user-attachments/assets/362e15bb-dced-4599-a412-b0ccaa63a931)
The new `A1111` add the function, see above image. @DenOfEquity

**Comment by Trikos** [comment]
Ok it worked, I guess there was a glitch or something else cause It always used the same images. I did a clean install.
Thank you all

**Comment by j238** [comment]
“Batch size” base is useless
For example, if you set 100 "Open Pose" images in the Controlnet Batch Folder and try to perform batch processing, Memory Overflow will occur.
A1111 can be used as above.
