### ISSUE TITLE
First generation EXTREMELY slow after updating (FLUX)

### ISSUE THREAD

**Issue by CustomGraphix1** [lllyasviel/stable-diffusion-webui-forge#1630]
So after updating to the new version last night the first generation speed is at an ungodly slow speed for some reason as shown here 
![Screenshot 2024-08-31 142338](https://github.com/user-attachments/assets/e20b1901-2c3e-4ded-9e78-f91c97633c00)

Just updated to the latest this morning and still happening.

If you cancel that gen and start another it goes back to normal speed.
![Screenshot 2024-08-31 142551](https://github.com/user-attachments/assets/7a27a91a-163e-40ad-9ddd-c27fe00b112a)

Wasnt an issue for the first gen with previous updates starting a day ago.

Using the Q4KS model with t5xxl_fp16

EDIT: tested again with the t5xxl_fp8 and also the same, first generation speed super tanks but again if you cancel it and start a fresh gen the speed is fine 
![Screenshot 2024-08-31 144738](https://github.com/user-attachments/assets/ac6e08d8-4e15-4b47-8db4-1e346670e9b8)

after canceling the initial gen

![Screenshot 2024-08-31 144901](https://github.com/user-attachments/assets/57952930-2f0f-40cc-917e-c78f51fa7793)

this is the version info 

![Screenshot 2024-08-31 151937](https://github.com/user-attachments/assets/3375b781-bfa8-4bdf-b3e2-cd066695b831)

Also on a sidenote something happened to the console layout, its no longer uniform, not sure if that was intended.

**Comment by DavideAlidosi** [comment]
Please check here...
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1607

**Comment by DavideAlidosi** [comment]
For a quick downgrade:
git reset --hard c70fb38

**Comment by CustomGraphix1** [comment]
> Please check here... #1607

doesnt seem the same issue, your console clearly shows you going into low vram, mine isnt
![Screenshot 2024-08-31 143224](https://github.com/user-attachments/assets/30718f54-3ad5-4fbe-8ddd-b906b0ab4f1f)

**Comment by CustomGraphix1** [comment]
Went back to c239200 and all is fine, so between that and the latest is where this started

**Comment by DavideAlidosi** [comment]
> Went back to [c239200](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/c239200705ddddb414b85d227381e92fcd53caa0) and all is fine, so between that and the latest is where this started

Anyway, it looks like another LoRA issue.

**Comment by CustomGraphix1** [comment]
> > Went back to [c239200](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/c239200705ddddb414b85d227381e92fcd53caa0) and all is fine, so between that and the latest is where this started
> 
> Anyway, it looks like another LoRA issue.

im not using loras

**Comment by lllyasviel** [comment]
Hi do you have full console logs

**Comment by lllyasviel** [comment]
I added a quick https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/1f91b35a43858d8884d2b08d725aa46ec67a0f6e

update and try again

**Comment by CustomGraphix1** [comment]
> I added a quick [1f91b35](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/1f91b35a43858d8884d2b08d725aa46ec67a0f6e)
> 
> update and try again

Seems to be back to normal, thanks for the update, keep up the great work!

**Comment by lllyasviel** [comment]
Good
