### ISSUE TITLE
what the hell is going on, been using for 4 hours and now says cant run?

### ISSUE THREAD

**Issue by lgwjames** [lllyasviel/stable-diffusion-webui-forge#1632]
i have been using and testing for the last 4 hours
linked the web ui to my SD folder for models etc

rebooted and now when i run it says

venv "C:\Users\jessi\Desktop\Forge\webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-224-g90019688
Commit hash: 9001968898187e5baf83ecc3b9e44c6a6a1651a6
Traceback (most recent call last):
  File "C:\Users\jessi\Desktop\Forge\webui\launch.py", line 51, in <module>
    main()
  File "C:\Users\jessi\Desktop\Forge\webui\launch.py", line 39, in main
    prepare_environment()
  File "C:\Users\jessi\Desktop\Forge\webui\modules\launch_utils.py", line 434, in prepare_environment
    raise RuntimeError(
RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version:
https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest

**Comment by prakashrkrishnan** [comment]
same for me .. using for past few days.. getting this error from today afternoon -  RuntimeError: Your device does not support the current version of Torch/CUDA! Consider download another version:
https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/latest

**Comment by lunar-studio** [comment]
Are you both on Windows 11. I skipped direct installs and went with Stability Matrix. Haven’t really had an.y issues. Also check you have the latest nVidia drivers.

**Comment by prakashrkrishnan** [comment]
i am on windows 10 .. after deploying visual studio and i missed restarting.. if got fixed after i did so .. - ref = https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1194#issuecomment-2323427894

**Comment by lgwjames** [comment]
randomly removed all files. started again and working

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
