### ISSUE TITLE
problem with the Civitai browser 

### ISSUE THREAD

**Issue by nevskiyik** [lllyasviel/stable-diffusion-webui-forge#1635]
Hi, there is a small problem with the Civitai browser + extension, after installing or restarting it, Show previews disappears and the pictures do not open in full size, after a few minutes it goes away, can this be solved somehow?

**Comment by angelika3377** [comment]
I wish, it sucks not to be able to see images of the models

**Comment by DenOfEquity** [comment]
extension issues should be reported to the repo of the extension. The developer of civitai-browser-plus has made some updates recently.
