### ISSUE TITLE
[Bug]: Instant-ID & IP-Adapter fail with error, "AttributeError: 'dict' object has no attribute 'clone'

### ISSUE THREAD

**Issue by CCpt5** [lllyasviel/stable-diffusion-webui-forge#164]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Attempting to generate w/ Controlnet (built-in) and IP-Adapter and Instant-ID fail w/ error 'dict' object has no attribute 'clone'

### Steps to reproduce the problem

Launch Webui
Toggle Controlnet / toggle Instant-ID
Select InsightFace (InstantID) / Model control_instant_id_sdxl [c5c25a50]
Add photo / prompt / generate
Console error / output doesn't use image

Same for IP-Adapter

### What should have happened?

Use image provided for generation / no error in console. 

### What browsers do you use to access the UI ?

Google Chrome, Microsoft Edge

### Sysinfo

[sysinfo-2024-02-10-06-18.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14228341/sysinfo-2024-02-10-06-18.json)

### Console logs

```Shell
venv "D:\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.10-latest-104-g5a7e7555
Commit hash: 5a7e7555287633d99da3ad3d733f8e4868643b76
Launching Web UI with arguments: --ckpt-dir e:\stable Diffusion Checkpoints
Total VRAM 24564 MB, total RAM 65244 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
*** "Disable all extensions" option was set, will only load built-in extensions ***
ControlNet preprocessor location: D:\stable-diffusion-webui-forge\models\ControlNetPreprocessor
Loading weights [31e35c80fc] from e:\stable Diffusion Checkpoints\SDXL\sd_xl_base_1.0.safetensors
2024-02-09 22:20:46,742 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
model_type EPS
UNet ADM Dimension 2816
Startup time: 5.8s (prepare environment: 1.1s, import torch: 1.7s, import gradio: 0.5s, setup paths: 0.4s, other imports: 0.3s, list SD models: 0.2s, load scripts: 0.8s, refresh VAE: 0.1s, create ui: 0.4s, gradio launch: 0.3s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Loading VAE weights specified in settings: D:\stable-diffusion-webui-forge\models\VAE\sdxl_vae.safetensors
To load target model SDXLClipModel
Begin to load 1 model
Moving model(s) has taken 0.27 seconds
Model loaded in 3.3s (load weights from disk: 0.5s, forge load real models: 2.3s, calculate empty prompt: 0.4s).
To load target model SDXL
Begin to load 1 model
Moving model(s) has taken 0.97 seconds
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27/27 [00:04<00:00,  5.46it/s]
To load target model AutoencoderKL███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27/27 [00:04<00:00,  7.23it/s]
Begin to load 1 model
Moving model(s) has taken 0.20 seconds
Total progress: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27/27 [00:05<00:00,  5.10it/s]
2024-02-09 22:21:55,630 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27/27 [00:05<00:00,  7.23it/s]
2024-02-09 22:21:55,633 - ControlNet - INFO - Using preprocessor: InsightFace+CLIP-H (IPAdapter)
2024-02-09 22:21:55,633 - ControlNet - INFO - preprocessor resolution = 0.5
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\stable-diffusion-webui-forge\models\insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\stable-diffusion-webui-forge\models\insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\stable-diffusion-webui-forge\models\insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\stable-diffusion-webui-forge\models\insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\stable-diffusion-webui-forge\models\insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
2024-02-09 22:22:04,916 - ControlNet - INFO - Current ControlNet IPAdapterPatcher: D:\stable-diffusion-webui-forge\models\ControlNet\ip-adapter-faceid_sdxl.bin
*** Error running process_before_every_sampling: D:\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui-forge\modules\scripts.py", line 830, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 533, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
      File "D:\stable-diffusion-webui-forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\stable-diffusion-webui-forge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 436, in process_unit_before_every_sampling
        cond_original=cond.clone() if cond is not None else None,
    AttributeError: 'dict' object has no attribute 'clone'

---
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27/27 [00:04<00:00,  5.89it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27/27 [00:05<00:00,  5.33it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27/27 [00:05<00:00,  7.34it/s]
```

### Additional information

Tested with the most recent commit as of this post (and the bunch just prior as a few updates were pushed while typing this)

Update forge_version.py (1 parent [5a7e755](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/5a7e7555287633d99da3ad3d733f8e4868643b76)
commit ac94f38)

Also deleted all config files and Venv / relaunched for clean install. Disabled all extra extensions w/ option.

Uninstalled/reinstalled insightface (Redownloaded C++ requirements via Visual Studio installer)

Error persists.

---

Screenshot:
![dfsdfdfdsfsdds](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/37972078/646ff357-50d2-4188-b658-5778066061ef)

**Comment by grigo-j** [comment]
Getting the same issue with today's code modifications.

**Comment by lllyasviel** [comment]
sorry for that
update and try again

**Comment by grigo-j** [comment]
Thank you for the quick fix!

**Comment by VantomPayne** [comment]
I am getting the same errors as above

**Comment by Zhincore** [comment]
the important part might be
> AttributeError: 'dict' object has no attribute 'shape'
> 'dict' object has no attribute 'shape'

and I have the same issue, am I doing something wrong?

**Comment by KohigashiHitona** [comment]
@lshqqytiger
what does "[Remove duplicate samplers] meaning? I met same problem
`Traceback (most recent call last):
  File "E:\Program Files\sd webui forge\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\modules\img2img.py", line 248, in img2img_function
    processed = process_images(p)
                ^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\modules\processing.py", line 842, in process_images
    res = process_images_inner(p)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\modules\processing.py", line 990, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\modules\processing.py", line 1865, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\modules\sd_samplers_kdiffusion.py", line 188, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\modules\sd_samplers_common.py", line 281, in launch_sampling
    return func()
           ^^^^^^
  File "E:\Program Files\sd webui forge\modules\sd_samplers_kdiffusion.py", line 188, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\k_diffusion\sampling.py", line 149, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\venv\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\venv\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\modules\sd_samplers_cfg_denoiser.py", line 199, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\backend\sampling\sampling_function.py", line 362, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\backend\sampling\sampling_function.py", line 303, in sampling_function_inner
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\backend\sampling\sampling_function.py", line 267, in calc_cond_uncond_batch
    c['control'] = control.get_control(input_x, timestep_, control_cond, len(cond_or_uncond))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\backend\patcher\controlnet.py", line 300, in get_control
    control_prev = self.previous_controlnet.get_control(x_noisy, t, cond, batched_number)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\backend\patcher\controlnet.py", line 318, in get_control
    self.cond_hint = image_resize.adaptive_resize(self.cond_hint_original, x_noisy.shape[3] * 8, x_noisy.shape[2] * 8, 'nearest-exact', "center").to(dtype)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\sd webui forge\backend\misc\image_resize.py", line 94, in adaptive_resize
    old_width = samples.shape[3]
                ^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'shape'
'dict' object has no attribute 'shape'`

**Comment by lshqqytiger** [comment]
That commit is not authored by me, see 89bb71e828b2fa65790689fc45873aaed5315420. I just merged the upstream changes into my fork. So I have no idea.
