### ISSUE TITLE
[Question] Missing IP Adapter's Processors

### ISSUE THREAD

**Issue by Alicyl** [lllyasviel/stable-diffusion-webui-forge#1651]
Hey, uh, if this section is purely supposed to be for issues (bug reports), feel free to just delete this one.

I was wondering if webui-forge natively has all of the IP Adapter preprocessors packaged with it but under different names? Whenever I look up guides for how to use IP Adapter to achieve consistency, I see a few preprocessors in guides that I can't find on webui-forge's list under ControlNET such as these:

![msedge_ICbP42BXZ7](https://github.com/user-attachments/assets/25a1596f-282b-4bcc-8f2e-f4dbd02c2d8b)

Is there something extra I need to install for ControlNet or are they outdated/have been renamed?

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/932

**Comment by Alicyl** [comment]
Thank you~ 

> #932

Thank you~ Sorry I didn't find it earlier; I've been having SD-related tabs upon tabs related trying to learn and figure out all I can, haha.
