### ISSUE TITLE
Constant problems with Reactor

### ISSUE THREAD

**Issue by KatD98** [lllyasviel/stable-diffusion-webui-forge#1668]
Reactor has continued to have issues for me, one moment it works then another it throws an error. Current error is this, does anyone know how I can resolve this?

ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

**Comment by DenOfEquity** [comment]
reactor works correctly; if you are still having issues try updating/reinstalling it. Guessing, you may have an incorrect version of a dependency. Otherwise, extension issues are usually best posted to the extension repo.
