### ISSUE TITLE
UI presets for each type of model (SD, XL or Flux)  where?  how?

### ISSUE THREAD

**Issue by epictetito** [lllyasviel/stable-diffusion-webui-forge#1696]
Hi. In a lllyasviel tuto it says that “Forge now supports UI presets” for each type of model chosen (SD, XL or Flux). 

I have tried to change it in the UI in SETTINGS, but without success, although I have checked that the ui-config.json file is overwritten. When I start Forge always appear other values that are set somewhere else, that I can't find.

can someone tell me where I can set some concrete data of Sampler, Schedule, CFG Scale, width ..... for each type of model?

Thanks guys

**Comment by serick4126** [comment]
![image](https://github.com/user-attachments/assets/76da3a89-9f0c-4f2a-9d47-3a940840d9be)
The “all” preset applies the settings from ui-config.json.
