### ISSUE TITLE
HiRes fix button error

### ISSUE THREAD

**Issue by physeo** [lllyasviel/stable-diffusion-webui-forge#1705]
Running into the same issue referenced [here](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/950)|

`webui_forge_cu121_torch231\webui\modules\txt2img.py", line 95, in txt2img_upscale_function
    fake_image.already_saved_as = image["name"].rsplit('?', 1)[0]
TypeError: tuple indices must be integers or slices, not str
tuple indices must be integers or slices, not str
*** Error completing request`

**Comment by DenOfEquity** [comment]
Update, that error was fixed some time ago.
