### ISSUE TITLE
Can't select checkpoints after last update [05/09/2024].

### ISSUE THREAD

**Issue by Tekamania** [lllyasviel/stable-diffusion-webui-forge#1707]
Hi:

Seems today there was an update a few hours ago and (seems there was a styless.css update or something similar) and after running SD Forge my Checkpoints aren't available to being selected and i have 10 on my stable-diffusion folder. Before this update (2 hours ago) i was using SD Forge correctly and i could select checkpoints normally. There is a pic about what i see:

![Checkpointsnoavailable](https://github.com/user-attachments/assets/cedfa716-416d-4242-af0c-7ab413fd1737)

I hope its fixed soon :)

EDIT: Ok seems there is a problem with SD Forge. If you delete the last checkpoint you were using the program try to find it and if it doesnt find it it doest find any other checkpoint inside stable-diffusion folder so.... its a bug that must be fixed because if you delete your last checkpoint and you cant restore it you can't use SD Forge. Seems the program try to load some of the checkpoints inside your folder but it fails so the checkpoint selector ends empty.

**Comment by DenOfEquity** [comment]
I've just tested your scenario with deleting the last used checkpoint. The list is still there, but it seems only a small region to the left of the input box works for the initial selection. Normal operation is restored after this first selection.

Otherwise, if you use symlinks to redirect models directories you may need to recreate them.

**Comment by Tekamania** [comment]
> I've just tested your scenario with deleting the last used checkpoint. The list is still there, but it seems only a small region to the left of the input box works for the initial selection. Normal operation is restored after this first selection.
> 
> Otherwise, if you use symlinks to redirect models directories you may need to recreate them.

Hi thanks for your reply. Yes seems there is an "error" with the input box because as you say only if you click just in the left border of it the list opens correctly my fail to no test it correctly but i hope if helps to see if it could be fixed "a bit" because it was happening with todays update and not before.

Again thanks for your reply :)

**Comment by DenOfEquity** [comment]
Yes, it's definitely something that needs to be looked at - thanks for reporting it, and it *is* due to the update earlier.
I have a fix, will update soon.
CSS is a PITA.
