### ISSUE TITLE
Please make the masked area white instead of white and gray checkered

### ISSUE THREAD

**Issue by LilithDragoness** [lllyasviel/stable-diffusion-webui-forge#1711]
Fooocus was the first SD UI I ever used, and Forge is the second. I love it more and more. Thank you for that.

One thing I miss from Fooocus is that the masked area is white, which makes it much easier to spot when I miss a small area while masking. It happens every now and then. The white and gray checkered area makes it much harder to notice.

Please change that if it's convenient.

**Comment by DenOfEquity** [comment]
There's an option in the settings for this: search for Inpaint, you can disable the high-contrast brush and pick whatever colour for masking.

**Comment by LilithDragoness** [comment]
Thank you. It worked.

The text might need an adjustment, as it didn’t require 'Reload UI' but rather 'Restart UI.'

**Comment by soyv4** [comment]
> Для этого в настройках есть опция: найдите Inpaint, там можно отключить высококонтрастную кисть и выбрать любой цвет для маскировки.

Is it possible to make the mask transparent, or is there no such option?
