### ISSUE TITLE
lora support for one trainer loras

### ISSUE THREAD

**Issue by DarkViewAI** [lllyasviel/stable-diffusion-webui-forge#1727]
would love to use loras from one trainer on here

**Comment by monotected** [comment]
same , missed keys ..... 2 days ago try to add keys in lora.py *(like in comfui latest build) but nothing

**Comment by lllyasviel** [comment]
do you have example lora

**Comment by DarkViewAI** [comment]
> do you have example lora

Here is one, this one is trained with T5 and Clip L 

https://huggingface.co/Maxivi/sda/tree/main

**Comment by DarkViewAI** [comment]
@lllyasviel in comfyui it works fine.

https://github.com/comfyanonymous/ComfyUI/commit/d043997d30d91ab057f770d3396c2e288e37b38a

this is what they did

**Comment by DarkViewAI** [comment]
@lllyasviel i also added in a smaller version

**Comment by DarkViewAI** [comment]
<img width="936" alt="xz" src="https://github.com/user-attachments/assets/b52a4021-7bd0-4684-89ad-3a296f2e3f97">
it also seems comfy hasnt fixed the te2/t5 keys being loaded in

**Comment by DarkViewAI** [comment]
opened issue with them as well - https://github.com/comfyanonymous/ComfyUI/issues/4837

**Comment by lllyasviel** [comment]
update and try again

**Comment by monotected** [comment]
everything works for me )) ,Tnx ! *(only low lora strenth  about~ 0.5 for Dev )

**Comment by DarkViewAI** [comment]
> update and try again

works now thank you!

**Comment by DarkViewAI** [comment]
@lllyasviel seems this update broke kohya loras now

**Comment by DarkViewAI** [comment]
@lllyasviel https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1747
