### ISSUE TITLE
i have error in my run.bat

### ISSUE THREAD

**Issue by amazingpaco** [lllyasviel/stable-diffusion-webui-forge#1730]
:\webui_forge_cu121_torch231\system\python\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.

how to solve this thank you!

**Comment by drdiggle** [comment]
This message is stating that you have an environment variable (TRANSFORMERS_CACHE) set to a value. According to the message, the transformers home directory (HF_HOME) is the new version expected by the transformers library. If this is causing issues, I would remove it from your environment variables and just let the library automatically set a path.
