### ISSUE TITLE
ModuleNotFoundError: No module named 'gguf' 

### ISSUE THREAD

**Issue by marcolipe** [lllyasviel/stable-diffusion-webui-forge#1743]
hi , is there a way to fix this so the installation can continue ,

**Comment by thealgean** [comment]
I'm having the exact same issue.

**Comment by TheFerumn** [comment]
If this is the same error as in the AMD version of Forge then you have fix here:
https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge/issues/24
Remember to change path to your 'packages_3rdparty' folder

**Comment by thealgean** [comment]
I actually just did this and it worked. Thank you!
