### ISSUE TITLE
Kohya loras now broken after fixing one trainer lora support

### ISSUE THREAD

**Issue by DarkViewAI** [lllyasviel/stable-diffusion-webui-forge#1747]
Model loaded in 2.2s (unload existing model: 1.8s, forge model load: 0.3s).
[LORA] LoRA version mismatch for KModel: D:\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\models\Lora\Model-step00001800.safetensors
Skipping unconditional conditioning when CFG = 1. Negative Prompts are ignored.
[Unload] Trying to free 20401.34 MB for cuda:0 with 0 models keep loaded ... Done.

Trained this model with the clip l and t5 as well

https://huggingface.co/Maxivi/Kohya/tree/main

**Comment by DarkViewAI** [comment]
works fine in comfy

**Comment by lllyasviel** [comment]
do you have example lora

**Comment by DarkViewAI** [comment]
@lllyasviel here you go https://huggingface.co/Maxivi/kohya3/tree/main

**Comment by lllyasviel** [comment]
update and try again

**Comment by DarkViewAI** [comment]
@lllyasviel nope they results now are just blurry and bad quality
