### ISSUE TITLE
update.bat overwrites webui/webui-user.bat

### ISSUE THREAD

**Issue by bob-r-alfrodull** [lllyasviel/stable-diffusion-webui-forge#1748]
On Windows, running update.bat overwrites webui/webui-user.bat, resetting user path customization.

To reproduce: 

1. Customize ./webui/webui-user.bat
2. Run ./update.bat
3. View ./webui/webui-user.bat to see it has been reset

Expected behavior:
1. Best case scenario, update.bat will add any additional path settings to the existing environment, warning the user if the added paths don't exist.
2. Second best, any new path settings are appended but commented out and the user is warned
3. Third, user webui-user.bat is not touched and the user is told to add any new path settings 
4. Fourth best solution, webui-user.bat is backed up, then overwritten, and the user is told to fix it themselves.

Don't know if this affects *.sh files as well.

**Comment by ZeroCool22** [comment]
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1566

**Comment by wkpark** [comment]
https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/main/webui.bat#L4C5-L4C28

you can  add `webui.settings.bat`

**Comment by bob-r-alfrodull** [comment]
> #1566

Son of a gun.  And I even searched for webui-user.bat first but missed this when I was scanning the results.
