### ISSUE TITLE
Speed degredation when using gguf with CFG >1

### ISSUE THREAD

**Issue by BaseMe2** [lllyasviel/stable-diffusion-webui-forge#1749]
Recent update, between yesterday and today broke gguf speed on increased CFG values.
CFG=1, regular speed as expected.
CFG=1.5, for example, generation times 10x slower.

NF4 works fine. Restarted Forge and reproduced it twice. 
Tested with gguf Q4

**Comment by aggregate15** [comment]
you mean CFG or Distilled CFG ? Because CFG in Flux has been like this for me since the beginning when flux came in, changing it really increases generation times. I don't think CFG makes an impact though. Unless you mean Distilled CFG ?

**Comment by Haoming02** [comment]
> speed degredation when CFG >1

This is true for all models, not just Flux. `CFG = 1` basically means ignoring negative prompt. When `CFG` is not `1`, you are doubling the work it needs to do. Depending on your configuration, you can experience the "10x slower" if your VRAM is overfilled for example.

**Comment by BaseMe2** [comment]
> you mean CFG or Distilled CFG ? Because CFG in Flux has been like this for me since the beginning when flux came in, changing it really increases generation times. I don't think CFG makes an impact though. Unless you mean Distilled CFG ?

CFG, not destilled CFG

> This is true for all models, not just Flux. `CFG = 1` basically means ignoring negative prompt. When `CFG` is not `1`, you are doubling the work it needs to do. Depending on your configuration, you can experience the "10x slower" if your VRAM is overfilled for example.

No, please read. 2 times slower was normal before. now its 10 times slower. Same settings as before, where it was only 2x as slow.

**Comment by Haoming02** [comment]
So you are using the exact same settings, and are not running out of VRAM?

**Comment by BaseMe2** [comment]
I lowered GPU weights by another 100 MB, now it's almost as fast as before. Now there's 800mb VRAM of my GPU not used but at least it's not running into shared memory any more.

**Comment by maraan666** [comment]
some of your vram needs to be used for other stuff...
