### ISSUE TITLE
Refiner Problem!

### ISSUE THREAD

**Issue by 2NoobPlayer** [lllyasviel/stable-diffusion-webui-forge#1759]
Refiner
▼
Refiner is currently under maintenance and unavailable. Sorry for the inconvenience.

This error comes up when I try to use it. How to fix?

**Comment by mkgiga** [comment]
it's because the refiner is currently under maintenance and unavailable

**Comment by SirDuffy** [comment]
the construction has been going on for quite a while now, several weeks. when will it work again? i cant remember when it worked - please repair

**Comment by mkgiga** [comment]
> the construction has been going on for quite a while now, several weeks. when will it work again? i cant remember when it worked - please repair

it seems there are a lot of features and bugs with higher priority at the moment.
maybe you can help out and fix it?

**Comment by SirDuffy** [comment]
now i am using the version: [f0.0.17v1.8.0rc-latest-278-gbfee03d8]     (https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/bfee03d8d9415a925616f40ede030fe7a51cbcfd) - this one is making much better creations then all new versions. how can this be. I dont update it, for flux i am using a newer version.
