### ISSUE TITLE
After the update, I can't reset the Sampling method and Schedule type in hires. They disappeared.

### ISSUE THREAD

**Issue by makichan2000505** [lllyasviel/stable-diffusion-webui-forge#1763]
![image](https://github.com/user-attachments/assets/42f84b54-cf7b-4b9d-afe4-fb58b20aa4e2)
There used to be a reset checkbox here

**Comment by drdiggle** [comment]
It is now a setting in config.json. Specifically hires_fix_show_sampler and hires_fix_show_prompts

**Comment by makichan2000505** [comment]
> It is now a setting in config.json. Specifically hires_fix_show_sampler and hires_fix_show_prompts

thank you
