### ISSUE TITLE
Problem lifting the prompt from PNG via Image browser to txt2img

### ISSUE THREAD

**Issue by Kallamamran** [lllyasviel/stable-diffusion-webui-forge#1769]
**This is what Image Browser shows:**

`Prompt: Extreme closeup hyperrealistic photo of a bald J0hfr3 man <lora:j0hfr3_man_Flux.dev.lora_000004000:1> with a full beard as a realistic version of Homer Simpson from the Simsons TV-show, movie still, <lora:xlabs_flux_realism_lora_comfui:1> <lora:ugly_flux:0.5>`
`Lora hashes: j0hfr3_man_Flux.dev.lora_000004000: e3b0c44298fc, xlabs_flux_realism_lora_comfui: 8c6dd764ceff, ugly_flux: 5a4becfcc624`

**This is what gets read in to txt2img:**

`Extreme closeup hyperrealistic photo of a bald J0hfr3 man <lora:lynkcorim_lora:1> with a full beard as a realistic version of Homer Simpson from the Simsons TV-show, movie still,  <lora:xlabs_flux_realism_lora_comfui:1> <lora:ugly_flux:0.5>`

**It changes to the lynkcorim-lora and it's not even in the folder of lora's any more. 🤔**

**Comment by DenOfEquity** [comment]
Possible solution:
In **Settings** -> **Infotext** -> **Disregard fields from pasted infotext**, add *Lora hashes* to the list.

**Comment by WalternateBishop** [comment]
I'm seeing the same issue on my end too, it seems to swap the LoRAs to random ones despite the metadata having the correct ones written down. 
The solution @DenOfEquity suggested solved it for me!

**Comment by Romangelo** [comment]
> Lora hashes

There's no Lora hashes for me to select.
