### ISSUE TITLE
GPU Weights Reset to Max After Reloading the UI

### ISSUE THREAD

**Issue by toyssamurai** [lllyasviel/stable-diffusion-webui-forge#1788]
After reloading the UI, the GPU Weights slider always resets to Max. 

Also, I think a better way to handle GPU Weights is to use a percentage value, and may be a max/min MB input box (in the Settings tab?)  People who are using Cloud GPU may not always use the same GPU, setting the GPU Weights to a fixed value is very inconvenient.

**Comment by Weatherby43** [comment]
Getting the same. In fact, most UI settings reset. I even tried the old forge trick of editing the config file and entering new defaults. No luck. Every time the ui is reloaded everything resets to an arbitrary value. Height, width, sampler, scheduler, highres-fix settings, etc, etc.

**Comment by toyssamurai** [comment]
Looks like the GPU Weights no longer reset to Max now.

**Comment by raffetazarius** [comment]
> Looks like the GPU Weights no longer reset to Max now.

Since which version?
