### ISSUE TITLE
Generate Forever does exactly that and won't stop.

### ISSUE THREAD

**Issue by Weatherby43** [lllyasviel/stable-diffusion-webui-forge#1793]
In version:
![image](https://github.com/user-attachments/assets/155ab7b1-2b0c-4344-afb8-7043c230d75c)

Of Forge, using generate forever does just that... and doesn't stop. Even when you click cancel generate forever, it keeps genning images. Only way to stop it is to ctrl+c the console and end the script.

**Comment by Cranbert** [comment]
Generate forever is completely broken. It stops working if you minimize and walk away, and then WON'T stop working when you come back.

**Comment by tusharbhutt** [comment]
> Generate forever is completely broken. It stops working if you minimize and walk away, and then WON'T stop working when you come back.

OHHHHH... I was wondering why it would stop working randomly.  As for not stopping, there was a bug fix a couple days ago, seems to work OK for now.
