### ISSUE TITLE
Custom Directory Path doesnt work

### ISSUE THREAD

**Issue by Trikos** [lllyasviel/stable-diffusion-webui-forge#1804]
Hi everybody, after using forge a bit, I decide to move all my models, ckpt, lora, etc, to an external drive and the outputs with it. I set the various path in the Settings -> Paths for saving but the images arent saved in those new folders but always in output/datetime, creating a new folder every day for storing the images.
These are the setts
![image](https://github.com/user-attachments/assets/1bab6bea-20fa-4d2b-a0ab-c6ba248c9f15)
And these are the folders (I created the blackie one)
![image](https://github.com/user-attachments/assets/5e1a17e2-c907-41fe-80e8-f33420503a62)
all the folders are empty and every outputs goes into the datetime folder, including grid and extra images. How can I solve it?
I manually created that folders but nothing changed

**Comment by SvenErik1968** [comment]
Check your settings under `Saving images > Saving to a directory`:
![image](https://github.com/user-attachments/assets/e8c62122-0c43-44f2-b996-6b84b0eb8a4b)

**Comment by Trikos** [comment]
> Check your settings under `Saving images > Saving to a directory`: ![image](https://private-user-images.githubusercontent.com/10983802/366950976-e8c62122-0c43-44f2-b996-6b84b0eb8a4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTU2MzQsIm5iZiI6MTcyNjE1NTMzNCwicGF0aCI6Ii8xMDk4MzgwMi8zNjY5NTA5NzYtZThjNjIxMjItMGM0My00NGYyLWI5OTYtNmI4NGIwZWI4YTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE1MzUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MWIwNzE3NTFjOWVjMThkMzIyMTJhZWEwMzY4NjFhYTJhZDYwYzY4MzQzMzU0MGU4ODA0ZmYyNmQ5YTkyM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.abOtoOjBau7WDrrZM_gNEJNeuQpbKv_iR61IhrdopNw)

I check and there are equal to yours, what does it mean? Should I remove the directory name pattern? Or uncheck the first two tick?

**Comment by SvenErik1968** [comment]
Remove the check-mark on `Save images to a subdirectory`, and remove the `[date]`

**Comment by Trikos** [comment]
> Remove the check-mark on `Save images to a subdirectory`, and remove the `[date]`

I did it and now the grid images are saved in a folder named score 9 score 8 up score 7 up and the single images are saved under outputs.

**Comment by SvenErik1968** [comment]
So the files are saved to the directory you set. The filenames are saved based on the filename pattern you have under `Saving images > Saving images/grids`.

Read the [wiki](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Custom-Images-Filename-Name-and-Subdirectory) that are linked to on the settings page.

Here is what I use:
![image](https://github.com/user-attachments/assets/8a016d64-5376-4968-b265-7df335aa0981)

**Comment by Trikos** [comment]
I make it work thanks, but it wasnt so clear the process. I solved putting these settings:
![image](https://github.com/user-attachments/assets/8c3e55e7-b52b-4cd2-8cbb-92f3a74f5318)
![image](https://github.com/user-attachments/assets/928c4c64-78ee-4277-aa35-6351d79392b8)
