### ISSUE TITLE
Lora tab of UI question

### ISSUE THREAD

**Issue by Psokratease** [lllyasviel/stable-diffusion-webui-forge#1813]
I recently switched to this from automatic 1111. 
Thank you for updating this.
![Error loading pic](https://github.com/user-attachments/assets/6733791b-b260-43ea-9a04-c1a87d0c546e)

On Txt2img >Lora tab; hovering over a Lora preview will give you 4 clickable options:  A Civitai emblem, model info, copy to clipboard,, edit metadata.
All funtion except for Civitai emblem, It will go to the "Loading model.." screen and will not load any info. It simply hangs there. 
I used this in automatic 1111 very much. It's helpful and speeds up my production very well.
I can not get it to work.   I think perhaps a parameter in settings I have not located?
API is in settings, and the civitai browser+ works to achive getting to the info page at civitai (that I want) but is inconvienient.

I would very much appreciate assistance on this.  
Thank you!

**Comment by DenOfEquity** [comment]
The civitai emblem is added by the extension; and that message is also from the extension. The three built-in buttons work properly without it, so it's one of multiple current problems with civitai browser plus.
