### ISSUE TITLE
LOAD AND UNLOAD every time i try to create an image ? 

### ISSUE THREAD

**Issue by MIKETUFFIN66** [lllyasviel/stable-diffusion-webui-forge#1819]
![1111111](https://github.com/user-attachments/assets/e90c02ef-7c8b-4f3b-8b47-422cd9a1cb95)

can any one please tell me what is this ,, and does this only happened when i use FLUX model ? is it normal or i have to do something ? thanks in advance

**Comment by DocShotgun** [comment]
The model moving is meant to only load the needed parts of the model into VRAM when they are being used. Without it, even a 4090 has too little VRAM to generate images using Flux.

**Comment by MIKETUFFIN66** [comment]
> The model moving is meant to only load the needed parts of the model into VRAM when they are being used. Without it, even a 4090 has too little VRAM to generate images using Flux.

so its normal and it happens to everyone ! right

**Comment by DocShotgun** [comment]
> > The model moving is meant to only load the needed parts of the model into VRAM when they are being used. Without it, even a 4090 has too little VRAM to generate images using Flux.
> 
> so its normal and it happens to everyone ! right

Probably unless you're running flux on a 48-80gb GPU or something lol.

**Comment by kwilliams81** [comment]
This seems to be new the load size (used to be partial for full flux dev), it was previously able to run on my 4090 just in VRAM at 512x512, 768x768.

**Comment by MIKETUFFIN66** [comment]
> The model moving is meant to only load the needed parts of the model into VRAM when they are being used. Without it, even a 4090 has too little VRAM to generate images using Flux.

yes you are right . thanks
