### ISSUE TITLE
is there any way to stop this moving model thing 

### ISSUE THREAD

**Issue by l33tx0** [lllyasviel/stable-diffusion-webui-forge#1820]
each time this take around 10-15 seconds while image generation itself take 30 sec for 20 step on a 3080 ti card fp8 quant flux 
this happens each time if i generate in batch or single single 

Moving model(s) has taken 10.72 seconds
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:28<00:00,  1.42s/it]
[Unload] Trying to free 4563.84 MB for cuda:0 with 0 models keep loaded ... Current free memory is 1877.96 MB ... Unload model KModel Done.█████████████████████████████████████████████████████████| 20/20 [00:28<00:00,  1.49s/it]
[Memory Management] Target: IntegratedAutoencoderKL, Free GPU: 10957.89 MB, Model Require: 159.87 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 9774.01 MB, All loaded to GPU.
Moving model(s) has taken 4.50 seconds

**Comment by nitinmukesh** [comment]
Yeah it increase the processing time.

**Comment by Vagrin** [comment]
Since I'm able to use models/clips/t5s that could never fit in my VRAM (3060 12GB) I've always assumed all that model moving was necessary to be able to use the good stuff at all. What you're describing is likely necessary. No?

**Comment by DocShotgun** [comment]
The model moving is meant to only load the needed parts of the model into VRAM when they are being used. Without model moving, you wouldn't be able to generate with Flux at all on a 3080ti.

**Comment by l33tx0** [comment]
> The model moving is meant to only load the needed parts of the model into VRAM when they are being used. Without model moving, you wouldn't be able to generate with Flux at all on a 3080ti.

Moving model from RAM to VRAM should not take this much time unless some kind of processing is occurring during the transfer, or there is an issue affecting the transfer.

**Comment by Juqowel** [comment]
Try my extension: https://github.com/Juqowel/GPU_For_T5

CPU option uses RAM for T5.

**Comment by nitinmukesh** [comment]
> The model moving is meant to only load the needed parts of the model into VRAM when they are being used. Without model moving, you wouldn't be able to generate with Flux at all on a 3080ti.

Make sense.
