### ISSUE TITLE
Hires fix broken for me the past few days. Anyone else?

### ISSUE THREAD

**Issue by Vagrin** [lllyasviel/stable-diffusion-webui-forge#1831]
High res fix was working great. Although understandably super slow. Foolhardyremarky (-sp). A few days ago after an update all my hires fixes look like this:
![image](https://github.com/user-attachments/assets/0d22b0c5-bbb8-4d44-b3e4-4d1c699d7412)
It doesn't matter what upscaler I use. Foolhardyremarky - latent - ESRGAN 4X. All look the same from first step. Super burnt. ESRGAN 4X works fine under Extras by the way.

If yours works, please tell me and I'll need to start researching a fix for my specific situation.

**Comment by NeiroNext** [comment]
Can you send your **High res fix** image (as file with meta data) to testing it by myself ?
It looks like some problems with VAE.

**Comment by lebeastmode** [comment]
make sure Hires CFG Scale is set to 1.
I had the same prob and it fixed it for me.

**Comment by Vagrin** [comment]
> make sure Hires CFG Scale is set to 1. I had the same prob and it fixed it for me.

Hooray! That was it. Great catch. I'm so used to settings you don't touch in highres fix using the main generation settings. I'm sure lots of people are. Now I and everyone else knows what happens when you crank CFG to 7! Thanks for the help!

**Comment by Vagrin** [comment]
Make sure you double check the settings in Highres fix everyone. If possible, CFG should default to 1 when Flux is selected or at least use the main generation settings if nothing is changed.
