### ISSUE TITLE
Inconsistent Generations Since " CFG and Distilled CFG for hiresfix (#1810)"?

### ISSUE THREAD

**Issue by Hypothyroidism** [lllyasviel/stable-diffusion-webui-forge#1841]
Please forgive me if this has already been addressed, as I am still trying to familiarize myself with GitHub. Since Commit: #1810, my generations have lacked the form of realism I was previously achieving, especially with the new Flux Realistic Sampler. Of course, this could be my own ignorance as I do not understand what settings should be set for the Distilled CFG and CFG Scales within HighRes Fix.

I guess my question is, what are the suggested settings for this? Or is there an issue present within this commit? I typically use 2.5-2.8 Distilled CFG with Flux Realistic & Simple and 1.0 CFG Scale, but I assumed matching this in HighRes Fix would lead to constitency, yet it still looks like its generating at like 3.5-4ish due to prominent artifacts and plastic-like skin.

Again, I apologize if this is the incorrect spot for this, but I just wanted to make sure I wasn't going crazy since I updated Forge lol.

**Comment by DenOfEquity** [comment]
Matching HighRes settings to base settings should lead to identical output before/after that commit. Previous behaviour simply reused the base generation settings in HighRes. (Even older behaviour didn't respect user set Distilled CFG in HighRes, defaulted to 3.5.)
