### ISSUE TITLE
SwinIR 4x Upscaler issue, anyone help me please...

### ISSUE THREAD

**Issue by goodbyerookie** [lllyasviel/stable-diffusion-webui-forge#1852]
when I'm trying to upscale any photo with swinIR 4x (with swinIR 4x default upscale model) in forge, here is the error..? how can I solve this? It didn't give such an error before. It started happening in the last few days. @lllyasviel 

BackendCompilerFailed: backend='inductor' raised: RuntimeError: Cannot find a working triton installation. More information on installing Triton can be found at https://github.com/openai/triton Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information You can suppress this exception and fall back to eager by setting: import torch._dynamo torch._dynamo.config.suppress_errors = True

**Comment by Melyns** [comment]
Sounds like a missing requirment but im not sure, the first thing id do is download forge to a new folder and see. Do you have this checked?
![image](https://github.com/user-attachments/assets/e4465f4d-fe61-4a1d-b04a-fa9f5350b453)

**Comment by Melyns** [comment]
Sounds like a missing dependency but im not sure, the first thing i'd do is download forge to a new folder and see. Do you have this checked? (settings > upscaling)

![image](https://github.com/user-attachments/assets/c17b8226-c0b2-4cca-8b23-0be9e306a0e4)

**Comment by goodbyerookie** [comment]
![Ekran Alıntısı](https://github.com/user-attachments/assets/c68298bd-9a8e-4b0a-8782-0a2b94acce23)
@Melyns that option is already selected.

**Comment by Melyns** [comment]
try to disable it, its disabled by default
