### ISSUE TITLE
HighresFix sometimes doesn't show sampler selection

### ISSUE THREAD

**Issue by maniac-0s** [lllyasviel/stable-diffusion-webui-forge#1859]
As the title says, I want to use a separate sampler in HiresFix. I saw it there a few times already but now it's gone again.

![Clipboard01](https://github.com/user-attachments/assets/6be55966-a03b-418d-803c-f680dbabbd45)

**Comment by DenOfEquity** [comment]
Settings -> UI alternatives -> Hires fix: show hires checkpoint and sampler selection
Previously, this option was ignored and the selections were always shown.
You won't get Checkpoint choice, but will get Sampler and Scheduler choices.

**Comment by maniac-0s** [comment]
Hm I never tinkered with that setting but but the selection is there sometimes and sometimes not.
