### ISSUE TITLE
Missing Options

### ISSUE THREAD

**Issue by QuoteRed** [lllyasviel/stable-diffusion-webui-forge#1874]
Half of my Ui/Options have gone missing and I have no idea how to reset UI or if that's a different kind of problem, resetting the PC and software does nothing.
![image](https://github.com/user-attachments/assets/1e5009c6-9a77-4f4d-9779-e4a9eda48aef)

**Comment by maraan666** [comment]
at the top left, select "flux" or "all" under "UI". does that help?

**Comment by LIQUIDMIND111** [comment]
> 确认下扩展是否开启?

yes

**Comment by QuoteRed** [comment]
not for me, i re-installed the whole thing that worked for me
