### ISSUE TITLE
forge crashes when generation starts

### ISSUE THREAD

**Issue by paul3Dmaster** [lllyasviel/stable-diffusion-webui-forge#1878]
A1111 work fine
![2024-09-20_20-09-27](https://github.com/user-attachments/assets/b71b3a18-a25b-430f-be34-690165b9ebba)

**Comment by likelovewant** [comment]
3G vram is not enough .try by increase your virtual memory . and test with swap section in top of right .https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1474
