### ISSUE TITLE
txt2img gallery and preview images not shown or previous not removed after creation

### ISSUE THREAD

**Issue by byteconcepts** [lllyasviel/stable-diffusion-webui-forge#1884]
From time to time (very often) either the preview images gallery (created images composed to one) and preview images from the last run were not removed or replaced in the GUI so still the preview images or the "gallery" from the last run are shown or no image nor gallery is shown.

Sometimes closing the tab and opening a new one in combination with the network tap of the developer tools with "Dont use cached" checked and leaving it open until the first run is complete helps displaying the preview images and gallery again. - But most of the times only for a few creations.

Sometimes killing! the browser and then opening forge-ui in a new tab with the above procedure is the last thing that helps.

Same on Firefox and Chrome on Linux.

Sometimes the developer tools network tab then shows JS connection errors, sometimes nothing.

Maybe this error message is the reason, appearing although no LoRA was selected, disturbing the networking of forge-ui? : 

```Traceback (most recent call last):
  File "/srv/www/vhosts/forge-ui/modules/extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "/srv/www/vhosts/forge-ui/extensions-builtin/sd_forge_lora/extra_networks_lora.py", line 45, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "/srv/www/vhosts/forge-ui/extensions-builtin/sd_forge_lora/networks.py", line 96, in load_networks
    errors.display(e, f"loading network {network_on_disk.filename}")
AttributeError: 'NoneType' object has no attribute 'filename'
```
I don't know... 
...slowly this is no longer fun

git pull says: Already up to date.

Ubuntu 22.04, NVIDIA 4090 24G

My call in my own start.sh:

```
./webui.sh \
 --cuda-malloc \
 --cuda-stream \
 --pin-shared-memory \
 --listen \
 --enable-insecure-extension-access \
 --administrator \
 $EXTRA_OPTS
```

Any Ideas?

**Comment by byteconcepts** [comment]
:-) ... Finally....

...a complete new installation and complete new manual configuration solved all the above.

Strangely, the first few runs after the basic configuration did create the images but all the above errors were still present.
I almost already wanted to give up but configured everything I need until the end and suddenly the errors went away and even fullscreen preview images are working now.

I really have no clue which config parameter did the trick, but now everything works like expected; as far as I can say now ;-)

**Comment by byteconcepts** [comment]
:-( Rejoiced too soon...

I'll create a last issue and then will probably give it up with forge-ui.

**Comment by Frankiesomeone** [comment]
yes when you lock and reuse the seed, the image preview doesn't update, it always displays the first image generated with that seed.

I fixed it this way (at least for now)

under Settings > Saving images / grids
check "Add number to filename when saving"

**Comment by DenOfEquity** [comment]
Another similar option is to use a filename pattern that will be unique - I always include `[datetime]`.

**Comment by byteconcepts** [comment]
ah,that may be re reason because after a fresh installation i first didn't adjust the filename prefix.

Many thanks!

Fortunately I can now also close this issue because I debugged the other error and it turned out that I had a SDXL LoRA "Perfect Hands 2" in my everyday "Default Negatives" Style in my personal styles.csv file :-(

Many thanks again!
