### ISSUE TITLE
WARNING: INCOMPATIBLE GRADIO VERSION DETECTED!

### ISSUE THREAD

**Issue by cuom1705** [lllyasviel/stable-diffusion-webui-forge#1889]
I got `WARNING: INCOMPATIBLE GRADIO VERSION DETECTED!` every launch of sd-forge web UI. I tried to uninstall and reinstall so many extensions but cannot found the problem.
Please help me to resolve it.
![image](https://github.com/user-attachments/assets/a4d845ab-22f9-4f1d-8c8d-301f2a56b8ba)

**Comment by cuom1705** [comment]
I tried to install https://github.com/hako-mikan/sd-webui-regional-prompter (after that I got the warning)

**Comment by DenOfEquity** [comment]
That extension is simply (currently) incompatible with new Forge.
There's a fork https://github.com/jessearodriguez/sd-forge-regional-prompter which you could try instead.
Also, an alternative: https://github.com/Haoming02/sd-forge-couple

**Comment by cuom1705** [comment]
Thank you, do you know how to remove this warning ?

**Comment by DenOfEquity** [comment]
Uninstall the incompatible extension by deleting its folder from `{Forge install location}\webui\extensions`, the folder should be called `sd-webui-regional-prompter`. Or disable it through the Extensions tab by unchecking the appropriate checkbox.

**Comment by cuom1705** [comment]
thank you

**Comment by DenOfEquity** [comment]
You're welcome. Closing issue as resolved.
