### ISSUE TITLE
Seed is increasing using fixed seed in a batch

### ISSUE THREAD

**Issue by zeittresor** [lllyasviel/stable-diffusion-webui-forge#1910]
While processing Images in a batch using a fixed seed it seams like for every new image the seed is currently increasing like seed=seed+1 like told in my problem here https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1871

**Comment by Haoming02** [comment]
Increasing seed by 1 in a batch is the intended behavior, dating back to Automatic1111 days.

Don't forget, Batch was for people to generate multiple images at once. It would be rather meaningless to only get 4 identical images, wouldn't it.

If you want to do comparison, what you are looking for is the `X/Y/Z Plot` instead. You can simply set the Axis to `Seed`, and enter the same value multiple times to achieve what you want.

**Comment by zeittresor** [comment]
> Increasing seed by 1 in a batch is the intended behavior, dating back to Automatic1111 days.
> 
> Don't forget, Batch was for people to generate multiple images at once. It would be rather meaningless to only get 4 identical images, wouldn't it.
> 
> If you want to do comparison, what you are looking for is the `X/Y/Z Plot` instead. You can simply set the Axis to `Seed`, and enter the same value multiple times to achieve what you want.

thanks. ok, thats a idea. i will try this using my https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1871 mod for the freeU extension with "random unet move" enabled but using your suggestion to use x/y/z with x using seed to a fixed value in a batch of 50 .. thumb up if it works this way :-)

**Comment by zeittresor** [comment]
ok, i have tested it but it is still increase the seed 
![grafik](https://github.com/user-attachments/assets/ba6e8f3f-c9cd-4c0c-b3fe-f56e0466d0a1)
even by setting the seed options to this:
![grafik](https://github.com/user-attachments/assets/6406d845-67a4-42c9-9cae-e3ef73415c39)

**Comment by zeittresor** [comment]
for sure i want to generate 50 same looking using a single seed but only with modifyed unet values like my random move script do.. any ideas ?

**Comment by zeittresor** [comment]
but for sure it is working like this.. but it is a little bit strange just to have this as a solution...
![grafik](https://github.com/user-attachments/assets/f0093116-6c61-481e-ba71-3b28e88a5493)

**Comment by zeittresor** [comment]
a result using this "workaround" is here: https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1871
