### ISSUE TITLE
/sdapi/v1/txt2img override_settings parameter don't override checkpoint

### ISSUE THREAD

**Issue by wangyafeng1990** [lllyasviel/stable-diffusion-webui-forge#1940]

**Comment by vaskers5** [comment]
+

**Comment by vaskers5** [comment]
+ - the same

**Comment by altoiddealer** [comment]
Frankly, I don't think `override_settings` is working at all right now.

As a workaround, you can POST your `override_settings` dict to the `/sdapi/v1/options` endpoint and it will change the image model and settings.

**Comment by vaskers5** [comment]
Open pr with fix for this issue

**Comment by altoiddealer** [comment]
> Open pr with fix for this issue

I do what I can :P

**Comment by vaskers5** [comment]
> > Open pr with fix for this issue
> 
> I do what I can :P

I mean, I've opened a pr with a fix for this problem and I'm waiting for a review)

**Comment by altoiddealer** [comment]
> > > Open pr with fix for this issue
> > 
> > 
> > I do what I can :P
> 
> I mean, I've opened a pr with a fix for this problem and I'm waiting for a review)

Awesome!   Can’t wait to check it out
