### ISSUE TITLE
TRANSFORMERS_CACHE

### ISSUE THREAD

**Issue by vkkk759** [lllyasviel/stable-diffusion-webui-forge#1944]
I am keep getting this warning, how to fix it?
TRANSFORMERS_CACHE
C:\Stable diffusion\webui_forge_cu121_torch231\system\python\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(

**Comment by vkkk759** [comment]
Also, Cuda using stream: false
it could generate problems?

**Comment by DarkPulse** [comment]
This is something more for Illyasviel to fix.

It's not an error or a setting you did wrong; basically it just means that some of the code (as-written) is deprecated, so if/when Forge moves to V5 of Transformers, they will have to adjust that. For now it's just putting up a notification, basically.

You can pretty safely ignore this.

**Comment by OtakuOW** [comment]
totally useless answers, which do not help to solve the problem
