### ISSUE TITLE
[Feature Request} Set standard LoRA trigger words and strength

### ISSUE THREAD

**Issue by gruzefix** [lllyasviel/stable-diffusion-webui-forge#1947]
If you click on a LoRA and it gets taken over into the prompt, you always get a strength of 1 and rarely, if ever, any trigger words. A strength of 1 is not always the best for certain LoRAs and maybe you like a strength of 0.8 better than the recommended 1.0 or it just spits out garbage at the preset value. Unfortunately, many LoRAs don't come with infos about their trigger words and/or optimal strength either once you download them, forcing you to go back to the page you downloaded them from in the first place or keeping spreadsheets.

These two settings could be saved as an entry in the HTML file accompanying the LoRA if you download sample images via, say, CivitAI Plus Browser, or another, standalone file.

**Comment by Juqowel** [comment]
Sounds like something that already exists.

![2024-09-30_00-01-39](https://github.com/user-attachments/assets/5f6b3526-483a-4be9-b58d-1b60712174fc)

Or do you mean something very non-standard?
