### ISSUE TITLE
Crop input image based on A1111 mask in Forge

### ISSUE THREAD

**Issue by Prigodjin** [lllyasviel/stable-diffusion-webui-forge#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Crop input image based on A1111 mask in Forge controlnet is absolutely need. I don see how to work with Instant-ID in inpaint without it.

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by huchenlei** [comment]
I think inpaint only crop is already disabled for instant id preprocessor.

See https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/8316773caaa3327ab205ae3b6250bbe07374d247/extensions-builtin/sd_forge_ipadapter/scripts/forge_ipadapter.py#L56-L67.

**Comment by Prigodjin** [comment]
I am very sorry. I probably expressed myself incorrectly. I'm not a programmer. I just wanted to say that I don’t see such a check box in Forge inpaint. Maybe i do something wrong?
![1](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/159698788/1a8e5964-443c-4204-bf41-81898a386981)
