### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by 37Stars** [lllyasviel/stable-diffusion-webui-forge#1980]
I am getting the error message "TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'" for everything I run now. New prompts, prompts from PNG Info, that worked yesterday. I have switched checkpoints, uninstalled extensions, deleted extensions, disabled all extensions. So far nothing has worked.

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-549-g4baf8ffb
Commit hash: 4baf8ffb9c617c05a4e3c23dcaafcdcedf5e42b2
Launching Web UI with arguments: --theme dark
Total VRAM 12282 MB, total RAM 65277 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Using pytorch cross attention
Using pytorch attention for VAE
*** "Disable all extensions" option was set, will not load any extensions ***
Loading additional modules ... done.
Model selected: {'checkpoint_info': {'filename': 'E:\\ForgeFlux\\webui\\models\\Stable-diffusion\\cyberrealisticPony_v63.safetensors', 'hash': '8da9e150'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 10.4s (prepare environment: 2.0s, import torch: 4.5s, initialize shared: 0.2s, other imports: 0.3s, initialize google blockly: 1.6s, create ui: 1.3s, gradio launch: 0.3s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 91.66% GPU memory (11257.00 MB) to load weights, and use 8.34% GPU memory (1024.00 MB) to do matrix computation.
Loading Model: {'checkpoint_info': {'filename': 'E:\\ForgeFlux\\webui\\models\\Stable-diffusion\\cyberrealisticPony_v63.safetensors', 'hash': '8da9e150'}, 'additional_modules': [], 'unet_storage_dtype': None}
[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... Done.
StateDict Keys: {'unet': 1680, 'vae': 248, 'text_encoder': 197, 'text_encoder_2': 518, 'ignore': 0}
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
K-Model Created: {'storage_dtype': torch.float16, 'computation_dtype': torch.float16}
Model loaded in 0.7s (unload existing model: 0.1s, forge model load: 0.6s).
Traceback (most recent call last):
  File "E:\ForgeFlux\webui\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "E:\ForgeFlux\webui\modules\txt2img.py", line 123, in txt2img_function
    processed = processing.process_images(p)
  File "E:\ForgeFlux\webui\modules\processing.py", line 817, in process_images
    res = process_images_inner(p)
  File "E:\ForgeFlux\webui\modules\processing.py", line 930, in process_images_inner
    p.setup_conds()
  File "E:\ForgeFlux\webui\modules\processing.py", line 1526, in setup_conds
    super().setup_conds()
  File "E:\ForgeFlux\webui\modules\processing.py", line 500, in setup_conds
    self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, total_steps, [self.cached_uc], self.extra_network_data)
  File "E:\ForgeFlux\webui\modules\processing.py", line 469, in get_conds_with_caching
    shared.sd_model.set_clip_skip(int(opts.CLIP_stop_at_last_layers))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by DenOfEquity** [comment]
That is CLIP skip, the particular error suggests the setting somehow doesn't exist. Try resetting it by adjusting the Clip skip slider in either 'sd' or 'all' UI setting, use **Apply settings** in the Settings tab afterward. If that doesn't work, try closing Forge then deleting `config.json` from the `{Forge install location}\webui` directory (but this will also lose any other settings you've changed).

**Comment by 37Stars** [comment]
Thanks. I made a backup the config.json, relaunched Forge and saved the settings. Then did a compare between the backup and the new config files and copied over the few settings I had changed.

Thank you!
