### ISSUE TITLE
Incorrect RAM definition

### ISSUE THREAD

**Issue by Dexxxt** [lllyasviel/stable-diffusion-webui-forge#1983]
Forge does not correctly determine the amount of RAM. It sees more than it actually has and tries to use this amount, but it runs into the actual amount of memory and crashes. Is there a way to specify the amount of RAM manually?

**Comment by DenOfEquity** [comment]
On start, Forge prints the amount of VRAM and RAM it finds to the console. Compare those to the expected values.
Also, see #1474.
