### ISSUE TITLE
The last days Forge on Runpod always OutOfMemoryError: 

### ISSUE THREAD

**Issue by carlmoss22** [lllyasviel/stable-diffusion-webui-forge#1984]
After 1 or 2 generations i always get this error on runpod. it worked before. seems like it's not clearing the memory.

OutOfMemoryError: CUDA out of memory. Tried to allocate 268.00 MiB. GPU 0 has a total capacity of 23.64 GiB of which 34.81 MiB is free. Process 1193254 has 23.60 GiB memory in use. Of the allocated memory 22.60 GiB is allocated by PyTorch, and 528.55 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by MysticDaedra** [comment]
I'm getting OOMs running on local using Cuda allocator, have to restart every couple of generations.

**Comment by alienzed** [comment]
getting lots of crashes... reverting to f5190349b43b6da91b039d5fa6cb85e23d0e5830 restores stability in my case.

**Comment by carlmoss22** [comment]
> getting lots of crashes... reverting to [f519034](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/f5190349b43b6da91b039d5fa6cb85e23d0e5830) restores stability in my case.

cool, but how to do this on runpod?

**Comment by carlmoss22** [comment]
it's working again. why? i don't know.

**Comment by alienzed** [comment]
I ... may... have changed my settings... I don't know anymore. I feel like some days are worse than others. I'm now avoiding multiple tabs, being more careful when switching models and all, sticking with low diffusion bits (fp8)

**Comment by ymouhoun** [comment]
Still having this issue with the latest version of Forge running via Runpod on a H100. Very annoying...
Any advice ?
