### ISSUE TITLE
Previews and grids are broken after update - with error: TypeError: '>' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by Lexxxco** [lllyasviel/stable-diffusion-webui-forge#1989]
After update - images can be generated and saved, but previews are broken after generation. Grids can't be generated with this bug as well. Bug appears always, when using any Loras. Windows 10, RTX4090 (Drivers 556.12). stable-diffusion-webui-forge: main@953e3f3
![2024-10-05_21-29](https://github.com/user-attachments/assets/365be95b-3167-4fba-a4a1-5d3277874000)

Traceback (most recent call last):
'>' not supported between instances of 'int' and 'NoneType'
  File "D:\Program files\Data\Packages\Stable Diffusion WebUI Forge\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\Program files\Data\Packages\Stable Diffusion WebUI Forge\modules\txt2img.py", line 123, in txt2img_function
    processed = processing.process_images(p)
  File "D:\Program files\Data\Packages\Stable Diffusion WebUI Forge\modules\processing.py", line 817, in process_images
    res = process_images_inner(p)
  File "D:\Program files\Data\Packages\Stable Diffusion WebUI Forge\modules\processing.py", line 1063, in process_images_inner
    images.save_image(image, p.outpath_samples, "", p.seeds[i], p.prompts[i], opts.samples_format, info=infotext(i), p=p)
  File "D:\Program files\Data\Packages\Stable Diffusion WebUI Forge\modules\images.py", line 738, in save_image
    oversize = image.width > opts.target_side_length or image.height > opts.target_side_length
TypeError: '>' not supported between instances of 'int' and 'NoneType'

**Comment by DenOfEquity** [comment]
The setting that the error is complaining about is **Settings** -> **Saving images/grids** -> **Width/height limit for the above option, in pixels**. Try setting it to something else, then **Apply settings**. You can set it back afterward if you want.
If that doesn't work, close Forge and delete/rename `config.json` from `{forge install directory}\webui`.

**Comment by Lexxxco** [comment]
Appreciate your help,@DenOfEquity ! Deleting the settings file helped, thanks.

When trying to change **Width/height limit**  - recreated the bug, but could not change **Width/height limit** back - the field for the limit appeared always empty even after saving and restart. - Found temporary solution:  to save above-mentioned limit - we need to change **File size limit for the above option, MB** / **Maximum image size (in megapixels)** - and save them along with **Width/height limit** at the same time. Save and restart UI.
