### ISSUE TITLE
can i run this as api mode?

### ISSUE THREAD

**Issue by cyy1133** [lllyasviel/stable-diffusion-webui-forge#1994]
like A1111, is it can use as api mode? --api is not working i think

**Comment by rockiecxh** [comment]
I've been using ` --api --listen` for api calling for a long time. it's working fine.

**Comment by vxiaobai** [comment]
> I've been using ` --api --listen` for api calling for a long time. it's working fine.我已经使用 ` --api --listen` 进行 api 调用很长时间了。工作正常。

I used --api 9999 to specify the port to run, but it doesn't work

**Comment by DenOfEquity** [comment]
vxiaobai: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings#running-within-local-area-network
