### ISSUE TITLE
Loading model info, please wait!

### ISSUE THREAD

**Issue by dxdgg** [lllyasviel/stable-diffusion-webui-forge#2012]
Hi
When I retrieve the checkpoints or LoRA models information, it prompts this, it has not changed, and it is always waiting. why?
because i need some Trigger words for using LoRA models etc.
Help pls

**Comment by dxdgg** [comment]
SD Automatic1111 is normal. but forge cant display the model info

**Comment by DenOfEquity** [comment]
Not a Forge issue.
That message is part of the civitai-browser-plus extension. The developer has starting working on it again recently, so try updating it.
