### ISSUE TITLE
Does the "Paste Prompt" button change the GPU Weights?

### ISSUE THREAD

**Issue by toyssamurai** [lllyasviel/stable-diffusion-webui-forge#2016]
I am not 100% sure this is the cause of my problem, but checking my log, I could only come to the conclusion that using the "Paste Prompt" button (the small angled down arrow under the "Generate" button) changes the GPU weights as well:

```
Environment vars changed: {'stream': False, 'inference_memory': 8676.0, 'pin_shared_memory': False}
[GPU Setting] You will use 82.18% GPU memory (40000.00 MB) to load weights, and use 17.82% GPU memory (8676.00 MB) to do matrix computation.
```

Above is what I had in my log before I pressed that button. After I clicked on it, I got:

```
Environment vars changed: {'stream': False, 'inference_memory': -31528.0, 'pin_shared_memory': False}
------------------
[Low VRAM Warning] You just set Forge to use 100% GPU memory (80204.00 MB) to load model weights.
[Low VRAM Warning] This means you will have 0% GPU memory (0.00 MB) to do matrix computation. Computations may fallback to CPU or go Out of Memory.
[Low VRAM Warning] In many cases, image generation will be 10x slower.
[Low VRAM Warning] To solve the problem, you can set the 'GPU Weights' (on the top of page) to a lower value.
[Low VRAM Warning] If you cannot find 'GPU Weights', you can click the 'all' option in the 'UI' area on the left-top corner of the webpage.
[Low VRAM Warning] Make sure that you know what you are testing.
------------------
```

FYI, I used a cloud GPU, and once I restarted, the GPU changed from a 80Gb A100 to a 48Gb A6000. The prompt I was trying to recall from the button came from the session BEFORE the restart.

Immediately after I saw that Low VRAM warning, I got the connection was lost error from the web UI, which kind of makes sense if I ran out of VRAM on the backend.

**Comment by DenOfEquity** [comment]
No, but the UI settings for 'xl' and 'flux' do. Those now have options in *Settings* for GPU weights, so they can be set differently if necessary. The current approach directly sets the memory used for model weights, intended so the sliders work/appear the same as the main UI control for GPU weights. I guess what has happened is that the setting was saved high when using the 80Gb A100. If so, the GPU weights control will show that too high value. Quick fix is to adjust the slider to bring the value back into range.

I'll add some checks in an update, to fall back to the default (total VRAM - 1024) if the saved values are not possible for current VRAM.
