### ISSUE TITLE
Flux crashes randomly with python.exe stopped working.

### ISSUE THREAD

**Issue by maniac-0s** [lllyasviel/stable-diffusion-webui-forge#2022]
I can like generate 20 images and then "python.exe has stopped working" appears. This only happens with Flux models, schnell and dev with and without Loras. Every gen is like Russian roulette.

Additionally there is a bug that when I close the forge command window to restart but keep the UI open to keep my prompt and settings, the newly generated image preview disappears when its finished and I see the previous image again. The finished image however appears in the output folder.

I am using it under windows [f2.0.1v1.10.1-previous-526-gc13b26ba](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/c13b26ba271bac327879d32f01307fc21a012321) with an 4060TI, swap location shared and low bits automatic.

**Comment by Haoming02** [comment]
> python.exe has stopped working

See: https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1474

**Comment by maniac-0s** [comment]
Thanks that helped. However the issue with the disappearing image existed when for some reason forge was closed but the UI not reloaded. Although with the solution it's a minor problem.

**Comment by Haoming02** [comment]
Yeah, if I have to re-launch the Webui, I always refresh the browser completely (`F5`, not `Reload UI`) as well. Simply reconnect the existing page usually doesn't work properly for me.

If you need to keep some information, just open the link in a new tab, and copy them over.
