### ISSUE TITLE
does anyone have an example of api call for FLUX?

### ISSUE THREAD

**Issue by GPU-server** [lllyasviel/stable-diffusion-webui-forge#2041]
please.

**Comment by rockiecxh** [comment]
give you an example and modify the parameters accordingly:

`{
    "alwayson_scripts":
    {
        "Never OOM Integrated":
        {
            "args": [
            {
                "unet_enabled": true,
                "vae_enabled": false
            }]
        }
    },
    "batch_size": 1,
    "cfg_scale": 1,
    "comments":
    {},
    "denoising_strength": 0.35,
    "disable_extra_networks": false,
    "do_not_save_grid": false,
    "do_not_save_samples": false,
    "enable_hr": false,
    "width": 832,
    "height": 1216,
    "hr_negative_prompt": "",
    "hr_prompt": "",
    "hr_resize_x": 0,
    "hr_resize_y": 0,
    "hr_scale": 1.5,
    "hr_second_pass_steps": 5,
    "hr_upscaler": "4x_NMKD-Siax_200k",
    "n_iter": 1,
    "negative_prompt": "",
    "override_settings":
    {
        "sd_model_checkpoint": "flux1-dev-bnb-nf4-v2",
        "forge_unet_storage_dtype": "Automatic",
        "forge_inference_memory": 1024,
        "forge_async_loading": "Async",
        "forge_pin_shared_memory": "Shared",
        "forge_preset": "flux"
    },
    "override_settings_restore_afterwards": true,
    "prompt": "Envision a photorealistic portrait of a distinguished scientist with silver hair and distant blue eyes, set against an otherworldly backdrop featuring swirling nebulae and distant galaxies. The subject\'s intense gaze captures a blend of deep contemplation and excitement for the vast unknown, reflecting their dedication to unraveling cosmic mysteries. With their lab coat billowing gently in the artificial breeze of their high-tech observatory, they stand at the edge of scientific breakthroughs yet to come, with the shimmering stars of various colors behind them. This unique combination of human intellect and the boundless expanse of space evokes a sense of awe and wonder, inviting viewers to explore the endless possibilities within our universe.",
    "restore_faces": false,
    "s_churn": 0.0,
    "s_min_uncond": 0,
    "s_noise": 1.0,
    "s_tmax": null,
    "s_tmin": 0.0,
    "sampler_name": "[Forge] Flux Realistic",
    "scheduler": "Simple",
    "script_args": [],
    "script_name": null,
    "seed": -1,
    "seed_enable_extras": true,
    "seed_resize_from_h": -1,
    "seed_resize_from_w": -1,
    "steps": 20,
    "styles": [],
    "subseed": -1,
    "subseed_strength": 0,
    "tiling": false
}`

**Comment by GPU-server** [comment]
Thanks! I later found the tool that create prompts json after each time you generate, forgot to remove this. But thanks

**Comment by TowhidKashem** [comment]
> Thanks! I later found the tool that create prompts json after each time you generate, forgot to remove this. But thanks

Hey it's my first time trying to use Forge and via API as well, can you tell me what tool you are referring to here? thanks!

**Comment by vinch00** [comment]
@TowhidKashem the extension to see the payload is called sd-webui-api-payload-display
