### ISSUE TITLE
can't generate without internet

### ISSUE THREAD

**Issue by zethfoxster** [lllyasviel/stable-diffusion-webui-forge#2042]
I can start forge and it will go as far as to generate an image, but once it hits 100% you get a warning that "connection error timeout" and never get the image it generated.

I feel this is strange behavior when running the ui locally. is there some commandarg or something im missing to completely remove the requirement of internet to generate?

**Comment by TheFerumn** [comment]
yeah he probably trying to use upscaler which is not downloaded yet this is why it happens on the end of generation process

**Comment by zethfoxster** [comment]
no thats not the case at all guys. a connection error time out happens from it losing connection to the cli. there is nothing downloading or being downloaded at all. this issue is not resolved. if you want to test it out, disconnect your modem and hit generate.

**Comment by DenOfEquity** [comment]
The first thing I did when I saw this issue two weeks ago was test using Flight mode. All worked correctly. Restarted Forge, still in Flight mode, all worked correctly. Also tested dropping connection mid-generation - no problem. Start another generation while still disconnected - no problem.

**Comment by zethfoxster** [comment]
just tried it on the version i was on, it failed...updated to the most current release and the issue is indeed now corrected. only tried with airplane mode, as i assume thats exactly the same as just unplugging the modem
