### ISSUE TITLE
inpaint mask editor sometimes goes crazy

### ISSUE THREAD

**Issue by Technologicat** [lllyasviel/stable-diffusion-webui-forge#2044]
As of ae8187bf, the inpaint mask editor goes crazy when multiple different base images are inpainted during the same Forge session.

**Symptoms**:

- The Reset button in the mask editor no longer does anything, or requires several presses.
  - Sometimes each press of the Reset button cycles through states in the mask editor undo history, instead of clearing the mask.
- Then, even if you successfully reset the mask (by pressing Reset enough times), drawing the mask with the mouse stops working.
 - As you draw, the mask starts flickering between the new state (being edited) and some previous state in the mask editor undo history.
 - Sometimes drawing with the mouse no longer updates the mask at all.

To get it working again, the Forge server must be restarted. Rebooting just the client (F5 in the web browser) is not enough.

**To reproduce**:

This is hard to reproduce reliably. I haven't been able to produce a minimal list of steps.

But it happens pretty much every time when I actually use Forge to do some detailing on a previously generated set of txt2imgs that I've stashed aside for finalizing later.

My general workflow for this use case is:

- Start Forge.
- Switch to PNG info tab.
- Drag and drop an image (a previous output from Forge) from the file manager. Send to inpaint.
- Work on the image. Loop the following several times:
  - Draw an inpaint mask with the mouse.
  - Tweak the settings (denoise, masked content mode, etc.).
  - Generate, possibly several attempts.
  - Send the result back to inpaint (palette button below generated image).
  - Reset inpaint mask.
- One image done. Move on to next one.
- Switch to PNG info tab.
- Press the 'X' (Remove Image).
- Drag and drop another image from the file manager. Send to inpaint.
- Work on the image, as above.
  - Randomly after 2-5 images, notice that the inpaint mask editor stops working.

**Environment**:

- Linux Mint 21.3
- NVIDIA driver 555.58.02 with CUDA 12.5
- NVIDIA RTX 3070 Ti mobile 8 GB
- `torch` 2.4.1

I searched the issue tracker and couldn't find anything similar.

If this issue really is new, and is really a bug, I could run a `git bisect` to figure out when it broke.

Also, if there is something helpful I could print out from the Javascript console, I could do that too (but I'm not familiar with Gradio, so I need information on what could be helpful for debugging this).

All I know at the moment is that it worked perfectly until I upgraded Forge last week. And unfortunately, I didn't save the commit ID of the old version I had before the upgrade.

I'm mainly posting this now to let others chime in. Has anyone else had issues with the inpaint mask editor recently? Any better luck in figuring out how to reproduce the problem? Any information on how to debug?

**Comment by SailingB0aty** [comment]
I am also experiencing this issue, Linux mint also.

**Comment by Technologicat** [comment]
Great, maybe we could narrow this down together.

One thought that occurred to me, what web browser are you running? Mine is Firefox 131.0.2 (64-bit), provided by Linux Mint.

**Comment by wktra** [comment]
Same here. Using the inpaint brush does NOTHING.

**Comment by Hubinator** [comment]
I've been experiencing this annoyance as well. It was introduced in a more recent version of Firefox for Linux. I downgraded to Firefox 115.12.0esr-1 and the issue was gone. You can also switch to a Chromium-based browser, they don't seem to be affected by whatever this is.

**Comment by Technologicat** [comment]
@Hubinator Thanks! That matches my own findings.

At least so far, no issue on Chromium (129.0.6668.100, 64-bit, provided by Linux Mint). I've been running Forge on it during the last couple of days, but I didn't post about it yet, because I wasn't sure if the issue was really gone or if I was just having better luck.

So for now, the workaround is to run on Chromium. Chalk another one up to Firefox quirks?
