### ISSUE TITLE
BUG: since a half year, CHECKPOINT UNLOAD does not work ,why ?

### ISSUE THREAD

**Issue by kalle07** [lllyasviel/stable-diffusion-webui-forge#2049]
CHECKPOINT UNLOAD
does not work ,why ?

**Comment by altoiddealer** [comment]
To be fair, I don't think this function works in any of the Web UIs lol

It's even an API endpoint in all of them, A1111, Forge, Reforge -- never worked.

**Comment by kalle07** [comment]
aprox one year ago it worked in a1111  ;)

**Comment by kalle07** [comment]
whooo it works   THX !!!
