### ISSUE TITLE
AssertionError: Bad value for setting sd-ppp_download: []; expecting list

### ISSUE THREAD

**Issue by wangxq1997** [lllyasviel/stable-diffusion-webui-forge#2063]
![screenshot](https://github.com/user-attachments/assets/0fc3ffe8-efad-4ea9-82f3-04a687c543e2)

Hello handsome, this is the error message for the "webui_forge_cu121_torch231" version. When I set the parameter points and save the settings in the settings, it will be like this, no matter what is set. How to solve this problem.

**Comment by DenOfEquity** [comment]
Looks like an issue with the [sd-ppp](https://github.com/zombieyang/sd-ppp) extension.
