### ISSUE TITLE
pidinet  “apply_fliter” word is misspelled

### ISSUE THREAD

**Issue by LL020202** [lllyasviel/stable-diffusion-webui-forge#2070]
I was using [comfyui_controlnet_aux](https://github.com/Fannovel16/comfyui_controlnet_aux) and wanted to implement the t2ia_sketch_pidi preprocessor you posted, and suddenly found a word error

In the extensions-builtin/forge_legacy_preprocessors/annotator/pidinet/__init__.py file, there is a word apply_filter, it should be apply_filter

**Comment by DenOfEquity** [comment]
Good catch, but it shouldn't affect anything - based on searching the code, all occurrences have the same misspelling. There's another preprocessor with 'pruple' instead of 'purple' in the name.
