### ISSUE TITLE
XFORMERS UPDATE ISSUE

### ISSUE THREAD

**Issue by goodbyerookie** [lllyasviel/stable-diffusion-webui-forge#2075]
Can you help?

![sssss](https://github.com/user-attachments/assets/088fcd9b-3091-4855-be59-a84bc4b1ca94) @Melyns

**Comment by goodbyerookie** [comment]
what do i need to do? @Melyns

**Comment by Arnaud3013** [comment]
hmm it say ninja not found. So install ninja. `pip install ninja`
Also you should use uv for pip. -> `pip install uv` then `uv pip install -U ninja xformers` you will see, wayyyy faster

**Comment by goodbyerookie** [comment]
uv pip install -U ninja <<< this comment not working? **_error: No virtual environment found; run `uv venv` to create an environment, or pass `--system` to install into a non-virtual environment_**

**Comment by Arnaud3013** [comment]
you have to install uv first `pip install uv`
but else just do
`pip install -U xformers --index-url https://download.pytorch.org/whl/cu124`
It should work

**Comment by goodbyerookie** [comment]
@Arnaud3013 thank you brother..it worked..
