### ISSUE TITLE
im getting this error

### ISSUE THREAD

**Issue by disereless** [lllyasviel/stable-diffusion-webui-forge#2076]
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-566-gcce30d33
Commit hash: cce30d3340fe7b09630a528af26975757a46c450
Launching Web UI with arguments: --cuda-stream --cuda-malloc
Using cudaMallocAsync backend.
Total VRAM 12288 MB, total RAM 16308 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: True
D:\a\webui_forge_cu121_torch231\system\python\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: D:\a\webui_forge_cu121_torch231\webui\models\ControlNetPreprocessor
Loading additional modules ... done.
2024-10-15 17:58:43,666 - ControlNet - INFO - ControlNet UI callback registered.
Model selected: {'checkpoint_info': {'filename': 'D:\\a\\webui_forge_cu121_torch231\\webui\\models\\Stable-diffusion\\flux1-dev-bnb-nf4-v2.safetensors', 'hash': 'f0770152'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 25.3s (prepare environment: 3.5s, import torch: 9.1s, initialize shared: 0.2s, other imports: 0.7s, list SD models: 0.2s, load scripts: 2.8s, initialize google blockly: 5.0s, create ui: 2.7s, gradio launch: 1.3s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 91.67% GPU memory (11263.00 MB) to load weights, and use 8.33% GPU memory (1024.00 MB) to do matrix computation.
Loading Model: {'checkpoint_info': {'filename': 'D:\\a\\webui_forge_cu121_torch231\\webui\\models\\Stable-diffusion\\flux1-dev-bnb-nf4-v2.safetensors', 'hash': 'f0770152'}, 'additional_modules': [], 'unet_storage_dtype': None}
[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... Done.
StateDict Keys: {'transformer': 1722, 'vae': 244, 'text_encoder': 198, 'text_encoder_2': 220, 'ignore': 0}
Using Detected T5 Data Type: torch.float8_e4m3fn
Using Detected UNet Type: nf4
Using pre-quant state dict!
Working with z of shape (1, 16, 32, 32) = 16384 dimensions.
K-Model Created: {'storage_dtype': 'nf4', 'computation_dtype': torch.bfloat16}
Model loaded in 0.8s (unload existing model: 0.2s, forge model load: 0.7s).
Skipping unconditional conditioning when CFG = 1. Negative Prompts are ignored.
[Unload] Trying to free 7725.00 MB for cuda:0 with 0 models keep loaded ... Done.
[Memory Management] Target: JointTextEncoder, Free GPU: 11235.00 MB, Model Require: 5154.62 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 5056.38 MB, All loaded to GPU.
Moving model(s) has taken 2.01 seconds
Distilled CFG Scale: 3.5
Press any key to continue . . .

**Comment by jswag245** [comment]
Try reducing the GPU weight

**Comment by DenOfEquity** [comment]
See also #1474.
