### ISSUE TITLE
It's now driving me mad... when changing the Diffusion in Low Bits, it often loads the wrong model, one i loaded much earlier

### ISSUE THREAD

**Issue by andy8992** [lllyasviel/stable-diffusion-webui-forge#2082]
This has been a minor inconvenience but I'm testing a lot of settings right and now it's happened like 5 times within the hour.

I get the terminal message about a new model being selected despite me not selecting a new one. It keeps loading juggernaut despite a different model being selected in the drop down, it's just reverting to a model i loaded earlier.

To fix i have to swap models, then swap again.

**Comment by DenOfEquity** [comment]
You should find this fixed, as of a few days ago.
