### ISSUE TITLE
Add support for non-png filetypes in batch img2img

### ISSUE THREAD

**Issue by leonard84** [lllyasviel/stable-diffusion-webui-forge#2098]
Right now, the batch processor only recognizes `.png` files, which is a problem when you are using `.avif` to save space.

As a workaround you can rename the files from `.avif` to `.png` and it will find and convert them just fine. So hard part of supporting other formats is already solved and only the batch input filter needs to be changed.

**Comment by DenOfEquity** [comment]
Added `.avif` to the list, it is now: `.png`, `.jpg`, `.jpeg`, `.webp`, `.tif`, `.tiff`, `.avif`

**Comment by mirh** [comment]
It would be nice if this was mentioned anywhere (or there was a dropdown list), rather than the user having to guess what may or may not be supported.
