### ISSUE TITLE
no clip skip option

### ISSUE THREAD

**Issue by Hugs288** [lllyasviel/stable-diffusion-webui-forge#2120]
its just not there
![image](https://github.com/user-attachments/assets/079e66df-af6e-48cb-b5f8-697525eb6adc)

**Comment by Hugs288** [comment]
i cant find it in settings at all either
![image](https://github.com/user-attachments/assets/ee8876c7-ec53-4ebb-adc8-2e2d088f23a5)

**Comment by jswag245** [comment]
Is it there when using the all option for UI?

**Comment by Hugs288** [comment]
oh youre right, that doesnt make much sense, i also hate how some options low diffusion with low bits and gpu weights cant be removed, but ig ill close this issue.

**Comment by jassde** [comment]
why close it when it has not got a response or a fix

**Comment by jswag245** [comment]
> why close it when it has not got a response or a fix

It got a response, and there's no fix required. Clip skip is an option that is showed when you use the show all options setting for the UI.
