### ISSUE TITLE
img2img Upscale doesn't respect it's own settings for number of steps

### ISSUE THREAD

**Issue by shaun-ba** [lllyasviel/stable-diffusion-webui-forge#2125]
When you send an image to img2img for upscaling it doesn't respect the number of steps in the slider. My UI is set to 20 steps but it only performs 16. I cannot see where the 16 is even coming from as I've never used that as a setting anywhere.

**Comment by DenOfEquity** [comment]
With default settings, img2img steps are reduced proportional to Denoise. There is a setting to always use the specified number of steps in Settings > img2img.

**Comment by shaun-ba** [comment]
@DenOfEquity  thank you. I had decreased the noise as there is another issue here reporting noise over 0.74 I believe as bugged.
