### ISSUE TITLE
Why Can't I choose WIDTH and HEIGHT as a parameter on X/Y/Z Plot ?????????

### ISSUE THREAD

**Issue by ClothingAI** [lllyasviel/stable-diffusion-webui-forge#2128]
There is no option to choose width and height ?
![image](https://github.com/user-attachments/assets/d1d24526-9804-4700-8761-fb44a3746cc4)

**Comment by DenOfEquity** [comment]
Use `Size` option, for example `512x512, 512x640, 640x832`.

**Comment by ClothingAI** [comment]
> Use `Size` option, for example `512x512, 512x640, 640x832`.

I saw size, then tried activating only one size, I put inside it: 512,768,1024.. etc
all images were the same.
The I figured mybe i can use 2 axes from the xyz and choose 2 times size?
I did this:
Size: 512,768,1024
Size: 512,768,1024

All the images were identical !
It does NOT work?

**Comment by Juqowel** [comment]
Only `WidthxHeight` format is work. Look console log.

**Comment by ClothingAI** [comment]
> Only `WidthxHeight` format is work. Look console log.

I don't get it.

**Comment by jswag245** [comment]
Juqowel is stating that you need to put it in the format of WidthxHeight, like in DenOfEquity's examples of 512x512, 1024x1024, etc. You are not doing this, and you are instead doing 512, 768, 1024, etc. Have you tried putting it in that format?

**Comment by ClothingAI** [comment]
> Juqowel is stating that you need to put it in the format of WidthxHeight, like in DenOfEquity's examples of 512x512, 1024x1024, etc. You are not doing this, and you are instead doing 512, 768, 1024, etc. Have you tried putting it in that format?

Oh i see, that's make sense actually. If that works then it is perfect

**Comment by jswag245** [comment]
I hope it does! If it works, please feel free to close the issue.

**Comment by ClothingAI** [comment]
You are right guys, it works like you mentioned!
