### ISSUE TITLE
Lots of seemingly internal Errors

### ISSUE THREAD

**Issue by Marrionetta** [lllyasviel/stable-diffusion-webui-forge#2130]
I think it will just be easier to just show what im getting.

First of all, I uninstalled all instances of Git and Python from my pc, then proceeded to download this archive (https://i.imgur.com/u8IbJT6.jpeg) on the main page of this repo.

As instructed, I extracted the files then ran the update.bat, then ran the run.bat. From what I can tell, everything ran perfectly fine and normally as seen here (https://i.imgur.com/235U9PT.jpeg).

So then I attempted to generate an image to see if it would work, it didn't. I got this (https://i.imgur.com/k9p1oKl.jpeg)

Things that stuck out to me were
"TypeError: gradio.data_classes.FileData() argument after ** must be a mapping, not bool"
"IndexError: function has no backend method."
"Input should be a valid list [type=list_type, input_value='', input_type=str]"
"AttributeError: 'NoneType' object has no attribute 'slider_resolution'"

This sounds like a problem with the program itself...but if that were the case I'd imagine a bunch of people would be having this problem. Unfortunately, I have no idea what to even search for to see if anyone else had this issue or solved it.
Ever since the UI updated to [this](https://i.imgur.com/ieofgfV.jpeg), i haven't been able to generate anything ever for an infinite number of reasons.

I also get this (https://i.imgur.com/gY2VwlN.jpeg) error in the UI whenever i try to change the UI option (sd/fl/flux/etc)

**Comment by Marrionetta** [comment]
No. I just installed it normally, copied a few checkpoints then tried to run it. i removed my installed stuff to ensure there were no conflicts and even then, it still didnt work.

i just dont understand how trying to add DorA support could have possibly caused so much mayhem. this used to be so painless before and now its been a nightmare just to get this thing to work. it's killing me. I've never ever seen anything so broken in all my years on pc where literally nothing i do, nothing suggested or nothing i try works. 

The only thing i can think of is that windows 10 is just no longer supported with forged cause thats the only major change ive made to my environment.

**Comment by Juqowel** [comment]
> windows 10 is just no longer supported

Nope. I'm on w10.
Just did a fresh install 2.3.1. Everything works. Dora works too. So it's something else.

**Comment by Marrionetta** [comment]
I tried running it again, cleared out everything, had no LorAs or models save for my favourite one. Ran it, Got this (https://i.imgur.com/zGuwgHP.jpeg). 

The reported fix was installing a very specific module in VS build tools but i have already not only installed it but everything else related to it that said "Latest version" (https://i.imgur.com/MgSgLja.jpeg) and yet still I get "Could not locate cudnn_ops_infer64_8.dll. Please make sure it is in your library path!"

So this brings me back to, wtf does the console mean when it says "Library Path" cause clearly it's not telling me to simply have it installed.

**Comment by Juqowel** [comment]
> "Could not locate cudnn_ops_infer64_8.dll. Please make sure it is in your library path!"

Ok. I see. Remove `[]` from folder name - `[0] AI Art Engine`.

**Comment by Marrionetta** [comment]
Holy shit!! That was it!! Aaaaaaaggggghhh~!! Omg thank you so much TTOTT
