### ISSUE TITLE
Using HiresFix completely crash forge

### ISSUE THREAD

**Issue by Anonimouche** [lllyasviel/stable-diffusion-webui-forge#2142]
Everytime i activate HiresFix, the program keeps shutting off at the same point.

Moving model(s) has taken 0.85 seconds
100%|####################################################################################| 3/3 [00:19<00:00,  6.52s/it]
[Unload] Trying to free 8990.72 MB for cuda:0 with 0 models keep loaded ... Current free memory is 1943.50 MB ... Current free memory is 1943.50 MB ... Unload model KModel Done.
[Memory Management] Target: IntegratedAutoencoderKL, Free GPU: 5086.93 MB, Model Require: 319.11 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 3743.82 MB, All loaded to GPU.
Moving model(s) has taken 1.19 seconds
Model selected: {'checkpoint_info': {'filename': 'E:\\Programs\\forge\\webui\\models\\Stable-diffusion\\sweetMix_xlPonyV13.safetensors', 'hash': 'd3e33eda'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Loading Model: {'checkpoint_info': {'filename': 'E:\\Programs\\forge\\webui\\models\\Stable-diffusion\\sweetMix_xlPonyV13.safetensors', 'hash': 'd3e33eda'}, 'additional_modules': [], 'unet_storage_dtype': None}
[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... Current free memory is 4631.21 MB ... Current free memory is 4631.21 MB ... Unload model IntegratedAutoencoderKL Done.
Appuyez sur une touche pour continuer...

It doesn't show any errors so i'm kinda lost, I tried reinstalling from zero, and the issue keeps happening.
I also checked and my PC is able to generate image at the resolution hiresfix would be generating them.

**Comment by Cranbert** [comment]
Try setting the "hires vae/text encoder" to "use same choices".
For some reason, leaving the box blank doesn't work anymore.

**Comment by Anonimouche** [comment]
Worked perfectly! Thank you very much, I don't know why using the button to reload the previous prompt actually removes the "use the same choice" but after putting it in it works.

Thank you again <3
