### ISSUE TITLE
How to tell Forge to read the FULL PROMPT please? 

### ISSUE THREAD

**Issue by ClothingAI** [lllyasviel/stable-diffusion-webui-forge#2162]
Forge seems to ignoreing the second half of my prompt (flux) (and it does not happen with Comfy)

Could you tell me if there an option in thes setting or something that let me tell forge to read my full prompt and give it to flux please ???

**Comment by Juqowel** [comment]
It's hard to say without knowing the prompt. Maybe you have `#` inside it.
