### ISSUE TITLE
Super slow after Update

### ISSUE THREAD

**Issue by VHCONTE** [lllyasviel/stable-diffusion-webui-forge#2179]
I’ve been away from image creation for a month, now I came back to Forge and it’s absurdly slower.
I started to use Forge because of how faster it was due to its great memory management, but now I’m getting 2-3it/s on my 4080 on SD1.5 models.
Is there a way to go back to a version before this update?

**Comment by scarlizzz** [comment]
https://www.reddit.com/r/StableDiffusion/comments/1dugpet/update_or_downgrade_forge_ui_heres_what_you_need/

I did this myself, you just have to look for an older version number and downgrade that way. Its super easy.

**Comment by mirh** [comment]
Maybe related to #2139?
