### ISSUE TITLE
Color picker always gives NaN for red component

### ISSUE THREAD

**Issue by Technologicat** [lllyasviel/stable-diffusion-webui-forge#2180]
As of ae8187bf, the color picker in inpaint sketch mode is not working, at least on Chromium on Linux.

This prevents the use of inpaint sketch mode, as it would be important to get accurate reference colors for sketching.

I tried also with Firefox (131.0.2, 64-bit, provided by Linux Mint), but it didn't display a color picker at all, as well as had a much more clunky UI in the color selection window.

I saw #1719 on the issue tracker, but I have no HDR displays.

**To reproduce**:

- Start Forge.
- Switch to PNG info tab.
- Drag and drop an image (a previous output from Forge) from the file manager. Send to inpaint.
- The img2img tab opens in inpaint mode.
- Below the image, press *to inpaint sketch*.
- Open the color picker. Click anywhere on the image.
- Always get NaN for the red component.
  - HSL mode doesn't work at all, all components NaN. Switching between the modes suggests this is because the red component of RGB is NaN (so the RGB↔HSL conversion formulas produce NaN for all components).

This is reproducible every time.

**Environment**:

- Linux Mint 21.3
- NVIDIA driver 555.58.02 with CUDA 12.5
- NVIDIA RTX 3070 Ti mobile 8 GB
- `torch` 2.4.1
- Chromium 129.0.6668.100, 64-bit, provided by Linux Mint

**Comment by DenOfEquity** [comment]
I think this is a browser issue. Relevant Forge code has not changed.
works correctly on Edge/Windows. Firefox/Windows also uses a different picker, without eye-dropper; looks like OS provided.

**Comment by Technologicat** [comment]
Thanks for the info!

I'll investigate further on my end.

**Comment by Technologicat** [comment]
Yes, this seems to be an issue in Chromium that occurs only on some Linux configurations. It's been there since 2021, but the devs have not been able to reproduce it on their systems.

https://issues.chromium.org/issues/40777177

Since it is not a Forge issue, I think we can close this.
