### ISSUE TITLE
Python-multipart unavailable, cannot run

### ISSUE THREAD

**Issue by Veliante** [lllyasviel/stable-diffusion-webui-forge#2194]
Hi, I was trying to use my sd forge in cloud, via google drive, and whenever i try to install it i get this error, that i never got until today.

-= Initial setup SDForge =-
Cloning into 'stable-diffusion-webui-forge'...
remote: Enumerating objects: 41515, done.
remote: Counting objects: 100% (7296/7296), done.
remote: Compressing objects: 100% (662/662), done.
remote: Total 41515 (delta 6897), reused 6664 (delta 6634), pack-reused 34219 (from 1)
Receiving objects: 100% (41515/41515), 47.52 MiB | 17.67 MiB/s, done.
Resolving deltas: 100% (28522/28522), done.
/content/stable-diffusion-webui-forge/stable-diffusion-webui-forge
-= Updating SDForge =-
Already up to date.
-= Install dependencies =-
Requirement already satisfied: insightface in /usr/local/lib/python3.10/dist-packages (0.7.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from insightface) (1.26.2)
Requirement already satisfied: onnx in /usr/local/lib/python3.10/dist-packages (from insightface) (1.17.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from insightface) (4.66.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from insightface) (2.32.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from insightface) (3.7.1)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from insightface) (9.5.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from insightface) (1.13.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from insightface) (1.5.2)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.10/dist-packages (from insightface) (0.21.0)
Requirement already satisfied: easydict in /usr/local/lib/python3.10/dist-packages (from insightface) (1.13)
Requirement already satisfied: cython in /usr/local/lib/python3.10/dist-packages (from insightface) (3.0.11)
Requirement already satisfied: albumentations in /usr/local/lib/python3.10/dist-packages (from insightface) (1.4.15)
Requirement already satisfied: prettytable in /usr/local/lib/python3.10/dist-packages (from insightface) (3.11.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from albumentations->insightface) (6.0.2)
Requirement already satisfied: pydantic>=2.7.0 in /usr/local/lib/python3.10/dist-packages (from albumentations->insightface) (2.8.2)
Requirement already satisfied: albucore>=0.0.15 in /usr/local/lib/python3.10/dist-packages (from albumentations->insightface) (0.0.16)
Requirement already satisfied: eval-type-backport in /usr/local/lib/python3.10/dist-packages (from albumentations->insightface) (0.2.0)
Requirement already satisfied: opencv-python-headless>=4.9.0.80 in /usr/local/lib/python3.10/dist-packages (from albumentations->insightface) (4.10.0.84)
Requirement already satisfied: networkx>=2.8 in /usr/local/lib/python3.10/dist-packages (from scikit-image->insightface) (3.4.2)
Requirement already satisfied: imageio>=2.27 in /usr/local/lib/python3.10/dist-packages (from scikit-image->insightface) (2.35.1)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.10/dist-packages (from scikit-image->insightface) (2024.9.20)
Requirement already satisfied: PyWavelets>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-image->insightface) (1.7.0)
Requirement already satisfied: packaging>=21 in /usr/local/lib/python3.10/dist-packages (from scikit-image->insightface) (24.1)
Requirement already satisfied: lazy_loader>=0.2 in /usr/local/lib/python3.10/dist-packages (from scikit-image->insightface) (0.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->insightface) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->insightface) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->insightface) (4.54.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->insightface) (1.4.7)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->insightface) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->insightface) (2.8.2)
Requirement already satisfied: protobuf>=3.20.2 in /usr/local/lib/python3.10/dist-packages (from onnx->insightface) (4.25.5)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prettytable->insightface) (0.2.13)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->insightface) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->insightface) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->insightface) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->insightface) (2024.8.30)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->insightface) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->insightface) (3.5.0)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2.7.0->albumentations->insightface) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2.7.0->albumentations->insightface) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2.7.0->albumentations->insightface) (4.12.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->insightface) (1.16.0)
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
Version: f2.0.1v1.10.1-previous-589-g41a21f66
Commit hash: 41a21f66fd0d55a18741532e7e64d8c3fce2ebbb
Cloning assets into /content/stable-diffusion-webui-forge/stable-diffusion-webui-forge/repositories/stable-diffusion-webui-assets...
Cloning into '/content/stable-diffusion-webui-forge/stable-diffusion-webui-forge/repositories/stable-diffusion-webui-assets'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 20 (delta 0), reused 20 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (20/20), 132.70 KiB | 22.12 MiB/s, done.
Cloning huggingface_guess into /content/stable-diffusion-webui-forge/stable-diffusion-webui-forge/repositories/huggingface_guess...
Cloning into '/content/stable-diffusion-webui-forge/stable-diffusion-webui-forge/repositories/huggingface_guess'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 46 (delta 26), reused 33 (delta 13), pack-reused 0 (from 0)
Receiving objects: 100% (46/46), 35.63 KiB | 11.88 MiB/s, done.
Resolving deltas: 100% (26/26), done.
Cloning google_blockly into /content/stable-diffusion-webui-forge/stable-diffusion-webui-forge/repositories/google_blockly_prototypes...
Cloning into '/content/stable-diffusion-webui-forge/stable-diffusion-webui-forge/repositories/google_blockly_prototypes'...
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 49 (delta 7), reused 43 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (49/49), 1.02 MiB | 27.44 MiB/s, done.
Resolving deltas: 100% (7/7), done.
Cloning BLIP into /content/stable-diffusion-webui-forge/stable-diffusion-webui-forge/repositories/BLIP...
Cloning into '/content/stable-diffusion-webui-forge/stable-diffusion-webui-forge/repositories/BLIP'...
remote: Enumerating objects: 277, done.
remote: Counting objects: 100% (183/183), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 277 (delta 145), reused 137 (delta 137), pack-reused 94 (from 1)
Receiving objects: 100% (277/277), 7.04 MiB | 22.44 MiB/s, done.
Resolving deltas: 100% (152/152), done.
Installing requirements
Launching Web UI with arguments: --share
Total VRAM 22700 MB, total RAM 54233 MB
pytorch version: 2.5.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA L4 : native
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
2024-10-27 11:52:13.730964: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-10-27 11:52:13.748562: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-27 11:52:13.769503: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-27 11:52:13.775879: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-27 11:52:13.791116: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-27 11:52:14.830587: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: /content/stable-diffusion-webui-forge/stable-diffusion-webui-forge/models/ControlNetPreprocessor
Loading additional modules ... done.
ERROR:fastapi:Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart

Exception in thread Thread-3 (webui_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/stable-diffusion-webui-forge/stable-diffusion-webui-forge/webui.py", line 69, in webui_worker
    shared.demo = ui.create_ui()
  File "/content/stable-diffusion-webui-forge/stable-diffusion-webui-forge/modules/ui.py", line 285, in create_ui
    with gr.Blocks(analytics_enabled=False, head=canvas_head) as txt2img_interface:
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1071, in __init__
    self.queue()
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 2133, in queue
    self.app = routes.App.create_app(self)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 320, in create_app
    def login(form_data: OAuth2PasswordRequestForm = Depends()):
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 921, in decorator
    self.add_api_route(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 860, in add_api_route
    route = route_class(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 496, in __init__
    self.body_field = get_body_field(dependant=self.dependant, name=self.unique_id)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 809, in get_body_field
    check_file_field(final_field)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 101, in check_file_field
    raise RuntimeError(multipart_not_installed_error) from None
RuntimeError: Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart

**Comment by Mysticloud** [comment]
Experiencing the same issue myself, Tried installing manually via pip, as-well as trying older releases and that didnt seem to fix it. Might try install manually rather then a bat script and see if that has the same issue

**Comment by stegreen** [comment]
I tried to install the Linux version today. Running into the same problem using the AppImage.

**Comment by DenOfEquity** [comment]
There seems to have been a problem with recent updates to `python-multipart`. There are a few relevant issues on the github repo for that project (now closed, as last update should have fixed it); and I saw a similar issue, with A1111, mentioned on reddit which was also resolved by the last update.
