### ISSUE TITLE
Can anyone help me about Flux_dev Fp8 please?

### ISSUE THREAD

**Issue by goodbyerookie** [lllyasviel/stable-diffusion-webui-forge#2204]
when I'm trying to run >> Flux_dev Fp8 model, I'm getting this Error.

TypeError: linear(): argument 'weight' (position 2) must be Tensor, not NoneType

What s this? And How can I solve? @Melyns

**Comment by VeteranXT** [comment]
Flux is not added to Forge.

**Comment by lvyonghuan** [comment]
> Flux is not added to Forge.

You can directly clone the main branch and take a look instead of using the February stable version.

**Comment by LoRAMilkshake** [comment]
> when I'm trying to run >> Flux_dev Fp8 model, I'm getting this Error.
> 
> TypeError: linear(): argument 'weight' (position 2) must be Tensor, not NoneType
> 
> What s this? And How can I solve? @Melyns

did you managed to solve your issue? I'm having the same problem

**Comment by VeteranXT** [comment]
Flux works in forge.
Step 1: download ae.Safetensor, clip_i.safetensor, txx5l
Step 2: Once downloaded put em in models/text_encoder.
Step 3: Launch Forge
Step 4: Select ae clip and txx into vae/text encoder
step 5: select flux model
step 6: ????
Step 7: Profit.

or else [Check guide](https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1050)
