### ISSUE TITLE
I don't understand this error....please help. Forge not loading

### ISSUE THREAD

**Issue by popsoda27** [lllyasviel/stable-diffusion-webui-forge#2206]
venv "E:\Downloads\stable-diffusion-webui-amdgpu-forge\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-1.10.1
Commit hash: 95c41067a3787eb982ceee246bec8fd9696257a8
ROCm: agents=['gfx1100', 'gfx1036']
ROCm: version=6.1, using agent gfx1100
ZLUDA support: experimental
Using ZLUDA in E:\Downloads\stable-diffusion-webui-amdgpu-forge\.zluda
Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-amdgpu-forge\extensions\adetailer':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-amdgpu-forge\extensions\sd-dynamic-prompts':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-amdgpu-forge\extensions\sd-webui-animatediff':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-amdgpu-forge\extensions\sd-webui-aspect-ratio-helper':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-amdgpu-forge\extensions\sd-webui-infinite-image-browsing':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-amdgpu-forge\extensions\sd-webui-prompt-all-in-one':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-amdgpu-forge\extensions\Stable-Diffusion-Webui-Civitai-Helper':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-amdgpu-forge\extensions\ultimate-upscale-for-automatic1111':
Already up to date.

Launching Web UI with arguments: --update-all-extensions --use-zluda
Total VRAM 24560 MB, total RAM 31850 MB
pytorch version: 2.3.0+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 7900 XTX [ZLUDA] : native
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Using pytorch cross attention
Using pytorch attention for VAE
Traceback (most recent call last):
  File "E:\Downloads\stable-diffusion-webui-amdgpu-forge\launch.py", line 57, in <module>
    main()
  File "E:\Downloads\stable-diffusion-webui-amdgpu-forge\launch.py", line 53, in main
    start()
  File "E:\Downloads\stable-diffusion-webui-amdgpu-forge\modules\launch_utils.py", line 682, in start
    import webui
  File "E:\Downloads\stable-diffusion-webui-amdgpu-forge\webui.py", line 23, in <module>
    initialize.imports()
  File "E:\Downloads\stable-diffusion-webui-amdgpu-forge\modules\initialize.py", line 28, in imports
    from modules import shared_init
  File "E:\Downloads\stable-diffusion-webui-amdgpu-forge\modules\shared_init.py", line 8, in <module>
    from modules.zluda import initialize_zluda
  File "E:\Downloads\stable-diffusion-webui-amdgpu-forge\modules\zluda.py", line 7, in <module>
    from modules.onnx_impl.execution_providers import available_execution_providers, ExecutionProvider
  File "E:\Downloads\stable-diffusion-webui-amdgpu-forge\modules\onnx_impl\__init__.py", line 192, in <module>
    def ORTDiffusionModelPart_to(self: optimum.onnxruntime.modeling_diffusion.ORTPipelinePart, *args, **kwargs):
AttributeError: module 'optimum.onnxruntime.modeling_diffusion' has no attribute 'ORTPipelinePart'
Press any key to continue . . .

Nothing changed since my last run few days ago. Only did a git pull and this happened.

**Comment by DenOfEquity** [comment]
You're using a fork, not base Forge. The error you're getting is in a file that isn't part of this repo.
Try asking https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge.

**Comment by popsoda27** [comment]
> You're using a fork, not base Forge. The error you're getting is in a file that isn't part of this repo. Try asking https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge.

oh sorry my bad. Thanks for the heads up.

**Comment by jswag245** [comment]
@popsoda27 if that works, remember to close the issue
