### ISSUE TITLE
Extensions “Snapshot” to recreate Full Installetikn

### ISSUE THREAD

**Issue by rafstahelin** [lllyasviel/stable-diffusion-webui-forge#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Anybody know of an extension like Comfyui Manager “Snapshot” which allows one install all extensions configured in a different webui in one click?

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by rafstahelin** [comment]
Oh yes I have that but what about xy plot script for instance? I'd like to save an xy plot state from scripts. Is it possible?

**Comment by aolko** [comment]
> Oh yes I have that but what about xy plot script for instance? I'd like to save an xy plot state from scripts. Is it possible?

try it yourself

**Comment by rafstahelin** [comment]
yea, xy plot dont work with this. thanks though, it's a really nice extension non-the-less. appreciated
