### ISSUE TITLE
full fp16 model asking for t5/clip/vae

### ISSUE THREAD

**Issue by derpina-ai** [lllyasviel/stable-diffusion-webui-forge#2229]
Hi, is this intended behavior for Forge UI?
People are reporting that in ComfyUI a full model only requires the model in fp16. In Forge, most fp16 models I have (~22GB each) still ask for T5/Clip/Vae, making it impossible for me to run them, as I go over 24GB VRAM trying to fit everything in twice.

**Comment by HMRMike** [comment]
What, Flux?
Being full fp16 doesn't mean T5/Clip/Vae are included. They must be loaded from somewhere, whether baked in the model or from external files, in any case and any UI.
