### ISSUE TITLE
[Feature Request]: Controlnet access via api same as Automatic 11111

### ISSUE THREAD

**Issue by VRVirtuosos** [lllyasviel/stable-diffusion-webui-forge#223]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

The Api is missing all the controlnet access features.  Please add them in.

**Comment by huchenlei** [comment]
See https://github.com/lllyasviel/stable-diffusion-webui-forge/wiki/ControlNet-Web-API
