### ISSUE TITLE
When using sdapi/v1/txt2img API to output WebP files, lossless option had been ignored

### ISSUE THREAD

**Issue by JujoHotaru** [lllyasviel/stable-diffusion-webui-forge#2242]
Hi, I'm using sdapi/v1/txt2img API to generate images. I want to use lossless webp as output format.

When using sdapi/v1/txt2img API to output WebP files, it seems that "use lossless webp" option is ignored.  

in `api.py`, `encode_pil_to_base64()` function :

```
image.save(output_bytes, format="WEBP", exif = exif_bytes, quality=opts.jpeg_quality)
```

This should be like below?

```
image.save(output_bytes, format="WEBP", exif = exif_bytes, quality=opts.jpeg_quality, lossless=opts.webp_lossless)
```

**Comment by catboxanon** [comment]
PR made upstream: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/16620

**Comment by JujoHotaru** [comment]
Thank you!
