### ISSUE TITLE
[Feature Request]: LoRA Tab is without folders

### ISSUE THREAD

**Issue by Dervlex** [lllyasviel/stable-diffusion-webui-forge#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

You can sort the loras by folders.

### Proposed workflow

1. Go to lora tab
2. Press show dirs

![grafik](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/142597552/4257fb00-8f79-41ad-8ec4-93f71df6e7bb)

**Comment by tripped144** [comment]
When under the Lora tab, if you look towards the right next to the search bar, there are a few options you can click. One of them is "Enable Tree View". That will allow you to access the folders.

**Comment by aolko** [comment]
**There is search, filters and file tree**
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/581458/9cae7aa9-3f74-4419-899e-7e99faa186c1)

**click through tabs until search bar and corrupted buttons appear**

**Comment by Dervlex** [comment]
![grafik](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/142597552/d3e63524-855e-4869-8f3a-e650a8ce5e55)
I dont have that ????

**Comment by aolko** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/142597552/304542039-d3e63524-855e-4869-8f3a-e650a8ce5e55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NTczNTEsIm5iZiI6MTcwNzg1NzA1MSwicGF0aCI6Ii8xNDI1OTc1NTIvMzA0NTQyMDM5LWQzZTYzNTI0LTg1NWUtNDg2OS04ZjNhLWU2NTBhOGNlNWU1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QyMDQ0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWU3ZTllOTBhNTEwODk2ODk4Y2U4ZmI3MzYzY2U2MjNhY2NjN2ZmNmMzNzE0YzVkMGYxNzBiNTAxY2ZjODhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d8enPNxrBcDjhV8Pkf-mvpU8EEAdn6Tsu6aLqvJVdTs) I dont have that ????

If it loads like this you gotta wait:
![](https://i.ibb.co/N9DLV5h/Pinokio-Okr-Avx-Pqm-U.gif)

So check your terminal for this state:
```
To create a public link, set `share=True` in `launch()`.
Startup time: 96.8s (initial startup: 0.2s, prepare environment: 29.7s, import torch: 42.8s, initialize shared: 0.9s, other imports: 6.8s, setup gfpgan: 0.2s, list SD models: 2.3s, load scripts: 7.8s, create ui: 3.0s, gradio launch: 3.3s).
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection'}
To load target model SDXLClipModel
Begin to load 1 model
Moving model(s) has taken 0.65 seconds
Model loaded in 246.7s (load weights from disk: 6.2s, forge solving config: 0.1s, forge instantiate config: 0.3s, forge load real models: 234.3s, load textual inversion embeddings: 0.5s, calculate empty prompt: 5.3s).
```

Then just click through:
![](https://i.ibb.co/JK5rkJN/Pinokio-Ii61c-QOXrf.gif)

**Comment by Dervlex** [comment]
After updating its there ^^

**Comment by 9wow** [comment]
@aolko my tree view is empty? 
![1TxbxmTIgn](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/102095866/30d1a0e5-cd43-4622-aa93-c80507f13b11)
