### ISSUE TITLE
Photomaker V2 cannot install due to accelerate version error during Python package

### ISSUE THREAD

**Issue by Won-JongHyun** [lllyasviel/stable-diffusion-webui-forge#2251]
Photomaker V2 cannot install due to accelerate version error during Python package. 
When installing PhotoMaker V2, the accelerate version must be 0.26 or higher, but the current version is 0.21. Even if I update it, when I restart forge, it goes back to version 0.21. Request error correction.

**Comment by thiagojramos** [comment]
Claro, aqui está a tradução do seu comentário para inglês:

Actually, it's not just that. It also asks for `[diffusers version > 0.29.1]`(https://github.com/TencentARC/PhotoMaker/issues/178#issuecomment-2294706763), but if you downgrade it gives an error.

**Comment by thiagojramos** [comment]
Actually, it's not just that. It also asks for `[diffusers version > 0.29.1] `(https://github.com/TencentARC/PhotoMaker/issues/178#issuecomment-2294706763), but if you downgrade it gives an error.

**Comment by SvenErik1968** [comment]
There has been many changes to Forge the last few months that are making many extensions made for A1111 not compatible with Forge anymore. Contact the developer of the extension and ask if they are planning to update it so that it will work with Forge.

**Comment by thiagojramos** [comment]
> There has been many changes to Forge the last few months that are making many extensions made for A1111 not compatible with Forge anymore. Contact the developer of the extension and ask if they are planning to update it so that it will work with Forge.

Well, at least from what I've said, it's not an "extension" itself, but rather one of the Spaces, the `forge_space_photo_maker_v2`. Besides, I think that in the case of these Spaces, even updating externally won't work, because I don't see a git repository in their folders.

**Comment by DenOfEquity** [comment]
You can prevent Forge downgrading `accelerate` by editing `requirements_versions.txt`. Currently Forge has it pinned to 0.21.0. I haven't had any issues, but it's at your own risk.
You can fix the `resume_download` error (that parameter is no longer used by `diffusers`) by manually editing `extensions-builtin/forge_space_photo_maker_v2/huggingface_space_mirror/pipeline_t2i_adapter.py` and removing the line `resume_download=resume_download,` which is line 229 or thereabouts.

**Comment by thiagojramos** [comment]
> You can prevent Forge downgrading `accelerate` by editing `requirements_versions.txt`. Currently Forge has it pinned to 0.21.0. I haven't had any issues, but it's at your own risk. You can fix the `resume_download` error (that parameter is no longer used by `diffusers`) by manually editing `extensions-builtin/forge_space_photo_maker_v2/huggingface_space_mirror/pipeline_t2i_adapter.py` and removing the line `resume_download=resume_download,` which is line 229 or thereabouts.

Thanks!! Removing the `resume_download` solved my issue 😁

**Comment by Techeek** [comment]
> You can prevent Forge downgrading `accelerate` by editing `requirements_versions.txt`. Currently Forge has it pinned to 0.21.0. I haven't had any issues, but it's at your own risk.您可以通过编辑 `requirements_versions.txt` 来阻止 Forge 降级`加速`。目前 Forge 已将其固定到 0.21.0。我没有遇到任何问题，但风险由您自己承担。 You can fix the `resume_download` error (that parameter is no longer used by `diffusers`) by manually editing `extensions-builtin/forge_space_photo_maker_v2/huggingface_space_mirror/pipeline_t2i_adapter.py` and removing the line `resume_download=resume_download,` which is line 229 or thereabouts.您可以通过手动编辑 `extensions-builtin/forge_space_photo_maker_v2/huggingface_space_mirror/pipeline_t2i_adapter.py` 和删除 `resume_download=resume_download,` 第 229 行或大约一行来修复`resume_download`错误（该参数不再被`扩散器`使用）。

Thanks, your answer solved my problem!
