### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for IntegratedAutoencoderKL

### ISSUE THREAD

**Issue by AlexYoung28** [lllyasviel/stable-diffusion-webui-forge#2255]
I've freshly installed this and i'm getting the following it was working fine on Friday and done the update and now i'm getting this?

RuntimeError: Error(s) in loading state_dict for IntegratedAutoencoderKL: size mismatch for encoder.conv_out.weight: copying a param with shape torch.Size([32, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([8, 512, 3, 3]). size mismatch for encoder.conv_out.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([8]). size mismatch for decoder.conv_in.weight: copying a param with shape torch.Size([512, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 4, 3, 3]).

**Comment by DenOfEquity** [comment]
Check you are using the correct VAE for the model.

**Comment by AlexYoung28** [comment]
oh don't i feel stupid lol, must have accidently clicked on that one! Thanks @DenOfEquity
