### ISSUE TITLE
Save Button seems to no longer work after recent updates

### ISSUE THREAD

**Issue by CubeRhythm** [lllyasviel/stable-diffusion-webui-forge#2259]
I hadn't changed anything in settings but when clicking the "save" button on image previews or below the generated images to the right of the prompt nothing happens. I thought it was an issue with my settings so I went in and updated the save folder location and saved my changes but nothing seems to have changed, still can't save with the save button. Opening images in a new tab and manually saving them seems to work. Not sure if it's just my install or an issue others are experiencing. I do have adetailer installed but am not currently using it, so it seems different from the other issue that's been reported but that might just be my ignorance. I'm not a coder so a lot of this is out of my depth, sorry!

**Comment by DenOfEquity** [comment]
Any error in console, something like the message in #2256?

**Comment by CubeRhythm** [comment]
Traceback (most recent call last):
  File "C:\Arena\Stable Diffusion\Data\Packages\Stable Diffusion WebUI Forge\modules\call_queue.py", line 76, in f
    res = list(func(*args, **kwargs))
  File "C:\Arena\Stable Diffusion\Data\Packages\Stable Diffusion WebUI Forge\modules\ui_common.py", line 123, in save_files
    fullfn, txt_fullfn = modules.images.save_image(image, path, "", seed=parameters['Seed'], prompt=parameters['Prompt'], extension=extension, info=p.infotexts[image_index], grid=is_grid, p=p, save_to_dirs=save_to_dirs)
  File "C:\Arena\Stable Diffusion\Data\Packages\Stable Diffusion WebUI Forge\modules\images.py", line 677, in save_image
    file_decoration = opts.samples_filename_pattern or p.override_settings.get("samples_filename_pattern") or "[seed]"
AttributeError: 'MyObject' object has no attribute 'override_settings'
'MyObject' object has no attribute 'override_settings'

**Comment by DenOfEquity** [comment]
Yep, same, thanks for confirming. Should be fixed now; Save button works for me with latest update.

**Comment by CubeRhythm** [comment]
Confirmed fixed, thank you!
