### ISSUE TITLE
UI Option to Add Checkpoint to Im2img not saving

### ISSUE THREAD

**Issue by andy8992** [lllyasviel/stable-diffusion-webui-forge#2262]
![image](https://github.com/user-attachments/assets/bcb8bc1c-25d7-4bf2-81f0-4178662bae01)

The checkpoint option in the above will not save. Upon reboot and refresh it is not there. I am hoping to set the checkpoint for text2img and img2img independently. Not sure if this will do that but I noticed this bug.

**Comment by BrickMissle** [comment]
It's supposed to do that, so it doesnt mess up the checkpoint dropdown at the top already
#2218
