### ISSUE TITLE
Control Net (SDXL) do not show up in the drop down menu

### ISSUE THREAD

**Issue by ClothingAI** [lllyasviel/stable-diffusion-webui-forge#2263]
I wanted to try "TILE" controlnet model for SDXL from here (https://huggingface.co/bdsqlsz/qinglong_controlnet-lllite)
And even after rereshing and erstarting they dont show up here:
![image](https://github.com/user-attachments/assets/c0425a6a-e2b1-4eea-9c1c-fad1e64d63bc)

**Comment by DenOfEquity** [comment]
Works for me. Downloaded *realistic* before starting Forge: it showed in the list straight away. Then downloaded 'anime alpha': it showed after using the refresh button, as expected.
Check the download location to make sure they are saved to the right place; also check the filesize - with huggingface you have to follow the filename link before downloading, or use the little download icon.

**Comment by ClothingAI** [comment]
I think the error was from me indeed, I had put it in another folder (I changed the base folder in the bat arguments and forgot) closing this. Thanks
