### ISSUE TITLE
I would prefer it to support sd or flux through the api

### ISSUE THREAD

**Issue by dhp666** [lllyasviel/stable-diffusion-webui-forge#2264]
Does forge currently support the flux api? I found that the previous parameters could not use the flux model, or I would prefer it to support sd or flux through the api

**Comment by altoiddealer** [comment]
Yes, forge can use flux just fine via the API.

You may post to the 'options' endpoint a dictionary containing the `sd_checkpoint_model` (string), `forge_additional_modules` (list of strings, can use short names like `['ae.safetensors', 'etc']`, `forge_inference_memory` (integer), etc - and those values will be set persistently.

You may also use the same dictionary structure for an `override_settings` in txt2img or img2img payloads, which would apply only to the current request (not set persistently).

**Comment by dhp666** [comment]
thanks~~

**Comment by dhp666** [comment]
def register(options_templates, options_section, OptionInfo):
    options_templates.update(options_section((None, "Forge Hidden options"), {
        "forge_unet_storage_dtype": OptionInfo('Automatic'),
        "forge_inference_memory": OptionInfo(1024),
        "forge_async_loading": OptionInfo('Queue'),
        "forge_pin_shared_memory": OptionInfo('CPU'),
        "forge_preset": OptionInfo('sd'),
        "forge_additional_modules": OptionInfo([]),
    }))
Are these parameters supported in the over settings api?

**Comment by altoiddealer** [comment]
Any options obtained via the options endpoint (GET) may be applied via options endpoint (POST), or `override_settings` (txt2img / img2img)

**Comment by dhp666** [comment]
thanks,very good

**Comment by dengtianbi** [comment]
May I ask if you executed successfully? Could you provide an example of a successful execution call? Thank you very much.

**Comment by altoiddealer** [comment]
> May I ask if you executed successfully? Could you provide an example of a successful execution call? Thank you very much.

When you are using the webui, in the addess bar add “/docs” to the end of the address and go, this will open the API UI.  From here, use the GET method for Options endpoint (“try it out”).  Now, copy the json format values, and paste them into the POST method for Options endpoint, except feel free to change the values.

When you execute it you will see it works.

**Comment by easylolicon** [comment]
I'm using the flux model and the 1.5 model, and when I load it for the first time it works, but when I set another version of the model via override_settings, I get Error(s) in loading state_dict for IntegratedAutoencoderKL.
