### ISSUE TITLE
strange results

### ISSUE THREAD

**Issue by Flaxmore** [lllyasviel/stable-diffusion-webui-forge#2265]
idk what is appening but i get those strange results

![00015-886491694](https://github.com/user-attachments/assets/d0ba482a-e3d9-4052-9fa5-6a8402dc3321)

PS: i got this error and i really can't find a way to solve it:

venv "D:\Pizza in culo\Smugma\sasso\Nuova cartella (2)\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-278-gbfee03d8
Commit hash: bfee03d8d9415a925616f40ede030fe7a51cbcfd
Installing requirements
Installing forge_legacy_preprocessor requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
Installing sd-forge-controlnet requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
Launching Web UI with arguments:
Total VRAM 8192 MB, total RAM 16262 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2070 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.float32
CUDA Stream Activated:  False
D:\Pizza in culo\Smugma\sasso\Nuova cartella (2)\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Using pytorch cross attention
*** Error loading script: preprocessor_marigold.py
    Traceback (most recent call last):
      File "D:\Pizza in culo\Smugma\sasso\Nuova cartella (2)\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Pizza in culo\Smugma\sasso\Nuova cartella (2)\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Pizza in culo\Smugma\sasso\Nuova cartella (2)\extensions-builtin\forge_preprocessor_marigold\scripts\preprocessor_marigold.py", line 10, in <module>
        from marigold.model.marigold_pipeline import MarigoldPipeline
      File "D:\Pizza in culo\Smugma\sasso\Nuova cartella (2)\extensions-builtin\forge_preprocessor_marigold\marigold\model\marigold_pipeline.py", line 9, in <module>
        from diffusers import (
      File "D:\Pizza in culo\Smugma\sasso\Nuova cartella (2)\venv\lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "D:\Pizza in culo\Smugma\sasso\Nuova cartella (2)\venv\lib\site-packages\diffusers\utils\__init__.py", line 37, in <module>
        from .dynamic_modules_utils import get_class_from_dynamic_module
      File "D:\Pizza in culo\Smugma\sasso\Nuova cartella (2)\venv\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
        from huggingface_hub import cached_download, hf_hub_download, model_info
    ImportError: cannot import name 'cached_download' from 'huggingface_hub' (D:\Pizza in culo\Smugma\sasso\Nuova cartella (2)\venv\lib\site-packages\huggingface_hub\__init__.py)

**Comment by jswag245** [comment]
Are you using Forge or are you using reForge? If you are using reForge, it may be better to post your issue there instead.

**Comment by Flaxmore** [comment]
> Are you using Forge or are you using reForge? If you are using reForge, it may be better to post your issue there instead.

i got the same results in both so i uploaded it here

**Comment by DenOfEquity** [comment]
You are using a very old version.

**Comment by jswag245** [comment]
Run update.bat or do a fresh reinstall of Forge and let us know what happens in case it is because of the old version.

**Comment by Flaxmore** [comment]
it appened after i runned the requirements.txt, and it's not related with update cause it appens in vary version of the base a111

**Comment by jswag245** [comment]
Do you get the same exact issue with commit 6e1a7908b444af40165986f383933a0d0e52ff6d? Is the error also the same with base A111? Sorry for all the questions, just trying to help diagnose the issue.

**Comment by Flaxmore** [comment]
> Do you get the same exact issue with commit [6e1a790](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/6e1a7908b444af40165986f383933a0d0e52ff6d)? Is the error also the same with base A111? Sorry for all the questions, just trying to help diagnose the issue.

sorry but i'm really god at coding and stuff and don't really know what where and when to see

**Comment by Flaxmore** [comment]
I just resolved and i'm gonna look dumb to make you (if anyone ever get the same issue) not look dumb... pls look if you got 2 python installed where one is a corrupted version that go on that version fix it and then uninstall it

**Comment by Flaxmore** [comment]
idc i'm gonna look stupid just to not let you (if ever anyone gotta get the same issue) look stupid, i just discovered i got 2 python version where 1 was corrupted and didn't updated and stayed there, pls install the installer of that specific python version (if you don't arledy have it) click on fix and then after the fix is finished uninstall it and do a fresh reinstall of python

**Comment by Flaxmore** [comment]
idc i'm gonna look stupid just to not let you (if ever anyone gotta get the same issue) look stupid, i just discovered i got 2 python version where 1 was corrupted and didn't updated and stayed there, pls install the installer of that specific python version (if you don't arledy have it) click on fix and then after the fix is finished uninstall it and do a fresh reinstall of python

**Comment by Flaxmore** [comment]
idc i'm gonna look stupid just to not let other (if ever anyone gotta get the same issue) look stupid, i just discovered i got 2 python version where 1 was corrupted and didn't updated and stayed there, pls install the installer of that specific python version (if you don't arledy have it) click on fix and then after the fix is finished uninstall it and do a fresh reinstall of python

**Comment by Flaxmore** [comment]
idc i'm gonna look stupid just to not let other (if ever anyone gotta get the same issue) look stupid, i just discovered i got 2 python version where 1 was corrupted and didn't updated and stayed there, pls install the installer of that specific python version (if you don't arledy have it) click on fix and then after the fix is finished uninstall it and do a fresh reinstall of python
