### ISSUE TITLE
Crop input image based on A1111 mask in Forge

### ISSUE THREAD

**Issue by Prigodjin** [lllyasviel/stable-diffusion-webui-forge#227]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I am very sorry. I'm not a programmer. I just wanted to say that I don’t see such a check box in Forge controlnet when I go inpaint. maybe this is worth adding? Maybe i do something wrong? I apologize again for my intrusiveness.
![1](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/159698788/1d8a45d1-846f-4dc3-b0e9-db16d60afb1d)

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by strawberrymelonpanda** [comment]
It was removed.  The thread's kind of hard to find, but it's mentioned [here](https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/40#discussion-6184773))

> Crop input image based on A1111 input checkbox removed. IPAdapter and many other control types now do not crop input image by default.

It was very important to me in the A1111 extension, but may be working without now.  Personally, I'm still testing my workflows with Forge.  Do you notice a difference in yours?

**Comment by Prigodjin** [comment]
when you do inpaint mask to improve your face in image to image inpaint, without this option instant_id_face_keypoints simply cannot find the face in the picture. 
![2](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/159698788/47c2a4c6-310e-4831-8983-a7f96582ab92)

**Comment by strawberrymelonpanda** [comment]
I noticed the issue was closed.  Did you find your issue with instant ID?  If not, I think it's reasonable to keep the issue open.

**Comment by Prigodjin** [comment]
now the problem is solved. instant_id CAN find face without Crop input image checkbox today. thanks for worrying about me!
