### ISSUE TITLE
Update broke the generations... temporarily

### ISSUE THREAD

**Issue by Dajova** [lllyasviel/stable-diffusion-webui-forge#2298]
I'm not sure what happened, but ever since the update yesterday (pulled today), i can gen maybe once or twice and then either the program crash or the graphics driver does. I've tried with multiple different models and all shows the same crash, so it's not just a single case...
This is all it says in the window before crashing:
```
[Unload] Trying to free 1024.00 MB for cuda:0 with 0 models keep loaded ... Current free memory is 3817.57 MB ... Done.
Cleanup minimal inference memory.
tiled upscale: 100%|#####################################################| 35/35 [00:04<00:00,  8.20it/s]
Press any key to continue . . .
```
Any ideas? 

edit: Only seems to happen with specifically pony-based models, but not sdxl ones... which is weird.

edit2: nwm, now it seems completely fine again. Im guessing the back-to-black crashes where only temporary? Nevertheless, ill keep the issue open just in case it creeps up again.

**Comment by jswag245** [comment]
Would you consider the issue closed?

**Comment by Dajova** [comment]
For now, yes. Haven't crashed once doing the fix, at least not with the program itself.
