### ISSUE TITLE
It seems that the refiner has a memory bug

### ISSUE THREAD

**Issue by lvyonghuan** [lllyasviel/stable-diffusion-webui-forge#2308]
I noticed that in the latest commit, the refiner was re-enabled. But when I open the refiner, I often get operating system level errors. The performance is that python stops running directly. When I stopped using the refiner, the error stopped happening.

This error happens by chance, but I'm almost certain it's because I turned on the refiner. When I turned on the refiner, the error occurred two or three times in half an hour. After I closed the refiner, the error did not occur again for three hours.

https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/2192

---

It looks like I've found the problem.

https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/2308#issuecomment-2470536030

**Comment by s4130** [comment]
For me, switching models causes the virtual memory to keep increasing. Could you observe this?

**Comment by lvyonghuan** [comment]
> For me, switching models causes the virtual memory to keep increasing. Could you observe this?

I don't think the problem is caused by virtual memory. I only remember one time when the refiner was enabled, I just clicked the start button (I had not switched models at this time), and then suddenly the screen went black twice, and then a system-level error message popped up, showing that python stopped running.

I'll try to reproduce this issue later.

**Comment by lvyonghuan** [comment]
> For me, switching models causes the virtual memory to keep increasing. Could you observe this?

Maybe you are right. There does seem to be some issue here regarding virtual memory.

I have previously terminated the generation process directly when encountering several unsatisfactory compositions. This time I terminated and watched the changes in virtual memory. I noticed that the amount of committed memory of the python process seemed to be spiraling up, not down. I wonder if the memory occupied by the refiner model is not cleaned up normally when it terminates?

I'm still testing it, and I don't know if it's causing the problem. I've only recently started to get into the way operating systems manage memory.

**Comment by lvyonghuan** [comment]
It does seem to be a memory related issue.

I ran program over and over several times. Sometimes the generation is interrupted, and sometimes it is allowed to complete normally. Whether interrupted or completed normally, committed memory continues to grow.

Finally an error was reported.

![图片](https://github.com/user-attachments/assets/eb02e338-0c36-4dae-b252-ba85e3b54846)

![图片](https://github.com/user-attachments/assets/abc70a87-8ad5-44c3-b37b-4b68c5b0146e)

![图片](https://github.com/user-attachments/assets/9bed8e37-8096-4bb1-9089-7996100cfa75)

![图片](https://github.com/user-attachments/assets/45fbcf77-2461-44d9-98e0-7625c735cbf4)

![图片](https://github.com/user-attachments/assets/00c6e05b-841c-4e4c-8655-755f65a8712b)

![图片](https://github.com/user-attachments/assets/6897c9fd-7be6-4043-861f-573d23d2e6ba)

**Comment by erew123** [comment]
There **might** be a wider memory issue. I was using X/Y/Z to load different checkpoints for the same prompt. No refiner was in-use. I've had this occur once or twice over the last week or so, but havnt been using forge too much anyway.

Using the X/.Y/Z to load in different checkpoints, I've had my Linux/Ubuntu Nvidia driver crash and throw me back to the login screen. It doesnt happen on the first run of using multiple checkpoints (about 6 checkpoints all SD 1.5), but maybe the 3-5th run. FYI I am also doing a 512x768 with a hi-res upscale 1.5x with Euler a.

So Im just throwing this into the pot as **something Ive seen** that may or may not be related.

![image](https://github.com/user-attachments/assets/7f4987a5-b51c-4591-8311-373da45748f4)

The only issue I can spot in the logs however is:

```
[drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Failed to grab modeset ownership
Nov 12 14:06:56 ubuntuuser-desktop kernel: 
```

Which seems to be a driver issue! And who knows if there is a memory leak in that or if its even related!

GPT claims:

"Failed to grab modeset ownership" Errors:

These errors from nvidia_drm (NVIDIA’s Direct Rendering Manager) indicate the driver is failing to control display modes (resolutions, refresh rates, etc.). This may be caused by an issue with the NVIDIA drivers or with how the GPU is interacting with the display server (Xorg or Wayland).

This issue can sometimes lead to display crashes or being logged out unexpectedly, as the display server fails to maintain a stable connection to the GPU.

**Comment by lvyonghuan** [comment]
> Does refiner work for flux? what is its purpose exactly?

I haven't tried it. refiner is a concept proposed by sdxl, and flux may not work. You can give it a try.

According to my popular understanding, the text2img result is made into img2img using the refiner model. The details are better than simple text2img.

I just started using it and haven't found any tricks yet.

**Comment by s4130** [comment]
> Does refiner work for flux? what is its purpose exactly?

If you start with an anime model and then choose a realistic model in the refiner, it can achieve effects that a realistic model alone cannot reach. Additionally, starting with a more 'obedient' model and then layering it with your preferred model may yield better results.

**Comment by DenOfEquity** [comment]
Please take a look at #2315.
I'd like the method tested on a range of setups before merging; but for me it prevents *Committed memory* blowing up, and has no downsides. The relevant change is only 3 (+1 comment) lines added to one file (`backend/memory_management.py`), so easy to manually add.

**Comment by s4130** [comment]
> Please take a look at #2315. I'd like the method tested on a range of setups before merging; but for me it prevents _Committed memory_ blowing up, and has no downsides. The relevant change is only 3 (+1 comment) lines added to one file (`backend/memory_management.py`), so easy to manually add.

Thanks, this worked for me

**Comment by lvyonghuan** [comment]
> Please take a look at #2315. I'd like the method tested on a range of setups before merging; but for me it prevents _Committed memory_ blowing up, and has no downsides. The relevant change is only 3 (+1 comment) lines added to one file (`backend/memory_management.py`), so easy to manually add.

But I suddenly thought whether there is some repeated loading phenomenon in the refiner? I'm using the same set of models, but the committed memory footprint keeps increasing.

I'm new to memory management so I'm sorry if what I said is wrong.

**Comment by DenOfEquity** [comment]
The refiner loads the second pass model by calling the same function that is used when a model is normally loaded. The process is the same. The difference is the starting conditions - a different model already being used, inference in progress.
In your case, you have enough VRAM that the problem doesn't get triggered with normal generation. But the extra demands of the refiner do expose it. Users with more VRAM might never see the issue; users with less could run into it every time they change model.

**Comment by lvyonghuan** [comment]
problem solved by https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/19a9a78c9bb54d13a8f291f43939331af3242e8a. Thanks!

**Comment by zhangqinghao0811** [comment]
> Please take a look at #2315. I'd like the method tested on a range of setups before merging; but for me it prevents _Committed memory_ blowing up, and has no downsides. The relevant change is only 3 (+1 comment) lines added to one file (`backend/memory_management.py`), so easy to manually add.

Why didn't the author merge this commit into the master? To be honest, this bug has severely affected the use of forge, which is basically in an unusable state. Every change of model is guaranteed to crash.

**Comment by lvyonghuan** [comment]
> > Please take a look at #2315. I'd like the method tested on a range of setups before merging; but for me it prevents _Committed memory_ blowing up, and has no downsides. The relevant change is only 3 (+1 comment) lines added to one file (`backend/memory_management.py`), so easy to manually add.
> 
> Why didn't the author merge this commit into the master? To be honest, this bug has severely affected the use of forge, which is basically in an unusable state. Every change of model is guaranteed to crash.

But it already merge...... I think. So I close the issue. I don't meet any memory (not include gpu's) problem after I upgrade, or maybe just beacause I have128G DDR3 memory. Anyway for me this issue disapper.
Maybe you need `git pull`?

**Comment by zhangqinghao0811** [comment]
> > > Please take a look at #2315. I'd like the method tested on a range of setups before merging; but for me it prevents _Committed memory_ blowing up, and has no downsides. The relevant change is only 3 (+1 comment) lines added to one file (`backend/memory_management.py`), so easy to manually add.
> > 
> > 
> > Why didn't the author merge this commit into the master? To be honest, this bug has severely affected the use of forge, which is basically in an unusable state. Every change of model is guaranteed to crash.
> 
> But it already merge...... I think. So I close the issue. I don't meet any memory (not include gpu's) problem after I upgrade, or maybe just beacause I have128G DDR3 memory. Anyway for me this issue disapper. Maybe you need `git pull`?

I'm so sorry. I just checked the code, this code has indeed been merged. But I do now cause crashes every time I change the model. I thought it was a memory management bug like this issue, but it wasn't. Looks like I need to raise a new issue, I ran into a different bug. 
Thanks for your reply.
