### ISSUE TITLE
[feature request] RescaleCFG on forge

### ISSUE THREAD

**Issue by wensleyoliv** [lllyasviel/stable-diffusion-webui-forge#2345]
With the release of new V-pred models like NoobAI-XL (NAI-XL), i see recomendations of using rescale cfg 0.7 with it, but looks like there's only one extension from a year ago which is unsupported on forge, and updated extensions available for comfyui, i don't know how much it would affect the generations because i can't test, but some kind of support would be appreciated.

**Comment by DenOfEquity** [comment]
It's in *LatentModifier Integrated* as *Rescale Cfg Phi*

**Comment by wensleyoliv** [comment]
Thanks!
