### ISSUE TITLE
Changing default width and height in ui config and the default in settings does not change on restart

### ISSUE THREAD

**Issue by borris345** [lllyasviel/stable-diffusion-webui-forge#2347]
![image](https://github.com/user-attachments/assets/65444457-aa7b-4499-8899-7caf44137cc6)

just keeps reverting back to above.

**Comment by tampadesignr** [comment]
maybe this can help while we wait to see what happens
https://github.com/altoiddealer/--sd-webui-ar-plusplus
i just added it for same reason
