### ISSUE TITLE
(Apologies for not directly related to program) Forge Compressed File not extracting ?

### ISSUE THREAD

**Issue by NorLio49** [lllyasviel/stable-diffusion-webui-forge#2375]
Hello,

I am very new to this so I do apologize in advance if this is a simple fix that gets repeated over and over. For some weird reason, when I download the Forge compressed file (both the latest recommended one and the next older version) it seems to refuse to extract. I am using 7z. It unpacks some of the files just fine, then grinds to a halt, the extraction progress claiming it is extracting KB/s! I decided to leave my PC on all night and when I woke up, it still basically didn't budge. 

This does not seem normal for unzipping a file, I have never seen a compressed file do this to me before. Am I doing something wrong? I should have the latest 7z program (Aug 2024). Is there a different tool I should use instead? 

Thank you,

**Comment by Juqowel** [comment]
It may be an antivirus.

**Comment by NorLio49** [comment]
> It may be an antivirus.

Oooh thank you. I didn't think about that. I had to Unblock the file's properties. Now it extracted in seconds. Problem solved.
