### ISSUE TITLE
How can I hide the default Quicksetting that appears at the top?

### ISSUE THREAD

**Issue by R5021** [lllyasviel/stable-diffusion-webui-forge#2397]
![Screenshot 2024-11-30 at 09 15 58](https://github.com/user-attachments/assets/0cbe3489-0ae3-4918-89a2-5447c2c787ce)

![Screenshot 2024-11-30 at 09 16 51](https://github.com/user-attachments/assets/ea3d1c69-e7d3-4e5a-8a0c-830c9eb58772)

I'm using Forge, and I'm trying to share my local server with other users via --share.

I want to hide the menus at the top to prevent other users from interacting with them, but I haven't found a way to hide the top menu in the settings.

The Quicksettings List option is left blank.

**Comment by DenOfEquity** [comment]
New option `UI tabs without QuickSettings bar (top row)` added in *Settings > User interface*.
