### ISSUE TITLE
Moving Forge to other HDD Don't work anymore 

### ISSUE THREAD

**Issue by carlmoss22** [lllyasviel/stable-diffusion-webui-forge#2418]
Forge don't work at all. i got the error. launch.py: error: unrecognized arguments: -preset normal

can somebody please help me out?

thx in advance

**Comment by MigCurto** [comment]
either you specify with start arguments the new location 8either st start in terminal or in webui-user.sh) or create symlinks from new location to new one.

**Comment by carlmoss22** [comment]
thx. now it's working
