### ISSUE TITLE
(solved) Start with an empty prompt box

### ISSUE THREAD

**Issue by Paraparaparaparapara** [lllyasviel/stable-diffusion-webui-forge#2427]
Hello. 

Every time I start the program, the same prompt appears. There is no way to make the box appear empty. I delete it, restart, and it reappears. I change it, use the new prompt, restart, and the old one reappears. I don't want to reinstall to avoid losing all the configuration, but I can't find a way to start with an empty prompt.

Thanks in advance.

**Comment by DenOfEquity** [comment]
Clear the prompt; go to *Settings > Defaults*; click *Apply*.

**Comment by Paraparaparaparapara** [comment]
Solved. Thanks. I didn't do it earlier because I thought it would erase all the configuration options.
