### ISSUE TITLE
flux makes forge crash

### ISSUE THREAD

**Issue by Melyns** [lllyasviel/stable-diffusion-webui-forge#2432]
i have this problem where using any flux model makes forge crash (all gguf quants, and flux schnell). looks like out of memory crash because on few occasions it made google chrome and explorer.exe also crash.

about two months ago i was using forge and flux on this pc without issues. my pc configuration is still the same. this problem only started happening after updating forge.

40gb swap
rtx 4070 super
32gb ddr5 ram
windows 11

**Comment by Melyns** [comment]
```
[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... Done.
StateDict Keys: {'transformer': 2336, 'vae': 244, 'text_encoder': 198, 'text_encoder_2': 220, 'ignore': 0}
Using Detected T5 Data Type: torch.float8_e4m3fn
Using Detected UNet Type: nf4
Using pre-quant state dict!
Working with z of shape (1, 16, 32, 32) = 16384 dimensions.
K-Model Created: {'storage_dtype': 'nf4', 'computation_dtype': torch.bfloat16}
Calculating sha256 for E:\AI\Forge\webui\models\Stable-diffusion\flux1SchnellBNBNF4.safetensors: 893309122338e0ce6cdd778cbd931e734dd0064cf86d7bf33b13619b450b2cf4
Model loaded in 1.6s (unload existing model: 0.2s, forge model load: 1.4s).
Skipping unconditional conditioning when CFG = 1. Negative Prompts are ignored.
[Unload] Trying to free 7725.00 MB for cuda:0 with 0 models keep loaded ... Done.
[Memory Management] Target: JointTextEncoder, Free GPU: 11041.00 MB, Model Require: 5154.62 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 4862.38 MB, All loaded to GPU.
Moving model(s) has taken 5.46 seconds
Distilled CFG Scale will be ignored for Schnell
Press any key to continue . . .
```

**Comment by x-ili-x** [comment]
I've been noticing mine crashing a lot more often with flux lately as well, and that's with 64GB RAM and a 4090. Between that and highres fix/inpainting/img2img being broken with flux I might just have to figure out a new workflow in comfyui or something, because I can't do anything useful in forge anymore.

**Comment by BenDes21** [comment]
> I've been noticing mine crashing a lot more often with flux lately as well, and that's with 64GB RAM and a 4090. Between that and highres fix/inpainting/img2img being broken with flux I might just have to figure out a new workflow in comfyui or something, because I can't do anything useful in forge anymore.

agree, forge is trash  now

**Comment by Fucktwit** [comment]
I have a similar problem and i've tried a LOT of things trying to fix it :)
Assuming yer on Windows, can you please crash it and immediately check the event log (eventvwr.msc) under applications and see what the error is?
Thanks

**Comment by Melyns** [comment]
```
Faulting application name: python.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffdf6d246a4
Faulting process id: 0x1270
Faulting application start time: 0x1DB496089BFE2F8
Faulting application path: E:\AI\Forge\system\python\python.exe
Faulting module path: unknown
Report Id: 476f313a-d24b-4865-98ba-35bf5b475fa6
Faulting package full name: 
Faulting package-relative application ID: 
```
