### ISSUE TITLE
[Bug]: Image Quality Degradation

### ISSUE THREAD

**Issue by JcynR** [lllyasviel/stable-diffusion-webui-forge#244]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I observed a degradation in the quality of images generated using the new webui-forge compared to the original generation in January and the retry with the same parameters using default webui configuration.
I have provided a comparison image below to illustrate the difference. I used adetailer but only because the original one was using it as well. Even without it the quality is still inferior to the original.

### Steps to reproduce the problem

Generated an image using the original webui in January with specific parameters.
Retried generating the same image again using the original webui with the same parameters and default webui configuration.
Generated the same image using the new webui-forge with the same parameters.

### What should have happened?

The quality of images generated using the new webui-forge should be comparable to the ones generated in January and the retry using default webui configuration.

### What browsers do you use to access the UI ?

Brave

### Sysinfo

![quality-degrading](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/22550885/634b1d15-1cac-4cb2-93ef-7a9468537cb5)

### Console logs

```Shell
-
```

### Additional information

I have not updated any drivers recently. The degradation in image quality is noticeable even without the use of adetailer.

**Comment by JcynR** [comment]
I assure you all the images are the same resolution and using the same generation parameters. The second and third image are using default webui config, the first one I'm 99% positive is the same config as the second one but some packages may have been updated in the mean time.
Also forgot to mention I'm using LCM + same LCM LoRa for all 3 of the images.
The images I generated in January were amazing and I cannot get to that quality anymore using the same parameters.

**Comment by TheRealPhooney** [comment]
That effect on skin is something I've only ever seen when using adetailer.  You've said the original generations were using adetailer, is that for sure?  Within adetailer are you using the same model, prompt(s) and settings?  How does the generation look without adetailer.

**Comment by lllyasviel** [comment]
do you have raw result with meta data?

**Comment by ArnorWing** [comment]
Is that LCM LORA or checkpoint? LCM does weird things to skin

**Comment by JcynR** [comment]
So, it turns out the eta noise seed delta was wrong and the images didn't match. Apparently it doesn't get stored in the image's meta anymore.

Also, the last image is an issue with adetailer. I left its prompts empty so it uses the original prompt, but the LCM lora I was using is inside a style instead of typed directly in the prompt, so it didn't use it.

Sorry for any confusion.
