### ISSUE TITLE
forge started creating blank, distorted images

### ISSUE THREAD

**Issue by navi38x** [lllyasviel/stable-diffusion-webui-forge#2451]
hi i been making images with forge for year just today everything worked normally ,made few images and then 5 images it just broke it looked broken disjointed and grainy ,interrupted then tried again same thing just now it was completely grey and grainy ,restarted same thing used same prompt same flux dev nf4 v2 i mean i get no error i get no info on what could it be everything seems to work normally no load error nothing in the terminal i thought my graphics died i tried using fooocus works normal thought it might be the flux model so i tried different model on forge same thing not sure what's happening, never had this happen and since there is no error anywhere have no idea what to do

**Comment by jswag245** [comment]
Maybe CFG is too low or high? Does this also occur on a fresh reinstall of Forge?

**Comment by x-ili-x** [comment]
Sounds similar to what's been happening to me with flux, but for me it only happens whenever i use highres fix, inpainting or img2img. It's driving me CRAZY, because my work hinges on highres fix/inpainting/img2img. https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/2404#issue-2712332582

**Comment by navi38x** [comment]
it works now i still don't know why but I'm thinking it was lora related not sure though cause all the loras working now also ,
yes it was happening on fresh install, distilled is always 2,5 to the default 3.5 normal cfg i never touch its always on default 1.
i still have no idea why this happened i, thinking lora cause i prompted without it and it started working but then i prompted back with the same lora and it worked with it also just fine so still confused but issue fixed :P
