### ISSUE TITLE
config.json is overriding ui-config options

### ISSUE THREAD

**Issue by lucyknada** [lllyasviel/stable-diffusion-webui-forge#2452]
for example if you set the (sd)xl sampler to `Euler a`, save defaults and then reboot it will always go back to dpm++ 2m no matter what ui-config is set to.

**Comment by MisterChief95** [comment]
There's a separate setting section called `UI defaults 'xl'` under the `User Interface` group where you can try changing it.

**Comment by lucyknada** [comment]
that indeed seems to be the case, thanks!
