### ISSUE TITLE
downloaded extensions not enabling (EDITED: will this extension ever be supported)

### ISSUE THREAD

**Issue by Namelessguy-ops** [lllyasviel/stable-diffusion-webui-forge#2476]
i recently downloaded this extension (https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111) but after after clicking on the apply  and restart ui in the installed tab it does not get enabled nowhere to be seen in text2img  or img2img tabs i even tried reinstalling the extension and also ticking the check box in installed tab but it still doesn't work ( i checked for errors in cmd, there were no errors). it also doesn't work with all the other extensions i downloaded from the extensions tab. Edited: so it seems like all those extensions i have been downloading are not compatible with forge. Now i wanna know will this extension ever work with forge?

**Comment by jswag245** [comment]
Which extension is it? I think you accidentally linked Forge instead.

**Comment by Namelessguy-ops** [comment]
> Which extension is it? I think you accidentally linked Forge instead.

Oops mb, i updated the link

**Comment by SvenErik1968** [comment]
I think you would be better served by raising a ticket with the creators of that extension and ask if they will update it so it will be compatible with Forge. A lot of changes have been done with Forge the last 6 months or so making a lot of (more likely most of) A1111-compatible extensions incompatible with Forge. It is up to the extension developers to make it compatible.

BTW, under Discussions, there is a [thread about Forge-compatible extensions](https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1754).

**Comment by Namelessguy-ops** [comment]
> I think you would be better served by raising a ticket with the creators of that extension and ask if they will update it so it will be compatible with Forge. A lot of changes have been done with Forge the last 6 months or so making a lot of (more likely most of) A1111-compatible extensions incompatible with Forge. It is up to the extension developers to make it compatible.
> 
> BTW, under Discussions, there is a [thread about Forge-compatible extensions](https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/1754).

thank you!
