### ISSUE TITLE
Bug in Forge (ValueError: unexpected EOF)

### ISSUE THREAD

**Issue by Farhad-F10** [lllyasviel/stable-diffusion-webui-forge#2493]
Hi All,
after I installed Forge, I got an error whenever I started generating an image

![error-11](https://github.com/user-attachments/assets/5400f615-80d6-4fe0-85fc-0b60917a7ca4)

ValueError: unexpected EOF, expected 796379 more bytes. The file might be corrupted. File corrupted: H:\stable-diffusion-forge\stable-diffusion-webui-forge-main\models\GFPGAN\detection_Resnet50_Final.pth Forge has tried to move the corrupted file to H:\stable-diffusion-forge\stable-diffusion-webui-forge-main\models\GFPGAN\detection_Resnet50_Final.pth.corrupted You may try again now and Forge will download models again. 

After searching, I found this file (detection_Resnet50_Final.pth) in the folder
H:\stable-diffusion-forge\stable-diffusion-webui-forge-
main\models\GFPGAN

![error-10](https://github.com/user-attachments/assets/a7df6699-8feb-479f-8714-4e735d09ae1e)

I manually deleted the corrupted file, but it keeps downloading every time I generate the image. 😕
I downloaded the file correctly and directly and manually placed it in the folder (GFPGAN), but the problem still has not been solved !!!

this is my bat file code
![webui-bat-forge](https://github.com/user-attachments/assets/4f455b5c-6bf8-4f0a-a37d-3a9bdcee4c50)

I have no issue with my internet and have a high-speed net

Where is the problem? How do you think I could fix it?
If you need any information, please do ask me.

Many Thanks All

**Comment by MisterChief95** [comment]
Is this happening during a standard txt2img generation? Do you have any extensions installed or options enabled that might affect it?

**Comment by Farhad-F10** [comment]
> Is this happening during a standard txt2img generation? Do you have any extensions installed or options enabled that might affect it?

Thanks for your reply
Yes, txt2img standard and I use very simple prompt 👇

![text2msg](https://github.com/user-attachments/assets/af560add-5cbe-4863-bf69-806b68481717)

Do you have any extensions installed or options enabled that might affect it? I did not change or install anything yet, these are normal by default list by this Forge 👇

![list ext](https://github.com/user-attachments/assets/9a993661-d284-420a-8f7a-97057152520e)

**Comment by Juqowel** [comment]
> I downloaded the file correctly and directly and manually placed it in the folder (GFPGAN), but the problem still has not been solved !!!

Did you rename it to `detection_Resnet50_Final.pth`?

**Comment by Farhad-F10** [comment]
> > I downloaded the file correctly and directly and manually placed it in the folder (GFPGAN), but the problem still has not been solved !!!
> 
> Did you rename it to `detection_Resnet50_Final.pth`?

I have changed but it did not work ❌

![resnet](https://github.com/user-attachments/assets/3e3d0910-5b56-461d-af4e-993be559e387)

this is after an Error and again made another file 👇

![parsing](https://github.com/user-attachments/assets/5e348d5f-2ffb-49e4-b1d5-220e5a0bc3be)

**Comment by Juqowel** [comment]
Second one should be 83,332 KB. Something wrong with the connection. Take it manually.

**Comment by Farhad-F10** [comment]
> Second one should be 83,332 KB. Something wrong with the connection. Take it manually.

Please give me a link so that I can get it manually?

**Comment by Farhad-F10** [comment]
this is BUG in ( Forege and Fooocus ) because when I use Automatic1111 I have NO issues! 

but Forge ❌ and Fooocus ❌ have the same problem!

**Comment by Juqowel** [comment]
> Please give me a link so that I can get it manually?

If it's still needed - [https://huggingface.co/Juqowel/parsing_parsenet/tree/main](https://huggingface.co/Juqowel/parsing_parsenet/tree/main)

**Comment by Farhad-F10** [comment]
> > Please give me a link so that I can get it manually?
> 
> If it's still needed - https://huggingface.co/Juqowel/parsing_parsenet/tree/main

Thanks, Mate for your file, I've replaced it but still is the same and does not work! ❌

![parsing-error1](https://github.com/user-attachments/assets/f09f0688-23eb-41ba-80f2-433e92c089f9)

**Comment by Juqowel** [comment]
I'm uploaded both files. Same link.

**Comment by Farhad-F10** [comment]
> > Please give me a link so that I can get it manually?
> 
> If it's still needed - https://huggingface.co/Juqowel/parsing_parsenet/tree/main

You are a STAR, Mate 🌟
Well done, It worked now! ☺️
I never thought that the problem was with the files at all
I thank you very much for your time and work

I have a request Mate
Do you also use Fooocus UI too?

**Comment by Juqowel** [comment]
> Do you also use Fooocus UI too?

No. I don't like it.

**Comment by MisterChief95** [comment]
Glad you got it working! If everything is working fine, please close this issue.
