### ISSUE TITLE
[Bug]: Previews are not showing

### ISSUE THREAD

**Issue by yacinesh** [lllyasviel/stable-diffusion-webui-forge#282]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

while it generating i can't see the preview of the image

### Steps to reproduce the problem

1. type a prompt
2. click on generate

### What should have happened?

generate and showing a preview of the image while it generate

### Sysinfo

[sysinfo-2024-02-16-22-06.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14316456/sysinfo-2024-02-16-22-06.json)

### Console logs

```Shell
/
```

**Comment by kakachiex2** [comment]
Same problem here

**Comment by whitesky1226** [comment]
Try this: https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/210#issuecomment-1949816255

**Comment by yacinesh** [comment]
@whitesky1226 
I don't exactly understand what to do, can you help me with the details?

**Comment by joneschunghk** [comment]
It is no live preview when generating, although it has no effect on the results. I've compared the settings of a1111 and forge.

**Comment by jhlchu** [comment]
> Try adding the path via the command-line argument --gradio-allowed-path.
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/210#issuecomment-1947301705
This worked for me to restore previews.

**Comment by joneschunghk** [comment]
I've added the argument
`set COMMANDLINE_ARGS=--xformers --no-half-vae --autolaunch --gradio-allowed-path`
but error:
> launch.py: error: argument --gradio-allowed-path: expected one argument

If I've changed the argument
`set COMMANDLINE_ARGS=--xformers --no-half-vae --autolaunch --gradio-allowed-path output`
nothing happen. Just show the final result without live previews.

What should be filled in `GRADIO_ALLOWED_PATH`?

**Comment by jhlchu** [comment]
`set COMMANDLINE_ARGS= --xformers --gradio-allowed-path "C:\Stable Diffusion\outputs"`
change the path in "" to your absolute path

**Comment by yacinesh** [comment]
@jhlchu i've added this argument but still show the final result without live previews

**Comment by joneschunghk** [comment]
I've tried
`--gradio-allowed-path "D:\AI\Stable Diffusion\stable-diffusion-webui-forge\output"`
`--gradio-allowed-path "D:/A/Stable Diffusion/stable-diffusion-webui-forge/output"`
`--gradio-allowed-path "D:\AI\Stable Diffusion\stable-diffusion-webui-forge\outputs"`
`--gradio-allowed-path "D:/AI/Stable Diffusion/stable-diffusion-webui-forge/outputs"`
all the same.

**Comment by VeteranXT** [comment]
I tried all of it, it does not work!

**Comment by onliner2021** [comment]
You have to specify the folder where the files actually reside, not the junction (mklink /J) that points to it.
For example: --gradio-allowed-path "d:\pinokio\drive\drives\peers\d1708930112345\outputs"
This works for me.

**Comment by VeteranXT** [comment]
Didn't work for me

**Comment by joneschunghk** [comment]
use the path of a1111? not forge?

**Comment by DigitalBeer** [comment]
I use junctions for all my folders so I have this issue currently. I have left my symbolic link in place until it's fixed but in the meantime I've just changed my settings in webui to my direct paths, restarted webui and it now works again. I'm a visuals person so hopefully this screenshot will make it easier for others too :)

![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/130303270/39a0c787-8ca5-4ae4-9a9e-8813389f966f)

**Comment by ZamZad** [comment]
> I use junctions for all my folders so I have this issue currently. I have left my symbolic link in place until it's fixed but in the meantime I've just changed my settings in webui to my direct paths, restarted webui and it now works again. I'm a visuals person so hopefully this screenshot will make it easier for others too :)
> 
> ![image](https://private-user-images.githubusercontent.com/130303270/309017542-39a0c787-8ca5-4ae4-9a9e-8813389f966f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjMzMDksIm5iZiI6MTcwOTI2MzAwOSwicGF0aCI6Ii8xMzAzMDMyNzAvMzA5MDE3NTQyLTM5YTBjNzg3LThjYTUtNGFlNC05YTllLTg4MTMzODlmOTY2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwMzE2NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMThjMTAwZDE5NDQ5MTZhMjlkNTU0ZmVkNTNmMzY0MzZjYTc0ODFhZmU3YjNhMzI0NWQ4MjgwNzVlZmMwMzU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vz83udxh8QrTnsxkUPWsLnEFE3MP1U_fAld49vfb6qM)

this fixed everything thank you

**Comment by VeteranXT** [comment]
Image is now showing,

**Comment by yacinesh** [comment]
@DigitalBeer i've done just like yours but still not showing previews 
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/156533253/10e30f7e-6369-4833-a6b5-de68718e285e)
