### ISSUE TITLE
Extra Network tab dont load with Lobehub theme

### ISSUE THREAD

**Issue by kakachiex2** [lllyasviel/stable-diffusion-webui-forge#285]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

After update to forge branch the lobehub theme extra network tab don't load I reported to the extension owner 
![Screenshot 2024-02-16 200816](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/1762112/27984684-d23b-46ee-8938-2ea27fe05096)

### Steps to reproduce the problem

Install the Lobehub theme extension an see it it do the same behavior 
https://github.com/lobehub/sd-webui-lobe-theme

### What should have happened?

This happen after change to forge branch

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

[sysinfo-2024-02-17-00-13.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14317058/sysinfo-2024-02-17-00-13.json)

### Console logs

```Shell
COMMANDLINE_ARGS does not contain --api, API won't be mounted.
[Lobe]: Initializing Lobe
Startup time: 38.2s (prepare environment: 18.6s, import torch: 6.3s, initialize shared: 0.1s, other imports: 0.6s, list SD models: 0.2s, load scripts: 10.5s, create ui: 1.3s, gradio launch: 0.4s).
model_type EPS
UNet ADM Dimension 2816
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
activating extra network lora: TypeError
Traceback (most recent call last):
  File "K:\Automatic111\stable-diffusion-webui\modules\extra_networks.py", line 145, in activate
    extra_network.activate(p, [])
  File "K:\Automatic111\stable-diffusion-webui\extensions-builtin\Lora\extra_networks_lora.py", line 18, in activate
    p.all_prompts = [x + f"<lora:{additional}:{shared.opts.extra_networks_default_multiplier}>" for x in p.all_prompts]
TypeError: 'NoneType' object is not iterable

To load target model SDXLClipModel
Begin to load 1 model
Moving model(s) has taken 0.60 seconds
Model loaded in 13.4s (load weights from disk: 1.5s, forge load real models: 7.3s, load textual inversion embeddings: 3.2s, calculate empty prompt: 1.4s).
```

**Comment by DenOfEquity** [comment]
Closed due to age.
