### ISSUE TITLE
Sora中文技术和应用讨论群：微信 openai0168

### ISSUE THREAD

**Issue by IMOSR** [lllyasviel/stable-diffusion-webui-forge#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/137986664/5e484b30-da41-4eb7-b7cc-bd58b72ddfb8)

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by huchenlei** [comment]
Irrelevant issue.
