### ISSUE TITLE
Face Restore Codeformer / GPFGAN slow speed compared to A1111

### ISSUE THREAD

**Issue by huchenlei** [lllyasviel/stable-diffusion-webui-forge#312]
### Discussed in https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/311

<div type='discussions-op-text'>

<sup>Originally posted by **TheRealPhooney** February 17, 2024</sup>
I couldn't see anybody else talking about this, so I wanted to check if it was just me.

Whenever I use face restore, either as part of txt2img/img2img or within the Reactor extension, the face restore part seems to take a lot longer than it did on A1111.

A quick and dirty comparison is a 512x768 image taking 3-4 seconds without any face restoration, and 12-14 seconds with face restoration, so 9-11 seconds for the GPFGAN/Codeformer to do its thing.

It's especially noticeable if you were using AnimateDiff, resulting in a bunch of frames to process.

Unfortunately, I pretty much gutted my A1111 installation moving all kinds of stuff over to Forge, and it would be a bit of a drag for me to set up A1111 again so all I have is my "feeling" that this part of the process is a lot slower rather than a direct comparison.

Is anybody else finding this slowdown too?</div>

**Comment by huchenlei** [comment]
Verified. We had to disable face restore unittests in CQ as they just get stuck there.

**Comment by ramnnv** [comment]
Yes, im using faceswaplab extension with same issue. My gpu is an old GTX 1060 6GB, so i was thinking was normal, but yes in automatic1111 the face is restored always in something like 3 seconds or less, and here with Forge maybe 8-10 seconds.

**Comment by Blueblizard** [comment]
Same problem here, Reactor is now very slow, around 5 seconds in A1111 to 15 in Forge.  I thought it was some problem with the extension but i see that it´s relative to GFPGAN/Codeformer. 

**ThereforeGames**, yes, in A1111 is configured the same way.
