### ISSUE TITLE
[Bug]: Repeated Upscaler Entries

### ISSUE THREAD

**Issue by Haoming02** [lllyasviel/stable-diffusion-webui-forge#313]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

In the **Extras** tab, the upscalers in the `ESRGAN` folder now show up twice in the dropdown.

<p align="center"><img src="https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/73768377/888e8b80-eb17-4648-b0ac-2c3e97986251"></p>

### Steps to reproduce the problem

1. Pull the latest commit ([43c9e3b](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/43c9e3b5ce1642073c7a9684e36b45489eeb4a49))
2. Launch the Webui
3. Go to **Extras** tab
4. Click on the Upscalers dropdown

### What should have happened?

Each file only shows up once

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

N/A

### Console logs

```Shell
N/A
```

### Additional information

N/A

**Comment by jipsita** [comment]
I have the same problem, any workaround? it's just aesthetically annoying but still :/

**Comment by Haoming02** [comment]
Right now, my Forge installation uses a **symlink** for the entire `models` folder, instead of using the `set A1111_HOME` thingy in the `.bat`. 
Maybe this is the cause?

I added a `print(file)` at [this line](https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/main/modules/esrgan_model.py#L26), and I got:
```bash
C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui\models\ESRGAN\2x-AnimeClassics-UltraLite.pth
C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui\models\ESRGAN\4x-UltraSharp.pth
C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui\models\ESRGAN\4xLSDIRplusC.pth
C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui-forge\models\ESRGAN\2x-AnimeClassics-UltraLite.pth
C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui-forge\models\ESRGAN\4x-UltraSharp.pth
C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui-forge\models\ESRGAN\4xLSDIRplusC.pth
```

Meaning, it somehow loads the files twice.

Funnily, I also put another model here:
```bash
C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui-forge\models\DAT\4xNomos8kDAT.pth
```
But this one doesn't show up twice.
