### ISSUE TITLE
Implement FreeU webui extension features into integrated extension

### ISSUE THREAD

**Issue by strawberrymelonpanda** [lllyasviel/stable-diffusion-webui-forge#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

FreeU Integrated is missing several features from the full FreeU plugin, which had quickly became one of my favorites.

The full FreeU supports presets with suggestions for Stable Diffusion, SD 2.0, and SDXL, as well as additional settings.  I would simply use the extension instead, but in my testing, it appears to be non-functional now.  

The original plugin will appear in an accordion as expected, and don't see any errors, it just doesn't seem to have any effect anymore.

### Proposed workflow

Ideally, please restore at least the preset functionality.

**Comment by strawberrymelonpanda** [comment]
Original FreeU plugin
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/152940198/765f3194-5957-4a30-85da-e67096e9121e)

FreeU Integrated
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/152940198/ad45b39c-84e1-4aa1-8b42-c8f6f45819f8)

Different options, different defaults, no presets.
I'm assuming B1/2 and S1/2 are Backbone 1/2 Scale and Skip 1/2 Scale.

**Comment by wardensc2** [comment]
FYI:
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/77379748/da828f63-efc9-4075-81b1-380694b396e0)

**Comment by strawberrymelonpanda** [comment]
> Essentially what you're asking for is for the webui extension features to be implemented upstream in ComfyUI.

I have to respectfully disagree with you there.  

What I'm asking for are similar features to the plugin this one replaces, such as presets, in *this* UI's plugin implementation.

**Comment by Koitenshin** [comment]
I agree with strawberrymelonpanda.

If you've used ComfyUI lately you'll notice it has both v1 & v2 FreeU nodes. Forge only has v2. I'm not sure about anyone else, but v2 crashes my local copy of Forge & A1111 while v1 on A1111 from the real extension simply works.
