### ISSUE TITLE
[Bug]: Setting A1111_HOME path in webui-user.bat file does not work on Ubuntu

### ISSUE THREAD

**Issue by diffusionStable** [lllyasviel/stable-diffusion-webui-forge#355]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Using ForgeUI on my Ubuntu os and trying to set the A1111_HOME path in webui-user.bat file, the models/ loras etc. do no not load from my A1111 directory. However I know this works using windows. 

### Steps to reproduce the problem

1. Using Ubuntu 22.04.4, navigate to ForgeUI webui directory
2. Open webui-user.bat file with text editor
3. Uncomment "@REM" from line 9, 11 and 12
4. At line 9, set  A1111_HOME path to : yourA1111path/A1111/stable-diffusion-webui/
5. Save File
6. Start ForgeUI
7. Check to see if models have been loaded from A1111 directory

### What should have happened?

The models, loras, vae's etc. should have loaded from the A1111 A1111/stable-diffusion-webui/ directory

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

..

### Console logs

```Shell
no console logs
```

**Comment by huchenlei** [comment]
See https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/206, we now have an easier way to reference existing A1111 checkout.

**Comment by diffusionStable** [comment]
Thank you 🙏️
