### ISSUE TITLE
[Feature Request]: SVD frames saving with metadata

### ISSUE THREAD

**Issue by sireneloreley** [lllyasviel/stable-diffusion-webui-forge#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Hello! Would be great if SVD extension could auto-save all the generated frames (not only video) and write some metadata in them. Sould be a nice feature <3 Thank you for Forge!

### Proposed workflow

1. Go to SVD and generate a video
2. a folder in outputs/svd with frames in png format and metadata stored appears

**Comment by DenOfEquity** [comment]
Closed due to age; lack of relevance to Forge2.
