### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kenneth55555** [lllyasviel/stable-diffusion-webui-forge#364]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

In the original webui, this issue does not seem to occur; however, when both the face-editor and https://github.com/Akegarasu/sd-webui-model-converter plugins are enabled in https://github.com/lllyasviel/stable-diffusion-webui-forge, the face-editor reports an error: ModuleNotFoundError: No module named 'scripts.ui.ui_builder'; 'scripts.ui' is not a package. Not being familiar with webui-forge myself, kindly investigate whether there might be a flaw in webui-forge's plugin isolation mechanism that leads to this problem. This issue has also been concurrently reported at https://github.com/ototadana/sd-face-editor/issues/189. 

### Steps to reproduce the problem

None

### What should have happened?

None

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

have no use for

### Console logs

```Shell
have no use for
```

**Comment by DenOfEquity** [comment]
Seems to be fixed by update to face-editor extension.
