### ISSUE TITLE
[Bug]: Hashes of Loras not displayed in infotext

### ISSUE THREAD

**Issue by neojam** [lllyasviel/stable-diffusion-webui-forge#372]
### Checklist

- [X] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Hallo,

i have checked the both checkboxes "Add Lora hashes to infotext" and "Add Textual Inversion hashes to infotext" under settings, but no LORA hashes are displayed when generating images. Only TI hashes are displayed.

Settings are in the config:
config.json
    "textual_inversion_add_hashes_to_infotext": true,
    "lora_add_hashes_to_infotext": true,

### Steps to reproduce the problem

1 go to settings
2 check "Add Lora hashes to infotext" and "Add Textual Inversion hashes to infotext"
3 generate an image with lora or TI
4 no Lora or hashes are displayed in Infotext

### What should have happened?

Lora hashes should be displayed in Infotext.

(and also saved to images metadata, if "Write infotext to metadata of the generated image" is enabled)

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

cant ATM

### Console logs

```Shell
no errors
```

**Comment by bishtybro** [comment]
bro i cannot even load lora. I have placed lora file in he correct folder and i am also using correct sd version that is compatible with lora. still loras dont show up in web ui. i have restarted the webui and also changed browsers ,but i get same results.
![Screenshot 2024-02-24 053427](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/127284447/ed6c070f-6cfd-4c7c-b0d3-acd048048ea1)

**Comment by QlipK** [comment]
Same thing for me... Up
It is since I have updated my ForgeUI SD
