### ISSUE TITLE
[Bug]: AnimateDiff not working in SD Forge

### ISSUE THREAD

**Issue by XmartySS** [lllyasviel/stable-diffusion-webui-forge#434]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I am getting errors; all the gifs are created as only GIFs of a batch of images. They are not consistent or smooth Frame interpolation between them. I tried to reinstall the extension many times but still not working.

![00029-3296264830](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/129748474/2616ed92-2ae9-4b80-8a56-aa2280cd3b4b)

### Steps to reproduce the problem

1. Prompt: A girl ( Also used ControlNet but still don't have a consistent gif )

2. Enable AnimateDiff

3. Using Settings

MM: mm_sd_v15_v2.ckpt
no. of frames: 14
FPS: 8

4. Press Generate.

### What should have happened?

GIF should be a batch of consistent images.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-02-27-23-00.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14426538/sysinfo-2024-02-27-23-00.json)

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.9-latest-51-g5bea443d
Commit hash: 5bea443d94f3a85f819cb8541c1bba0aac208d83
Launching Web UI with arguments:
Total VRAM 4096 MB, total RAM 28524 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --always-normal-vram
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
ControlNet preprocessor location: C:\SD\Stable Diffusion WebUI Forge\webui\models\ControlNetPreprocessor
Loading weights [15012c538f] from C:\SD\Stable Diffusion WebUI Forge\webui\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors
2024-02-28 04:31:34,316 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860
model_type EPS
UNet ADM Dimension 0

To create a public link, set `share=True` in `launch()`.
Startup time: 9.5s (prepare environment: 2.3s, import torch: 3.0s, import gradio: 0.8s, setup paths: 0.7s, other imports: 0.6s, load scripts: 1.1s, create ui: 0.6s, gradio launch: 0.3s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
To load target model SD1ClipModel
Begin to load 1 model
Model loaded in 3.1s (load weights from disk: 0.7s, forge load real models: 1.7s, calculate empty prompt: 0.7s).
2024-02-28 04:32:49,574 - AnimateDiff - INFO - AnimateDiff process start.
2024-02-28 04:32:49,574 - AnimateDiff - INFO - Loading motion module mm_sd_v15_v2.ckpt from C:\SD\Stable Diffusion WebUI Forge\webui\extensions\sd-webui-animatediff\model\mm_sd_v15_v2.ckpt
2024-02-28 04:32:50,238 - AnimateDiff - INFO - Guessed mm_sd_v15_v2.ckpt architecture: MotionModuleType.AnimateDiffV2
2024-02-28 04:32:50,492 - AnimateDiff - WARNING - Missing keys <All keys matched successfully>
2024-02-28 04:32:50,522 - AnimateDiff - INFO - Setting DDIM alpha.
2024-02-28 04:32:51,018 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet.
*** Error running process_before_every_sampling: C:\SD\Stable Diffusion WebUI Forge\webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\SD\Stable Diffusion WebUI Forge\webui\modules\scripts.py", line 830, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "C:\SD\Stable Diffusion WebUI Forge\webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 74, in process_before_every_sampling
        motion_module.inject(p.sd_model, params.model)
      File "C:\SD\Stable Diffusion WebUI Forge\webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 125, in inject
        unet.set_controlnet_model_function_wrapper(mm_cn_forward)
    AttributeError: 'UnetPatcher' object has no attribute 'set_controlnet_model_function_wrapper'

---
To load target model BaseModel
Begin to load 1 model
Moving model(s) has taken 0.46 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:53<00:00,  2.67s/it]
To load target model AutoencoderKL█████████████████████████████████████████████████████| 20/20 [00:50<00:00,  2.64s/it]
Begin to load 1 model
2024-02-28 04:33:50,994 - AnimateDiff - INFO - Merging images into GIF.
2024-02-28 04:33:53,586 - AnimateDiff - INFO - AnimateDiff process end.
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [01:00<00:00,  3.01s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [01:00<00:00,  2.64s/it]
```

**Comment by TheRealPhooney** [comment]
There is a branch of the AnimateDiff extension especially for Forge:

https://github.com/continue-revolution/sd-forge-animatediff

**Comment by XmartySS** [comment]
> There is a branch of the AnimateDiff extension especially for Forge:
> 
> https://github.com/continue-revolution/sd-forge-animatediff

Yes i know that, i am using Forge version of AnimateDiff.

I am following this message by continue-revolution

https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/330#issuecomment-1962275654

I already tried webui version but that was not even creating any images. So it is the Forge version i shared the issue. Sorry for my bad english.

**Comment by XmartySS** [comment]
> i am using Forge version of AnimateDiff.This situation has also occurred ![00007-1849231418](https://private-user-images.githubusercontent.com/74442467/308467374-368f5206-1cdc-4069-94b8-f7ca71ed97a2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDc2NzYsIm5iZiI6MTcwOTEwNzM3NiwicGF0aCI6Ii83NDQ0MjQ2Ny8zMDg0NjczNzQtMzY4ZjUyMDYtMWNkYy00MDY5LTk0YjgtZjdjYTcxZWQ5N2EyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA4MDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNGFhZjU2OWVjZjgxOGY2MTIwMzczNmVlZjU5M2ViNjVmZjM5ZDdiN2Q5YTVjMDYxNTc5NmFhZTMwNjU4MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bI3hz2IaVmqzrqF5pR8hwUlW9XWiLlu4K4mMHrSyY3Y) [ ![00007-1849231418](https://private-user-images.githubusercontent.com/74442467/308467374-368f5206-1cdc-4069-94b8-f7ca71ed97a2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDc2NzYsIm5iZiI6MTcwOTEwNzM3NiwicGF0aCI6Ii83NDQ0MjQ2Ny8zMDg0NjczNzQtMzY4ZjUyMDYtMWNkYy00MDY5LTk0YjgtZjdjYTcxZWQ5N2EyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA4MDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNGFhZjU2OWVjZjgxOGY2MTIwMzczNmVlZjU5M2ViNjVmZjM5ZDdiN2Q5YTVjMDYxNTc5NmFhZTMwNjU4MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bI3hz2IaVmqzrqF5pR8hwUlW9XWiLlu4K4mMHrSyY3Y) ](https://private-user-images.githubusercontent.com/74442467/308467374-368f5206-1cdc-4069-94b8-f7ca71ed97a2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDc2NzYsIm5iZiI6MTcwOTEwNzM3NiwicGF0aCI6Ii83NDQ0MjQ2Ny8zMDg0NjczNzQtMzY4ZjUyMDYtMWNkYy00MDY5LTk0YjgtZjdjYTcxZWQ5N2EyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA4MDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNGFhZjU2OWVjZjgxOGY2MTIwMzczNmVlZjU5M2ViNjVmZjM5ZDdiN2Q5YTVjMDYxNTc5NmFhZTMwNjU4MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bI3hz2IaVmqzrqF5pR8hwUlW9XWiLlu4K4mMHrSyY3Y) [ ](https://private-user-images.githubusercontent.com/74442467/308467374-368f5206-1cdc-4069-94b8-f7ca71ed97a2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDc2NzYsIm5iZiI6MTcwOTEwNzM3NiwicGF0aCI6Ii83NDQ0MjQ2Ny8zMDg0NjczNzQtMzY4ZjUyMDYtMWNkYy00MDY5LTk0YjgtZjdjYTcxZWQ5N2EyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA4MDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNGFhZjU2OWVjZjgxOGY2MTIwMzczNmVlZjU5M2ViNjVmZjM5ZDdiN2Q5YTVjMDYxNTc5NmFhZTMwNjU4MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bI3hz2IaVmqzrqF5pR8hwUlW9XWiLlu4K4mMHrSyY3Y) After adjusting the settings, it will be fine, but the effect is not as good as SVD ![00013-274043634](https://private-user-images.githubusercontent.com/74442467/308467741-15c4702d-4f2e-429a-ada5-d92db5c759f8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDc2NzYsIm5iZiI6MTcwOTEwNzM3NiwicGF0aCI6Ii83NDQ0MjQ2Ny8zMDg0Njc3NDEtMTVjNDcwMmQtNGYyZS00MjlhLWFkYTUtZDkyZGI1Yzc1OWY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA4MDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NDVlMDMyMTJmMjY2ZWYzZTM4ODQ2Zjc3YThjYjAyMjQ4NGYyZmNhYWU2MmY4MzE2ZTc0MmIyZWRiZDg3NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LhX73r3BAfJCgexEvo4uWXLD8yDxMTztckHGMjBpshY) [ ![00013-274043634](https://private-user-images.githubusercontent.com/74442467/308467741-15c4702d-4f2e-429a-ada5-d92db5c759f8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDc2NzYsIm5iZiI6MTcwOTEwNzM3NiwicGF0aCI6Ii83NDQ0MjQ2Ny8zMDg0Njc3NDEtMTVjNDcwMmQtNGYyZS00MjlhLWFkYTUtZDkyZGI1Yzc1OWY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA4MDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NDVlMDMyMTJmMjY2ZWYzZTM4ODQ2Zjc3YThjYjAyMjQ4NGYyZmNhYWU2MmY4MzE2ZTc0MmIyZWRiZDg3NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LhX73r3BAfJCgexEvo4uWXLD8yDxMTztckHGMjBpshY) ](https://private-user-images.githubusercontent.com/74442467/308467741-15c4702d-4f2e-429a-ada5-d92db5c759f8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDc2NzYsIm5iZiI6MTcwOTEwNzM3NiwicGF0aCI6Ii83NDQ0MjQ2Ny8zMDg0Njc3NDEtMTVjNDcwMmQtNGYyZS00MjlhLWFkYTUtZDkyZGI1Yzc1OWY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA4MDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NDVlMDMyMTJmMjY2ZWYzZTM4ODQ2Zjc3YThjYjAyMjQ4NGYyZmNhYWU2MmY4MzE2ZTc0MmIyZWRiZDg3NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LhX73r3BAfJCgexEvo4uWXLD8yDxMTztckHGMjBpshY) [ ](https://private-user-images.githubusercontent.com/74442467/308467741-15c4702d-4f2e-429a-ada5-d92db5c759f8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDc2NzYsIm5iZiI6MTcwOTEwNzM3NiwicGF0aCI6Ii83NDQ0MjQ2Ny8zMDg0Njc3NDEtMTVjNDcwMmQtNGYyZS00MjlhLWFkYTUtZDkyZGI1Yzc1OWY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA4MDI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NDVlMDMyMTJmMjY2ZWYzZTM4ODQ2Zjc3YThjYjAyMjQ4NGYyZmNhYWU2MmY4MzE2ZTc0MmIyZWRiZDg3NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LhX73r3BAfJCgexEvo4uWXLD8yDxMTztckHGMjBpshY) You need to tell AnimateDiff what you want to do, such as zooming in and out of the camera

Thank you for your reply. I am sorry i am new to it. If you can help me to produce like your result. I tried everything but not able to have result like this. Even nothing is working like if i am uploading video. AnimateDiff not taking reference from it and just creating random images.

**Comment by newxhy** [comment]
The Chinese interface I am using, I hope you can understand it.I hope I can help you.
![微信截图_20240228192126](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/74442467/c15af256-c084-4200-8b98-883742410b11)

1 girl in a blue dress,Shopping in the supermarket,She walked from far to near,Lens zoomed in from far,
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 3114735162, Size: 512x512, Model hash: 15012c538f, Model: realisticVisionV51_v51VAE, AnimateDiff: "model: mm_sd_v15_v2.ckpt, video_length: 24, fps: 8, loop_number: 0, closed_loop: N, batch_size: 16, stride: 1, overlap: 4, interp: Off, interp_x: 10, mm_hash: 69ed0f5f, version: v2.0.0-f-2-gc25a46d", Version: f0.0.16v1.8.0rc-latest-268-gb59deaa38

用时:2 min. 40.3 sec.

A: 3.55 GB, R: 3.85 GB, Sys: 5.0/7.99609 GB (62.3%)

https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/74442467/ed6e5da3-b2e5-465b-94ba-5bbab381afa6

**Comment by TheRealPhooney** [comment]
> > There is a branch of the AnimateDiff extension especially for Forge:
> > https://github.com/continue-revolution/sd-forge-animatediff
> 
> Yes i know that, i am using Forge version of AnimateDiff.
> 
> I am following this message by continue-revolution
> 
> [#330 (comment)](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/330#issuecomment-1962275654)
> 
> I already tried webui version but that was not even creating any images. So it is the Forge version i shared the issue. Sorry for my bad english.

Ah, sorry.

I just got a similar result to you, but my error came from trying to use AnimateDiff with a SDXL checkpoint.  By any chance is that what you were doing?  If so, try a SD1.5 model.

I don't think it has anything to do with needing to mention a zoom in our out etc.

**Comment by XmartySS** [comment]
> The Chinese interface I am using, I hope you can understand it.I hope I can help you. ![微信截图_20240228192126](https://private-user-images.githubusercontent.com/74442467/308529029-c15af256-c084-4200-8b98-883742410b11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxODYxODgsIm5iZiI6MTcwOTE4NTg4OCwicGF0aCI6Ii83NDQ0MjQ2Ny8zMDg1MjkwMjktYzE1YWYyNTYtYzA4NC00MjAwLThiOTgtODgzNzQyNDEwYjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA1NTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZWUzZjgyMzAzYTAzNjhlZWFjNmI5M2E0NTkyMGQ3MTg0MDJmOTllZmFhMGE0OWE4NzY4NDRjN2YyYjUxNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.um1e-HCB8cnwK4zJh34Y4yeeUO61W25uU1UerY-v3iQ)
> 
> 1 girl in a blue dress,Shopping in the supermarket,She walked from far to near,Lens zoomed in from far, Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 3114735162, Size: 512x512, Model hash: 15012c538f, Model: realisticVisionV51_v51VAE, AnimateDiff: "model: mm_sd_v15_v2.ckpt, video_length: 24, fps: 8, loop_number: 0, closed_loop: N, batch_size: 16, stride: 1, overlap: 4, interp: Off, interp_x: 10, mm_hash: 69ed0f5f, version: v2.0.0-f-2-gc25a46d", Version: f0.0.16v1.8.0rc-latest-268-gb59deaa38
> 
> 用时:2 min. 40.3 sec.
> 
> A: 3.55 GB, R: 3.85 GB, Sys: 5.0/7.99609 GB (62.3%)
> 
>  00016-3114735162.mp4

Thank you Newxhy, i will definitely try that out :)

**Comment by XmartySS** [comment]
> > > There is a branch of the AnimateDiff extension especially for Forge:
> > > https://github.com/continue-revolution/sd-forge-animatediff
> > 
> > 
> > Yes i know that, i am using Forge version of AnimateDiff.
> > I am following this message by continue-revolution
> > [#330 (comment)](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/330#issuecomment-1962275654)
> > I already tried webui version but that was not even creating any images. So it is the Forge version i shared the issue. Sorry for my bad english.
> 
> Ah, sorry.
> 
> I just got a similar result to you, but my error came from trying to use AnimateDiff with a SDXL checkpoint. By any chance is that what you were doing? If so, try a SD1.5 model.
> 
> I don't think it has anything to do with needing to mention a zoom in our out etc.

Thank you so much for reply :), But i never used any SDXL model. I am using only SD 1.5 models. And with all models i am getting this result only.

**Comment by newxhy** [comment]
https://github.com/continue-revolution/sd-forge-animatediff/blob/forge-master/docs/features.md#prompt-travel
Give it a try. Actually, your problem is not with Forge, but with the use of Animatediff

**Comment by XmartySS** [comment]
> https://github.com/continue-revolution/sd-forge-animatediff/blob/forge-master/docs/features.md#prompt-travel Give it a try. Actually, your problem is not with Forge, but with the use of Animatediff

Thank you so much , i will try that out :)

**Comment by XmartySS** [comment]
Sorry i marked as completed by mistake.

**Comment by newxhy** [comment]
> 抱歉，我错误地标记为已完成。

It should have been completed, because this issue is actually a usage issue with animatediff

**Comment by drewb583** [comment]
I'm getting the same issue, not sure how to not get this problem.
