### ISSUE TITLE
[Feature Request]: Let model to be kept on VRAM to not lose performance moving the model.

### ISSUE THREAD

**Issue by Panchovix** [lllyasviel/stable-diffusion-webui-forge#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Thanks for the new UI!

I'm wondering if it was possible to add an option to keep the model all times in VRAM. Tried disabling the option "Only keep one model on device" but it still loads-unloads the model for every stage.

I have a 4090, using Windows and:

* python: 3.11.6
* torch: 2.3.0.dev20240102+cu121
* xformers: 0.0.24+042abc8.d20240102

And SDXL. Using the same settings and venv that on a1111.

Generation itself seems to be a bit faster, but for total time, it seems to take about 15-20% more time to do the same task, and it seems to be related to the model being loaded first into RAM, then into VRAM, then into RAM, etc.

So if using normal txt2img + hires fix + adetailer, the model does this 3 times. For that workflow specifically, it takes an extra 4.59 seconds moving the model, for a image gen on SDXL at 896x1088, 1.3 upscale with ESRGAN and adetailer for the face.

```
CD Tuner Effective : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0, 0]
To load target model SDXLClipModel
Begin to load 1 model
unload clone 2
Moving model(s) has taken 0.71 seconds
To load target model SDXL
Begin to load 1 model
unload clone 2
Moving model(s) has taken 1.32 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  7.56it/s]
Upscale script freed memory successfully.███████████████████████████████████████▍    | 130/140 [01:29<00:01,  7.66it/s]
tiled upscale: 100%|███████████████████████████████████████████████████████████████████| 30/30 [00:01<00:00, 22.05it/s]
To load target model SDXL
Begin to load 1 model
unload clone 1
Moving model(s) has taken 0.90 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.33it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████| 140/140 [01:36<00:00,  2.12it/s]
0: 640x544 1 face, 8.5ms
Speed: 2.0ms preprocess, 8.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 544)
To load target model SDXLClipModel
Begin to load 1 model
unload clone 2
Moving model(s) has taken 0.73 seconds
To load target model SDXL
Begin to load 1 model
unload clone 2
Moving model(s) has taken 0.93 seconds
```

### Proposed workflow

1. Go to Settings
2. Search option to keep always the model in VRAM
3. Enable it
4. Keep model all times into VRAM.

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/stable-diffusion-webui-forge?tab=readme-ov-file#forge-backend

try --always-gpu for 4090

**Comment by Panchovix** [comment]
Perfect, that did work. Thanks!
