### ISSUE TITLE
[Bug]: Disabling SVD causes Errors

### ISSUE THREAD

**Issue by Haoming02** [lllyasviel/stable-diffusion-webui-forge#49]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

If `sd_forge_svd` is disabled, the Webui will **not** launch

### Steps to reproduce the problem

1. Go to **Extensions** tab
2. Scroll down and find `sd_forge_svd`
3. Untick the enable checkbox
4. **Apply and restart UI**
5. See the errors below
6. `Press any key to continue . . .`
7. Console is then closed with no UI shown

### What should have happened?

Simply removes the **SVD** tab

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

{
    "Platform": "Windows-10-10.0.22621-SP0",
    "Python": "3.10.10",
    "Version": "f0.0.6-latest-39-g1ecbff15",
    "Commit": "1ecbff15fa6893c68875cdc2d2f60ca5cc9c0343",
    "Script path": "C:\\Users\\Michael.C\\Documents\\GitHub\\stable-diffusion-webui-forge",
    "Data path": "C:\\Users\\Michael.C\\Documents\\GitHub\\stable-diffusion-webui-forge",
    "Extensions dir": "C:\\Users\\Michael.C\\Documents\\GitHub\\stable-diffusion-webui-forge\\extensions",
    "Checksum": "f848aa1c4dffacecb3ff5b90594681c28e280181b179b60f849e1ae4e45b3164",
    "Commandline": [
        "launch.py",
        "--xformers"
    ],
    "Torch env info": {
        "torch_version": "2.1.2+cu121",
        "is_debug_build": "False",
        "cuda_compiled_version": "12.1",
        "gcc_version": null,
        "clang_version": null,
        "cmake_version": "version 3.26.0-rc6",
        "os": "Microsoft Windows 11 Pro",
        "libc_version": "N/A",
        "python_version": "3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)",
        "python_platform": "Windows-10-10.0.22621-SP0",
        "is_cuda_available": "True",
        "cuda_runtime_version": "11.8.89\r",
        "cuda_module_loading": "LAZY",
        "nvidia_driver_version": "546.01",
        "nvidia_gpu_models": "GPU 0: NVIDIA GeForce RTX 3060",
        "cudnn_version": null,
        "pip_version": "pip3",
        "pip_packages": [
            "numpy==1.26.2",
            "open-clip-torch==2.20.0",
            "pytorch-lightning==1.9.4",
            "torch==2.1.2+cu121",
            "torchdiffeq==0.2.3",
            "torchmetrics==1.3.0.post0",
            "torchsde==0.2.6",
            "torchvision==0.16.2+cu121",
            "triton==2.1.0"
        ],
        "conda_packages": null,
        "hip_compiled_version": "N/A",
        "hip_runtime_version": "N/A",
        "miopen_runtime_version": "N/A",
        "caching_allocator_config": "",
        "is_xnnpack_available": "True",
        "cpu_info": [
            "Architecture=9",
            "CurrentClockSpeed=2100",
            "DeviceID=CPU0",
            "Family=198",
            "L2CacheSize=24576",
            "L2CacheSpeed=",
            "Manufacturer=GenuineIntel",
            "MaxClockSpeed=2100",
            "Name=13th Gen Intel(R) Core(TM) i7-13700",
            "ProcessorType=3",
            "Revision="
        ]
    },
    "Exceptions": [],
    "CPU": {
        "model": "Intel64 Family 6 Model 183 Stepping 1, GenuineIntel",
        "count logical": 24,
        "count physical": 16
    },
    "RAM": {
        "total": "32GB",
        "used": "15GB",
        "free": "17GB"
    },
    "Extensions": [
        {
            "name": "Catppuccin",
            "path": "C:\\Users\\Michael.C\\Documents\\GitHub\\stable-diffusion-webui-forge\\extensions\\Catppuccin",
            "version": "6f1eebbe",
            "branch": "main",
            "remote": "https://github.com/catppuccin/stable-diffusion-webui"
        },
        {
            "name": "sd-webui-memory-release",
            "path": "C:\\Users\\Michael.C\\Documents\\GitHub\\stable-diffusion-webui-forge\\extensions\\sd-webui-memory-release",
            "version": "bca5ccce",
            "branch": "main",
            "remote": "https://github.com/Haoming02/sd-webui-memory-release"
        },
        {
            "name": "sd-webui-prompt-format",
            "path": "C:\\Users\\Michael.C\\Documents\\GitHub\\stable-diffusion-webui-forge\\extensions\\sd-webui-prompt-format",
            "version": "b7b9c07c",
            "branch": "main",
            "remote": "https://github.com/Haoming02/sd-webui-prompt-format"
        },
        {
            "name": "sd-webui-tabs-extension",
            "path": "C:\\Users\\Michael.C\\Documents\\GitHub\\stable-diffusion-webui-forge\\extensions\\sd-webui-tabs-extension",
            "version": "7cb72eea",
            "branch": "main",
            "remote": "https://github.com/Haoming02/sd-webui-tabs-extension"
        }
    ],
    "Inactive extensions": [],
    "Environment": {
        "COMMANDLINE_ARGS": " --xformers",
        "GRADIO_ANALYTICS_ENABLED": "False"
    },
    "Config": {
        "ldsr_steps": 100,
        "ldsr_cached": false,
        "SCUNET_tile": 256,
        "SCUNET_tile_overlap": 8,
        "SWIN_tile": 192,
        "SWIN_tile_overlap": 8,
        "SWIN_torch_compile": false,
        "control_net_detectedmap_dir": "detected_maps",
        "control_net_models_path": "",
        "control_net_modules_path": "",
        "control_net_unit_count": 3,
        "control_net_model_cache_size": 5,
        "control_net_no_detectmap": false,
        "control_net_detectmap_autosaving": false,
        "control_net_allow_script_control": false,
        "control_net_sync_field_args": true,
        "controlnet_show_batch_images_in_ui": false,
        "controlnet_increment_seed_during_batch": false,
        "controlnet_disable_openpose_edit": false,
        "controlnet_disable_photopea_edit": false,
        "controlnet_photopea_warning": true,
        "controlnet_input_thumbnail": true,
        "sd_model_checkpoint": "animagineXLV3_v30.safetensors",
        "sd_checkpoint_hash": "1449e5b0b9de87b0f414c5f29cb11ce3b3dc61fa2b320e784c9441720bf7b766",
        "outdir_samples": "",
        "outdir_txt2img_samples": "output\\txt2img-images",
        "outdir_img2img_samples": "output\\img2img-images",
        "outdir_extras_samples": "output\\extras-images",
        "outdir_grids": "",
        "outdir_txt2img_grids": "output\\txt2img-grids",
        "outdir_img2img_grids": "output\\img2img-grids",
        "outdir_save": "log\\images",
        "outdir_init_images": "output\\init-images",
        "samples_save": true,
        "samples_format": "png",
        "samples_filename_pattern": "",
        "save_images_add_number": true,
        "save_images_replace_action": "Replace",
        "grid_save": true,
        "grid_format": "png",
        "grid_extended_filename": false,
        "grid_only_if_multiple": true,
        "grid_prevent_empty_spots": false,
        "grid_zip_filename_pattern": "",
        "n_rows": -1,
        "font": "",
        "grid_text_active_color": "#000000",
        "grid_text_inactive_color": "#999999",
        "grid_background_color": "#ffffff",
        "save_images_before_face_restoration": false,
        "save_images_before_highres_fix": false,
        "save_images_before_color_correction": false,
        "save_mask": false,
        "save_mask_composite": false,
        "jpeg_quality": 80,
        "webp_lossless": false,
        "export_for_4chan": true,
        "img_downscale_threshold": 4.0,
        "target_side_length": 4000.0,
        "img_max_size_mp": 200.0,
        "use_original_name_batch": true,
        "use_upscaler_name_as_suffix": false,
        "save_selected_only": true,
        "save_init_img": false,
        "temp_dir": "",
        "clean_temp_dir_at_start": false,
        "save_incomplete_images": false,
        "notification_audio": true,
        "notification_volume": 100,
        "save_to_dirs": true,
        "grid_save_to_dirs": true,
        "use_save_to_dirs_for_ui": false,
        "directories_filename_pattern": "[date]",
        "directories_max_prompt_words": 8,
        "auto_backcompat": true,
        "use_old_emphasis_implementation": false,
        "use_old_karras_scheduler_sigmas": false,
        "no_dpmpp_sde_batch_determinism": false,
        "use_old_hires_fix_width_height": false,
        "dont_fix_second_order_samplers_schedule": false,
        "hires_fix_use_firstpass_conds": false,
        "use_old_scheduling": false,
        "use_downcasted_alpha_bar": false,
        "lora_functional": false,
        "extra_networks_show_hidden_directories": true,
        "extra_networks_dir_button_function": false,
        "extra_networks_hidden_models": "When searched",
        "extra_networks_default_multiplier": 1,
        "extra_networks_card_width": 0.0,
        "extra_networks_card_height": 0.0,
        "extra_networks_card_text_scale": 1,
        "extra_networks_card_show_desc": true,
        "extra_networks_card_order_field": "Path",
        "extra_networks_card_order": "Ascending",
        "extra_networks_tree_view_default_enabled": false,
        "extra_networks_add_text_separator": " ",
        "ui_extra_networks_tab_reorder": "",
        "textual_inversion_print_at_load": false,
        "textual_inversion_add_hashes_to_infotext": true,
        "sd_hypernetwork": "None",
        "sd_lora": "None",
        "lora_preferred_name": "Alias from file",
        "lora_add_hashes_to_infotext": true,
        "lora_show_all": false,
        "lora_hide_unknown_for_versions": [],
        "lora_in_memory_limit": 0,
        "lora_not_found_warning_console": false,
        "lora_not_found_gradio_warning": false,
        "cross_attention_optimization": "xformers",
        "s_min_uncond": 0,
        "token_merging_ratio": 0,
        "token_merging_ratio_img2img": 0,
        "token_merging_ratio_hr": 0,
        "pad_cond_uncond": true,
        "pad_cond_uncond_v0": false,
        "persistent_cond_cache": true,
        "batch_cond_uncond": true,
        "fp8_storage": "Disable",
        "cache_fp16_weight": false,
        "hide_samplers": [],
        "eta_ddim": 0,
        "eta_ancestral": 1,
        "ddim_discretize": "uniform",
        "s_churn": 0,
        "s_tmin": 0,
        "s_tmax": 0,
        "s_noise": 1,
        "k_sched_type": "Automatic",
        "sigma_min": 0.0,
        "sigma_max": 0.0,
        "rho": 0.0,
        "eta_noise_seed_delta": 0,
        "always_discard_next_to_last_sigma": false,
        "sgm_noise_multiplier": false,
        "uni_pc_variant": "bh1",
        "uni_pc_skip_type": "time_uniform",
        "uni_pc_order": 3,
        "uni_pc_lower_order_final": true,
        "sd_noise_schedule": "Default",
        "sd_checkpoints_limit": 1,
        "sd_checkpoints_keep_in_cpu": true,
        "sd_checkpoint_cache": 0,
        "sd_unet": "Automatic",
        "enable_quantization": false,
        "enable_emphasis": true,
        "enable_batch_seeds": true,
        "comma_padding_backtrack": 20,
        "upcast_attn": false,
        "randn_source": "CPU",
        "tiling": false,
        "hires_fix_refiner_pass": "second pass",
        "sdxl_crop_top": 0.0,
        "sdxl_crop_left": 0.0,
        "sdxl_refiner_low_aesthetic_score": 2.5,
        "sdxl_refiner_high_aesthetic_score": 6.0,
        "sd_vae_checkpoint_cache": 0,
        "sd_vae_overrides_per_model_preferences": true,
        "auto_vae_precision_bfloat16": false,
        "auto_vae_precision": true,
        "sd_vae_encode_method": "Full",
        "sd_vae_decode_method": "Full",
        "inpainting_mask_weight": 1,
        "initial_noise_multiplier": 1,
        "img2img_extra_noise": 0,
        "img2img_color_correction": false,
        "img2img_fix_steps": false,
        "img2img_background_color": "#ffffff",
        "img2img_editor_height": 720,
        "img2img_sketch_default_brush_color": "#ffffff",
        "img2img_inpaint_mask_brush_color": "#ffffff",
        "img2img_inpaint_sketch_default_brush_color": "#ffffff",
        "return_mask": false,
        "return_mask_composite": false,
        "img2img_batch_show_results_limit": 32,
        "overlay_inpaint": true,
        "return_grid": true,
        "do_not_show_images": false,
        "js_modal_lightbox": true,
        "js_modal_lightbox_initially_zoomed": true,
        "js_modal_lightbox_gamepad": false,
        "js_modal_lightbox_gamepad_repeat": 250.0,
        "sd_webui_modal_lightbox_icon_opacity": 1,
        "sd_webui_modal_lightbox_toolbar_opacity": 0.9,
        "gallery_height": "",
        "enable_pnginfo": true,
        "save_txt": false,
        "add_model_name_to_info": true,
        "add_model_hash_to_info": true,
        "add_vae_name_to_info": true,
        "add_vae_hash_to_info": true,
        "add_user_name_to_info": false,
        "add_version_to_infotext": true,
        "disable_weights_auto_swap": true,
        "infotext_skip_pasting": [],
        "infotext_styles": "Apply if any",
        "show_progressbar": true,
        "live_previews_enable": true,
        "live_previews_image_format": "jpeg",
        "show_progress_grid": true,
        "show_progress_every_n_steps": 4,
        "show_progress_type": "TAESD",
        "live_preview_allow_lowvram_full": false,
        "live_preview_content": "Combined",
        "live_preview_refresh_period": 1000.0,
        "live_preview_fast_interrupt": true,
        "js_live_preview_in_modal_lightbox": false,
        "keyedit_precision_attention": 0.1,
        "keyedit_precision_extra": 0.05,
        "keyedit_delimiters": ".,\\/!?%^*;:{}=`~() ",
        "keyedit_delimiters_whitespace": [
            "Tab",
            "Carriage Return",
            "Line Feed"
        ],
        "keyedit_move": true,
        "disable_token_counters": false,
        "extra_options_txt2img": [],
        "extra_options_img2img": [],
        "extra_options_cols": 1,
        "extra_options_accordion": false,
        "compact_prompt_box": false,
        "samplers_in_dropdown": true,
        "dimensions_and_batch_together": true,
        "sd_checkpoint_dropdown_use_short": false,
        "hires_fix_show_sampler": false,
        "hires_fix_show_prompts": false,
        "txt2img_settings_accordion": false,
        "img2img_settings_accordion": false,
        "interrupt_after_current": true,
        "localization": "None",
        "quicksettings_list": [
            "sd_model_checkpoint",
            "sd_vae",
            "CLIP_stop_at_last_layers"
        ],
        "ui_tab_order": [],
        "hidden_tabs": [],
        "ui_reorder_list": [],
        "gradio_theme": "Default",
        "gradio_themes_cache": true,
        "show_progress_in_title": true,
        "send_seed": true,
        "send_size": true,
        "api_enable_requests": true,
        "api_forbid_local_requests": true,
        "api_useragent": "",
        "auto_launch_browser": "Local",
        "enable_console_prompts": false,
        "show_warnings": false,
        "show_gradio_deprecation_warnings": true,
        "memmon_poll_rate": 8,
        "samples_log_stdout": false,
        "multiple_tqdm": true,
        "enable_upscale_progressbar": true,
        "print_hypernet_extra": false,
        "list_hidden_files": true,
        "disable_mmap_load_safetensors": false,
        "hide_ldm_prints": true,
        "dump_stacks_on_signal": false,
        "face_restoration": false,
        "face_restoration_model": "CodeFormer",
        "code_former_weight": 0.5,
        "face_restoration_unload": false,
        "postprocessing_enable_in_main_ui": [],
        "postprocessing_operation_order": [],
        "upscaling_max_images_in_cache": 5,
        "postprocessing_existing_caption_action": "Ignore",
        "ESRGAN_tile": 192,
        "ESRGAN_tile_overlap": 8,
        "realesrgan_enabled_models": [
            "R-ESRGAN 4x+",
            "R-ESRGAN 4x+ Anime6B"
        ],
        "dat_enabled_models": [
            "DAT x2",
            "DAT x3",
            "DAT x4"
        ],
        "DAT_tile": 192,
        "DAT_tile_overlap": 8,
        "unload_models_when_training": false,
        "pin_memory": false,
        "save_optimizer_state": false,
        "save_training_settings_to_txt": true,
        "dataset_filename_word_regex": "",
        "dataset_filename_join_string": " ",
        "training_image_repeats_per_epoch": 1,
        "training_write_csv_every": 500.0,
        "training_xattention_optimizations": false,
        "training_enable_tensorboard": false,
        "training_tensorboard_save_images": false,
        "training_tensorboard_flush_every": 120.0,
        "canvas_hotkey_zoom": "Alt",
        "canvas_hotkey_adjust": "Ctrl",
        "canvas_hotkey_shrink_brush": "Q",
        "canvas_hotkey_grow_brush": "W",
        "canvas_hotkey_move": "F",
        "canvas_hotkey_fullscreen": "S",
        "canvas_hotkey_reset": "R",
        "canvas_hotkey_overlap": "O",
        "canvas_show_tooltip": true,
        "canvas_auto_expand": true,
        "canvas_blur_prompt": false,
        "canvas_disabled_functions": [
            "Overlap"
        ],
        "interrogate_keep_models_in_memory": false,
        "interrogate_return_ranks": false,
        "interrogate_clip_num_beams": 1,
        "interrogate_clip_min_length": 24,
        "interrogate_clip_max_length": 48,
        "interrogate_clip_dict_limit": 1500.0,
        "interrogate_clip_skip_categories": [],
        "interrogate_deepbooru_score_threshold": 0.5,
        "deepbooru_sort_alpha": true,
        "deepbooru_use_spaces": true,
        "deepbooru_escape": true,
        "deepbooru_filter_tags": "",
        "disabled_extensions": [
            "ScuNET",
            "SwinIR",
            "sd_forge_hypertile",
            "sd_forge_kohya_hrfix"
        ],
        "disable_all_extensions": "none",
        "ctp_flavor": "mocha",
        "accent_color": "maroon",
        "memre_debug": false,
        "memre_unload": false,
        "pf_disableupdateinput": false,
        "pf_startinauto": true,
        "pf_startwithdedupe": true,
        "pf_startwithrmudscr": false,
        "tabs_ex_delay": 10
    },
    "Startup": {
        "total": 7.244654893875122,
        "records": {
            "initial startup": 0.01399993896484375,
            "prepare environment/checks": 0.0050029754638671875,
            "prepare environment/git version info": 0.02999734878540039,
            "prepare environment/torch GPU test": 1.2456755638122559,
            "prepare environment/clone repositores": 0.10100388526916504,
            "prepare environment/run extensions installers/Catppuccin": 0.004999637603759766,
            "prepare environment/run extensions installers/sd-webui-memory-release": 0.0,
            "prepare environment/run extensions installers/sd-webui-prompt-format": 0.0,
            "prepare environment/run extensions installers/sd-webui-tabs-extension": 0.0,
            "prepare environment/run extensions installers": 0.004999637603759766,
            "prepare environment/run extensions_builtin installers/canvas-zoom-and-pan": 0.001041412353515625,
            "prepare environment/run extensions_builtin installers/extra-options-section": 0.0,
            "prepare environment/run extensions_builtin installers/forge_legacy_preprocessors": 0.21195769309997559,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_inpaint": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_marigold": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_normalbae": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_recolor": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_reference": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_revision": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_tile": 0.0,
            "prepare environment/run extensions_builtin installers/LDSR": 0.0,
            "prepare environment/run extensions_builtin installers/Lora": 0.0,
            "prepare environment/run extensions_builtin installers/mobile": 0.0010004043579101562,
            "prepare environment/run extensions_builtin installers/prompt-bracket-checker": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_controlllite": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_controlnet": 0.20831847190856934,
            "prepare environment/run extensions_builtin installers/sd_forge_controlnet_example": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_freeu": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_ipadapter": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_photomaker": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_sag": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_stylealign": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_svd": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_z123": 0.0,
            "prepare environment/run extensions_builtin installers/soft-inpainting": 0.0,
            "prepare environment/run extensions_builtin installers": 0.4223179817199707,
            "prepare environment": 1.8282389640808105,
            "launcher": 0.0019989013671875,
            "import torch": 2.5522780418395996,
            "import gradio": 0.5890505313873291,
            "setup paths": 0.3713691234588623,
            "import ldm": 0.0039997100830078125,
            "import sgm": 0.0,
            "initialize shared": 0.08098769187927246,
            "other imports": 0.4270145893096924,
            "opts onchange": 0.0,
            "setup SD model": 0.0,
            "setup codeformer": 0.0010018348693847656,
            "setup gfpgan": 0.005997180938720703,
            "set samplers": 0.0,
            "list extensions": 0.0030045509338378906,
            "restore config state file": 0.0,
            "list SD models": 0.0049953460693359375,
            "list localizations": 0.0009999275207519531,
            "load scripts/custom_code.py": 0.0019998550415039062,
            "load scripts/img2imgalt.py": 0.0010006427764892578,
            "load scripts/loopback.py": 0.0,
            "load scripts/outpainting_mk_2.py": 0.0,
            "load scripts/poor_mans_outpainting.py": 0.0,
            "load scripts/postprocessing_caption.py": 0.0,
            "load scripts/postprocessing_codeformer.py": 0.0,
            "load scripts/postprocessing_create_flipped_copies.py": 0.0009999275207519531,
            "load scripts/postprocessing_focal_crop.py": 0.0019996166229248047,
            "load scripts/postprocessing_gfpgan.py": 0.0,
            "load scripts/postprocessing_split_oversized.py": 0.0010001659393310547,
            "load scripts/postprocessing_upscale.py": 0.0,
            "load scripts/processing_autosized_crop.py": 0.0,
            "load scripts/prompt_matrix.py": 0.0,
            "load scripts/prompts_from_file.py": 0.0,
            "load scripts/sd_upscale.py": 0.0009999275207519531,
            "load scripts/xyz_grid.py": 0.004002094268798828,
            "load scripts/ldsr_model.py": 0.30700087547302246,
            "load scripts/lora_script.py": 0.06499671936035156,
            "load scripts/hotkey_config.py": 0.0010004043579101562,
            "load scripts/extra_options_section.py": 0.0,
            "load scripts/legacy_preprocessors.py": 0.006309032440185547,
            "load scripts/preprocessor_inpaint.py": 0.0060465335845947266,
            "load scripts/preprocessor_marigold.py": 0.0625302791595459,
            "load scripts/preprocessor_normalbae.py": 0.002997875213623047,
            "load scripts/preprocessor_recolor.py": 0.0,
            "load scripts/forge_reference.py": 0.0,
            "load scripts/preprocessor_revision.py": 0.0,
            "load scripts/preprocessor_tile.py": 0.0,
            "load scripts/forge_controllllite.py": 0.0050885677337646484,
            "load scripts/controlnet.py": 0.18680882453918457,
            "load scripts/xyz_grid_support.py": 0.0,
            "load scripts/sd_forge_controlnet_example.py": 0.0,
            "load scripts/forge_freeu.py": 0.0020782947540283203,
            "load scripts/forge_ipadapter.py": 0.004999876022338867,
            "load scripts/forge_photomaker.py": 0.0009992122650146484,
            "load scripts/forge_sag.py": 0.0010001659393310547,
            "load scripts/forge_stylealign.py": 0.0010001659393310547,
            "load scripts/forge_svd.py": 0.014906167984008789,
            "load scripts/forge_z123.py": 0.012960672378540039,
            "load scripts/soft_inpainting.py": 0.0,
            "load scripts/main.py": 0.009999275207519531,
            "load scripts/release.py": 0.01199960708618164,
            "load scripts/pf_settings.py": 0.01000070571899414,
            "load scripts/tabs_config.py": 0.0,
            "load scripts/tabsex.py": 0.010999917984008789,
            "load scripts/refiner.py": 0.0,
            "load scripts/seed.py": 0.0,
            "load scripts": 0.7357254028320312,
            "load upscalers": 0.003234386444091797,
            "refresh VAE": 0.0,
            "refresh textual inversion templates": 0.0,
            "scripts list_optimizers": 0.00099945068359375,
            "scripts list_unets": 0.0,
            "reload hypernetworks": 0.003999948501586914,
            "initialize extra networks": 0.003000020980834961,
            "scripts before_ui_callback": 0.0009999275207519531,
            "create ui": 0.3920004367828369,
            "gradio launch": 0.2329998016357422,
            "add APIs": 0.00500035285949707,
            "app_started_callback/lora_script.py": 0.0010004043579101562,
            "app_started_callback": 0.0010004043579101562
        }
    },
    "Packages": [
        "absl-py==2.1.0",
        "accelerate==0.21.0",
        "addict==2.4.0",
        "aenum==3.1.15",
        "aiofiles==23.2.1",
        "aiohttp==3.9.3",
        "aiosignal==1.3.1",
        "albumentations==1.3.1",
        "altair==5.2.0",
        "antlr4-python3-runtime==4.9.3",
        "anyio==3.7.1",
        "async-timeout==4.0.3",
        "attrs==23.2.0",
        "basicsr==1.4.2",
        "blendmodes==2022",
        "certifi==2024.2.2",
        "cffi==1.16.0",
        "chardet==5.2.0",
        "charset-normalizer==3.3.2",
        "clean-fid==0.1.35",
        "click==8.1.7",
        "clip==1.0",
        "colorama==0.4.6",
        "coloredlogs==15.0.1",
        "colorlog==6.8.2",
        "contourpy==1.2.0",
        "cssselect2==0.7.0",
        "cycler==0.12.1",
        "cython==3.0.8",
        "deprecation==2.1.0",
        "depth-anything==2024.1.22.0",
        "diffusers==0.25.0",
        "easydict==1.11",
        "einops==0.4.1",
        "embreex==2.17.7.post4",
        "exceptiongroup==1.2.0",
        "facexlib==0.3.0",
        "fastapi==0.94.0",
        "ffmpy==0.3.1",
        "filelock==3.13.1",
        "filterpy==1.4.5",
        "flatbuffers==23.5.26",
        "fonttools==4.47.2",
        "frozenlist==1.4.1",
        "fsspec==2024.2.0",
        "ftfy==6.1.3",
        "future==0.18.3",
        "fvcore==0.1.5.post20221221",
        "gitdb==4.0.11",
        "gitpython==3.1.32",
        "gradio-client==0.5.0",
        "gradio==3.41.2",
        "grpcio==1.60.1",
        "h11==0.12.0",
        "handrefinerportable==2024.1.18.0",
        "httpcore==0.15.0",
        "httpx==0.24.1",
        "huggingface-hub==0.20.3",
        "humanfriendly==10.0",
        "idna==3.6",
        "imageio==2.33.1",
        "importlib-metadata==7.0.1",
        "importlib-resources==6.1.1",
        "inflection==0.5.1",
        "insightface==0.7.3",
        "iopath==0.1.9",
        "jinja2==3.1.3",
        "joblib==1.3.2",
        "jsonmerge==1.8.0",
        "jsonschema-specifications==2023.12.1",
        "jsonschema==4.21.1",
        "kiwisolver==1.4.5",
        "kornia==0.6.7",
        "lark==1.1.2",
        "lazy-loader==0.3",
        "lightning-utilities==0.10.1",
        "llvmlite==0.42.0",
        "lmdb==1.4.1",
        "lxml==5.1.0",
        "mapbox-earcut==1.0.1",
        "markdown==3.5.2",
        "markupsafe==2.1.5",
        "matplotlib==3.8.2",
        "mediapipe==0.10.9",
        "mpmath==1.3.0",
        "multidict==6.0.5",
        "networkx==3.2.1",
        "numba==0.59.0",
        "numpy==1.26.2",
        "omegaconf==2.2.3",
        "onnx==1.15.0",
        "onnxruntime==1.17.0",
        "open-clip-torch==2.20.0",
        "opencv-contrib-python==4.9.0.80",
        "opencv-python-headless==4.9.0.80",
        "opencv-python==4.9.0.80",
        "orjson==3.9.13",
        "packaging==23.2",
        "pandas==2.2.0",
        "piexif==1.1.3",
        "pillow==9.5.0",
        "pip==22.3.1",
        "platformdirs==4.2.0",
        "portalocker==2.8.2",
        "prettytable==3.9.0",
        "protobuf==3.20.3",
        "psutil==5.9.5",
        "pycollada==0.8",
        "pycparser==2.21",
        "pydantic==1.10.14",
        "pydub==0.25.1",
        "pyparsing==3.1.1",
        "pyreadline3==3.4.1",
        "python-dateutil==2.8.2",
        "python-multipart==0.0.7",
        "pytorch-lightning==1.9.4",
        "pytz==2024.1",
        "pywavelets==1.5.0",
        "pywin32==306",
        "pyyaml==6.0.1",
        "qudida==0.0.4",
        "referencing==0.33.0",
        "regex==2023.12.25",
        "reportlab==4.0.9",
        "requests==2.31.0",
        "resize-right==0.0.2",
        "rpds-py==0.17.1",
        "rtree==1.2.0",
        "safetensors==0.4.2",
        "scikit-image==0.21.0",
        "scikit-learn==1.4.0",
        "scipy==1.12.0",
        "semantic-version==2.10.0",
        "sentencepiece==0.1.99",
        "setuptools==65.5.0",
        "shapely==2.0.2",
        "six==1.16.0",
        "smmap==5.0.1",
        "sniffio==1.3.0",
        "sounddevice==0.4.6",
        "spandrel==0.1.6",
        "starlette==0.26.1",
        "svg.path==6.3",
        "svglib==1.5.1",
        "sympy==1.12",
        "tabulate==0.9.0",
        "tb-nightly==2.16.0a20240205",
        "tensorboard-data-server==0.7.2",
        "termcolor==2.4.0",
        "tf-keras-nightly==2.16.0.dev2024020510",
        "threadpoolctl==3.2.0",
        "tifffile==2024.1.30",
        "timm==0.9.12",
        "tinycss2==1.2.1",
        "tokenizers==0.13.3",
        "tomesd==0.1.3",
        "tomli==2.0.1",
        "toolz==0.12.1",
        "torch==2.1.2+cu121",
        "torchdiffeq==0.2.3",
        "torchmetrics==1.3.0.post0",
        "torchsde==0.2.6",
        "torchvision==0.16.2+cu121",
        "tqdm==4.66.1",
        "trampoline==0.1.2",
        "transformers==4.30.2",
        "trimesh==4.1.3",
        "triton==2.1.0",
        "typing-extensions==4.9.0",
        "tzdata==2023.4",
        "urllib3==2.2.0",
        "uvicorn==0.27.0.post1",
        "vhacdx==0.0.5",
        "wcwidth==0.2.13",
        "webencodings==0.5.1",
        "websockets==11.0.3",
        "werkzeug==3.0.1",
        "xformers==0.0.23.post1",
        "xxhash==3.4.1",
        "yacs==0.1.8",
        "yapf==0.40.2",
        "yarl==1.9.4",
        "zipp==3.17.0"
    ]
}

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui-forge\launch.py", line 48, in <module>
    main()
  File "C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui-forge\launch.py", line 44, in main
    start()
  File "C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui-forge\modules\launch_utils.py", line 512, in start
    webui.webui()
  File "C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui-forge\webui.py", line 68, in webui
    shared.demo = ui.create_ui()
  File "C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui-forge\modules\ui.py", line 1135, in create_ui
    parameters_copypaste.connect_paste_params_buttons()
  File "C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui-forge\modules\infotext_utils.py", line 141, in connect_paste_params_buttons
    destination_image_component = paste_fields[binding.tabname]["init_img"]
KeyError: 'svd'
model_type EPS
UNet ADM Dimension 2816
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection'}
To load target model SDXLClipModel
Begin to load 1 model
Moving model(s) has taken 0.33 seconds
Model loaded in 5.5s (load weights from disk: 0.4s, forge load real models: 4.5s, calculate empty prompt: 0.6s).
Press any key to continue . . .
```

### Additional information

If I open `config.json` and delete the entry from the list of `disabled_extensions` manually, then the UI opens as normal again

**Comment by Haoming02** [comment]
Disabling `sd_forge_z123` works with no error

**Comment by lllyasviel** [comment]
@huchenlei i think this is related to your codes for "send to svd" plz take a look
