### ISSUE TITLE
[Bug]: Lora sub-folder and some Lora didn't show up

### ISSUE THREAD

**Issue by obs945** [lllyasviel/stable-diffusion-webui-forge#518]
### Checklist

- [x] The issue exists after disabling all extensions
- [x] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [x] The issue exists in the current version of the webui
- [x] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Some of the Lora sub-folder didn't show up.

### Steps to reproduce the problem

1. Go to Lora tab
2. Click "Enable Tree View"
3. Expand Folder
4. Some of the Sub-folders didn't show up, moreover, not all the loras in folder show up

### What should have happened?

Sub-folders all showed up in the lora tab.

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

[sysinfo-2024-03-08-22-44.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14543896/sysinfo-2024-03-08-22-44.json)

### Console logs

```Shell
No any error message appeared.
```

**Comment by Gourieff** [comment]
Just try to "Refresh" it
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/85128026/3c636cdb-f1b7-47b0-b08f-20448fb491f5)

**Comment by obs945** [comment]
> Just try to "Refresh" it ![image](https://private-user-images.githubusercontent.com/85128026/311413658-3c636cdb-f1b7-47b0-b08f-20448fb491f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NjcyNTcsIm5iZiI6MTcwOTk2Njk1NywicGF0aCI6Ii84NTEyODAyNi8zMTE0MTM2NTgtM2M2MzZjZGItZjFiNy00N2IwLWIwOGYtMjA0NDhmYjQ5MWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDA2NDkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhYzg0MDlkZjg4ZTk0NTRkNjc3NWFlNjA1YjBmM2M2NWU2MDIzYmI1NzVkYWU1ZDczYWUxYzU5ODYwNGYwOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bWUVMLKTdvQ4OuN5ZAKZXsUigHky3n9v2VoJFBOfxF0)

Thanks for the advice but I already tried it several time but in vain.

**Comment by rktvr** [comment]
latest git pull causes lora to not update for me too.
also can't update extensions

**Comment by rktvr** [comment]
removing the --listen flag made the lora refresh work

**Comment by obs945** [comment]
> removing the --listen flag made the lora refresh work

Sounds good ! But remove --listen flag still cannot fix my issue. 
My lora refresh works fine but sub-folder and some loras not show up.

**Comment by obs945** [comment]
Originally my refresh is working. 
After remove and re-add --listen flag, my refresh function not work...
So, I removed --listen now.

**Comment by klintan96** [comment]
Settings/Extra Networks

✔Always show all networks on the Lora page 
(otherwise, those detected as for incompatible version of Stable Diffusion will be hidden)

**Comment by obs945** [comment]
> Settings/Extra Networks
> 
> ✔Always show all networks on the Lora page (otherwise, those detected as for incompatible version of Stable Diffusion will be hidden)

It works !!  You save the day. 
Now I will change the title to "--listen flag made lora refresh button not work"

**Comment by obs945** [comment]
If anyone migrate from other SD webui to forge, please check "Settings/Extra Networks" ✔Always show all networks on the Lora page. 
(otherwise, those detected as for incompatible version of Stable Diffusion will be hidden)

**Comment by a3nima** [comment]
> If anyone migrate from other SD webui to forge, please check "Settings/Extra Networks" ✔Always show all networks on the Lora page. (otherwise, those detected as for incompatible version of Stable Diffusion will be hidden)

yeah but I think its also this way per default in sd-webui. and its quite practical, if you dont have your loras in different folders because only the loras for the model type (1.5 - xl) are shown. or am I missing something here ? :)
