### ISSUE TITLE
[Bug]: "Disable All Extensions"  option in Extension tab prevents UI from launching afterwards

### ISSUE THREAD

**Issue by CCpt5** [lllyasviel/stable-diffusion-webui-forge#53]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I was attempting to get info to report a different bug (full quality previews not appearing) when I used the option in Extensions to disable all extensions. After  setting that the following restart and any other attempts to relaunch the webui-user.bat file end w/ a silent crash "Press any key to continue . . ."

Fortunately I happened to have config.json open in Notepad++ so I was able to resave the pre-disable settings and the webui launched again w/o any problem.

I then renamed my extensions folder (so WEbui wouldn't find my extensions) and it loaded fine. That left all the baked in extensions still there.

At that point (w/o any of my added extensions there) I tried the "disable all extensions" button and again it broke the UI from launching.

This could be a common problem if it happens to everyone as the bug report forum here ask if you've tried reproducing the issue w/o any extensions running. 

### Steps to reproduce the problem

Go To extensions tab, use disable all extensions "All" button, restart.

### What should have happened?

Restart completely w/o extensions - not crash

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

can update tomorrow if needed - too late now

### Console logs

```Shell
venv "D:\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.7-latest-41-g6aee7a20
Commit hash: 6aee7a20329b4a0e10b87d841d680562bdde65c7
Launching Web UI with arguments: --ckpt-dir e:\stable Diffusion Checkpoints
Total VRAM 24564 MB, total RAM 65244 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
*** "Disable all extensions" option was set, will not load any extensions ***
Loading weights [ba12f15e72] from e:\stable Diffusion Checkpoints\f222\juggernaut_aftermath.safetensors
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-forge\launch.py", line 48, in <module>
    main()
  File "D:\stable-diffusion-webui-forge\launch.py", line 44, in main
    start()
  File "D:\stable-diffusion-webui-forge\modules\launch_utils.py", line 512, in start
    webui.webui()
  File "D:\stable-diffusion-webui-forge\webui.py", line 68, in webui
    shared.demo = ui.create_ui()
  File "D:\stable-diffusion-webui-forge\modules\ui.py", line 1135, in create_ui
    parameters_copypaste.connect_paste_params_buttons()
  File "D:\stable-diffusion-webui-forge\modules\infotext_utils.py", line 141, in connect_paste_params_buttons
    destination_image_component = paste_fields[binding.tabname]["init_img"]
KeyError: 'svd'
model_type EPS
UNet ADM Dimension 0
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['alphas_cumprod', 'alphas_cumprod_prev', 'betas', 'log_one_minus_alphas_cumprod', 'model_ema.decay', 'model_ema.num_updates', 'posterior_log_variance_clipped', 'posterior_mean_coef1', 'posterior_mean_coef2', 'posterior_variance', 'sqrt_alphas_cumprod', 'sqrt_one_minus_alphas_cumprod', 'sqrt_recip_alphas_cumprod', 'sqrt_recipm1_alphas_cumprod'])
Loading VAE weights specified in settings: D:\stable-diffusion-webui-forge\models\VAE\vae-ft-mse-840000-ema-pruned.pt
To load target model SD1ClipModel
Begin to load 1 model
Model loaded in 1.2s (load weights from disk: 0.2s, forge load real models: 0.6s, load VAE: 0.2s, calculate empty prompt: 0.1s).
Press any key to continue . . .
```

### Additional information

I can post sys info in the morning if needed - very late but wanted to add these two issues (this one came while I was reporting the last so took more time).

Thanks for all your work on these - amazing job!

**Comment by mohitsrivastavazzz** [comment]
Same issue here.
