### ISSUE TITLE
[Bug]: 'sdapi/v1/unload-checkpoint' Does literally nothing

### ISSUE THREAD

**Issue by altoiddealer** [lllyasviel/stable-diffusion-webui-forge#558]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I have a discord bot that manages sd-webui-forge as well as textgen-webui.

I wanted to add a feature to 'unload image model', but apparently this endpoint does not actually do anything at all.

When I execute it from the API window, nothing appears in the cmd window and my system resources are perfectly unchanged.

### Steps to reproduce the problem

1. Go to http://127.0.0.1:7860/docs
2. Go to [POST] **sdapi_v1_unload_checkpoint**
3. Click "Try it out"
4. Click "Execute"
5. **Nothing happens**

### What should have happened?

The currently loaded image model should get unloaded

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-03-14-18-10.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14606408/sysinfo-2024-03-14-18-10.json)

### Console logs

```Shell
venv "C:\0_SD\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.8.0
Commit hash: bef51aed032c0aaa5cfd80445bc4cf0d85b408b5
CUDA 12.1
Launching Web UI with arguments: --ckpt-dir C:\0_SD\stable-diffusion-webui\xtra\models --lora-dir C:\0_SD\stable-diffusion-webui\xtra\Lora --embeddings-dir C:\0_SD\stable-diffusion-webui\xtra\embeddings --ui-settings-file C:\0_SD\stable-diffusion-webui\xtra\config-alt.json --api --listen --no-half-vae
No module 'xformers'. Proceeding without it.
ControlNet preprocessor location: C:\0_SD\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-03-14 14:03:12,527 - ControlNet - INFO - ControlNet v1.1.441
2024-03-14 14:03:12,598 - ControlNet - INFO - ControlNet v1.1.441
14:03:12 - ReActor - STATUS - Running v0.7.0-b6 on Device: CUDA
Loading weights [05280ea2fa] from C:\0_SD\stable-diffusion-webui\xtra\models\sdxl\deepDarkHentaiMixNSFW_v40.safetensors
2024-03-14 14:03:13,481 - ControlNet - INFO - ControlNet UI callback registered.
Creating model from config: C:\0_SD\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 17.9s (prepare environment: 6.2s, import torch: 2.8s, import gradio: 0.8s, setup paths: 0.8s, initialize shared: 0.1s, other imports: 0.4s, load scripts: 1.3s, create ui: 0.8s, gradio launch: 4.2s, add APIs: 0.5s).
Applying attention optimization: Doggettx... done.
Model loaded in 17.5s (load weights from disk: 0.5s, create model: 0.6s, apply weights to model: 15.9s, calculate empty prompt: 0.2s).
```

**Comment by catboxanon** [comment]
No longer does anything via https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/2038. Closing.
