### ISSUE TITLE
[Bug]: Installation failed

### ISSUE THREAD

**Issue by bigwinboy** [lllyasviel/stable-diffusion-webui-forge#568]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

installation failed
RuntimeError: Couldn't clone assets.
Command: "git" clone --config core.filemode=false "https://githubfast.com/AUTOMATIC1111/stable-diffusion-webui-assets.git" "F:\AI\Stable-Diffusion-Webui-Forge\repositories\stable-diffusion-webui-assets"
Error code: 128

### Steps to reproduce the problem

Frist time run webui.bat

### What should have happened?

Successful installation

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

installation failed

### Console logs

```Shell
Cloning assets into F:\AI\Stable-Diffusion-Webui-Forge\repositories\stable-diffusion-webui-assets...
Cloning into 'F:\AI\Stable-Diffusion-Webui-Forge\repositories\stable-diffusion-webui-assets'...
fatal: unable to access 'https://githubfast.com/AUTOMATIC1111/stable-diffusion-webui-assets.git/': The requested URL returned error: 403
Traceback (most recent call last):
  File "F:\AI\Stable-Diffusion-Webui-Forge\launch.py", line 51, in <module>
    main()
  File "F:\AI\Stable-Diffusion-Webui-Forge\launch.py", line 39, in main
    prepare_environment()
  File "F:\AI\Stable-Diffusion-Webui-Forge\modules\launch_utils.py", line 507, in prepare_environment
    git_clone(assets_repo, repo_dir('stable-diffusion-webui-assets'), "assets", assets_commit_hash)
  File "F:\AI\Stable-Diffusion-Webui-Forge\modules\launch_utils.py", line 201, in git_clone
    run(f'"{git}" clone --config core.filemode=false "{url}" "{dir}"', f"Cloning {name} into {dir}...", f"Couldn't clone {name}", live=True)
  File "F:\AI\Stable-Diffusion-Webui-Forge\modules\launch_utils.py", line 125, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't clone assets.
Command: "git" clone --config core.filemode=false "https://githubfast.com/AUTOMATIC1111/stable-diffusion-webui-assets.git" "F:\AI\Stable-Diffusion-Webui-Forge\repositories\stable-diffusion-webui-assets"
Error code: 128
```

**Comment by rastarr** [comment]
Hi, did you find a resolution to this? I'm getting the same

**Comment by bigwinboy** [comment]
> Hi, did you find a resolution to this? I'm getting the same

Solved, there should be a problem with the source provided by the author, I was installing another project, https://github.com/lshqqytiger/stable-diffusion-webui-directml, which has the same name folder 'repositories‘ After I downloaded it, I copied and overwrote the folder directly into the forge directory, and it worked!

**Comment by bigwinboy** [comment]
It has been solved, it should be a problem with the download source provided by the author, I installed another author's project, https://github.com/lshqqytiger/stable-diffusion-webui-directml, and there is a folder with the same name inside that project named ' repositories', I copied and overwrote this folder directly into the forge directory, and it worked!

**Comment by bigwinboy** [comment]
> Hi, did you find a resolution to this? I'm getting the same

It has been solved, it should be a problem with the download source provided by the author, I installed another author's project, https://github.com/lshqqytiger/stable-diffusion-webui-directml, and there is a folder with the same name inside that project named ' repositories', I copied and overwrote this folder directly into the forge directory, and it worked!
