### ISSUE TITLE
[Bug]: Once Xformers is activate, Forge will no longer launch without Xformers

### ISSUE THREAD

**Issue by 6630507** [lllyasviel/stable-diffusion-webui-forge#598]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Everything installed and worked well. I was doing some speed and optimization tests, and wanted to compare performance with and without Xformers.  Launched with optimization flags " --pin-shared-memory --cuda-malloc --cuda-stream" and everything worked fine.  Re-launched with "--xformers" added.  Everything worked fine.  Re-launched again without "--xformers" and Forge will no longer launch.

Running Ubuntu 20.04, NVIDIA RTX 3060

The error reported is:

`ModuleNotFoundError: import of xformers halted; None in sys.modules
`

This error is reported elsewhere, with somebody attempting a clean install with xformers:

https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/323

I have a working install, but am trying to launch *without* Xformers after previously enabling it in the command line.

```
Launching launch.py...
################################################################
glibc version is 2.31
Check TCMalloc: libtcmalloc_minimal.so.4
libtcmalloc_minimal.so.4 is not linked with libpthread will trigger undefined symbol: pthread_Key_create error
Check TCMalloc: libtcmalloc.so.4
libtcmalloc.so.4 is linked with libpthread,execute LD_PRELOAD=/lib/x86_64-linux-gnu/libtcmalloc.so.4
Python 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
Legacy Preprocessor init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.
Launching Web UI with arguments: --listen --port 8888 --enable-insecure-extension-access
Total VRAM 12043 MB, total RAM 19969 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Traceback (most recent call last):
  File "/home/zostrianos/ml/stable-diffusion-webui-forge/launch.py", line 51, in <module>
    main()
  File "/home/zostrianos/ml/stable-diffusion-webui-forge/launch.py", line 47, in main
    start()
  File "/home/zostrianos/ml/stable-diffusion-webui-forge/modules/launch_utils.py", line 541, in start
    import webui
  File "/home/zostrianos/ml/stable-diffusion-webui-forge/webui.py", line 19, in <module>
    initialize.imports()
  File "/home/zostrianos/ml/stable-diffusion-webui-forge/modules/initialize.py", line 53, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "/home/zostrianos/ml/stable-diffusion-webui-forge/modules/processing.py", line 18, in <module>
    import modules.sd_hijack
  File "/home/zostrianos/ml/stable-diffusion-webui-forge/modules/sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "/home/zostrianos/ml/stable-diffusion-webui-forge/modules/sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "/home/zostrianos/ml/stable-diffusion-webui-forge/modules/hypernetworks/hypernetwork.py", line 13, in <module>
    from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
  File "/home/zostrianos/ml/stable-diffusion-webui-forge/modules/sd_models.py", line 20, in <module>
    from modules_forge import forge_loader
  File "/home/zostrianos/ml/stable-diffusion-webui-forge/modules_forge/forge_loader.py", line 5, in <module>
    from ldm_patched.modules import model_detection
  File "/home/zostrianos/ml/stable-diffusion-webui-forge/ldm_patched/modules/model_detection.py", line 5, in <module>
    import ldm_patched.modules.supported_models
  File "/home/zostrianos/ml/stable-diffusion-webui-forge/ldm_patched/modules/supported_models.py", line 5, in <module>
    from . import model_base
  File "/home/zostrianos/ml/stable-diffusion-webui-forge/ldm_patched/modules/model_base.py", line 6, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "/home/zostrianos/ml/stable-diffusion-webui-forge/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 22, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/home/zostrianos/ml/stable-diffusion-webui-forge/ldm_patched/ldm/modules/attention.py", line 21, in <module>
    import xformers
ModuleNotFoundError: import of xformers halted; None in sys.modules

```

### Steps to reproduce the problem

1. Install WebUI Forge.
2. Launch and generate an image.
3. Terminate server.  Re-launch with "--xformers" optimization command line.
4. Generate a image
5. Terminate server.  Re-launch without "--xformers" optimization in command line.
6. Server will not launch.

### What should have happened?

Forge should launch without "--xformers" optimization flag.  Using this flag once should not permanently bork the entire installation.

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome

### Sysinfo

{
    "Platform": "Linux-5.4.0-169-generic-x86_64-with-glibc2.31",
    "Python": "3.10.14",
    "Version": "f0.0.17v1.8.0rc-latest-276-g29be1da7",
    "Commit": "29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7",
    "Script path": "/home/zostrianos/ml/stable-diffusion-webui-forge",
    "Data path": "/home/zostrianos/ml/stable-diffusion-webui-forge",
    "Extensions dir": "/home/zostrianos/ml/stable-diffusion-webui-forge/extensions",
    "Checksum": "7f2ef3d2732d2de9ab060d8fcef37898a7cc32ebc8afae0fb4f5eb0d4f8c1a1a",
    "Commandline": [
        "launch.py",
        "--listen",
        "--port",
        "8888",
        "--enable-insecure-extension-access",
        "--pin-shared-memory",
        "--cuda-malloc",
        "--cuda-stream",
        "--xformers"
    ],
    "Torch env info": {
        "torch_version": "2.1.2+cu121",
        "is_debug_build": "False",
        "cuda_compiled_version": "12.1",
        "gcc_version": "(Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0",
        "clang_version": null,
        "cmake_version": null,
        "os": "Linux Mint 20.3 (x86_64)",
        "libc_version": "glibc-2.31",
        "python_version": "3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0] (64-bit runtime)",
        "python_platform": "Linux-5.4.0-169-generic-x86_64-with-glibc2.31",
        "is_cuda_available": "True",
        "cuda_runtime_version": "11.3.109",
        "cuda_module_loading": "LAZY",
        "nvidia_driver_version": "535.104.12",
        "nvidia_gpu_models": "GPU 0: NVIDIA GeForce RTX 3060",
        "cudnn_version": [
            "Probably one of the following:",
            "/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.7",
            "/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.7",
            "/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.7",
            "/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.7",
            "/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.7",
            "/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7",
            "/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.7"
        ],
        "pip_version": "pip3",
        "pip_packages": [
            "numpy==1.26.2",
            "open-clip-torch==2.20.0",
            "pytorch-lightning==1.9.4",
            "torch==2.1.2+cu121",
            "torchdiffeq==0.2.3",
            "torchmetrics==1.3.2",
            "torchsde==0.2.6",
            "torchvision==0.16.2+cu121",
            "triton==2.1.0"
        ],
        "conda_packages": [
            "numpy                     1.26.4                   pypi_0    pypi",
            "open-clip-torch           2.24.0                   pypi_0    pypi",
            "pytorch-lightning         2.2.1                    pypi_0    pypi",
            "torch                     2.2.1                    pypi_0    pypi",
            "torchdiffeq               0.2.3                    pypi_0    pypi",
            "torchmetrics              1.3.2                    pypi_0    pypi",
            "torchsde                  0.2.6                    pypi_0    pypi",
            "torchvision               0.17.1                   pypi_0    pypi",
            "triton                    2.2.0                    pypi_0    pypi"
        ],
        "hip_compiled_version": "N/A",
        "hip_runtime_version": "N/A",
        "miopen_runtime_version": "N/A",
        "caching_allocator_config": "backend:cudaMallocAsync",
        "is_xnnpack_available": "True",
        "cpu_info": [
            "Architecture:                       x86_64",
            "CPU op-mode(s):                     32-bit, 64-bit",
            "Byte Order:                         Little Endian",
            "Address sizes:                      36 bits physical, 48 bits virtual",
            "CPU(s):                             4",
            "On-line CPU(s) list:                0-3",
            "Thread(s) per core:                 1",
            "Core(s) per socket:                 4",
            "Socket(s):                          1",
            "NUMA node(s):                       1",
            "Vendor ID:                          GenuineIntel",
            "CPU family:                         6",
            "Model:                              58",
            "Model name:                         Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz",
            "Stepping:                           9",
            "CPU MHz:                            1757.950",
            "CPU max MHz:                        3500.0000",
            "CPU min MHz:                        1600.0000",
            "BogoMIPS:                           6192.70",
            "Virtualization:                     VT-x",
            "L1d cache:                          128 KiB",
            "L1i cache:                          128 KiB",
            "L2 cache:                           1 MiB",
            "L3 cache:                           6 MiB",
            "NUMA node0 CPU(s):                  0-3",
            "Vulnerability Gather data sampling: Not affected",
            "Vulnerability Itlb multihit:        KVM: Mitigation: Split huge pages",
            "Vulnerability L1tf:                 Mitigation; PTE Inversion; VMX conditional cache flushes, SMT disabled",
            "Vulnerability Mds:                  Mitigation; Clear CPU buffers; SMT disabled",
            "Vulnerability Meltdown:             Mitigation; PTI",
            "Vulnerability Mmio stale data:      Unknown: No mitigations",
            "Vulnerability Retbleed:             Not affected",
            "Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp",
            "Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization",
            "Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected",
            "Vulnerability Srbds:                Vulnerable: No microcode",
            "Vulnerability Tsx async abort:      Not affected",
            "Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d"
        ]
    },
    "Exceptions": [],
    "CPU": {
        "model": "x86_64",
        "count logical": 4,
        "count physical": 4
    },
    "RAM": {
        "total": "20GB",
        "used": "3GB",
        "free": "198MB",
        "active": "10GB",
        "inactive": "8GB",
        "buffers": "458MB",
        "cached": "15GB",
        "shared": "16MB"
    },
    "Extensions": [],
    "Inactive extensions": [],
    "Environment": {
        "GIT": "git",
        "GRADIO_ANALYTICS_ENABLED": "False"
    },
    "Config": {
        "ldsr_steps": 100,
        "ldsr_cached": false,
        "SCUNET_tile": 256,
        "SCUNET_tile_overlap": 8,
        "SWIN_tile": 192,
        "SWIN_tile_overlap": 8,
        "SWIN_torch_compile": false,
        "control_net_detectedmap_dir": "detected_maps",
        "control_net_models_path": "",
        "control_net_modules_path": "",
        "control_net_unit_count": 3,
        "control_net_model_cache_size": 5,
        "control_net_no_detectmap": false,
        "control_net_detectmap_autosaving": false,
        "control_net_allow_script_control": false,
        "control_net_sync_field_args": true,
        "controlnet_show_batch_images_in_ui": false,
        "controlnet_increment_seed_during_batch": false,
        "controlnet_disable_openpose_edit": false,
        "controlnet_disable_photopea_edit": false,
        "controlnet_photopea_warning": true,
        "controlnet_input_thumbnail": true,
        "sd_checkpoint_hash": "84d76a0328ee5a1a2a1d466ba7478ab59183e3fea385441528aa4c5d567fd43e",
        "sd_model_checkpoint": "epicrealism_naturalSinRC1VAE.safetensors [84d76a0328]"
    },
    "Startup": {
        "total": 12.59731125831604,
        "records": {
            "initial startup": 0.009324789047241211,
            "prepare environment/checks": 5.91278076171875e-05,
            "prepare environment/git version info": 0.05655550956726074,
            "prepare environment/torch GPU test": 1.81427001953125,
            "prepare environment/clone repositores": 0.05749225616455078,
            "prepare environment/run extensions installers": 0.0002944469451904297,
            "prepare environment/run extensions_builtin installers/sd_forge_controlllite": 0.000102996826171875,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_normalbae": 1.71661376953125e-05,
            "prepare environment/run extensions_builtin installers/sd_forge_ipadapter": 1.5020370483398438e-05,
            "prepare environment/run extensions_builtin installers/mobile": 1.4781951904296875e-05,
            "prepare environment/run extensions_builtin installers/sd_forge_kohya_hrfix": 1.5020370483398438e-05,
            "prepare environment/run extensions_builtin installers/LDSR": 1.5020370483398438e-05,
            "prepare environment/run extensions_builtin installers/sd_forge_freeu": 1.4543533325195312e-05,
            "prepare environment/run extensions_builtin installers/ScuNET": 1.4543533325195312e-05,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_reference": 1.4781951904296875e-05,
            "prepare environment/run extensions_builtin installers/sd_forge_fooocus_inpaint": 1.4781951904296875e-05,
            "prepare environment/run extensions_builtin installers/extra-options-section": 1.4543533325195312e-05,
            "prepare environment/run extensions_builtin installers/sd_forge_controlnet_example": 1.4543533325195312e-05,
            "prepare environment/run extensions_builtin installers/sd_forge_latent_modifier": 1.430511474609375e-05,
            "prepare environment/run extensions_builtin installers/sd_forge_z123": 1.5020370483398438e-05,
            "prepare environment/run extensions_builtin installers/Lora": 1.4543533325195312e-05,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_inpaint": 1.4543533325195312e-05,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_recolor": 1.5020370483398438e-05,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_marigold": 1.4543533325195312e-05,
            "prepare environment/run extensions_builtin installers/sd_forge_sag": 1.430511474609375e-05,
            "prepare environment/run extensions_builtin installers/sd_forge_svd": 1.4781951904296875e-05,
            "prepare environment/run extensions_builtin installers/forge_legacy_preprocessors": 0.27110767364501953,
            "prepare environment/run extensions_builtin installers/sd_forge_stylealign": 7.367134094238281e-05,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_revision": 2.47955322265625e-05,
            "prepare environment/run extensions_builtin installers/sd_forge_hypertile": 2.1219253540039062e-05,
            "prepare environment/run extensions_builtin installers/prompt-bracket-checker": 2.09808349609375e-05,
            "prepare environment/run extensions_builtin installers/sd_forge_dynamic_thresholding": 2.002716064453125e-05,
            "prepare environment/run extensions_builtin installers/soft-inpainting": 2.0742416381835938e-05,
            "prepare environment/run extensions_builtin installers/sd_forge_photomaker": 2.0265579223632812e-05,
            "prepare environment/run extensions_builtin installers/sd_forge_controlnet": 0.23434877395629883,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_tile": 7.677078247070312e-05,
            "prepare environment/run extensions_builtin installers/SwinIR": 2.47955322265625e-05,
            "prepare environment/run extensions_builtin installers/sd_forge_neveroom": 2.1219253540039062e-05,
            "prepare environment/run extensions_builtin installers/sd_forge_multidiffusion": 2.0742416381835938e-05,
            "prepare environment/run extensions_builtin installers/canvas-zoom-and-pan": 2.0503997802734375e-05,
            "prepare environment/run extensions_builtin installers": 0.506218671798706,
            "prepare environment": 2.4675371646881104,
            "launcher": 0.0016193389892578125,
            "import torch": 5.0554094314575195,
            "import gradio": 0.8956151008605957,
            "setup paths": 0.731285572052002,
            "import ldm": 0.0030944347381591797,
            "import sgm": 4.76837158203125e-06,
            "initialize shared": 0.06662607192993164,
            "other imports": 0.45783376693725586,
            "opts onchange": 0.0003914833068847656,
            "setup SD model": 6.437301635742188e-05,
            "setup codeformer": 0.0005533695220947266,
            "setup gfpgan": 0.0050089359283447266,
            "set samplers": 4.696846008300781e-05,
            "list extensions": 0.0032122135162353516,
            "restore config state file": 1.0967254638671875e-05,
            "list SD models": 0.0038175582885742188,
            "list localizations": 0.0002765655517578125,
            "load scripts/custom_code.py": 0.0028820037841796875,
            "load scripts/img2imgalt.py": 0.00029277801513671875,
            "load scripts/loopback.py": 0.000148773193359375,
            "load scripts/outpainting_mk_2.py": 0.0001876354217529297,
            "load scripts/poor_mans_outpainting.py": 0.00013875961303710938,
            "load scripts/postprocessing_caption.py": 0.00011324882507324219,
            "load scripts/postprocessing_codeformer.py": 0.00012063980102539062,
            "load scripts/postprocessing_create_flipped_copies.py": 0.00011157989501953125,
            "load scripts/postprocessing_focal_crop.py": 0.0026891231536865234,
            "load scripts/postprocessing_gfpgan.py": 0.0001308917999267578,
            "load scripts/postprocessing_split_oversized.py": 0.0001270771026611328,
            "load scripts/postprocessing_upscale.py": 0.0001926422119140625,
            "load scripts/processing_autosized_crop.py": 0.00013709068298339844,
            "load scripts/prompt_matrix.py": 0.00015091896057128906,
            "load scripts/prompts_from_file.py": 0.0001647472381591797,
            "load scripts/sd_upscale.py": 0.00013399124145507812,
            "load scripts/xyz_grid.py": 0.0018928050994873047,
            "load scripts/ldsr_model.py": 0.392653226852417,
            "load scripts/lora_script.py": 0.3879082202911377,
            "load scripts/scunet_model.py": 0.06521296501159668,
            "load scripts/swinir_model.py": 0.06276631355285645,
            "load scripts/hotkey_config.py": 0.00018215179443359375,
            "load scripts/extra_options_section.py": 0.00022530555725097656,
            "load scripts/legacy_preprocessors.py": 0.004633188247680664,
            "load scripts/preprocessor_inpaint.py": 0.005306720733642578,
            "load scripts/preprocessor_marigold.py": 0.06380319595336914,
            "load scripts/preprocessor_normalbae.py": 0.002005338668823242,
            "load scripts/preprocessor_recolor.py": 0.00016546249389648438,
            "load scripts/forge_reference.py": 0.00021314620971679688,
            "load scripts/preprocessor_revision.py": 0.00017142295837402344,
            "load scripts/preprocessor_tile.py": 0.0001995563507080078,
            "load scripts/forge_controllllite.py": 0.0031278133392333984,
            "load scripts/controlnet.py": 0.543426513671875,
            "load scripts/xyz_grid_support.py": 0.0003440380096435547,
            "load scripts/sd_forge_controlnet_example.py": 0.0002129077911376953,
            "load scripts/forge_dynamic_thresholding.py": 0.0011835098266601562,
            "load scripts/forge_fooocus_inpaint.py": 0.0002353191375732422,
            "load scripts/forge_freeu.py": 0.0023431777954101562,
            "load scripts/forge_hypertile.py": 0.0008535385131835938,
            "load scripts/forge_ipadapter.py": 0.17477822303771973,
            "load scripts/kohya_hrfix.py": 0.0010652542114257812,
            "load scripts/forge_latent_modifier.py": 0.0019192695617675781,
            "load scripts/forge_multidiffusion.py": 0.0038118362426757812,
            "load scripts/forge_never_oom.py": 0.0001373291015625,
            "load scripts/forge_photomaker.py": 0.0009927749633789062,
            "load scripts/forge_sag.py": 0.0009469985961914062,
            "load scripts/forge_stylealign.py": 0.00014519691467285156,
            "load scripts/forge_svd.py": 0.08813309669494629,
            "load scripts/forge_z123.py": 0.07186532020568848,
            "load scripts/soft_inpainting.py": 0.0003616809844970703,
            "load scripts/comments.py": 0.06767439842224121,
            "load scripts/refiner.py": 0.0001995563507080078,
            "load scripts/seed.py": 0.00019431114196777344,
            "load scripts": 1.9590554237365723,
            "load upscalers": 0.0016818046569824219,
            "refresh VAE": 0.0012128353118896484,
            "refresh textual inversion templates": 4.76837158203125e-05,
            "scripts list_optimizers": 0.04863238334655762,
            "scripts list_unets": 1.1444091796875e-05,
            "reload hypernetworks": 0.00011420249938964844,
            "initialize extra networks": 0.001461029052734375,
            "scripts before_ui_callback": 0.0006694793701171875,
            "create ui": 0.7203481197357178,
            "gradio launch": 0.18334555625915527,
            "add APIs": 0.00993490219116211,
            "app_started_callback/lora_script.py": 0.0003535747528076172,
            "app_started_callback/controlnet.py": 0.0015022754669189453,
            "app_started_callback": 0.0018618106842041016
        }
    },
    "Packages": [
        "absl-py==2.1.0",
        "accelerate==0.21.0",
        "addict==2.4.0",
        "aenum==3.1.15",
        "aiofiles==23.2.1",
        "aiohttp==3.9.3",
        "aiosignal==1.3.1",
        "altair==5.2.0",
        "antlr4-python3-runtime==4.9.3",
        "anyio==3.7.1",
        "async-timeout==4.0.3",
        "attrs==23.2.0",
        "basicsr==1.4.2",
        "blendmodes==2022",
        "certifi==2024.2.2",
        "cffi==1.16.0",
        "chardet==5.2.0",
        "charset-normalizer==3.3.2",
        "clean-fid==0.1.35",
        "click==8.1.7",
        "clip==1.0",
        "coloredlogs==15.0.1",
        "colorlog==6.8.2",
        "contourpy==1.2.0",
        "cssselect2==0.7.0",
        "cycler==0.12.1",
        "deprecation==2.1.0",
        "depth-anything==2024.1.22.0",
        "diffusers==0.25.0",
        "einops==0.4.1",
        "embreex==2.17.7.post4",
        "exceptiongroup==1.2.0",
        "facexlib==0.3.0",
        "fastapi==0.94.0",
        "ffmpy==0.3.2",
        "filelock==3.13.1",
        "filterpy==1.4.5",
        "flatbuffers==24.3.7",
        "fonttools==4.50.0",
        "frozenlist==1.4.1",
        "fsspec==2024.3.1",
        "ftfy==6.2.0",
        "future==1.0.0",
        "fvcore==0.1.5.post20221221",
        "gitdb==4.0.11",
        "gitpython==3.1.32",
        "gradio-client==0.5.0",
        "gradio==3.41.2",
        "grpcio==1.62.1",
        "h11==0.12.0",
        "handrefinerportable==2024.2.12.0",
        "httpcore==0.15.0",
        "httpx==0.24.1",
        "huggingface-hub==0.21.4",
        "humanfriendly==10.0",
        "idna==3.6",
        "imageio==2.34.0",
        "importlib-metadata==7.1.0",
        "importlib-resources==6.4.0",
        "inflection==0.5.1",
        "iopath==0.1.9",
        "jax==0.4.25",
        "jaxlib==0.4.25",
        "jinja2==3.1.3",
        "jsonmerge==1.8.0",
        "jsonschema-specifications==2023.12.1",
        "jsonschema==4.21.1",
        "kiwisolver==1.4.5",
        "kornia==0.6.7",
        "lark==1.1.2",
        "lazy-loader==0.3",
        "lightning-utilities==0.11.0",
        "llvmlite==0.42.0",
        "lmdb==1.4.1",
        "lxml==5.1.0",
        "mapbox-earcut==1.0.1",
        "markdown==3.6",
        "markupsafe==2.1.5",
        "matplotlib==3.8.3",
        "mediapipe==0.10.11",
        "ml-dtypes==0.3.2",
        "mpmath==1.3.0",
        "multidict==6.0.5",
        "networkx==3.2.1",
        "numba==0.59.1",
        "numpy==1.26.2",
        "omegaconf==2.2.3",
        "onnxruntime==1.17.1",
        "open-clip-torch==2.20.0",
        "opencv-contrib-python==4.9.0.80",
        "opencv-python==4.9.0.80",
        "opt-einsum==3.3.0",
        "orjson==3.9.15",
        "packaging==24.0",
        "pandas==2.2.1",
        "piexif==1.1.3",
        "pillow==9.5.0",
        "pip==23.0.1",
        "platformdirs==4.2.0",
        "portalocker==2.8.2",
        "protobuf==3.20.0",
        "psutil==5.9.5",
        "pycollada==0.8",
        "pycparser==2.21",
        "pydantic==1.10.14",
        "pydub==0.25.1",
        "pyparsing==3.1.2",
        "python-dateutil==2.9.0.post0",
        "python-multipart==0.0.9",
        "pytorch-lightning==1.9.4",
        "pytz==2024.1",
        "pywavelets==1.5.0",
        "pyyaml==6.0.1",
        "referencing==0.34.0",
        "regex==2023.12.25",
        "reportlab==4.1.0",
        "requests==2.31.0",
        "resize-right==0.0.2",
        "rpds-py==0.18.0",
        "rtree==1.2.0",
        "safetensors==0.4.2",
        "scikit-image==0.21.0",
        "scipy==1.12.0",
        "semantic-version==2.10.0",
        "sentencepiece==0.2.0",
        "setuptools==65.5.0",
        "shapely==2.0.3",
        "six==1.16.0",
        "smmap==5.0.1",
        "sniffio==1.3.1",
        "sounddevice==0.4.6",
        "spandrel==0.1.6",
        "starlette==0.26.1",
        "svg.path==6.3",
        "svglib==1.5.1",
        "sympy==1.12",
        "tabulate==0.9.0",
        "tb-nightly==2.17.0a20240322",
        "tensorboard-data-server==0.7.2",
        "termcolor==2.4.0",
        "tifffile==2024.2.12",
        "timm==0.9.16",
        "tinycss2==1.2.1",
        "tokenizers==0.13.3",
        "tomesd==0.1.3",
        "tomli==2.0.1",
        "toolz==0.12.1",
        "torch==2.1.2+cu121",
        "torchdiffeq==0.2.3",
        "torchmetrics==1.3.2",
        "torchsde==0.2.6",
        "torchvision==0.16.2+cu121",
        "tqdm==4.66.2",
        "trampoline==0.1.2",
        "transformers==4.30.2",
        "trimesh==4.2.0",
        "triton==2.1.0",
        "typing-extensions==4.10.0",
        "tzdata==2024.1",
        "urllib3==2.2.1",
        "uvicorn==0.29.0",
        "vhacdx==0.0.6",
        "wcwidth==0.2.13",
        "webencodings==0.5.1",
        "websockets==11.0.3",
        "werkzeug==3.0.1",
        "xatlas==0.0.9",
        "xformers==0.0.23.post1",
        "xxhash==3.4.1",
        "yacs==0.1.8",
        "yapf==0.40.2",
        "yarl==1.9.4",
        "zipp==3.18.1"
    ]
}

### Console logs

```Shell
(stable-diffusion-webui-forge) user@user-ai:~/ml/stable-diffusion-webui-forge$ bash webui.sh

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.
################################################################

################################################################
Running on user user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
glibc version is 2.31
Check TCMalloc: libtcmalloc_minimal.so.4
libtcmalloc_minimal.so.4 is not linked with libpthread will trigger undefined symbol: pthread_Key_create error
Check TCMalloc: libtcmalloc.so.4
libtcmalloc.so.4 is linked with libpthread,execute LD_PRELOAD=/lib/x86_64-linux-gnu/libtcmalloc.so.4
Python 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
Legacy Preprocessor init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.
Launching Web UI with arguments: 
Total VRAM 12043 MB, total RAM 19969 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Traceback (most recent call last):
  File "/home/user/ml/stable-diffusion-webui-forge/launch.py", line 51, in <module>
    main()
  File "/home/user/ml/stable-diffusion-webui-forge/launch.py", line 47, in main
    start()
  File "/home/user/ml/stable-diffusion-webui-forge/modules/launch_utils.py", line 541, in start
    import webui
  File "/home/user/ml/stable-diffusion-webui-forge/webui.py", line 19, in <module>
    initialize.imports()
  File "/home/user/ml/stable-diffusion-webui-forge/modules/initialize.py", line 53, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "/home/user/ml/stable-diffusion-webui-forge/modules/processing.py", line 18, in <module>
    import modules.sd_hijack
  File "/home/user/ml/stable-diffusion-webui-forge/modules/sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "/home/user/ml/stable-diffusion-webui-forge/modules/sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "/home/user/ml/stable-diffusion-webui-forge/modules/hypernetworks/hypernetwork.py", line 13, in <module>
    from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
  File "/home/user/ml/stable-diffusion-webui-forge/modules/sd_models.py", line 20, in <module>
    from modules_forge import forge_loader
  File "/home/user/ml/stable-diffusion-webui-forge/modules_forge/forge_loader.py", line 5, in <module>
    from ldm_patched.modules import model_detection
  File "/home/user/ml/stable-diffusion-webui-forge/ldm_patched/modules/model_detection.py", line 5, in <module>
    import ldm_patched.modules.supported_models
  File "/home/user/ml/stable-diffusion-webui-forge/ldm_patched/modules/supported_models.py", line 5, in <module>
    from . import model_base
  File "/home/user/ml/stable-diffusion-webui-forge/ldm_patched/modules/model_base.py", line 6, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "/home/user/ml/stable-diffusion-webui-forge/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 22, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/home/user/ml/stable-diffusion-webui-forge/ldm_patched/ldm/modules/attention.py", line 21, in <module>
    import xformers
ModuleNotFoundError: import of xformers halted; None in sys.modules
(stable-diffusion-webui-forge) user@user-ai:~/ml/stable-diffusion-webui-forge$
```

**Comment by altoiddealer** [comment]
Forge has a cmd arg `--disable-xformers` which I use to disable xformers.

Try it!

**Comment by 6630507** [comment]
> Forge has a cmd arg `--disable-xformers` which I use to disable xformers.
> 
> Try it!

Thank you, that worked!

**Comment by 6630507** [comment]
Recommended solution worked.
