### ISSUE TITLE
Support for Multi-Diffusion Upscaler

### ISSUE THREAD

**Issue by LindezaBlue** [lllyasviel/stable-diffusion-webui-forge#672]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I have spent the last 2 months working with other members and the developers of the extension "Multdiffusion-upscaler" and so far there is an insane amount of support to have this extension implemented or available for Forge users. There is so much requests for it the developers are getting flooded with requests to have it work... but from what I can tell it's not on their end, it seems forge has it hard locked out.

_(link to authors post)_
https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/350#issuecomment-2058241530

**Extension in forge being locked:**
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/141217866/c5a27837-e1b6-4882-8074-27c6e8b7ac8d)
_(cannot be enabled, and resets back to disabled upon restart.)_

This extension is the reason a lot of people have not switched to Forge since it is highly memory efficient and works really well at upscaling and regional prompting. I myself am only use forge due to the speed it provides compared to A1111, however the only thing that I keep going back to A1111 is that there is no support for this one extension. 

If at all possible could this be added as a usable extension? 

Thanks!~

### Proposed workflow

* Enable it in the backend so that the extension can be used and worked on by the authors of the extension.

### Additional information

**Link to Extension:**
https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111

**Comment by Vigilence** [comment]
Agreed!

**Comment by muwaaaah** [comment]
Me too, I can't use multidiffusion upscale!!!
The only thing that i need to run a1111 is Multidiffusion upscale.

**Comment by Derjyn** [comment]
Isn't this already integrated?

![Screenshot 2024-04-17 192728](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/648059/841d9502-1672-4aa3-8e87-43bc4910229a)

**Comment by Vigilence** [comment]
Only a stripped down version is integrated, which doesn't function the same as the original.  Something is better then nothing, but atm the original author and friends want to improve the extension for forge and can't since its being blocked.
________________________________

**Comment by LindezaBlue** [comment]
I would be nice to not have the stripped down version for sure. I've tried it and it doesn't give results that are even remotely good. I also want to be able to use the region control that comes with Multi-Diffusion. That thing is a God send!

**Comment by altoiddealer** [comment]
This 100% should happen, unfortunately I haven't seen any evidence that Forge development even has a pulse right now?

**Comment by LindezaBlue** [comment]
> This 100% should happen, unfortunately I haven't seen any evidence that Forge development even has a pulse right now?

Like they haven't worked on any Commits/Updates to the program?

**Comment by altoiddealer** [comment]
If you go to Discussions tab you’ll see people have been asking repeatedly for a dev to make any sort of comment about development status but reaponse is nothing but crickets

**Comment by LindezaBlue** [comment]
> If you go to Discussions tab you’ll see people have been asking repeatedly for a dev to make any sort of comment about development status but response is nothing but crickets

Well, if that is true/the case atm, that just sucks. We really need a webui that is highly optimized like Forge and that has support for all A1111 extensions. If support is indeed dropped, I hope someone else picks up the pieces and develops a new webui that's actually maintained.

**Comment by nosdregamon** [comment]
I just searched for the better part of an hour, why this extension didn't show up (without a noticeable error message). Would be to bad, if Forge couldn't run this.

**Comment by LindezaBlue** [comment]
> I just searched for the better part of an hour, why this extension didn't show up (without a noticeable error message). Would be to bad, if Forge couldn't run this.

It was the same for me, and that's why I'm here, also bouncing back and forth between the discussions for the extension and hopefully Forge as well. But it seems like Forge Developers are dead quite atm. Not even a peep.

**Comment by GuruVirus** [comment]
> > I just searched for the better part of an hour, why this extension didn't show up (without a noticeable error message). Would be to bad, if Forge couldn't run this.
> 
> It was the same for me, and that's why I'm here, also bouncing back and forth between the discussions for the extension and hopefully Forge as well. But it seems like Forge Developers are dead quite atm. Not even a peep.

The author has been working on this repo instead this week: https://github.com/lllyasviel/IC-Light

**Comment by Vigilence** [comment]
This doesn’t need the Illyasviel.  It just needs the code blocking the extension removed, which hopefully anyone why the know how can do.

**Comment by louiskaneko34m** [comment]
+999999999999999999

**Comment by nosdregamon** [comment]
> This doesn’t need the Illyasviel. It just needs the code blocking the extension removed, which hopefully anyone why the know how can do.

To achieve this, disable the inbuilt extension in the settings. Apply and close Forge.

Then open "modules_forge/config.py" with a text-editor. The file only has 4 lines, so it will not be complicated.

Change
```
always_disabled_extensions = [
    'sd-webui-controlnet',
    'multidiffusion-upscaler-for-automatic1111'
]
```
to 
```
always_disabled_extensions = [
    'sd-webui-controlnet',
    # 'multidiffusion-upscaler-for-automatic1111'
]
```
(the # makes Python ignore the whole line)
Then you can start Forge and install/run the full extension. No clue how smooth this will run.

**Comment by realmalikov** [comment]
Native upscaler support would be highly appreciated.

**Comment by miro-ux** [comment]
@nosdregamon this does seem to allow you to enable the extension but the tab is still nowhere to be found under img2img:
![image](https://github.com/user-attachments/assets/b06c1881-ac6c-4958-987a-2e17965bb633)

**Comment by mr-september** [comment]
> @nosdregamon this does seem to allow you to enable the extension but the tab is still nowhere to be found under img2img: ![image](https://private-user-images.githubusercontent.com/7188826/358889849-b06c1881-ac6c-4958-987a-2e17965bb633.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzY3NDgsIm5iZiI6MTcyNTMzNjQ0OCwicGF0aCI6Ii83MTg4ODI2LzM1ODg4OTg0OS1iMDZjMTg4MS1hYzZjLTQ5NTgtOTg3YS0yZTE3OTY1YmI2MzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDNUMDQwNzI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQ4NTAwODdjMmEzYTc0NGE3M2RhNTc0OGU2ZTRjMTc0OWMyNGUwMmEyMjNjZTY3MGU4MzQ5YzRkNTU5ODFkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m1HDv91NtwxOtxQVOUtMRbqf6zqOuuk_sb0r0DIPgLk)

+1 same here. This is honestly so childish and unlike @lllyasviel's usual behaviour. No response, no explanation, can only leave Forge.

**Comment by Nancyeleanor** [comment]
I don't know why the author of forge is not providing support for this awesome extension. It's extremely dejecting.

**Comment by gigend** [comment]
any update for this multidiffusion with upscaler?

**Comment by schrai** [comment]
up

**Comment by Reptile-MTK** [comment]
I really want this extension to work. There is no working regional prompt for Forge at the moment. That is a real argument to just leave Forge behind although it is great in many things.

**Comment by altoiddealer** [comment]
> There is no working regional prompt for Forge at the moment. That is a real argument to just leave Forge behind although it is great in many things.

Forge Couple is a regional prompt extension designed specifically for Forge
