### ISSUE TITLE
[Feature Request]: disabling CN for 2nd pass

### ISSUE THREAD

**Issue by adnanT11** [lllyasviel/stable-diffusion-webui-forge#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

being able to disable CN in highres-fix is very important if you have low vram, this feature already exist in the other webui but its somehow not appearing, don't know if its a bug or the feature is cut 

### Proposed workflow

1. Go to controlnet settings
2. Press disable for 2nd pass
3. done

**Comment by huchenlei** [comment]
The hr option will be added soon. For now it is temporarily removed. See https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/40

**Comment by adnanT11** [comment]
thanks
