### ISSUE TITLE
[Bug]: Textual inversions not appearing

### ISSUE THREAD

**Issue by AbaddonFmL** [lllyasviel/stable-diffusion-webui-forge#759]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

Textual inversions not appearing.
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/85813206/2288c08c-abe4-48d4-b5da-7b766a1ab384)
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/85813206/ef2d5c4e-61f7-4ce9-b3ea-7082be346853)

### Steps to reproduce the problem

It's a fresh install.

### What should have happened?

Textual inversions should appear.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-05-22-20-11.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/15408257/sysinfo-2024-05-22-20-11.json)

### Console logs

```Shell
none
```

**Comment by BBird6** [comment]
What base model have you selected?

**Comment by AbaddonFmL** [comment]
> What base model have you selected?

Pony V6 XL

**Comment by wideload1971** [comment]
Well there's your answer. TI's only work with SD1.5 models, not XL models.
Same thing applies to loras as well, they only work with the model they were created for.
