### ISSUE TITLE
[Bug]: zero123

### ISSUE THREAD

**Issue by kalle07** [lllyasviel/stable-diffusion-webui-forge#772]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

no model load

### Steps to reproduce the problem

copy a 
stableVideoDiffusion.safetensors to
\webui\models\z123\
press reload button
nothing happened

which model i can use?
you have a link?

### What should have happened?

should be in the list

### Sysinfo

win10
rtx4060

### Console logs

```Shell
-
```

### Additional information

>>>  the model apears after restart

**Comment by worst-su** [comment]
umhm
SVD and Z123 are different things...
