### ISSUE TITLE
[Bug]: Control mode - in ControlNet Unit 0 - disappearing and reappearing

### ISSUE THREAD

**Issue by sugatasanshiro** [lllyasviel/stable-diffusion-webui-forge#78]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Control mode - in ControlNet Unit 0 - disappearing and reappearing

### Steps to reproduce the problem

Control mode - in ControlNet Unit 0 - disappearing and reappearing

### What should have happened?

Control mode - in ControlNet Unit 0 - disappearing and reappearing

### Sysinfo

Control mode - in ControlNet Unit 0 - disappearing and reappearing

### Console logs

```Shell
nothing
```

### Additional information

https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/143538601/d67401b7-1273-4364-9ca9-b5d1a2252ab5

**Comment by altoiddealer** [comment]
@sugatasanshiro There is no bug here.

- This is not occurring in ControlNet 0 only, it is in all ControlNet windows, for specific Control Types.
- The Control types where the menu goes away... these are Control types where the setting is completely irrelevant.
- If the setting was there it would confuse people that it has an effect for those control types but it does not
