### ISSUE TITLE
[Bug]: ControlNet not working in img2img

### ISSUE THREAD

**Issue by VladCorvi** [lllyasviel/stable-diffusion-webui-forge#81]
### Checklist

- [ ] The issue exists after disabling all extensions
- [x] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [x] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

ControlNet not working in img2img with any SDXL model like - dreamshaperXL.

### Steps to reproduce the problem

Start generation with SDXL ControlNet model like - diffusers_xl_canny_mid

### What should have happened?

ControlNet works perfectly with current model in txt2img mode but not in img2img.

### Sysinfo

{
    "Platform": "Windows-10-10.0.22631-SP0",
    "Python": "3.10.6",
    "Version": "f0.0.9-latest-52-gb58b0bd4",
    "Commit": "b58b0bd4259cf71077dfd7787fb77af4c02760a1",
    "Script path": "D:\\SD\\Forge\\webui",
    "Data path": "D:\\SD\\Forge\\webui",
    "Extensions dir": "D:\\SD\\Forge\\webui\\extensions",
    "Checksum": "7806745ba73e3bf9f1d0bb716b839ecba5881600587999be303bae7821a2a6ef",
    "Commandline": [
        "launch.py"
    ],
    "Torch env info": {
        "torch_version": "2.1.2+cu121",
        "is_debug_build": "False",
        "cuda_compiled_version": "12.1",
        "gcc_version": null,
        "clang_version": null,
        "cmake_version": null,
        "os": "Майкрософт Windows 11 Pro",
        "libc_version": "N/A",
        "python_version": "3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] (64-bit runtime)",
        "python_platform": "Windows-10-10.0.22631-SP0",
        "is_cuda_available": "True",
        "cuda_runtime_version": "12.1.105\r",
        "cuda_module_loading": "LAZY",
        "nvidia_driver_version": "551.32",
        "nvidia_gpu_models": "GPU 0: NVIDIA GeForce RTX 3050",
        "cudnn_version": null,
        "pip_version": "pip3",
        "pip_packages": [
            "numpy==1.26.2",
            "open-clip-torch==2.20.0",
            "pytorch-lightning==1.9.4",
            "torch==2.1.2+cu121",
            "torchdiffeq==0.2.3",
            "torchmetrics==1.3.0.post0",
            "torchsde==0.2.6",
            "torchvision==0.16.2+cu121"
        ],
        "conda_packages": null,
        "hip_compiled_version": "N/A",
        "hip_runtime_version": "N/A",
        "miopen_runtime_version": "N/A",
        "caching_allocator_config": "",
        "is_xnnpack_available": "True",
        "cpu_info": [
            "Architecture=9",
            "CurrentClockSpeed=3501",
            "DeviceID=CPU0",
            "Family=107",
            "L2CacheSize=3072",
            "L2CacheSpeed=",
            "Manufacturer=AuthenticAMD",
            "MaxClockSpeed=3501",
            "Name=AMD Ryzen 5 5600 6-Core Processor              ",
            "ProcessorType=3",
            "Revision=8450"
        ]
    },
    "Exceptions": [
        {
            "exception": "0",
            "traceback": [
                [
                    "D:\\SD\\Forge\\webui\\modules\\scripts.py, line 854, postprocess_batch_list",
                    "script.postprocess_batch_list(p, pp, *script_args, **kwargs)"
                ],
                [
                    "D:\\SD\\Forge\\system\\python\\lib\\site-packages\\torch\\utils\\_contextlib.py, line 115, decorate_context",
                    "return func(*args, **kwargs)"
                ],
                [
                    "D:\\SD\\Forge\\webui\\extensions-builtin\\sd_forge_controlnet\\scripts\\controlnet.py, line 493, postprocess_batch_list",
                    "self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)"
                ]
            ]
        },
        {
            "exception": "0",
            "traceback": [
                [
                    "D:\\SD\\Forge\\webui\\modules\\scripts.py, line 830, process_before_every_sampling",
                    "script.process_before_every_sampling(p, *script_args, **kwargs)"
                ],
                [
                    "D:\\SD\\Forge\\system\\python\\lib\\site-packages\\torch\\utils\\_contextlib.py, line 115, decorate_context",
                    "return func(*args, **kwargs)"
                ],
                [
                    "D:\\SD\\Forge\\webui\\extensions-builtin\\sd_forge_controlnet\\scripts\\controlnet.py, line 487, process_before_every_sampling",
                    "self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)"
                ]
            ]
        },
        {
            "exception": "",
            "traceback": [
                [
                    "D:\\SD\\Forge\\webui\\modules\\scripts.py, line 798, process",
                    "script.process(p, *script_args)"
                ],
                [
                    "D:\\SD\\Forge\\system\\python\\lib\\site-packages\\torch\\utils\\_contextlib.py, line 115, decorate_context",
                    "return func(*args, **kwargs)"
                ],
                [
                    "D:\\SD\\Forge\\webui\\extensions-builtin\\sd_forge_controlnet\\scripts\\controlnet.py, line 480, process",
                    "self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)"
                ],
                [
                    "D:\\SD\\Forge\\system\\python\\lib\\site-packages\\torch\\utils\\_contextlib.py, line 115, decorate_context",
                    "return func(*args, **kwargs)"
                ],
                [
                    "D:\\SD\\Forge\\webui\\extensions-builtin\\sd_forge_controlnet\\scripts\\controlnet.py, line 266, process_unit_after_click_generate",
                    "input_list, resize_mode = self.get_input_data(p, unit, preprocessor)"
                ],
                [
                    "D:\\SD\\Forge\\webui\\extensions-builtin\\sd_forge_controlnet\\scripts\\controlnet.py, line 205, get_input_data",
                    "mask = HWC3(np.asarray(a1111_i2i_mask))"
                ],
                [
                    "D:\\SD\\Forge\\webui\\modules_forge\\forge_util.py, line 13, HWC3",
                    "assert x.dtype == np.uint8"
                ]
            ]
        },
        {
            "exception": "0",
            "traceback": [
                [
                    "D:\\SD\\Forge\\webui\\modules\\scripts.py, line 854, postprocess_batch_list",
                    "script.postprocess_batch_list(p, pp, *script_args, **kwargs)"
                ],
                [
                    "D:\\SD\\Forge\\system\\python\\lib\\site-packages\\torch\\utils\\_contextlib.py, line 115, decorate_context",
                    "return func(*args, **kwargs)"
                ],
                [
                    "D:\\SD\\Forge\\webui\\extensions-builtin\\sd_forge_controlnet\\scripts\\controlnet.py, line 493, postprocess_batch_list",
                    "self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)"
                ]
            ]
        },
        {
            "exception": "0",
            "traceback": [
                [
                    "D:\\SD\\Forge\\webui\\modules\\scripts.py, line 830, process_before_every_sampling",
                    "script.process_before_every_sampling(p, *script_args, **kwargs)"
                ],
                [
                    "D:\\SD\\Forge\\system\\python\\lib\\site-packages\\torch\\utils\\_contextlib.py, line 115, decorate_context",
                    "return func(*args, **kwargs)"
                ],
                [
                    "D:\\SD\\Forge\\webui\\extensions-builtin\\sd_forge_controlnet\\scripts\\controlnet.py, line 487, process_before_every_sampling",
                    "self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)"
                ]
            ]
        }
    ],
    "CPU": {
        "model": "AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD",
        "count logical": 12,
        "count physical": 6
    },
    "RAM": {
        "total": "48GB",
        "used": "18GB",
        "free": "30GB"
    },
    "Extensions": [],
    "Inactive extensions": [],
    "Environment": {
        "GRADIO_ANALYTICS_ENABLED": "False"
    },
    "Config": {
        "ldsr_steps": 100,
        "ldsr_cached": false,
        "SCUNET_tile": 256,
        "SCUNET_tile_overlap": 8,
        "SWIN_tile": 192,
        "SWIN_tile_overlap": 8,
        "SWIN_torch_compile": false,
        "control_net_detectedmap_dir": "detected_maps",
        "control_net_models_path": "",
        "control_net_modules_path": "",
        "control_net_unit_count": 3,
        "control_net_model_cache_size": 5,
        "control_net_no_detectmap": false,
        "control_net_detectmap_autosaving": false,
        "control_net_allow_script_control": false,
        "control_net_sync_field_args": true,
        "controlnet_show_batch_images_in_ui": false,
        "controlnet_increment_seed_during_batch": false,
        "controlnet_disable_openpose_edit": false,
        "controlnet_disable_photopea_edit": false,
        "controlnet_photopea_warning": true,
        "controlnet_input_thumbnail": true,
        "sd_checkpoint_hash": "3a22504d8a995171b7d10a618a11614e4c15313f8277b742596299fdb07d227f",
        "sd_model_checkpoint": "dreamshaperXL_sfwTurboDpmppSDE.safetensors"
    },
    "Startup": {
        "total": 18.804677963256836,
        "records": {
            "initial startup": 0.01701521873474121,
            "prepare environment/checks": 0.007006645202636719,
            "prepare environment/git version info": 0.03102850914001465,
            "prepare environment/torch GPU test": 5.137334108352661,
            "prepare environment/clone repositores": 0.15213847160339355,
            "prepare environment/run extensions installers": 0.006005764007568359,
            "prepare environment/run extensions_builtin installers/canvas-zoom-and-pan": 0.0010006427764892578,
            "prepare environment/run extensions_builtin installers/extra-options-section": 0.0,
            "prepare environment/run extensions_builtin installers/forge_legacy_preprocessors": 0.27351832389831543,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_inpaint": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_marigold": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_normalbae": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_recolor": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_reference": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_revision": 0.0,
            "prepare environment/run extensions_builtin installers/forge_preprocessor_tile": 0.0,
            "prepare environment/run extensions_builtin installers/LDSR": 0.0,
            "prepare environment/run extensions_builtin installers/Lora": 0.0,
            "prepare environment/run extensions_builtin installers/mobile": 0.0,
            "prepare environment/run extensions_builtin installers/prompt-bracket-checker": 0.0,
            "prepare environment/run extensions_builtin installers/ScuNET": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_controlllite": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_controlnet": 0.2202005386352539,
            "prepare environment/run extensions_builtin installers/sd_forge_controlnet_example": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_freeu": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_hypertile": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_ipadapter": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_kohya_hrfix": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_photomaker": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_sag": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_stylealign": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_svd": 0.0,
            "prepare environment/run extensions_builtin installers/sd_forge_z123": 0.0,
            "prepare environment/run extensions_builtin installers/soft-inpainting": 0.0010004043579101562,
            "prepare environment/run extensions_builtin installers/SwinIR": 0.0,
            "prepare environment/run extensions_builtin installers": 0.49571990966796875,
            "prepare environment": 6.025410890579224,
            "launcher": 0.0020017623901367188,
            "import torch": 4.681923866271973,
            "import gradio": 1.8073339462280273,
            "setup paths": 1.968393087387085,
            "import ldm": 0.007043123245239258,
            "import sgm": 0.0,
            "initialize shared": 0.11365199089050293,
            "other imports": 1.5643608570098877,
            "opts onchange": 0.0010006427764892578,
            "setup SD model": 0.0,
            "setup codeformer": 0.0016913414001464844,
            "setup gfpgan": 0.017375946044921875,
            "set samplers": 0.0,
            "list extensions": 0.002003908157348633,
            "restore config state file": 0.0,
            "list SD models": 0.027151107788085938,
            "list localizations": 0.0010008811950683594,
            "load scripts/custom_code.py": 0.006005525588989258,
            "load scripts/img2imgalt.py": 0.0010013580322265625,
            "load scripts/loopback.py": 0.0,
            "load scripts/outpainting_mk_2.py": 0.001001119613647461,
            "load scripts/poor_mans_outpainting.py": 0.0,
            "load scripts/postprocessing_caption.py": 0.0010008811950683594,
            "load scripts/postprocessing_codeformer.py": 0.0,
            "load scripts/postprocessing_create_flipped_copies.py": 0.0,
            "load scripts/postprocessing_focal_crop.py": 0.005004405975341797,
            "load scripts/postprocessing_gfpgan.py": 0.0010008811950683594,
            "load scripts/postprocessing_split_oversized.py": 0.0,
            "load scripts/postprocessing_upscale.py": 0.001001119613647461,
            "load scripts/processing_autosized_crop.py": 0.0,
            "load scripts/prompt_matrix.py": 0.0010006427764892578,
            "load scripts/prompts_from_file.py": 0.0,
            "load scripts/sd_upscale.py": 0.0010018348693847656,
            "load scripts/xyz_grid.py": 0.00099945068359375,
            "load scripts/ldsr_model.py": 0.583221435546875,
            "load scripts/lora_script.py": 0.07838296890258789,
            "load scripts/scunet_model.py": 0.020529508590698242,
            "load scripts/swinir_model.py": 0.016014575958251953,
            "load scripts/hotkey_config.py": 0.0013041496276855469,
            "load scripts/extra_options_section.py": 0.0005116462707519531,
            "load scripts/legacy_preprocessors.py": 0.008218765258789062,
            "load scripts/preprocessor_inpaint.py": 0.01484823226928711,
            "load scripts/preprocessor_marigold.py": 0.11364269256591797,
            "load scripts/preprocessor_normalbae.py": 0.005044221878051758,
            "load scripts/preprocessor_recolor.py": 0.0,
            "load scripts/forge_reference.py": 0.0010943412780761719,
            "load scripts/preprocessor_revision.py": 0.0004773139953613281,
            "load scripts/preprocessor_tile.py": 0.00043511390686035156,
            "load scripts/forge_controllllite.py": 0.010459661483764648,
            "load scripts/controlnet.py": 0.43412065505981445,
            "load scripts/xyz_grid_support.py": 0.0008428096771240234,
            "load scripts/sd_forge_controlnet_example.py": 0.0006906986236572266,
            "load scripts/forge_freeu.py": 0.0024423599243164062,
            "load scripts/forge_hypertile.py": 0.0020017623901367188,
            "load scripts/forge_ipadapter.py": 0.006807565689086914,
            "load scripts/kohya_hrfix.py": 0.002619504928588867,
            "load scripts/forge_photomaker.py": 0.0014388561248779297,
            "load scripts/forge_sag.py": 0.0021936893463134766,
            "load scripts/forge_stylealign.py": 0.0010008811950683594,
            "load scripts/forge_svd.py": 0.027201175689697266,
            "load scripts/forge_z123.py": 0.01983928680419922,
            "load scripts/soft_inpainting.py": 0.0012614727020263672,
            "load scripts/refiner.py": 0.0006113052368164062,
            "load scripts/seed.py": 0.0004775524139404297,
            "load scripts": 1.37675142288208,
            "load upscalers": 0.003003835678100586,
            "refresh VAE": 0.0010008811950683594,
            "refresh textual inversion templates": 0.0,
            "scripts list_optimizers": 0.001001119613647461,
            "scripts list_unets": 0.0,
            "reload hypernetworks": 0.009601354598999023,
            "initialize extra networks": 0.03903698921203613,
            "scripts before_ui_callback": 0.0035402774810791016,
            "create ui": 0.6431972980499268,
            "gradio launch": 0.6713500022888184,
            "add APIs": 0.018016576766967773,
            "app_started_callback/lora_script.py": 0.0,
            "app_started_callback": 0.0
        }
    },
    "Packages": [
        "absl-py==2.1.0",
        "accelerate==0.21.0",
        "addict==2.4.0",
        "aenum==3.1.15",
        "aiofiles==23.2.1",
        "aiohttp==3.9.3",
        "aiosignal==1.3.1",
        "albumentations==1.3.1",
        "altair==5.2.0",
        "antlr4-python3-runtime==4.9.3",
        "anyio==3.7.1",
        "async-timeout==4.0.3",
        "attrs==23.2.0",
        "basicsr==1.4.2",
        "blendmodes==2022",
        "certifi==2024.2.2",
        "cffi==1.16.0",
        "chardet==5.2.0",
        "charset-normalizer==3.3.2",
        "clean-fid==0.1.35",
        "click==8.1.7",
        "clip==1.0",
        "colorama==0.4.6",
        "coloredlogs==15.0.1",
        "colorlog==6.8.2",
        "contourpy==1.2.0",
        "cssselect2==0.7.0",
        "cycler==0.12.1",
        "cython==3.0.8",
        "deprecation==2.1.0",
        "depth-anything==2024.1.22.0",
        "diffusers==0.25.0",
        "easydict==1.11",
        "einops==0.4.1",
        "embreex==2.17.7.post4",
        "exceptiongroup==1.2.0",
        "facexlib==0.3.0",
        "fastapi==0.94.0",
        "ffmpy==0.3.1",
        "filelock==3.13.1",
        "filterpy==1.4.5",
        "flatbuffers==23.5.26",
        "fonttools==4.47.2",
        "frozenlist==1.4.1",
        "fsspec==2024.2.0",
        "ftfy==6.1.3",
        "future==0.18.3",
        "fvcore==0.1.5.post20221221",
        "gitdb==4.0.11",
        "gitpython==3.1.32",
        "gradio-client==0.5.0",
        "gradio==3.41.2",
        "grpcio==1.60.1",
        "h11==0.12.0",
        "handrefinerportable==2024.1.18.0",
        "httpcore==0.15.0",
        "httpx==0.24.1",
        "huggingface-hub==0.20.3",
        "humanfriendly==10.0",
        "idna==3.6",
        "imageio==2.33.1",
        "importlib-metadata==7.0.1",
        "importlib-resources==6.1.1",
        "inflection==0.5.1",
        "insightface==0.7.3",
        "iopath==0.1.9",
        "jinja2==3.1.3",
        "joblib==1.3.2",
        "jsonmerge==1.8.0",
        "jsonschema-specifications==2023.12.1",
        "jsonschema==4.21.1",
        "kiwisolver==1.4.5",
        "kornia==0.6.7",
        "lark==1.1.2",
        "lazy-loader==0.3",
        "lightning-utilities==0.10.1",
        "llvmlite==0.42.0",
        "lmdb==1.4.1",
        "lxml==5.1.0",
        "mapbox-earcut==1.0.1",
        "markdown==3.5.2",
        "markupsafe==2.1.5",
        "matplotlib==3.8.2",
        "mediapipe==0.10.9",
        "mpmath==1.3.0",
        "multidict==6.0.5",
        "networkx==3.2.1",
        "numba==0.59.0",
        "numpy==1.26.2",
        "omegaconf==2.2.3",
        "onnx==1.15.0",
        "onnxruntime==1.17.0",
        "open-clip-torch==2.20.0",
        "opencv-contrib-python==4.9.0.80",
        "opencv-python-headless==4.9.0.80",
        "opencv-python==4.9.0.80",
        "orjson==3.9.13",
        "packaging==23.2",
        "pandas==2.2.0",
        "piexif==1.1.3",
        "pillow==9.5.0",
        "pip==24.0",
        "platformdirs==4.2.0",
        "portalocker==2.8.2",
        "prettytable==3.9.0",
        "protobuf==3.20.0",
        "psutil==5.9.5",
        "pycollada==0.8",
        "pycparser==2.21",
        "pydantic==1.10.14",
        "pydub==0.25.1",
        "pyparsing==3.1.1",
        "pyreadline3==3.4.1",
        "python-dateutil==2.8.2",
        "python-multipart==0.0.7",
        "pytorch-lightning==1.9.4",
        "pytz==2024.1",
        "pywavelets==1.5.0",
        "pywin32==306",
        "pyyaml==6.0.1",
        "qudida==0.0.4",
        "referencing==0.33.0",
        "regex==2023.12.25",
        "reportlab==4.0.9",
        "requests==2.31.0",
        "resize-right==0.0.2",
        "rpds-py==0.17.1",
        "rtree==1.2.0",
        "safetensors==0.4.2",
        "scikit-image==0.21.0",
        "scikit-learn==1.4.0",
        "scipy==1.12.0",
        "semantic-version==2.10.0",
        "sentencepiece==0.1.99",
        "setuptools==69.0.3",
        "shapely==2.0.2",
        "six==1.16.0",
        "smmap==5.0.1",
        "sniffio==1.3.0",
        "sounddevice==0.4.6",
        "spandrel==0.1.6",
        "starlette==0.26.1",
        "svg.path==6.3",
        "svglib==1.5.1",
        "sympy==1.12",
        "tabulate==0.9.0",
        "tb-nightly==2.16.0a20240204",
        "tensorboard-data-server==0.7.2",
        "termcolor==2.4.0",
        "tf-keras-nightly==2.16.0.dev2024020410",
        "threadpoolctl==3.2.0",
        "tifffile==2024.1.30",
        "timm==0.9.12",
        "tinycss2==1.2.1",
        "tokenizers==0.13.3",
        "tomesd==0.1.3",
        "tomli==2.0.1",
        "toolz==0.12.1",
        "torch==2.1.2+cu121",
        "torchdiffeq==0.2.3",
        "torchmetrics==1.3.0.post0",
        "torchsde==0.2.6",
        "torchvision==0.16.2+cu121",
        "tqdm==4.66.1",
        "trampoline==0.1.2",
        "transformers==4.30.2",
        "trimesh==4.1.3",
        "typing-extensions==4.9.0",
        "tzdata==2023.4",
        "urllib3==2.2.0",
        "uvicorn==0.27.0.post1",
        "vhacdx==0.0.5",
        "wcwidth==0.2.13",
        "webencodings==0.5.1",
        "websockets==11.0.3",
        "werkzeug==3.0.1",
        "wheel==0.42.0",
        "yacs==0.1.8",
        "yapf==0.40.2",
        "yarl==1.9.4",
        "zipp==3.17.0"
    ]
}

### Console logs

```Shell
2024-02-06 22:32:46,259 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE████| 4/4 [00:01<00:00,  3.51it/s]
*** Error running process: D:\SD\Forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\SD\Forge\webui\modules\scripts.py", line 798, in process
        script.process(p, *script_args)
      File "D:\SD\Forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\SD\Forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 480, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "D:\SD\Forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\SD\Forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 266, in process_unit_after_click_generate
        input_list, resize_mode = self.get_input_data(p, unit, preprocessor)
      File "D:\SD\Forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 205, in get_input_data
        mask = HWC3(np.asarray(a1111_i2i_mask))
      File "D:\SD\Forge\webui\modules_forge\forge_util.py", line 13, in HWC3
        assert x.dtype == np.uint8
    AssertionError

---
*** Error running process_before_every_sampling: D:\SD\Forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\SD\Forge\webui\modules\scripts.py", line 830, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\SD\Forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\SD\Forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 487, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0
```

**Comment by haru832** [comment]
Getting the same error for both txt2img and img2img.  Not sure why txt2img is not working for me, but it works for you.

**Comment by RedDestiny** [comment]
我也是，文生图的CN模型是可以用，但是图生图的不行。
而且CN的预设保存好之后，无法加载的样子。一起反馈下的样子。

**Comment by lllyasviel** [comment]
update and try again

**Comment by haru832** [comment]
> update and try again

Thank you!! Works for img2img, but I'm still having issues with txt2img, no errors in console.  I also took out all extensions other than forge modules.

**Comment by VladCorvi** [comment]
> update and try again
All works. Apreciate for a fast fix!
