### ISSUE TITLE
[Bug]: ESRGAN 4xUltrasharp.pth not shown in UI

### ISSUE THREAD

**Issue by kornerson** [lllyasviel/stable-diffusion-webui-forge#82]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I put the 4x-Ultrasharp upscaler in the folder ESRGAN - which is not present - and the Upscaler doesnt show on the gui. Don't know if ESRGAN is not implemented or not used. 4x-Ultrasharp is a great upscaler

### Steps to reproduce the problem

1. Create directory ESRGAN
2. Place 4x-Ultrasharp.pth upscaler
3. Not shown in the GUI (it is shown in original webui)

### What should have happened?

should show the 4xUltrasharp upscaler for selection

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-02-06-21-20.json](https://github.com/lllyasviel/stable-diffusion-webui-forge/files/14186152/sysinfo-2024-02-06-21-20.json)

### Console logs

```Shell
venv "C:\SD\Forge\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Version: f0.0.9-latest-52-gb58b0bd4
Commit hash: b58b0bd4259cf71077dfd7787fb77af4c02760a1
Launching Web UI with arguments: --listen --enable-insecure-extension-access
Total VRAM 12287 MB, total RAM 16275 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
ControlNet preprocessor location: C:\SD\Forge\stable-diffusion-webui-forge\models\ControlNetPreprocessor
Civitai Helper: Get Custom Model Folder
[-] ADetailer initialized. version: 23.11.1, num models: 9
Loading weights [aeb7e9e689] from C:\SD\Forge\stable-diffusion-webui-forge\models\Stable-diffusion\juggernautXL_v8Rundiffusion.safetensors
2024-02-06 22:10:55,100 - ControlNet - INFO - ControlNet UI callback registered.Civitai Helper: Settings:
Civitai Helper: max_size_preview: True
Civitai Helper: skip_nsfw_preview: False
Civitai Helper: open_url_with_js: True
Civitai Helper: proxy:
Civitai Helper: use civitai api key: False
*** Error executing callback ui_tabs_callback for C:\SD\Forge\stable-diffusion-webui-forge\extensions\deforum\scripts\deforum.py
    Traceback (most recent call last):
      File "C:\SD\Forge\stable-diffusion-webui-forge\modules\script_callbacks.py", line 169, in ui_tabs_callback
        res += c.callback() or []
      File "C:\SD\Forge\stable-diffusion-webui-forge\extensions\deforum\scripts\deforum_helpers\ui_right.py", line 92, in on_ui_tabs
        deforum_gallery, generation_info, html_info, _ = create_output_panel("deforum", opts.outdir_img2img_samples)
    TypeError: cannot unpack non-iterable OutputPanel object

---
model_type EPS
UNet ADM Dimension 2816
Running on local URL:  http://0.0.0.0:7861

To create a public link, set `share=True` in `launch()`.
Startup time: 38.4s (prepare environment: 8.8s, import torch: 6.6s, import gradio: 2.0s, setup paths: 1.5s, initialize shared: 0.3s, other imports: 1.3s, load scripts: 5.2s, create ui: 8.3s, gradio launch: 4.4s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
loaded straight to GPU
To load target model SDXL
Begin to load 1 model
To load target model SDXLClipModel
Begin to load 1 model
Moving model(s) has taken 1.12 seconds
Model loaded in 51.4s (load weights from disk: 1.1s, forge instantiate config: 0.1s, forge load real models: 46.2s, load textual inversion embeddings: 0.2s, calculate empty prompt: 3.6s).
```

**Comment by sanmilano** [comment]
I'm having the same issue. Everything else works perfect!

**Comment by bendecruz745** [comment]
Odd, I have manually created the ESRGAN folder too (inside /models) and put in several upscalers (including 4x-UltraSharp) and I can see it in HiRes, Extras, etc.
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/56718206/ce3716ec-884f-407c-bc24-7a5cd5cfb97e)
![image](https://github.com/lllyasviel/stable-diffusion-webui-forge/assets/56718206/afa4d006-31be-46f0-8e74-4b32375e3943)

**Comment by kornerson** [comment]
Its solved. It is my mistake

**Comment by sanmilano** [comment]
I copied the files into an ESRGAN folder and it worked. It seems it doesn't work with symlinks. I'm using symlinks for everything else (checkpoints, loras, controlnets, etc.) with no issues. So for now, the solution is do it the traditional way by creating the folder and paste the upscalers there
