### ISSUE TITLE
[Feature Request]: Search and download model in WebUI

### ISSUE THREAD

**Issue by VeteranXT** [lllyasviel/stable-diffusion-webui-forge#829]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Ability to find on CivitAI/huggingFace models to download as well as loras without going to sites.

### Proposed workflow

Search bar to find what ya need.
Picture of what it is
Download button.

**Comment by dan4in** [comment]
just download CIVITAI +plus extension

**Comment by VeteranXT** [comment]
Thanks!
