### ISSUE TITLE
Hypertile Integrated section has disappeared

### ISSUE THREAD

**Issue by Blueblizard** [lllyasviel/stable-diffusion-webui-forge#860]
After the last update the hypertile section has disappeared. Instead appears the PerturbedAttentionGuidance Integrated.

![Hypertile](https://github.com/user-attachments/assets/93e4e6c8-59a5-45f9-a898-3e5551954aaa)

**Comment by lllyasviel** [comment]
Some extensions are moved to legacy to make room for newer features. You can get files here if you want to have them:

https://github.com/lllyasviel/forge-legacy-extensions

download and put `sd-forge-XXX` to `extensions` folder

**Comment by Blueblizard** [comment]
> Some extensions are moved to legacy to make room for newer features. You can get files here if you want to have them:
> 
> https://github.com/lllyasviel/forge-legacy-extensions
> 
> download and put `sd-forge-XXX` to `extensions` folder

I did it and it was working but with the last update hypertile integrated section has disappeared again. :(

**Comment by Wozzasworld** [comment]
I really miss the Hypertile feature, it did some wonderful effects when using translucent/transparent prompting.
I couldn't get it to work using the legacy download, then did some digging around and it could have to do with the fact PAG and HyprtTile have the same sorting priority, because when I try to install Hypertile PAG breaks.

**Comment by Blueblizard** [comment]
Hypertile is one of my basic features because without using it, each image is about 20 seconds slow. I downloaded and added like legacy extension, creating the folder "sd-forge-Hypertile integrated" in the extensions folder, and copying the archives into it. It worked, but now has disappeared again. It appears in the extension list but no in the interface. Besides of this problem, when you left the txt2img window, the preview view fail, only shows the final image, progress bar doesn´t work, it says "waiting" and is impossible to stop generations without closing the console.

**Comment by Blueblizard** [comment]
> I really miss the Hypertile feature, it did some wonderful effects when using translucent/transparent prompting. I couldn't get it to work using the legacy download, then did some digging around and it could have to do with the fact PAG and HyprtTile have the same sorting priority, because when I try to install Hypertile PAG breaks.

¿Some advance? I really miss this.

**Comment by alebeard** [comment]
I am really hoping that the extensions All one of the final touches that
gets fixed.

**Comment by Blueblizard** [comment]
> Some extensions are moved to legacy to make room for newer features. You can get files here if you want to have them:
> 
> https://github.com/lllyasviel/forge-legacy-extensions
> 
> download and put `sd-forge-XXX` to `extensions` folder

I installed the extension using the legacy link and the hypertile integrated section reappeared again, but after a day or two using it disappeared again after the new updates. :(

**Comment by Blueblizard** [comment]
> I am really hoping that the extensions All one of the final touches that gets fixed.


¿Some advance?

**Comment by Seedmanc** [comment]
imagine doing all this the heavy-lifting Flux and hi-res image generation requires without hypertiling

**Comment by 780ilk8ui9otk** [comment]
hypertile no longer works, patching ldm_patched doesn't help

**Comment by Blueblizard** [comment]
Yes, when i install the legacy link and put it in a folder with her name the extension appears in the list... but it doesn´t appear in the main Forge gui.

![hypertile extension](https://github.com/user-attachments/assets/b1fee6e6-db18-4e63-b454-097f6bd25655)

**Comment by Blueblizard** [comment]
¡Hey, we are lucky!. I have seen that there is an actualized extension that enable hypertile in the new forge. Go to extensions tab and paste the link below in "install for URL" field. 

https://github.com/DenOfEquity/HyperTile
