### ISSUE TITLE
Pony Models not working

### ISSUE THREAD

**Issue by GatorsUF** [lllyasviel/stable-diffusion-webui-forge#866]
Since the latest update I cannot generate images using the Pony Diffusion models. The exact same parameters that worked on the previous version resulting in a high quality image now result in a grey image or blobs of grey with not distinctive characteristics at all.  I'm not what may be causing this, but it seems to be directly related to the recent update.

**Comment by Haoming02** [comment]
Seems to work correctly if you set **Clip Skip** to `1` instead of `2`

**Comment by GatorsUF** [comment]
That seems to have fixed it, thanks! Odd because Clip Skip 2 was always required before.

**Comment by lllyasviel** [comment]
This is because forge clip skip now actually works

try these:

1. set clip skip to 1 in forge and see if that fix the problem.
2. set clip skip to 1 in automatic1111 to get a result, say X
3. set clip skip to 2 in automatic1111 to get a result, say Y

then compare X and Y

**Comment by jahaynes256** [comment]
Changing clip from 2 to 1 was made my old image seeds work again. Thanks for the comment.

**Comment by lllyasviel** [comment]
After some consideration I changed to a less aggressive method for clip skip and now it should handle pony just like a1111 but also have some technical correctness.

**Comment by mimimi999** [comment]
> Since the latest update I cannot generate images using the Pony Diffusion models. The exact same parameters that worked on the previous version resulting in a high quality image now result in a grey image or blobs of grey with not distinctive characteristics at all. I'm not what may be causing this, but it seems to be directly related to the recent update.

I have tested various models for transmission, but in most cases the images are either not transparent or the colors are muddy.
I am having trouble with the same result with the default pony model (V6).

I don't know what the cause is, so if there is a successful transparent image pattern for the pony model, could you please show me the settings screen?

(*Generated using SD-forge in a local environment of Windows 11.)

**Comment by 2NoobPlayer** [comment]
I came back after a long time. Reinstalled forge using zip file. Checked a Pony model. Got completely BLACK image. with both Clip Skip 1 and 2. 

I ran update, now I am unable to run FORGE altogether. WHAT IS WRONG WITH THIS!!
