### ISSUE TITLE
Since this new set of updates the Civitai Helper is not working, Where should I be asking about this? 

### ISSUE THREAD

**Issue by Fretag** [lllyasviel/stable-diffusion-webui-forge#872]
Here? 
The Civitai Helper creators github? 

Civitai?

![Screenshot 2024-07-27 at 11-02-56 Stable Diffusion](https://github.com/user-attachments/assets/ff8cfe3b-794b-4e7f-b716-1af701fbcdf9)

**Comment by Fretag** [comment]
I thought maybe the API had been the problem but it doesn't seem to be the reason.

**Comment by irldoggo** [comment]
It's working fine for me. I had a bunch of errors after I updated, Including with Browser Plus, I just deleted the venv and let the start script recreate it, everything was fine after that. Minus a few issues with the icons. Open an issue on the plugin maintainer's [Github](https://github.com/BlafKing/sd-civitai-browser-plus/issues) if you are still having problems.

**Comment by Fretag** [comment]
I tried deleting and letting venv rebuild. No luck. Closing this without a solution.

**Comment by Fretag** [comment]
Thank you for the advice. So little has gone wrong in the past 6 months
that I forget about rebuilding the venv. But unfortunately that didn't
help.
