### ISSUE TITLE
UI won't load after the latest set of updates.

### ISSUE THREAD

**Issue by Bubalus-Bubalis** [lllyasviel/stable-diffusion-webui-forge#876]
UI is stuck at the loading screen.

![image](https://github.com/user-attachments/assets/69583312-a5d9-476e-ad9d-ce70b7b32152)
![image](https://github.com/user-attachments/assets/26c5d0dc-1fe6-49e5-9801-43c5c1f816ee)

**Comment by koopa990** [comment]
I am sort of in the same boat here
![image](https://github.com/user-attachments/assets/77f78b25-7d8d-45ac-b85e-bd7cfd7a81a5)

**Comment by Bubalus-Bubalis** [comment]
Fresh download was required to get it to work again. Not sure why it broke like that.

**Comment by Bubalus-Bubalis** [comment]
Marking as closed.
