### ISSUE TITLE
New Inpainting GUI does not work with pen in Microsoft Surface 

### ISSUE THREAD

**Issue by Digiearts** [lllyasviel/stable-diffusion-webui-forge#881]
New Inpainting GUI does not work with pen in Microsoft Surface 
Previously it worked perfect. The new GUI for inpainting currently does not work in tablet mode for pen and hand gesture.

**Comment by lllyasviel** [comment]
update and see if works

**Comment by Digiearts** [comment]
Thankyou for your quick response to this issue. It still does not work. Please see the attached video:

https://github.com/user-attachments/assets/9aaff2bb-be6a-4911-be1d-43063c892737

**Comment by Digiearts** [comment]
The inpainting GUI works perfect on version before update. See the attached video : 

https://github.com/user-attachments/assets/98f8daf4-e95f-440c-a458-7a4b10c46ec3

**Comment by Modusprimax** [comment]
Do your inpaint outputs come out blurry with the new inpainting UI, or is it just that the touch response doesn't work well? On my end, ever since the inpaint UI was changed a few days ago, inpaint has been completely unusable

**Comment by Digiearts** [comment]
> Do your inpaint outputs come out blurry with the new inpainting UI, or is it just that the touch response doesn't work well? On my end, ever since the inpaint UI was changed a few days ago, inpaint has been completely unusable

The inpainting result looks normal to me. Only the inpainting GUI is not responsive in tablet mode. It still works with mouse and touch pad  for laptop. I also notice the progress bar does not show up after we press 'Generate' button.

**Comment by Digiearts** [comment]
I just develop an extension myself to fix this issue. With this extension, Stylus pen of Microsoft Surface Laptop Studio works smoothly again in latest SD Forge Canvas with Gradio 4 environment.
If you have similar issue and using Microsoft Surface Studio, you can [install this extension](https://github.com/Digiearts/sd-forge-surface-pen-fix ) to fix the issue.

**Comment by Digiearts** [comment]
For now this issue is resolved.
