### ISSUE TITLE
img2img/inpainting always uses grids

### ISSUE THREAD

**Issue by DeviLandlight** [lllyasviel/stable-diffusion-webui-forge#884]
Taking a picture from text2img to img2img, instead of taking the picture selected, it takes the grid of all images instead. Tried again later and instead of bringing the whole grid, it just brought the wrong picture.

And it runs awfully. I can run txt2img just fine, and I used to be able to use inpainting and img2img too, but now either slows my computer to a standstill and takes five times as long, And the results at best, poorly mesh with their surroundings and at worst are completely different than what it was before. I dunno when I last updated or what version I was using, but this version seems almost entirely inferior

**Comment by tnotariano** [comment]
What do you mean by grids, many of thr same image? Or, many different? What extensions are uou running? Scripts? Are you outputting batches?
