### ISSUE TITLE
Version Issue

### ISSUE THREAD

**Issue by Blitzarts** [lllyasviel/stable-diffusion-webui-forge#904]
**Hey! is any chance to go back to "Version: f0.0.17v1.8.0rc-latest-278-gbfee03d8"?** 

The thing is, I tried switching to the latest version, but some extensions that are part of my workflow didn't work. So, since I have work right now, I prefer to revert to the previous version. However, I can't find that version I mentioned earlier. Even the previous version is causing conflicts with those extensions, and I don't know what to do

**Comment by Panchovix** [comment]
You can go back to before gradio 4 commit with `git checkout bfee03d`. Now if you were using layer diffusion, you have to go back some commits as well, since now it is only for gradio 4

**Comment by Hapseleg** [comment]
This is where things went bad:
https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/e26abf87ecd1eefd9ab0a198eee56f9c643e4001

git checkout e95333c
thats the newest one before Gradio got updated and a lot of stuff broke

**Comment by Blitzarts** [comment]
Thank you! i'll try :D
