### ISSUE TITLE
ADetailer ControlNet support

### ISSUE THREAD

**Issue by zcatharisis** [lllyasviel/stable-diffusion-webui-forge#93]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Adetailer's controlnet module is disabled when using it with forge. All other functionalities seem to be intact other than this.
Hovering over the option for selecting a CN model changes the cursor to a 'stop' sign, and the sliders cannot be adjusted. 

### Steps to reproduce the problem

1. Install adetailer extension on newly installed forge.
2. Restart forge-ui.
3. Controlnet Module cannot be changed/is disabled. 

### What should have happened?

Controlnet module should be fully operable given that Controlnet is natively installed in forge-ui.

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

I had deleted my forge-ui yesterday, only thought to report it now. 

### Console logs

```Shell
no log.
```

**Comment by schilling3003** [comment]
This, along with controlnet not working with Inpaint Anything are the two things keeping me from switching to Forge. I hope you are able to get this fixed.

**Comment by hinablue** [comment]
Adetailer CN is not compatible with forge. You can ask the original author.
