### ISSUE TITLE
TypeError: 'NoneType' object is not iterable (Script: X/Y/Z plot)

### ISSUE THREAD

**Issue by CraftWibu** [lllyasviel/stable-diffusion-webui-forge#930]
When I want a script that X/Y/Z plot, then type X: Prompt S/R > X value: "v sign, peace sign, victory hand" I cannot get it error message "TypeError: 'NoneType' object is not iterable"

Is there a solution?

CMD Windows 10:
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f1.0.2v1.10.1-previous-104-g430482d1
Commit hash: 430482d1a0105398de455ec11062feecac50a324
Installing requirements
loading WD14-tagger reqs from F:\SOFTWARE\A.I\webui_forge_cu121_torch21\webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt
Checking WD14-tagger requirements.
Launching Web UI with arguments: --pin-shared-memory --cuda-malloc --cuda-stream
Using cudaMallocAsync backend.
Total VRAM 8192 MB, total RAM 16218 MB
pytorch version: 2.1.2+cu121
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 3050 : cudaMallocAsync
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Stream Activated:  True
2024-08-04 20:37:00.429480: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-08-04 20:37:11.903644: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: F:\SOFTWARE\A.I\webui_forge_cu121_torch21\webui\models\ControlNetPreprocessor
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.8.0, num models: 10
== WD14 tagger /gpu:0, uname_result(system='Windows', node='LG', release='10', version='10.0.19045', machine='AMD64') ==Loading weights [e3c47aedb0] from F:\SOFTWARE\A.I\webui_forge_cu121_torch21\webui\models\Stable-diffusion\animagineXLV31_v31.safetensors
2024-08-04 20:38:24,650 - ControlNet - INFO - ControlNet UI callback registered.
F:\SOFTWARE\A.I\webui_forge_cu121_torch21\webui\extensions\sd-webui-model-converter\scripts\ui.py:60: GradioDeprecationWarning: unexpected argument for Button: label
  model_converter_convert = gr.Button(elem_id="model_converter_convert", label="Convert",
F:\SOFTWARE\A.I\webui_forge_cu121_torch21\webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\ui.py:232: GradioDeprecationWarning: unexpected argument for HTML: interactive
  info = gr.HTML(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 222.0s (initial startup: 0.4s, prepare environment: 87.5s, launcher: 16.0s, import torch: 19.3s, setup paths: 53.8s, initialize shared: 0.8s, other imports: 11.6s, setup gfpgan: 0.2s, list SD models: 0.6s, load scripts: 7.1s, create ui: 21.7s, gradio launch: 2.9s, add APIs: 0.1s).
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
To load target model JointCLIPTextEncoder
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  7183.808685302734
[Memory Management] Model Memory (MB) =  1753.803913116455
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  4406.004772186279
Moving model(s) has taken 1.03 seconds
Model loaded in 395.3s (calculate hash: 0.4s, load weights from disk: 16.6s, forge instantiate config: 2.3s, forge load real models: 315.1s, forge set components: 0.2s, forge finalize: 1.5s, load textual inversion embeddings: 5.4s, scripts callbacks: 0.2s, calculate empty prompt: 53.5s).
To load target model KModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  7145.687429428101
[Memory Management] Model Memory (MB) =  4897.05216217041
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  1224.6352672576904
Moving model(s) has taken 5.33 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:27<00:00,  1.09it/s]
To load target model IntegratedAutoencoderKL███████████████████████████████████████████| 30/30 [00:08<00:00,  3.49it/s]
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  2228.5102672576904
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  1044.9531860351562
Moving model(s) has taken 0.34 seconds
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:12<00:00,  2.32it/s]
To load target model JointCLIPTextEncoder██████████████████████████████████████████████| 30/30 [00:12<00:00,  3.49it/s]
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  6958.067848205566
[Memory Management] Model Memory (MB) =  1753.803913116455
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  4180.263935089111
Moving model(s) has taken 1.91 seconds
To load target model KModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  7116.942476272583
[Memory Management] Model Memory (MB) =  4897.05216217041
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  1195.8903141021729
Moving model(s) has taken 1.19 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:07<00:00,  3.79it/s]
To load target model IntegratedAutoencoderKL███████████████████████████████████████████| 30/30 [00:07<00:00,  3.69it/s]
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  2211.765314102173
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  1028.2082328796387
Moving model(s) has taken 0.30 seconds
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:08<00:00,  3.63it/s]
To load target model JointCLIPTextEncoder██████████████████████████████████████████████| 30/30 [00:08<00:00,  3.69it/s]
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  6949.322895050049
[Memory Management] Model Memory (MB) =  1753.803913116455
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  4171.518981933594
Moving model(s) has taken 1.81 seconds
To load target model KModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  7107.449415206909
[Memory Management] Model Memory (MB) =  4897.05216217041
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  1186.397253036499
Moving model(s) has taken 1.05 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:24<00:00,  1.21it/s]
To load target model IntegratedAutoencoderKL███████████████████████████████████████████| 30/30 [00:23<00:00,  1.23it/s]
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  7105.052808761597
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  5921.4957275390625
Moving model(s) has taken 0.83 seconds
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:25<00:00,  1.16it/s]
X/Y/Z plot will create 3 images on 1 3x1 grid. (Total steps to process: 90)████████████| 30/30 [00:25<00:00,  1.23it/s]
                                  Traceback (most recent call last):
  File "F:\SOFTWARE\A.I\webui_forge_cu121_torch21\webui\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "F:\SOFTWARE\A.I\webui_forge_cu121_torch21\webui\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "F:\SOFTWARE\A.I\webui_forge_cu121_torch21\webui\modules\txt2img.py", line 107, in txt2img_function
    processed = modules.scripts.scripts_txt2img.run(p, *p.script_args)
  File "F:\SOFTWARE\A.I\webui_forge_cu121_torch21\webui\modules\scripts.py", line 792, in run
    processed = script.run(p, *script_args)
  File "F:\SOFTWARE\A.I\webui_forge_cu121_torch21\webui\scripts\xyz_grid.py", line 769, in run
    processed = draw_xyz_grid(
  File "F:\SOFTWARE\A.I\webui_forge_cu121_torch21\webui\scripts\xyz_grid.py", line 362, in draw_xyz_grid
    process_cell(x, y, z, ix, iy, iz)
  File "F:\SOFTWARE\A.I\webui_forge_cu121_torch21\webui\scripts\xyz_grid.py", line 306, in process_cell
    processed: Processed = cell(x, y, z, ix, iy, iz)
  File "F:\SOFTWARE\A.I\webui_forge_cu121_torch21\webui\scripts\xyz_grid.py", line 713, in cell
    x_opt.apply(pc, x, xs)
  File "F:\SOFTWARE\A.I\webui_forge_cu121_torch21\webui\scripts\xyz_grid.py", line 39, in apply_prompt
    raise RuntimeError(f"Prompt S/R did not find {xs[0]} in prompt or negative prompt.")
RuntimeError: Prompt S/R did not find v sign in prompt or negative prompt.
Prompt S/R did not find v sign in prompt or negative prompt.
*** Error completing request
*** Arguments: ('task(kaombmehnijsl5p)', <gradio.route_utils.Request object at 0x000001DC148FEF50>, '1girl, masterpiece, best quality,', '', [], 1, 1, 7, 912, 912, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', None, 3, 30, 'Euler a', 'Automatic', False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, {'ad_model': 'face_yolov8n.pt', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=None, batch_mask_gallery=None, generated_image=None, mask_image=None, mask_image_fg=None, hr_option='Both', enabled=False, module='None', model='None', weight=1, image=None, image_fg=None, resize_mode='Crop and Resize', processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode='Balanced', save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, False, 0.5, 2, False, 3, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 7, 'v sign, peace sign, victory hand', [''], 0, '', '', 0, '', '', True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "F:\SOFTWARE\A.I\webui_forge_cu121_torch21\webui\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

---

![RbzBz3HrFw](https://github.com/user-attachments/assets/202935c6-9226-4256-b92c-ea7e928443d4)

---

![7m1TdPhe1k](https://github.com/user-attachments/assets/192a84c4-0d6f-4fd1-9f0c-9612ffeeab01)

---

**Comment by Panchovix** [comment]
You have to put the first string of your prompt S/R into the prompt (be positive or negative)

So in your case, if you put "v sign" after best quality,

It should work

**Comment by CraftWibu** [comment]
> You have to put the first string of your prompt S/R into the prompt (be positive or negative)
> 
> So in your case, if you put "v sign" after best quality,
> 
> And then it should work-

Thanks works!

**Comment by CraftWibu** [comment]
> You have to put the first string of your prompt S/R into the prompt (be positive or negative)
> 
> So in your case, if you put "v sign" after best quality,
> 
> And then it should work-

Thanks works!

**Comment by mart-hill** [comment]
The same bug now plagues the normal txt2img, too, at least since 0525a9dd5daf2ac0738b0107c1aafcfe38c3b5a6 commit. It wasn't an issue before, did something change in the prompt parser?

**Comment by vhanla** [comment]
**requirements_versions.txt** gradio **4.40.0** throws `http://127.0.0.1:7860http://127.0.0.1:7860/info is not a valid URL`. 
Previous version doesn't show that error. However, even reinstalling those previous versions. Still, this `TypeError: 'NoneType' object is not iterable` shows, using `--skip-install --disable-all-extensions` for that.
