### ISSUE TITLE
multiple errors after recent update

### ISSUE THREAD

**Issue by michael-shur** [lllyasviel/stable-diffusion-webui-forge#933]
after this morning update ( this git pull update was released sometime between 6am - 9am ET ):

1.

Euler A + Automatic scheduler type returning error: "ValueError: Wrong scheduler!" Image generation crashes almost instantly at the beginning.
Changing scheduler type to "Uniform" returning same error
Changing scheduler type to "Karras" - works just fine, no errors...
Changing sampling method to DPM++2M AND Automatic works fine, no error...

- tested on two different machines.

2.

adetailer extension stopped functioning. 

*** Error running postprocess_image: D:\forge\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "D:\forge\modules\scripts.py", line 940, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\forge\extensions\adetailer\aaaaaa\traceback.py", line 173, in wrapper
        raise error from None

--------------------------
 AttributeError: module 'modules.safe' has no attribute 'unsafe_torch_load'

- reinstalling extension is not fixing the problem. Image generation getting completed but without adetailer make any changes to generated image
- tested on two different machines.

P.S. both tested machines have automatic1111 and forge using same venv. automatic111 received latest git pull update couple days ago and everything is still working fine, adetailer extension have no issues as well as Euler A + Automatic scheduler type...

P.P.S/update: I reinstalled forge with git clone and got both errors back... So now I'm curious... is it only me who is using forge this days? or euler a? or adetailer? Should be bunch of people creating support tickets here but it's not, no one relay cares. Alright, moving back to automatic1111, enjoy it here...

**Comment by zefie** [comment]
I am on commit f052fabd4ddc9bebe73ed8fa24cccb1dc9b400ad and have been waiting until after August 7th (per the readme) for the updates to stabilize before updating again. I've had no issues with this commit.

**Comment by michael-shur** [comment]
Just to confirm that the rollback for this morning's update that was released about half an hour ago fixed reported bugs of ADetailer and combination of sampling methods+schedule types that was broken. Thank you very much.
