### ISSUE TITLE
diffusers v0.30.0 is out  Flux support and Perturbed Attention Guidance for SD1&XL

### ISSUE THREAD

**Issue by mr-lab** [lllyasviel/stable-diffusion-webui-forge#951]
https://github.com/huggingface/diffusers/releases/tag/v0.30.0
diffusers v0.30.0  with it Flux integration is gonna be much more  easier  plus it packs more New Methods  that would improve Image results.
I know [lllyasviel](https://github.com/lllyasviel) you are hard at work cleaning up years of unrelated hack-solutions and scripts that none use , plus duplicates and absolute madness inside the Webui  , i'm just letting you know about this for future plans , keep up the good work .

**Comment by ollobrains** [comment]
good idea

**Comment by zethfoxster** [comment]
> https://github.com/huggingface/diffusers/releases/tag/v0.30.0 diffusers v0.30.0 with it Flux integration is gonna be much more easier plus it packs more New Methods that would improve Image results. I know [lllyasviel](https://github.com/lllyasviel) you are hard at work cleaning up years of unrelated hack-solutions and scripts that none use , plus duplicates and absolute madness inside the Webui , i'm just letting you know about this for future plans , keep up the good work .

years?

**Comment by ollobrains** [comment]
> > https://github.com/huggingface/diffusers/releases/tag/v0.30.0 diffusers v0.30.0 with it Flux integration is gonna be much more easier plus it packs more New Methods that would improve Image results. I know [lllyasviel](https://github.com/lllyasviel) you are hard at work cleaning up years of unrelated hack-solutions and scripts that none use , plus duplicates and absolute madness inside the Webui , i'm just letting you know about this for future plans , keep up the good work .
> 
> years?

or not at all

**Comment by zethfoxster** [comment]
> > > https://github.com/huggingface/diffusers/releases/tag/v0.30.0 diffusers v0.30.0 with it Flux integration is gonna be much more easier plus it packs more New Methods that would improve Image results. I know [lllyasviel](https://github.com/lllyasviel) you are hard at work cleaning up years of unrelated hack-solutions and scripts that none use , plus duplicates and absolute madness inside the Webui , i'm just letting you know about this for future plans , keep up the good work .
> > 
> > 
> > years?
> 
> or not at all

lol when they said years of hack solutions, all i could think was whhhaaat? cause this hasnt even been a full year yet!!!

**Comment by mr-lab** [comment]
> > > > https://github.com/huggingface/diffusers/releases/tag/v0.30.0 diffusers v0.30.0 with it Flux integration is gonna be much more easier plus it packs more New Methods that would improve Image results. I know [lllyasviel](https://github.com/lllyasviel) you are hard at work cleaning up years of unrelated hack-solutions and scripts that none use , plus duplicates and absolute madness inside the Webui , i'm just letting you know about this for future plans , keep up the good work .
> > > 
> > > 
> > > years?
> > 
> > 
> > or not at all
> 
> lol when they said years of hack solutions, all i could think was whhhaaat? cause this hasnt even been a full year yet!!! i guess that puts into perspective how fast ai is moving that people think its been out for years.
example :
you know that sd hijack was implemented in Auto1111 webui  ?   Auto1111  [AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commits?author=AUTOMATIC1111)
committed
2 years ago , and forge is based on some Auto1111  implementations ...  and he just got rid of sd hijack for example 
so yeah 2 YEARS is  still YEARS
