### ISSUE TITLE
How to use multiple extensions with same name?

### ISSUE THREAD

**Issue by nemesiscompletion** [lllyasviel/stable-diffusion-webui-forge#954]
Hi. I'm trying to use some extensions that has same name but under 2 different developers and have different functions
I added '2' at the end of one of the folders, and I can see 2 tabs on SD Forge but I can't click one of them
Is there way to use both of the extensions?
![20240807_142748](https://github.com/user-attachments/assets/8a88fac3-2781-4b94-8b48-42c90117ebb5)
![20240807_144122](https://github.com/user-attachments/assets/90a30565-93e6-4c9d-ad33-8b0e0271e0f2)

**Comment by DenOfEquity** [comment]
The best solution would be to contact the developer of whichever of these extensions looks best maintained and/or already has the most features you want and ask them if they'd be willing to add the other functions.
It's likely both extensions use the same name for internal reference by the webUI, hence the conflict. Very likely, even, as they share a repo name and a tab title. Lazy forking devs.
<sup>Also, not a Forge issue.</sup>
