### ISSUE TITLE
New tab menu (Color/Detail & Face1) but blank inside

### ISSUE THREAD

**Issue by obs945** [lllyasviel/stable-diffusion-webui-forge#959]
After upgrading to new version of Forge with Gradio 4, there are two tab menus  added.
But it seems blank in these two menus and there is no sceenshot for new version Forge in README page for user to compare with.
Can anyone tell me how are the correct content in these two tab menus show ?
![截圖 2024-08-08 清晨7 00 47](https://github.com/user-attachments/assets/d5607ceb-60c7-4722-bf65-e344ee3c088d)

**Comment by lllyasviel** [comment]
No these are not Forge. Try uninstall all extensions.
