### ISSUE TITLE
the new package are starting with error 

### ISSUE THREAD

**Issue by coddz** [lllyasviel/stable-diffusion-webui-forge#983]
error1: torch version donot support cuda, need add --skip-torch-cuda-test
error2: OSError: [WinError 126] 找不到指定的模块。 Error loading "F:\forge2\system\python\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

Version: f2.0.1v1.10.1-previous-218-g643a485d
Commit hash: 643a485d1aff11acc657b24ee32d019e28d85b07
Installing clip
Installing open_clip
Installing xformers
Installing requirements
Installing forge_legacy_preprocessor requirement: fvcore
Installing forge_legacy_preprocessor requirement: mediapipe
Installing forge_legacy_preprocessor requirement: svglib
Launching Web UI with arguments: --theme dark --xformers --skip-torch-cuda-test --ckpt-dir E:/SDWebUI/sd-webui-aki-v4.4/models/Stable-diffusion --hypernetwork-dir E:/SDWebUI/sd-webui-aki-v4.4/models/hypernetworks --embeddings-dir E:/SDWebUI/sd-webui-aki-v4.4/embeddings --lora-dir E:/SDWebUI/sd-webui-aki-v4.4/models/Lora
Traceback (most recent call last):
  File "F:\forge2\webui\launch.py", line 51, in <module>
    main()
  File "F:\forge2\webui\launch.py", line 47, in main
    start()
  File "F:\forge2\webui\modules\launch_utils.py", line 544, in start
    import webui
  File "F:\forge2\webui\webui.py", line 19, in <module>
    initialize_forge()
  File "F:\forge2\webui\modules_forge\initialization.py", line 48, in initialize_forge
    from backend import memory_management
  File "F:\forge2\webui\backend\memory_management.py", line 6, in <module>
    import torch
  File "F:\forge2\system\python\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "F:\forge2\system\python\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
Press any key to continue . . .

**Comment by Firewolf63** [comment]
I'm having the exact same issue with the exact same setup.

**Comment by Yashpal2004** [comment]
> error1: torch version donot support cuda, need add --skip-torch-cuda-test error2: OSError: [WinError 126] 找不到指定的模块。 Error loading "F:\forge2\system\python\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
> 
> Version: f2.0.1v1.10.1-previous-218-g643a485d Commit hash: [643a485](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/643a485d1aff11acc657b24ee32d019e28d85b07) Installing clip Installing open_clip Installing xformers Installing requirements Installing forge_legacy_preprocessor requirement: fvcore Installing forge_legacy_preprocessor requirement: mediapipe Installing forge_legacy_preprocessor requirement: svglib Launching Web UI with arguments: --theme dark --xformers --skip-torch-cuda-test --ckpt-dir E:/SDWebUI/sd-webui-aki-v4.4/models/Stable-diffusion --hypernetwork-dir E:/SDWebUI/sd-webui-aki-v4.4/models/hypernetworks --embeddings-dir E:/SDWebUI/sd-webui-aki-v4.4/embeddings --lora-dir E:/SDWebUI/sd-webui-aki-v4.4/models/Lora Traceback (most recent call last): File "F:\forge2\webui\launch.py", line 51, in main() File "F:\forge2\webui\launch.py", line 47, in main start() File "F:\forge2\webui\modules\launch_utils.py", line 544, in start import webui File "F:\forge2\webui\webui.py", line 19, in initialize_forge() File "F:\forge2\webui\modules_forge\initialization.py", line 48, in initialize_forge from backend import memory_management File "F:\forge2\webui\backend\memory_management.py", line 6, in import torch File "F:\forge2\system\python\lib\site-packages\torch__init__.py", line 148, in raise err OSError: [WinError 126] 找不到指定的模块。 Error loading "F:\forge2\system\python\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies. Press any key to continue . . .

Uninstalling torch and reinstalling helped me.

**Comment by abozahran** [comment]
same error on the last update

**Comment by pyzzle9** [comment]
I was able to get around this by using webui_forge_cu121_torch21 and just updating it from there. I'm not well-versed in this stuff so I hope that helps.

**Comment by coddz** [comment]
thank you very much. webui_forge_cu121_torch21 started ok.
