### ISSUE TITLE
Problem with IMG2IMG with any Flux model

### ISSUE THREAD

**Issue by got2bi** [lllyasviel/stable-diffusion-webui-forge#992]
IMG2IMG works fine with any other model (SD, SDXL) but whenever i try to use a Flux model (automode, nf4, etc.), the image is blurred and oversaturated. I tried lots of sampler and scheduler and different denoising strength but the result still the same.
![image](https://github.com/user-attachments/assets/b2537e4d-04c0-409a-85e7-b5729033caea)

**Comment by LookParOff** [comment]
How you solve it?

**Comment by mnofresno** [comment]
@LookParOff I've the same problem. what do you mean by updating the repo?

**Comment by LookParOff** [comment]
> @LookParOff I've the same problem. what do you mean by updating the repo?

Search your folder, you will find file like update.cmd or something like this, run it, it will update your code and all start to work

Also you can search on GitHub of forge instructions how to update

**Comment by Archviz360** [comment]
when i try to do img2img to make realistic render of my sketchup images it doiesnt do any thing at all. it just give same image as input. 

![Image](https://github.com/user-attachments/assets/3072577a-76b1-400a-906f-f9eb0b8496f3) 

other services on internet have simliar you give a sketch image and then they give out relasitic images. i want to do same thing without using internet and giving my information to unknown companies that might sell info to databrokers. 

anyone here know how to make flux convert sketch in to realsitic images?
