### ISSUE TITLE
Am i doing something wrong? should i downgrade cuda to 12.4 as 12.6 was working with the previous commits.

### ISSUE THREAD

**Issue by cyaniddev** [lllyasviel/stable-diffusion-webui-forge#999]
![Screenshot from 2024-08-11 16-59-11](https://github.com/user-attachments/assets/f677a28e-45b7-4b12-bf34-24ddd69edf31)

**Comment by VeteranXT** [comment]
This is new Update. Wait for patches

**Comment by Preises** [comment]
Same issue here, only that I just installed it. So its gonna be compatible with 12.6 soon or downgrade 12.4 for now?

**Comment by azulxzzz** [comment]
I had the same issue. I installed 12.1 and then it worked. Although my nvidia-smi shows that I'm using 12.4.

**Comment by hollowstrawberry** [comment]
Same issue here

**Comment by hollowstrawberry** [comment]
This fixed it https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/988#issuecomment-2282715004

**Comment by cyaniddev** [comment]
> This fixed it [#988 (comment)](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/988#issuecomment-2282715004)

using linux

**Comment by cyaniddev** [comment]
recent commits has fixed it

**Comment by cyaniddev** [comment]
recent commits has fixed it
